// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) package import OpenAPIRuntime
#if os(Linux)
@preconcurrency package import struct Foundation.URL
@preconcurrency package import struct Foundation.Data
@preconcurrency package import struct Foundation.Date
#else
package import struct Foundation.URL
package import struct Foundation.Data
package import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    package enum Headers {}
}
