// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) package import OpenAPIRuntime
#if os(Linux)
@preconcurrency package import struct Foundation.URL
@preconcurrency package import struct Foundation.Data
@preconcurrency package import struct Foundation.Date
#else
package import struct Foundation.URL
package import struct Foundation.Data
package import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
package protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /api/v1/agent/ask`.
    /// - Remark: Generated from `#/paths//api/v1/agent/ask/post(agent.ask)`.
    func agent_ask(_ input: Operations.Agent_ask.Input) async throws -> Operations.Agent_ask.Output
    /// - Remark: HTTP `GET /api/v1/dashboard/counts`.
    /// - Remark: Generated from `#/paths//api/v1/dashboard/counts/get(dashboard.counts)`.
    func dashboard_counts(_ input: Operations.Dashboard_counts.Input) async throws -> Operations.Dashboard_counts.Output
    /// - Remark: HTTP `POST /api/v1/image/markUploaded`.
    /// - Remark: Generated from `#/paths//api/v1/image/markUploaded/post(image.markUploaded)`.
    func image_markUploaded(_ input: Operations.Image_markUploaded.Input) async throws -> Operations.Image_markUploaded.Output
    /// - Remark: HTTP `POST /api/v1/image/uploadImage`.
    /// - Remark: Generated from `#/paths//api/v1/image/uploadImage/post(image.uploadImage)`.
    func image_uploadImage(_ input: Operations.Image_uploadImage.Input) async throws -> Operations.Image_uploadImage.Output
    /// - Remark: HTTP `GET /api/v1/inventory/findDuplicates`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/findDuplicates/get(inventory.findDuplicates)`.
    func inventory_findDuplicates(_ input: Operations.Inventory_findDuplicates.Input) async throws -> Operations.Inventory_findDuplicates.Output
    /// - Remark: HTTP `GET /api/v1/inventory/getByLocationIds`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/getByLocationIds/get(inventory.getByLocationIds)`.
    func inventory_getByLocationIds(_ input: Operations.Inventory_getByLocationIds.Input) async throws -> Operations.Inventory_getByLocationIds.Output
    /// - Remark: HTTP `POST /api/v1/inventory/reconcileSession`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/reconcileSession/post(inventory.reconcileSession)`.
    func inventory_reconcileSession(_ input: Operations.Inventory_reconcileSession.Input) async throws -> Operations.Inventory_reconcileSession.Output
    /// - Remark: HTTP `POST /api/v1/inventory/resolveScanStrays`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/resolveScanStrays/post(inventory.resolveScanStrays)`.
    func inventory_resolveScanStrays(_ input: Operations.Inventory_resolveScanStrays.Input) async throws -> Operations.Inventory_resolveScanStrays.Output
    /// - Remark: HTTP `POST /api/v1/inventory/scanAtLocation`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/scanAtLocation/post(inventory.scanAtLocation)`.
    func inventory_scanAtLocation(_ input: Operations.Inventory_scanAtLocation.Input) async throws -> Operations.Inventory_scanAtLocation.Output
    /// - Remark: HTTP `POST /api/v1/location/bulkUpdateParent`.
    /// - Remark: Generated from `#/paths//api/v1/location/bulkUpdateParent/post(location.bulkUpdateParent)`.
    func location_bulkUpdateParent(_ input: Operations.Location_bulkUpdateParent.Input) async throws -> Operations.Location_bulkUpdateParent.Output
    /// - Remark: HTTP `POST /api/v1/location/ensureGlobalUnknown`.
    /// - Remark: Generated from `#/paths//api/v1/location/ensureGlobalUnknown/post(location.ensureGlobalUnknown)`.
    func location_ensureGlobalUnknown(_ input: Operations.Location_ensureGlobalUnknown.Input) async throws -> Operations.Location_ensureGlobalUnknown.Output
    /// - Remark: HTTP `GET /api/v1/location/makeTree`.
    /// - Remark: Generated from `#/paths//api/v1/location/makeTree/get(location.makeTree)`.
    func location_makeTree(_ input: Operations.Location_makeTree.Input) async throws -> Operations.Location_makeTree.Output
    /// - Remark: HTTP `GET /api/v1/problems/getCounts`.
    /// - Remark: Generated from `#/paths//api/v1/problems/getCounts/get(problems.getCounts)`.
    func problems_getCounts(_ input: Operations.Problems_getCounts.Input) async throws -> Operations.Problems_getCounts.Output
    /// - Remark: HTTP `POST /api/v1/product/findOrCreateByUPC`.
    /// - Remark: Generated from `#/paths//api/v1/product/findOrCreateByUPC/post(product.findOrCreateByUPC)`.
    func product_findOrCreateByUPC(_ input: Operations.Product_findOrCreateByUPC.Input) async throws -> Operations.Product_findOrCreateByUPC.Output
    /// - Remark: HTTP `GET /api/v1/search/find`.
    /// - Remark: Generated from `#/paths//api/v1/search/find/get(search.find)`.
    func search_find(_ input: Operations.Search_find.Input) async throws -> Operations.Search_find.Output
    /// - Remark: HTTP `GET /api/v1/task/todayBriefing`.
    /// - Remark: Generated from `#/paths//api/v1/task/todayBriefing/get(task.todayBriefing)`.
    func task_todayBriefing(_ input: Operations.Task_todayBriefing.Input) async throws -> Operations.Task_todayBriefing.Output
    /// - Remark: HTTP `GET /api/v1/upc/lookup`.
    /// - Remark: Generated from `#/paths//api/v1/upc/lookup/get(upc.lookup)`.
    func upc_lookup(_ input: Operations.Upc_lookup.Input) async throws -> Operations.Upc_lookup.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/products`.
    /// - Remark: Generated from `#/paths//api/v1/products/get(resources.product.list)`.
    func resources_product_list(_ input: Operations.Resources_product_list.Input) async throws -> Operations.Resources_product_list.Output
    /// - Remark: HTTP `GET /api/v1/products/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/products/{id}/get(resources.product.get)`.
    func resources_product_get(_ input: Operations.Resources_product_get.Input) async throws -> Operations.Resources_product_get.Output
    /// - Remark: HTTP `PATCH /api/v1/products/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/products/{id}/patch(resources.product.update)`.
    func resources_product_update(_ input: Operations.Resources_product_update.Input) async throws -> Operations.Resources_product_update.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/recipes`.
    /// - Remark: Generated from `#/paths//api/v1/recipes/get(resources.recipe.list)`.
    func resources_recipe_list(_ input: Operations.Resources_recipe_list.Input) async throws -> Operations.Resources_recipe_list.Output
    /// - Remark: HTTP `GET /api/v1/recipes/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/recipes/{id}/get(resources.recipe.get)`.
    func resources_recipe_get(_ input: Operations.Resources_recipe_get.Input) async throws -> Operations.Resources_recipe_get.Output
    /// - Remark: HTTP `PATCH /api/v1/recipes/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/recipes/{id}/patch(resources.recipe.update)`.
    func resources_recipe_update(_ input: Operations.Resources_recipe_update.Input) async throws -> Operations.Resources_recipe_update.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/ingredients`.
    /// - Remark: Generated from `#/paths//api/v1/ingredients/get(resources.ingredient.list)`.
    func resources_ingredient_list(_ input: Operations.Resources_ingredient_list.Input) async throws -> Operations.Resources_ingredient_list.Output
    /// - Remark: HTTP `GET /api/v1/ingredients/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/ingredients/{id}/get(resources.ingredient.get)`.
    func resources_ingredient_get(_ input: Operations.Resources_ingredient_get.Input) async throws -> Operations.Resources_ingredient_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/locations`.
    /// - Remark: Generated from `#/paths//api/v1/locations/get(resources.location.list)`.
    func resources_location_list(_ input: Operations.Resources_location_list.Input) async throws -> Operations.Resources_location_list.Output
    /// - Remark: HTTP `GET /api/v1/locations/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/locations/{id}/get(resources.location.get)`.
    func resources_location_get(_ input: Operations.Resources_location_get.Input) async throws -> Operations.Resources_location_get.Output
    /// - Remark: HTTP `PATCH /api/v1/locations/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/locations/{id}/patch(resources.location.update)`.
    func resources_location_update(_ input: Operations.Resources_location_update.Input) async throws -> Operations.Resources_location_update.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/inventory`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/get(resources.inventory.list)`.
    func resources_inventory_list(_ input: Operations.Resources_inventory_list.Input) async throws -> Operations.Resources_inventory_list.Output
    /// - Remark: HTTP `POST /api/v1/inventory`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/post(resources.inventory.create)`.
    func resources_inventory_create(_ input: Operations.Resources_inventory_create.Input) async throws -> Operations.Resources_inventory_create.Output
    /// - Remark: HTTP `GET /api/v1/inventory/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/{id}/get(resources.inventory.get)`.
    func resources_inventory_get(_ input: Operations.Resources_inventory_get.Input) async throws -> Operations.Resources_inventory_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/meals`.
    /// - Remark: Generated from `#/paths//api/v1/meals/get(resources.meal.list)`.
    func resources_meal_list(_ input: Operations.Resources_meal_list.Input) async throws -> Operations.Resources_meal_list.Output
    /// - Remark: HTTP `GET /api/v1/meals/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/meals/{id}/get(resources.meal.get)`.
    func resources_meal_get(_ input: Operations.Resources_meal_get.Input) async throws -> Operations.Resources_meal_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/ledger-parties`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-parties/get(resources.ledgerParty.list)`.
    func resources_ledgerParty_list(_ input: Operations.Resources_ledgerParty_list.Input) async throws -> Operations.Resources_ledgerParty_list.Output
    /// - Remark: HTTP `GET /api/v1/ledger-parties/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-parties/{id}/get(resources.ledgerParty.get)`.
    func resources_ledgerParty_get(_ input: Operations.Resources_ledgerParty_get.Input) async throws -> Operations.Resources_ledgerParty_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/ledger-transfers`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-transfers/get(resources.ledgerTransfer.list)`.
    func resources_ledgerTransfer_list(_ input: Operations.Resources_ledgerTransfer_list.Input) async throws -> Operations.Resources_ledgerTransfer_list.Output
    /// - Remark: HTTP `GET /api/v1/ledger-transfers/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-transfers/{id}/get(resources.ledgerTransfer.get)`.
    func resources_ledgerTransfer_get(_ input: Operations.Resources_ledgerTransfer_get.Input) async throws -> Operations.Resources_ledgerTransfer_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/projects`.
    /// - Remark: Generated from `#/paths//api/v1/projects/get(resources.project.list)`.
    func resources_project_list(_ input: Operations.Resources_project_list.Input) async throws -> Operations.Resources_project_list.Output
    /// - Remark: HTTP `GET /api/v1/projects/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/projects/{id}/get(resources.project.get)`.
    func resources_project_get(_ input: Operations.Resources_project_get.Input) async throws -> Operations.Resources_project_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/tasks`.
    /// - Remark: Generated from `#/paths//api/v1/tasks/get(resources.task.list)`.
    func resources_task_list(_ input: Operations.Resources_task_list.Input) async throws -> Operations.Resources_task_list.Output
    /// - Remark: HTTP `GET /api/v1/tasks/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/tasks/{id}/get(resources.task.get)`.
    func resources_task_get(_ input: Operations.Resources_task_get.Input) async throws -> Operations.Resources_task_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/vendors`.
    /// - Remark: Generated from `#/paths//api/v1/vendors/get(resources.vendor.list)`.
    func resources_vendor_list(_ input: Operations.Resources_vendor_list.Input) async throws -> Operations.Resources_vendor_list.Output
    /// - Remark: HTTP `GET /api/v1/vendors/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/vendors/{id}/get(resources.vendor.get)`.
    func resources_vendor_get(_ input: Operations.Resources_vendor_get.Input) async throws -> Operations.Resources_vendor_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/purchases`.
    /// - Remark: Generated from `#/paths//api/v1/purchases/get(resources.purchase.list)`.
    func resources_purchase_list(_ input: Operations.Resources_purchase_list.Input) async throws -> Operations.Resources_purchase_list.Output
    /// - Remark: HTTP `GET /api/v1/purchases/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/purchases/{id}/get(resources.purchase.get)`.
    func resources_purchase_get(_ input: Operations.Resources_purchase_get.Input) async throws -> Operations.Resources_purchase_get.Output
    /// - Remark: HTTP `PATCH /api/v1/purchases/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/purchases/{id}/patch(resources.purchase.update)`.
    func resources_purchase_update(_ input: Operations.Resources_purchase_update.Input) async throws -> Operations.Resources_purchase_update.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/financial-accounts`.
    /// - Remark: Generated from `#/paths//api/v1/financial-accounts/get(resources.financialAccount.list)`.
    func resources_financialAccount_list(_ input: Operations.Resources_financialAccount_list.Input) async throws -> Operations.Resources_financialAccount_list.Output
    /// - Remark: HTTP `GET /api/v1/financial-accounts/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/financial-accounts/{id}/get(resources.financialAccount.get)`.
    func resources_financialAccount_get(_ input: Operations.Resources_financialAccount_get.Input) async throws -> Operations.Resources_financialAccount_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/financial-transactions`.
    /// - Remark: Generated from `#/paths//api/v1/financial-transactions/get(resources.financialTransaction.list)`.
    func resources_financialTransaction_list(_ input: Operations.Resources_financialTransaction_list.Input) async throws -> Operations.Resources_financialTransaction_list.Output
    /// - Remark: HTTP `GET /api/v1/financial-transactions/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/financial-transactions/{id}/get(resources.financialTransaction.get)`.
    func resources_financialTransaction_get(_ input: Operations.Resources_financialTransaction_get.Input) async throws -> Operations.Resources_financialTransaction_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/wishes`.
    /// - Remark: Generated from `#/paths//api/v1/wishes/get(resources.wish.list)`.
    func resources_wish_list(_ input: Operations.Resources_wish_list.Input) async throws -> Operations.Resources_wish_list.Output
    /// - Remark: HTTP `GET /api/v1/wishes/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/wishes/{id}/get(resources.wish.get)`.
    func resources_wish_get(_ input: Operations.Resources_wish_get.Input) async throws -> Operations.Resources_wish_get.Output
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/expenses`.
    /// - Remark: Generated from `#/paths//api/v1/expenses/get(resources.expense.list)`.
    func resources_expense_list(_ input: Operations.Resources_expense_list.Input) async throws -> Operations.Resources_expense_list.Output
    /// - Remark: HTTP `GET /api/v1/expenses/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/expenses/{id}/get(resources.expense.get)`.
    func resources_expense_get(_ input: Operations.Resources_expense_get.Input) async throws -> Operations.Resources_expense_get.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /api/v1/agent/ask`.
    /// - Remark: Generated from `#/paths//api/v1/agent/ask/post(agent.ask)`.
    package func agent_ask(
        headers: Operations.Agent_ask.Input.Headers = .init(),
        body: Operations.Agent_ask.Input.Body? = nil
    ) async throws -> Operations.Agent_ask.Output {
        try await agent_ask(Operations.Agent_ask.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/dashboard/counts`.
    /// - Remark: Generated from `#/paths//api/v1/dashboard/counts/get(dashboard.counts)`.
    package func dashboard_counts(headers: Operations.Dashboard_counts.Input.Headers = .init()) async throws -> Operations.Dashboard_counts.Output {
        try await dashboard_counts(Operations.Dashboard_counts.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /api/v1/image/markUploaded`.
    /// - Remark: Generated from `#/paths//api/v1/image/markUploaded/post(image.markUploaded)`.
    package func image_markUploaded(
        headers: Operations.Image_markUploaded.Input.Headers = .init(),
        body: Operations.Image_markUploaded.Input.Body? = nil
    ) async throws -> Operations.Image_markUploaded.Output {
        try await image_markUploaded(Operations.Image_markUploaded.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/image/uploadImage`.
    /// - Remark: Generated from `#/paths//api/v1/image/uploadImage/post(image.uploadImage)`.
    package func image_uploadImage(
        headers: Operations.Image_uploadImage.Input.Headers = .init(),
        body: Operations.Image_uploadImage.Input.Body? = nil
    ) async throws -> Operations.Image_uploadImage.Output {
        try await image_uploadImage(Operations.Image_uploadImage.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/inventory/findDuplicates`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/findDuplicates/get(inventory.findDuplicates)`.
    package func inventory_findDuplicates(
        query: Operations.Inventory_findDuplicates.Input.Query = .init(),
        headers: Operations.Inventory_findDuplicates.Input.Headers = .init()
    ) async throws -> Operations.Inventory_findDuplicates.Output {
        try await inventory_findDuplicates(Operations.Inventory_findDuplicates.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/inventory/getByLocationIds`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/getByLocationIds/get(inventory.getByLocationIds)`.
    package func inventory_getByLocationIds(
        query: Operations.Inventory_getByLocationIds.Input.Query,
        headers: Operations.Inventory_getByLocationIds.Input.Headers = .init()
    ) async throws -> Operations.Inventory_getByLocationIds.Output {
        try await inventory_getByLocationIds(Operations.Inventory_getByLocationIds.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/inventory/reconcileSession`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/reconcileSession/post(inventory.reconcileSession)`.
    package func inventory_reconcileSession(
        headers: Operations.Inventory_reconcileSession.Input.Headers = .init(),
        body: Operations.Inventory_reconcileSession.Input.Body? = nil
    ) async throws -> Operations.Inventory_reconcileSession.Output {
        try await inventory_reconcileSession(Operations.Inventory_reconcileSession.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/inventory/resolveScanStrays`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/resolveScanStrays/post(inventory.resolveScanStrays)`.
    package func inventory_resolveScanStrays(
        headers: Operations.Inventory_resolveScanStrays.Input.Headers = .init(),
        body: Operations.Inventory_resolveScanStrays.Input.Body? = nil
    ) async throws -> Operations.Inventory_resolveScanStrays.Output {
        try await inventory_resolveScanStrays(Operations.Inventory_resolveScanStrays.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/inventory/scanAtLocation`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/scanAtLocation/post(inventory.scanAtLocation)`.
    package func inventory_scanAtLocation(
        headers: Operations.Inventory_scanAtLocation.Input.Headers = .init(),
        body: Operations.Inventory_scanAtLocation.Input.Body? = nil
    ) async throws -> Operations.Inventory_scanAtLocation.Output {
        try await inventory_scanAtLocation(Operations.Inventory_scanAtLocation.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/location/bulkUpdateParent`.
    /// - Remark: Generated from `#/paths//api/v1/location/bulkUpdateParent/post(location.bulkUpdateParent)`.
    package func location_bulkUpdateParent(
        headers: Operations.Location_bulkUpdateParent.Input.Headers = .init(),
        body: Operations.Location_bulkUpdateParent.Input.Body? = nil
    ) async throws -> Operations.Location_bulkUpdateParent.Output {
        try await location_bulkUpdateParent(Operations.Location_bulkUpdateParent.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/location/ensureGlobalUnknown`.
    /// - Remark: Generated from `#/paths//api/v1/location/ensureGlobalUnknown/post(location.ensureGlobalUnknown)`.
    package func location_ensureGlobalUnknown(
        headers: Operations.Location_ensureGlobalUnknown.Input.Headers = .init(),
        body: Operations.Location_ensureGlobalUnknown.Input.Body? = nil
    ) async throws -> Operations.Location_ensureGlobalUnknown.Output {
        try await location_ensureGlobalUnknown(Operations.Location_ensureGlobalUnknown.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/location/makeTree`.
    /// - Remark: Generated from `#/paths//api/v1/location/makeTree/get(location.makeTree)`.
    package func location_makeTree(headers: Operations.Location_makeTree.Input.Headers = .init()) async throws -> Operations.Location_makeTree.Output {
        try await location_makeTree(Operations.Location_makeTree.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /api/v1/problems/getCounts`.
    /// - Remark: Generated from `#/paths//api/v1/problems/getCounts/get(problems.getCounts)`.
    package func problems_getCounts(headers: Operations.Problems_getCounts.Input.Headers = .init()) async throws -> Operations.Problems_getCounts.Output {
        try await problems_getCounts(Operations.Problems_getCounts.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /api/v1/product/findOrCreateByUPC`.
    /// - Remark: Generated from `#/paths//api/v1/product/findOrCreateByUPC/post(product.findOrCreateByUPC)`.
    package func product_findOrCreateByUPC(
        headers: Operations.Product_findOrCreateByUPC.Input.Headers = .init(),
        body: Operations.Product_findOrCreateByUPC.Input.Body? = nil
    ) async throws -> Operations.Product_findOrCreateByUPC.Output {
        try await product_findOrCreateByUPC(Operations.Product_findOrCreateByUPC.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/search/find`.
    /// - Remark: Generated from `#/paths//api/v1/search/find/get(search.find)`.
    package func search_find(
        query: Operations.Search_find.Input.Query,
        headers: Operations.Search_find.Input.Headers = .init()
    ) async throws -> Operations.Search_find.Output {
        try await search_find(Operations.Search_find.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/task/todayBriefing`.
    /// - Remark: Generated from `#/paths//api/v1/task/todayBriefing/get(task.todayBriefing)`.
    package func task_todayBriefing(headers: Operations.Task_todayBriefing.Input.Headers = .init()) async throws -> Operations.Task_todayBriefing.Output {
        try await task_todayBriefing(Operations.Task_todayBriefing.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /api/v1/upc/lookup`.
    /// - Remark: Generated from `#/paths//api/v1/upc/lookup/get(upc.lookup)`.
    package func upc_lookup(
        query: Operations.Upc_lookup.Input.Query,
        headers: Operations.Upc_lookup.Input.Headers = .init()
    ) async throws -> Operations.Upc_lookup.Output {
        try await upc_lookup(Operations.Upc_lookup.Input(
            query: query,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/products`.
    /// - Remark: Generated from `#/paths//api/v1/products/get(resources.product.list)`.
    package func resources_product_list(
        query: Operations.Resources_product_list.Input.Query = .init(),
        headers: Operations.Resources_product_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_product_list.Output {
        try await resources_product_list(Operations.Resources_product_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/products/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/products/{id}/get(resources.product.get)`.
    package func resources_product_get(
        path: Operations.Resources_product_get.Input.Path,
        headers: Operations.Resources_product_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_product_get.Output {
        try await resources_product_get(Operations.Resources_product_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/products/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/products/{id}/patch(resources.product.update)`.
    package func resources_product_update(
        path: Operations.Resources_product_update.Input.Path,
        headers: Operations.Resources_product_update.Input.Headers = .init(),
        body: Operations.Resources_product_update.Input.Body? = nil
    ) async throws -> Operations.Resources_product_update.Output {
        try await resources_product_update(Operations.Resources_product_update.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/recipes`.
    /// - Remark: Generated from `#/paths//api/v1/recipes/get(resources.recipe.list)`.
    package func resources_recipe_list(
        query: Operations.Resources_recipe_list.Input.Query = .init(),
        headers: Operations.Resources_recipe_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_recipe_list.Output {
        try await resources_recipe_list(Operations.Resources_recipe_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/recipes/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/recipes/{id}/get(resources.recipe.get)`.
    package func resources_recipe_get(
        path: Operations.Resources_recipe_get.Input.Path,
        headers: Operations.Resources_recipe_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_recipe_get.Output {
        try await resources_recipe_get(Operations.Resources_recipe_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/recipes/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/recipes/{id}/patch(resources.recipe.update)`.
    package func resources_recipe_update(
        path: Operations.Resources_recipe_update.Input.Path,
        headers: Operations.Resources_recipe_update.Input.Headers = .init(),
        body: Operations.Resources_recipe_update.Input.Body? = nil
    ) async throws -> Operations.Resources_recipe_update.Output {
        try await resources_recipe_update(Operations.Resources_recipe_update.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/ingredients`.
    /// - Remark: Generated from `#/paths//api/v1/ingredients/get(resources.ingredient.list)`.
    package func resources_ingredient_list(
        query: Operations.Resources_ingredient_list.Input.Query = .init(),
        headers: Operations.Resources_ingredient_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_ingredient_list.Output {
        try await resources_ingredient_list(Operations.Resources_ingredient_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/ingredients/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/ingredients/{id}/get(resources.ingredient.get)`.
    package func resources_ingredient_get(
        path: Operations.Resources_ingredient_get.Input.Path,
        headers: Operations.Resources_ingredient_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_ingredient_get.Output {
        try await resources_ingredient_get(Operations.Resources_ingredient_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/locations`.
    /// - Remark: Generated from `#/paths//api/v1/locations/get(resources.location.list)`.
    package func resources_location_list(
        query: Operations.Resources_location_list.Input.Query = .init(),
        headers: Operations.Resources_location_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_location_list.Output {
        try await resources_location_list(Operations.Resources_location_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/locations/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/locations/{id}/get(resources.location.get)`.
    package func resources_location_get(
        path: Operations.Resources_location_get.Input.Path,
        headers: Operations.Resources_location_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_location_get.Output {
        try await resources_location_get(Operations.Resources_location_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/locations/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/locations/{id}/patch(resources.location.update)`.
    package func resources_location_update(
        path: Operations.Resources_location_update.Input.Path,
        headers: Operations.Resources_location_update.Input.Headers = .init(),
        body: Operations.Resources_location_update.Input.Body? = nil
    ) async throws -> Operations.Resources_location_update.Output {
        try await resources_location_update(Operations.Resources_location_update.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/inventory`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/get(resources.inventory.list)`.
    package func resources_inventory_list(
        query: Operations.Resources_inventory_list.Input.Query = .init(),
        headers: Operations.Resources_inventory_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_inventory_list.Output {
        try await resources_inventory_list(Operations.Resources_inventory_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/inventory`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/post(resources.inventory.create)`.
    package func resources_inventory_create(
        headers: Operations.Resources_inventory_create.Input.Headers = .init(),
        body: Operations.Resources_inventory_create.Input.Body? = nil
    ) async throws -> Operations.Resources_inventory_create.Output {
        try await resources_inventory_create(Operations.Resources_inventory_create.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/inventory/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/inventory/{id}/get(resources.inventory.get)`.
    package func resources_inventory_get(
        path: Operations.Resources_inventory_get.Input.Path,
        headers: Operations.Resources_inventory_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_inventory_get.Output {
        try await resources_inventory_get(Operations.Resources_inventory_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/meals`.
    /// - Remark: Generated from `#/paths//api/v1/meals/get(resources.meal.list)`.
    package func resources_meal_list(
        query: Operations.Resources_meal_list.Input.Query = .init(),
        headers: Operations.Resources_meal_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_meal_list.Output {
        try await resources_meal_list(Operations.Resources_meal_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/meals/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/meals/{id}/get(resources.meal.get)`.
    package func resources_meal_get(
        path: Operations.Resources_meal_get.Input.Path,
        headers: Operations.Resources_meal_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_meal_get.Output {
        try await resources_meal_get(Operations.Resources_meal_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/ledger-parties`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-parties/get(resources.ledgerParty.list)`.
    package func resources_ledgerParty_list(
        query: Operations.Resources_ledgerParty_list.Input.Query = .init(),
        headers: Operations.Resources_ledgerParty_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_ledgerParty_list.Output {
        try await resources_ledgerParty_list(Operations.Resources_ledgerParty_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/ledger-parties/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-parties/{id}/get(resources.ledgerParty.get)`.
    package func resources_ledgerParty_get(
        path: Operations.Resources_ledgerParty_get.Input.Path,
        headers: Operations.Resources_ledgerParty_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_ledgerParty_get.Output {
        try await resources_ledgerParty_get(Operations.Resources_ledgerParty_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/ledger-transfers`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-transfers/get(resources.ledgerTransfer.list)`.
    package func resources_ledgerTransfer_list(
        query: Operations.Resources_ledgerTransfer_list.Input.Query = .init(),
        headers: Operations.Resources_ledgerTransfer_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_ledgerTransfer_list.Output {
        try await resources_ledgerTransfer_list(Operations.Resources_ledgerTransfer_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/ledger-transfers/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/ledger-transfers/{id}/get(resources.ledgerTransfer.get)`.
    package func resources_ledgerTransfer_get(
        path: Operations.Resources_ledgerTransfer_get.Input.Path,
        headers: Operations.Resources_ledgerTransfer_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_ledgerTransfer_get.Output {
        try await resources_ledgerTransfer_get(Operations.Resources_ledgerTransfer_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/projects`.
    /// - Remark: Generated from `#/paths//api/v1/projects/get(resources.project.list)`.
    package func resources_project_list(
        query: Operations.Resources_project_list.Input.Query = .init(),
        headers: Operations.Resources_project_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_project_list.Output {
        try await resources_project_list(Operations.Resources_project_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/projects/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/projects/{id}/get(resources.project.get)`.
    package func resources_project_get(
        path: Operations.Resources_project_get.Input.Path,
        headers: Operations.Resources_project_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_project_get.Output {
        try await resources_project_get(Operations.Resources_project_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/tasks`.
    /// - Remark: Generated from `#/paths//api/v1/tasks/get(resources.task.list)`.
    package func resources_task_list(
        query: Operations.Resources_task_list.Input.Query = .init(),
        headers: Operations.Resources_task_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_task_list.Output {
        try await resources_task_list(Operations.Resources_task_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/tasks/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/tasks/{id}/get(resources.task.get)`.
    package func resources_task_get(
        path: Operations.Resources_task_get.Input.Path,
        headers: Operations.Resources_task_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_task_get.Output {
        try await resources_task_get(Operations.Resources_task_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/vendors`.
    /// - Remark: Generated from `#/paths//api/v1/vendors/get(resources.vendor.list)`.
    package func resources_vendor_list(
        query: Operations.Resources_vendor_list.Input.Query = .init(),
        headers: Operations.Resources_vendor_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_vendor_list.Output {
        try await resources_vendor_list(Operations.Resources_vendor_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/vendors/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/vendors/{id}/get(resources.vendor.get)`.
    package func resources_vendor_get(
        path: Operations.Resources_vendor_get.Input.Path,
        headers: Operations.Resources_vendor_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_vendor_get.Output {
        try await resources_vendor_get(Operations.Resources_vendor_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/purchases`.
    /// - Remark: Generated from `#/paths//api/v1/purchases/get(resources.purchase.list)`.
    package func resources_purchase_list(
        query: Operations.Resources_purchase_list.Input.Query = .init(),
        headers: Operations.Resources_purchase_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_purchase_list.Output {
        try await resources_purchase_list(Operations.Resources_purchase_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/purchases/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/purchases/{id}/get(resources.purchase.get)`.
    package func resources_purchase_get(
        path: Operations.Resources_purchase_get.Input.Path,
        headers: Operations.Resources_purchase_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_purchase_get.Output {
        try await resources_purchase_get(Operations.Resources_purchase_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/purchases/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/purchases/{id}/patch(resources.purchase.update)`.
    package func resources_purchase_update(
        path: Operations.Resources_purchase_update.Input.Path,
        headers: Operations.Resources_purchase_update.Input.Headers = .init(),
        body: Operations.Resources_purchase_update.Input.Body? = nil
    ) async throws -> Operations.Resources_purchase_update.Output {
        try await resources_purchase_update(Operations.Resources_purchase_update.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/financial-accounts`.
    /// - Remark: Generated from `#/paths//api/v1/financial-accounts/get(resources.financialAccount.list)`.
    package func resources_financialAccount_list(
        query: Operations.Resources_financialAccount_list.Input.Query = .init(),
        headers: Operations.Resources_financialAccount_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_financialAccount_list.Output {
        try await resources_financialAccount_list(Operations.Resources_financialAccount_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/financial-accounts/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/financial-accounts/{id}/get(resources.financialAccount.get)`.
    package func resources_financialAccount_get(
        path: Operations.Resources_financialAccount_get.Input.Path,
        headers: Operations.Resources_financialAccount_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_financialAccount_get.Output {
        try await resources_financialAccount_get(Operations.Resources_financialAccount_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/financial-transactions`.
    /// - Remark: Generated from `#/paths//api/v1/financial-transactions/get(resources.financialTransaction.list)`.
    package func resources_financialTransaction_list(
        query: Operations.Resources_financialTransaction_list.Input.Query = .init(),
        headers: Operations.Resources_financialTransaction_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_financialTransaction_list.Output {
        try await resources_financialTransaction_list(Operations.Resources_financialTransaction_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/financial-transactions/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/financial-transactions/{id}/get(resources.financialTransaction.get)`.
    package func resources_financialTransaction_get(
        path: Operations.Resources_financialTransaction_get.Input.Path,
        headers: Operations.Resources_financialTransaction_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_financialTransaction_get.Output {
        try await resources_financialTransaction_get(Operations.Resources_financialTransaction_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/wishes`.
    /// - Remark: Generated from `#/paths//api/v1/wishes/get(resources.wish.list)`.
    package func resources_wish_list(
        query: Operations.Resources_wish_list.Input.Query = .init(),
        headers: Operations.Resources_wish_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_wish_list.Output {
        try await resources_wish_list(Operations.Resources_wish_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/wishes/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/wishes/{id}/get(resources.wish.get)`.
    package func resources_wish_get(
        path: Operations.Resources_wish_get.Input.Path,
        headers: Operations.Resources_wish_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_wish_get.Output {
        try await resources_wish_get(Operations.Resources_wish_get.Input(
            path: path,
            headers: headers
        ))
    }
    /// Use page=1&pageSize=20&sort=name,-createdAt. Filters are individual query parameters: text is literal, numbers and booleans are plain, and a list repeats its key (tag=a&tag=b). Response pagination metadata remains zero-based. Resource methods depend on entity capabilities.
    ///
    /// - Remark: HTTP `GET /api/v1/expenses`.
    /// - Remark: Generated from `#/paths//api/v1/expenses/get(resources.expense.list)`.
    package func resources_expense_list(
        query: Operations.Resources_expense_list.Input.Query = .init(),
        headers: Operations.Resources_expense_list.Input.Headers = .init()
    ) async throws -> Operations.Resources_expense_list.Output {
        try await resources_expense_list(Operations.Resources_expense_list.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/expenses/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/expenses/{id}/get(resources.expense.get)`.
    package func resources_expense_get(
        path: Operations.Resources_expense_get.Input.Path,
        headers: Operations.Resources_expense_get.Input.Headers = .init()
    ) async throws -> Operations.Resources_expense_get.Output {
        try await resources_expense_get(Operations.Resources_expense_get.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
package enum Servers {
    package enum Server1 {
        package static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    package static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "/",
            variables: []
        )
    }
}
