/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false --strict-vars=false` (hash: 7150253ee5e7b8a9898c2f375970c44e)
interface __BaseEnv_Env {
	PROBLEM_COUNTS_KV: KVNamespace;
	HYPERDRIVE: Hyperdrive;
	HYPERDRIVE_CACHED: Hyperdrive;
	BACKGROUND_QUEUE: Queue;
	TELEMETRY_QUEUE: Queue;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	NODE_ENV: string;
	ALLOW_SIGNUP: string;
	E2E_AUTH_TEST_MODE: string;
	SENTRY_ENVIRONMENT: string;
	APP_ORIGIN: string;
	R2_KEY_PREFIX: string;
	BETTER_AUTH_SECRET: string;
	DATABASE_URL: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ENDPOINT: string;
	R2_BUCKET_NAME: string;
	R2_PUBLIC_URL: string;
	USDA_API_URL: string;
	UPC_LOOKUP_API_URL: string;
	UPC_LOOKUP_API_KEY: string;
	NOTION_API_KEY: string;
	CALENDAR_FEED: DurableObjectNamespace<import("./src/cf-server").CalendarFeedDurableObject>;
	USDA_API: Fetcher /* usda-api */;
	UPC_LOOKUP: Fetcher /* upc-lookup */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cf-server");
		durableNamespaces: "CalendarFeedDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "ALLOW_SIGNUP" | "E2E_AUTH_TEST_MODE" | "SENTRY_ENVIRONMENT" | "APP_ORIGIN" | "R2_KEY_PREFIX" | "BETTER_AUTH_SECRET" | "DATABASE_URL" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "R2_ENDPOINT" | "R2_BUCKET_NAME" | "R2_PUBLIC_URL" | "USDA_API_URL" | "UPC_LOOKUP_API_URL" | "UPC_LOOKUP_API_KEY" | "NOTION_API_KEY">> {}
}
