/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false --strict-vars=false` (hash: a764ff485b4281335edc573fa43e36e3)
interface __BaseEnv_Env {
	VECTORIZE: VectorizeIndex;
	HYPERDRIVE: Hyperdrive;
	HYPERDRIVE_CACHED: Hyperdrive;
	BACKGROUND_QUEUE: Queue;
	TELEMETRY_QUEUE: Queue;
	PURCHASE_AGENT_QUEUE: Queue;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	NODE_ENV: string;
	ALLOW_SIGNUP: string;
	E2E_AUTH_TEST_MODE: string;
	APP_ORIGIN: string;
	R2_KEY_PREFIX: string;
	GOOGLE_CLIENT_ID: string;
	BETTER_AUTH_SECRET: string;
	DATABASE_URL: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ENDPOINT: string;
	R2_BUCKET_NAME: string;
	R2_PUBLIC_URL: string;
	USDA_API_URL: string;
	UPC_UPSTREAM_DISABLED: string;
	NOTION_API_KEY: string;
	DB_FRESHNESS: DurableObjectNamespace<import("./src/server/worker-bindings").DatabaseFreshnessDurableObject>;
	CALENDAR_FEED: DurableObjectNamespace<import("./src/server/worker-bindings").CalendarFeedDurableObject>;
	PURCHASE_IMPORT: DurableObjectNamespace<import("./src/server/worker-bindings").PurchaseImportDurableObject>;
	IMAGE_PROCESSING: DurableObjectNamespace<import("./src/server/worker-bindings").ImageProcessingDurableObject>;
	AI_RESPONSE_CACHE: DurableObjectNamespace<import("./src/server/worker-bindings").AiResponseCacheDurableObject>;
	USDA_API: Fetcher /* usda-api */;
	PURCHASE_AGENT: Fetcher /* purchase-agent */;
	SEARCH_INDEX_REPAIR: Workflow<Parameters<import("./src/server/worker-bindings").SearchIndexRepairWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/worker-bindings");
		durableNamespaces: "DatabaseFreshnessDurableObject" | "CalendarFeedDurableObject" | "PurchaseImportDurableObject" | "ImageProcessingDurableObject" | "AiResponseCacheDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "ALLOW_SIGNUP" | "E2E_AUTH_TEST_MODE" | "APP_ORIGIN" | "R2_KEY_PREFIX" | "GOOGLE_CLIENT_ID" | "BETTER_AUTH_SECRET" | "DATABASE_URL" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "R2_ENDPOINT" | "R2_BUCKET_NAME" | "R2_PUBLIC_URL" | "USDA_API_URL" | "UPC_UPSTREAM_DISABLED" | "NOTION_API_KEY">> {}
}
