/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars=false --include-runtime=false` (hash: e25138c15dc6b9ed2212ec7395a0413c)
interface __BaseEnv_Env {
  HYPERDRIVE: Hyperdrive;
  R2_KEY_PREFIX: string;
  NODE_ENV: string;
  DATABASE_URL: string;
  BETTER_AUTH_SECRET: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  R2_ENDPOINT: string;
  R2_BUCKET_NAME: string;
  R2_PUBLIC_URL: string;
  E2E_TEST_USER_EMAIL: string;
  E2E_TEST_USER_PASSWORD: string;
  UPC_LOOKUP_API_URL: string;
  UPC_LOOKUP_API_KEY: string;
  GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: string;
  AI_GATEWAY_API_KEY: string;
  NOTION_API_KEY: string;
  USDA_API_URL: string;
  USDA_API: Fetcher /* usda-api */;
  UPC_LOOKUP: Fetcher /* upc-lookup */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/cf-server");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "R2_KEY_PREFIX"
        | "NODE_ENV"
        | "DATABASE_URL"
        | "BETTER_AUTH_SECRET"
        | "R2_ACCESS_KEY_ID"
        | "R2_SECRET_ACCESS_KEY"
        | "R2_ENDPOINT"
        | "R2_BUCKET_NAME"
        | "R2_PUBLIC_URL"
        | "E2E_TEST_USER_EMAIL"
        | "E2E_TEST_USER_PASSWORD"
        | "UPC_LOOKUP_API_URL"
        | "UPC_LOOKUP_API_KEY"
        | "GOOGLE_SERVICE_ACCOUNT_EMAIL"
        | "GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY"
        | "AI_GATEWAY_API_KEY"
        | "NOTION_API_KEY"
        | "USDA_API_URL"
      >
    > {}
}
