import type { GardenGuidesDocumentInput } from "./garden-guide";

/**
 * Source-specific planting-window calendar data for the household's garden
 * guides. Kept as a TypeScript module (not JSON) so `satisfies` checks it at
 * compile time instead of parsing an unverified runtime JSON import.
 *
 * Every source/guide/window value here must stay byte-for-byte identical to
 * the original `apps/web/src/server/garden/planting-guides.json` it was
 * converted from.
 */
export const plantingGuides = {
  schemaVersion: 1,
  sources: [
    {
      id: "uc-sunny",
      name: "UC Master Gardeners: Sunny areas of San Francisco and northern San Mateo County",
      url: "https://www.ucanr.edu/sites/default/files/2023-05/384712.pdf",
      publishedOrRevised: "Revised 2023-05-25",
      reviewedAt: "2026-09-12",
      basedOn: ["Golden Gate Gardening: Third Edition, Pam Peirce (2010)"],
      notes:
        "S means seed and T means transplant. The calendar marks first-half and second-half months separately.",
    },
    {
      id: "uc-foggy",
      name: "UC Master Gardeners: Foggy areas of San Francisco and coastal San Mateo County",
      url: "https://ucanr.edu/sites/default/files/2017-03/259572.pdf",
      publishedOrRevised: "Revised 2017-03-27",
      reviewedAt: "2026-09-12",
      basedOn: ["Golden Gate Gardening: Third Edition, Pam Peirce (2010)"],
      notes:
        "S means seed and T means transplant. The calendar marks first-half and second-half months separately.",
    },
    {
      id: "sf-bay-gardening",
      name: "SF Bay Gardening: Bay Area Planting Calendar",
      url: "https://sfbaygardening.com/resources/bay-area-planting-calendar/",
      publishedOrRevised: "Updated 2018-10-10",
      reviewedAt: "2026-09-12",
      basedOn: [
        "UC Master Gardener calendar",
        "Golden Gate Gardening: Third Edition, Pam Peirce (2010)",
        "SF Seed Library planting calendar",
      ],
      notes:
        "Unmarked entries are direct-sown seeds; its seedling icon denotes seedlings or plants. It is not an independent vote from its listed upstream sources.",
    },
    {
      id: "sloat",
      name: "Sloat Garden Center: Vegetable Planting Calendar",
      url: "https://sloatgardens.com/wp-content/uploads/2025/02/vegetable-planting-chart-calendar.pdf",
      publishedOrRevised: "2025-02-12",
      reviewedAt: "2026-09-12",
      basedOn: [],
      notes:
        "The chart names best planting months but does not state seed versus transplant method. Asterisks identify crops that will not thrive in cool areas.",
    },
  ],
  guides: [
    {
      key: "artichoke",
      name: "Artichoke",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "root",
          months: [1, 2, 3, 4, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "root",
          months: [1, 2, 3, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "root",
          months: [1, 2, 3, 4, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "basil",
      name: "Basil",
      aliases: [],
      windows: [
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "bean-fava",
      name: "Fava bean",
      aliases: ["broad bean"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "sow",
          months: [5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "bean-runner",
      name: "Runner bean",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [3, 4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [3, 4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [3],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "bean-snap",
      name: "Snap bean",
      aliases: ["bush bean"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "beet",
      name: "Beet",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "broccoli",
      name: "Broccoli",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [10],
          monthPart: "weeks-1-2",
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "transplant",
          months: [10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "transplant",
          months: [10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "brussels-sprout",
      name: "Brussels sprout",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "transplant",
          months: [5],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "cabbage",
      name: "Cabbage",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [1],
          monthPart: "weeks-3-4",
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [10],
          monthPart: "weeks-1-2",
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1],
          monthPart: "weeks-3-4",
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "carrot",
      name: "Carrot",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "sow",
          months: [9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "cauliflower",
      name: "Cauliflower",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [10],
          monthPart: "weeks-1-2",
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [9],
          monthPart: "weeks-1-2",
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [2, 3, 5, 6, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "transplant",
          months: [4, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "celery",
      name: "Celery",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [3, 4, 5, 6, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "transplant",
          months: [7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "chard",
      name: "Swiss chard",
      aliases: ["chard"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
          monthPart: null,
          notes: "Sloat groups chard and kale.",
        },
      ],
      notes: null,
    },
    {
      key: "collard",
      name: "Collard",
      aliases: ["collards"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [2, 3, 4, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "sow",
          months: [1],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "sow",
          months: [10],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "corn",
      name: "Early corn",
      aliases: ["corn"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "cucumber",
      name: "Cucumber",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [3, 4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [3, 4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [3, 4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "eggplant",
      name: "Eggplant",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [4, 5],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [4, 5],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: "Will not thrive in cool areas.",
        },
      ],
      notes: null,
    },
    {
      key: "garlic",
      name: "Garlic",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "set",
          months: [1, 2, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "set",
          months: [10],
          monthPart: "weeks-3-4",
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "set",
          months: [1, 2, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "set",
          months: [10],
          monthPart: "weeks-3-4",
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "set",
          months: [1, 2, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "kale",
      name: "Kale",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [2, 3, 4, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
          monthPart: null,
          notes: "Sloat groups chard and kale.",
        },
      ],
      notes: null,
    },
    {
      key: "kohlrabi",
      name: "Kohlrabi",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "transplant",
          months: [1],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "transplant",
          months: [2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 7, 8],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "leek",
      name: "Leek",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1, 2, 3, 4],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [2, 3, 4],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "lettuce",
      name: "Lettuce",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "mustard",
      name: "Mustard greens",
      aliases: ["mustard"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [2, 3, 4, 5, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1],
          monthPart: "weeks-3-4",
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1],
          monthPart: "weeks-3-4",
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "sow",
          months: [1, 5, 6, 7, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [2, 3, 4, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "onion",
      name: "Onion",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [1, 2, 3, 4, 5, 6, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 4, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "sow",
          months: [5],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [1, 2, 3],
          monthPart: null,
          notes: "Sloat labels this bulbing onions.",
        },
      ],
      notes: null,
    },
    {
      key: "parsnip",
      name: "Parsnip",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "sow",
          months: [2],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "sow",
          months: [9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "pea",
      name: "Pea",
      aliases: ["peas"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [2, 3, 8, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [2, 3, 8, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "sow",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "pepper",
      name: "Pepper",
      aliases: ["peppers"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [5],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [6],
          monthPart: "weeks-1-2",
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [5, 6],
          monthPart: null,
          notes: "Will not thrive in cool areas.",
        },
      ],
      notes: null,
    },
    {
      key: "potato",
      name: "Potato",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "tuber",
          months: [2, 3, 4, 5, 6, 7, 8],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "tuber",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "tuber",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 5, 6, 8],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "radish",
      name: "Radish",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "rhubarb",
      name: "Rhubarb",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "root",
          months: [1, 2, 3],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "root",
          months: [1, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "root",
          months: [1],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "root",
          months: [2, 3, 4],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "foggy",
          method: "root",
          months: [12],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "shallot",
      name: "Shallot",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "set",
          months: [1, 2, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "set",
          months: [1, 2, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "set",
          months: [1, 2, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "spinach",
      name: "Spinach",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [2, 3, 4, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [2, 3, 4, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [2, 3, 4, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [2, 3, 4, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [1, 2, 3, 4, 7, 8, 9, 10, 11, 12],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "squash-summer",
      name: "Summer squash",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [3, 4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [3, 4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [3, 4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6, 7],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "squash-winter",
      name: "Winter squash",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [5, 6],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "sunflower",
      name: "Sunflower",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "tomato",
      name: "Tomato",
      aliases: ["tomatoes"],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "transplant",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "transplant",
          months: [4],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "transplant",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [4, 5, 6],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "turnip",
      name: "Turnip",
      aliases: [],
      windows: [
        {
          sourceId: "uc-sunny",
          microclimate: "sunny",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "uc-foggy",
          microclimate: "foggy",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "bay-area",
          method: "sow",
          months: [1, 2, 3, 4, 5, 6, 7, 8, 9],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sf-bay-gardening",
          microclimate: "sunny",
          method: "sow",
          months: [10],
          monthPart: null,
          notes: null,
        },
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "melon",
      name: "Melon",
      aliases: [],
      windows: [
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [5, 6],
          monthPart: null,
          notes: "Will not thrive in cool areas.",
        },
      ],
      notes: null,
    },
    {
      key: "pumpkin",
      name: "Pumpkin",
      aliases: ["pumpkins"],
      windows: [
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [5, 6],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "rutabaga",
      name: "Rutabaga",
      aliases: [],
      windows: [
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [2, 3, 8, 9],
          monthPart: null,
          notes: null,
        },
      ],
      notes: null,
    },
    {
      key: "watermelon",
      name: "Watermelon",
      aliases: [],
      windows: [
        {
          sourceId: "sloat",
          microclimate: "bay-area",
          method: "unspecified",
          months: [5, 6],
          monthPart: null,
          notes: "Will not thrive in cool areas.",
        },
      ],
      notes: null,
    },
  ],
} satisfies GardenGuidesDocumentInput;

/** Every guide key, in declaration order — usable directly by `z.enum`. */
export const gardenGuideKeys = [
  "artichoke",
  "basil",
  "bean-fava",
  "bean-runner",
  "bean-snap",
  "beet",
  "broccoli",
  "brussels-sprout",
  "cabbage",
  "carrot",
  "cauliflower",
  "celery",
  "chard",
  "collard",
  "corn",
  "cucumber",
  "eggplant",
  "garlic",
  "kale",
  "kohlrabi",
  "leek",
  "lettuce",
  "mustard",
  "onion",
  "parsnip",
  "pea",
  "pepper",
  "potato",
  "radish",
  "rhubarb",
  "shallot",
  "spinach",
  "squash-summer",
  "squash-winter",
  "sunflower",
  "tomato",
  "turnip",
  "melon",
  "pumpkin",
  "rutabaga",
  "watermelon",
] as const;
