import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { EntityDeclarationError } from "./declarations.ts";
import type { EntityArtifacts } from "./declarations.ts";

export const generatedHeader =
  "// Generated by `pnpm entity:generate` from `packages/schemas/src/entity-definitions/*.entity.ts`. Do not edit.\n\n";

export const compactLiteral = <T>(value: T) =>
  JSON.stringify(value).replaceAll(
    /"([A-Za-z_$][\w$]*)":/g,
    (_, key: string) => `${key}:`,
  );

const formatSource = (root: string, artifact: EntityArtifacts): string => {
  // oxfmt only understands the JS/TS family; it returns the literal string
  // "Unsupported file type for stdin-filepath" for anything else (e.g. the
  // generated Swift catalog). Non-.ts artifacts pass through unformatted.
  if (!artifact.relativePath.endsWith(".ts")) return artifact.source;
  const result = execFileSync(
    "pnpm",
    ["exec", "oxfmt", "--stdin-filepath", artifact.relativePath],
    { cwd: root, encoding: "utf8", input: artifact.source },
  );
  return result;
};

const ARTIFACT_HASH_PATTERN =
  /^\/\/ Entity artifact hashes: source=([a-f0-9]+) content=([a-f0-9]+)\n/m;
const artifactHash = (source: string) =>
  createHash("sha256").update(source).digest("hex").slice(0, 16);

export const sealArtifact = (
  root: string,
  artifact: EntityArtifacts,
): EntityArtifacts => {
  const formatted = formatSource(root, artifact);
  const hashLine = `// Entity artifact hashes: source=${artifactHash(artifact.source)} content=${artifactHash(formatted)}\n`;
  return {
    ...artifact,
    source: formatted.replace(generatedHeader, generatedHeader + hashLine),
  };
};

// The generator ownership header's first line, shared by every artifact this
// generator writes (the `.ts` family and `EntityCatalog.swift` alike — the
// Swift catalog only appends its own `// swift-format-ignore-file` line after
// it). Matching on this instead of a hand-maintained filename allowlist means
// a retired artifact name is still caught as extraneous: the stale file on
// disk keeps carrying the header until something deletes it.
// SAFETY: generatedHeader is a non-empty literal defined above, so splitting
// on "\n" always yields at least one element.
const generatedHeaderMarker = generatedHeader.split("\n")[0] as string;

const carriesGeneratedHeader = async (absolutePath: string) => {
  try {
    const content = await readFile(absolutePath, "utf8");
    return content.startsWith(generatedHeaderMarker);
  } catch {
    // Unreadable (permissions, binary, race with a concurrent delete) is
    // never one of ours to flag.
    return false;
  }
};

const findExtraArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  const expected = new Set(artifacts.map(({ relativePath }) => relativePath));
  const directories = new Set(
    artifacts.map(({ relativePath }) => dirname(relativePath)),
  );
  const extras: string[] = [];
  for (const directory of directories) {
    const absoluteDirectory = resolve(root, directory);
    try {
      const entries = await readdir(absoluteDirectory, { withFileTypes: true });
      for (const entry of entries) {
        const relativePath = `${directory}/${entry.name}`;
        if (
          entry.isFile() &&
          !expected.has(relativePath) &&
          (await carriesGeneratedHeader(resolve(root, relativePath)))
        ) {
          extras.push(relativePath);
        }
      }
    } catch (error) {
      if (
        !(error instanceof Error) ||
        !("code" in error) ||
        error.code !== "ENOENT"
      ) {
        throw error;
      }
    }
  }
  return extras.sort();
};

export const checkEntityArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  const problems: string[] = [];
  for (const artifact of artifacts) {
    const artifactPath = resolve(root, artifact.relativePath);
    try {
      const current = await readFile(artifactPath, "utf8");
      if (current !== artifact.source) {
        problems.push(`stale: ${artifact.relativePath}`);
      }
    } catch (error) {
      if (
        error instanceof Error &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        problems.push(`missing: ${artifact.relativePath}`);
        continue;
      }
      throw error;
    }
  }
  for (const extra of await findExtraArtifacts(root, artifacts)) {
    problems.push(`extraneous: ${extra}`);
  }
  return problems;
};

export const checkSealedEntityArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  const problems: string[] = [];
  for (const artifact of artifacts) {
    try {
      const current = await readFile(
        resolve(root, artifact.relativePath),
        "utf8",
      );
      const hashes = current.match(ARTIFACT_HASH_PATTERN);
      const content = current.replace(ARTIFACT_HASH_PATTERN, "");
      if (
        hashes?.[1] !== artifactHash(artifact.source) ||
        hashes?.[2] !== artifactHash(content)
      ) {
        problems.push(`stale: ${artifact.relativePath}`);
      }
    } catch (error) {
      if (
        error instanceof Error &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        problems.push(`missing: ${artifact.relativePath}`);
        continue;
      }
      throw error;
    }
  }
  for (const extra of await findExtraArtifacts(root, artifacts)) {
    problems.push(`extraneous: ${extra}`);
  }
  return problems;
};

export const writeEntityArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  const problems = await checkEntityArtifacts(root, artifacts);
  const extras = problems.filter((problem) =>
    problem.startsWith("extraneous:"),
  );
  if (extras.length > 0) {
    throw new EntityDeclarationError(
      `Refusing to overwrite with ${extras.join(", ")}.`,
    );
  }
  for (const artifact of artifacts) {
    const artifactPath = resolve(root, artifact.relativePath);
    await stat(dirname(artifactPath)).catch(async (error) => {
      if (
        error instanceof Error &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        await mkdir(dirname(artifactPath), { recursive: true });
        return;
      }
      throw error;
    });
    await writeFile(artifactPath, artifact.source);
  }
};
