locations:
  - name: garage
    type: room
    children:
      - name: toolbag
        type: bag
        products:
          - name: Packout toolbag
            manufacturer: Milwaukee
            upc: "045242505296"
            model: 48-22-8315
            price_per: 99
      - name: chrome wire shelf
        type: shelf
        children:
          - name: oscillating and grinder
            type: half-crate
            products:
              - name: Ryobi Angle Grinder
                manufacturer: Ryobi
                upc: "033287188048"
                model: PBLAG01B
                price_per: 129
              - name: Ryobi Oscillating Tool
                manufacturer: Ryobi
                upc: "033287190706"
                model: PBLMT50B
                price_per: 129
              - name: angle grinder discs
                manufacturer: generic
                price_per: 4
              - name: oscillating toolblades
                manufacturer: generic
                price_per: 8
          - name: bin B
            type: crate
          - name: bin C
            type: crate
      - name: black wire shelf
        type: shelf
      - name: white metal shelf
        type: shelf
      - name: packout wall
        type: shelf
      - name: butcher block workbench
        type: table
      - name: rolling cart
        type: cart
        children:
          - name: top drawer
            type: drawer
          - name: MFT drawer
            type: drawer
          - name: hex drawer
            type: drawer
      - name: wooden cabinets
        type: cabinet
  - name: kitchen
    type: room
    children:
      - name: kitchen
        type: room
        children:
          - name: fridge
            type: cabinet
            productReferences:
              - name: cilantro
              - name: white sugar
      - name: pantry
        type: cabinet
        children:
          - name: spice drawer
            type: drawer
          - name: coffee drawer
            type: drawer
      - name: peninsula drawers
        type: cabinet
        children:
          - name: small dry goods
            type: drawer
          - name: large dry goods
            type: drawer
products:
  - name: White sugar
    ingredient: true
    manufacturer: C&H
    upc: "015800030621"
    unit_mappings:
      - 4 lb = $5 @ whole foods
      - 4 lb = 1each @ general
    aliases:
      - sugar
      - granulated sugar
  - name: powdered sugar
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 lb = $5 @ whole foods
    ndb_number: 19336
    aliases:
      - confectioner's sugar
      - confectioners sugar
  - name: All Purpose Flour
    ingredient: true
    manufacturer: King Arthur
    upc: "071012010509"
    unit_mappings:
      - 5 lb = $8 @ whole foods
      - 1 cup = 120g @ unk
    aliases:
      - AP flour
      - flour
      - white flour
      - all-purpose flour
  - name: All Purpose Flour
    ingredient: true
    manufacturer: Bob's Red Mill
    upc: "039978533012"
    unit_mappings:
      - 5 lb = $7 @ whole foods
      - 1 cup = 120g @ unk
    aliases:
      - AP flour
      - flour
      - white flour
      - all-purpose flour
  - name: pastry flour
    ingredient: true
    manufacturer: generic
    upc: "075211436504"
    unit_mappings:
      - 5 lb = $8 @ whole foods
      - 1 cup = 120g @ unk
  - name: cake flour
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 5 lb = $8 @ whole foods
      - 1 cup = 120g @ unk
    ndb_number: 20084
  - name: whole wheat flour
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 5 lb = $8 @ whole foods
      - 1 cup = 120g @ unk
    ndb_number: 20649
  - name: large brown eggs
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 12 whole = $7 @ whole foods
      - 1 whole = 50grams @ general
      - 4.86 large = 1 cup @ usda
    ndb_number: 1123
    aliases:
      - eggs
      - large egg
      - large eggs
      - egg
      - large brown egg
  - name: large brown eggs
    ingredient: true
    manufacturer: Pete & Gerry's
    upc: "815652004142"
    aliases:
      - eggs
      - large egg
      - large eggs
      - egg
      - large brown egg
  - name: butter
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 stick = 113g @ whole foods
      - 4 stick = $8 @ whole foods
    ndb_number: 1145
    aliases:
      - unsalted butter
  - name: milk
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 ml = 1g @ unk
      - 0.5 Quart = $3 @ general
      - 1 Cup = 236.588ml @ TEST, should be part of unit/lib.rs
    ndb_number: 1077
  - name: olive oil
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 ml = 0.9g @ unk
      - 2 liter = $23 @ costco
    ndb_number: 4053
    aliases:
      - Extra Virgin Olive Oil
      - evoo
  - name: olive oil
    ingredient: true
    manufacturer: CA olive range
    upc: "850687100339"
    unit_mappings:
      - 15 dollars = 500ml @ whole foods
    aliases:
      - Extra Virgin Olive Oil
      - evoo
  - name: vegetable oil
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 ml = 0.9g @ unk
      - 1 liter = $6 @ whole foods
    ndb_number: 44005
  - name: canola oil
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 ml = 0.9g @ unk
      - 1 liter = $6 @ whole foods
    ndb_number: 4582
  - name: avocado oil
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 ml = 0.9g @ unk
      - 2 liter = $23 @ costco
    ndb_number: 4581
  - name: water
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 ml = 1g @ unk
      - 11968 cups = $11.4 @ sf puc
    ndb_number: 14411
  - name: kosher salt
    ingredient: true
    manufacturer: Diamond Crystal
    upc: "013600020019"
    unit_mappings:
      - 3 lb = $8 @ whole foods
    aliases:
      - salt
  - name: baking soda
    ingredient: true
    manufacturer: Arm & Hammer
    upc: "033200011408"
    unit_mappings:
      - 10 oz = $3 @ whole foods
      - 1 cup = 520.49grams @ google search
    ndb_number: 18372
  - name: baking powder
    ingredient: true
    manufacturer: Clabber Girl
    upc: "019900003202"
    unit_mappings:
      - 10 oz = $3 @ whole foods
    ndb_number: 18369
  - name: ginger
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 lb = $4 @ safeway
    ndb_number: 11216
  - name: ground ginger
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 oz = $8 @ whole foods
    ndb_number: 2021
  - name: ground cinnamon
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 oz = $8 @ whole foods
    ndb_number: 2010
  - name: nutmeg
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 oz = $8 @ whole foods
    ndb_number: 2025
  - name: black pepper
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 oz = $8 @ whole foods
      - 1 tsp = 1tsp, ground @ tmp
    ndb_number: 2030
    aliases:
      - pepper
  - name: cilantro
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 1 bunch = $2 @ whole foods
      - 1 bunch = 100sprig @ general
      - 1 bunch = 1each @ general
    ndb_number: 11165
  - name: molasses
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 oz = $8 @ whole foods
    ndb_number: 19304
  - name: vanilla extract
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 oz = $8 @ whole foods
    ndb_number: 2050
  - name: salsa
    ingredient: true
    manufacturer: generic
    unit_mappings:
      - 2 cups = $6 @ whole foods
    ndb_number: 6164
  - name: M18 Hackzall
    manufacturer: Milwaukee
    upc: "045242502776"
    model: 2719-20
    price_per: 169
