locations:
  - name: "garage"
    type: "room"
    children:
      - name: "chrome wire shelf"
        type: "shelf"
        children:
          - name: "bin A"
            type: "crate"
          - name: "bin B"
            type: "crate"
          - name: "bin C"
            type: "crate"
      - name: "black wire shelf"
        type: "shelf"
      - name: "white metal shelf"
        type: "shelf"
      - name: "packout wall"
        type: "shelf"
      - name: "butcher block workbench"
        type: "table"
      - name: "rolling cart"
        type: "cart"
        children:
          - name: "top drawer"
            type: "drawer"
          - name: "MFT drawer"
            type: "drawer"
          - name: "hex drawer"
            type: "drawer"
      - name: "wooden cabinets"
        type: "cabinet"

  - name: "kitchen"
    type: "room"
    children:
      - name: "pantry"
        type: "cabinet"
        children:
          - name: "spice drawer"
            type: "drawer"
          - name: "coffee drawer"
            type: "drawer"
      - name: "peninsula drawers"
        type: "cabinet"
        children:
          - name: "small dry goods"
            type: "drawer"
          - name: "large dry goods"
            type: "drawer"
products:
  - name: "White sugar"
    productType: "Ingredient"
    upc: "015800030621"
    manufacturer: "C&H"
    unit_mappings:
      - a:
          unit: lb
          value: 4
        b:
          unit: dollars
          value: 3
        source: whole foods
  - name: "All Purpose Flour"
    productType: "Ingredient"
    upc: "071012010509"
    manufacturer: "King Arthur"
    unit_mappings:
      - a:
          unit: lb
          value: 5
        b:
          unit: dollars
          value: 8
        source: whole foods
  - name: "All Purpose Flour"
    productType: "Ingredient"
    upc: "039978533012"
    manufacturer: "Bob's Red Mill"
    unit_mappings:
      - a:
          unit: lb
          value: 5
        b:
          unit: dollars
          value: 7
        source: whole foods
  - name: M18 Hackzall
    productType: "Item"
    upc: "045242502776"
    manufacturer: "Milwaukee"
    model: "2719-20"
    unit_mappings:
      - a:
          unit: dollars
          value: 169
        b:
          unit: each
          value: 1
        source: home depot
