services:
  integresql:
    image: ghcr.io/allaboutapps/integresql:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment: 
      PGHOST: db
      PGUSER: recipehub
      PGPASSWORD: example
  db:
    image: postgres:17.2
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: recipehub
      POSTGRES_PASSWORD: example
      POSTGRES_DB: recipes
    command:
      [
        "postgres",
        "-c",
        "log_min_duration_statement=0",
        "-c",
        "log_destination=stderr",
        "-c",
        "log_line_prefix=%t [%p]:[%l] user=%u, db=%d "
      ]
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - "4318:4318"
      - "4317:4317"
