services:
  integresql:
    image: ghcr.io/allaboutapps/integresql:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
  db:
  # 17 until https://github.com/drizzle-team/drizzle-orm/issues/4944
    image: postgres:17.10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cubby
    command:
      [
        "postgres",
        "-c",
        "log_min_duration_statement=0",
        "-c",
        "log_destination=stderr",
        "-c",
        "log_line_prefix=%t [%p]:[%l] user=%u, db=%d "
      ]
  jaeger-all-in-one:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.19.0
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
      - "4318:4318"
      - "4317:4317"
