services:
  db:
    image: postgres:17.0
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: recipehub
      POSTGRES_PASSWORD: example
      POSTGRES_DB: recipes
    command:
      [
        "postgres",
        "-c",
        "log_min_duration_statement=0",
        "-c",
        "log_destination=stderr",
        "-c",
        "log_line_prefix=%t [%p]:[%l] user=%u, db=%d "
      ]