-- Durable entity identity and shared attachments (ADR 0006).
-- Generated by the PR that ships it; the runbook is
-- docs/runbooks/entity-identity-schema.md. Run entity-identity.preflight.sql
-- first and stop on any row it returns. Run this in Neon BEFORE merging the
-- PR: everything here is additive, and the triggers keep old code's writes
-- consistent until the new build deploys. The legacy image joins, the cover
-- and logo columns, `Image.targetType`/`targetId`/`idempotencyKey`, and the
-- `dataExceptions` columns stay until entity-identity.drop.sql.
--
-- One transaction. Entity tables are locked against writes (reads continue)
-- so no row is created between its backfill and its identity FK.

BEGIN;

LOCK TABLE "Cookbook", "Device", "Expense", "FinancialAccount", "FinancialTransaction", "GardenEntry", "Image", "ImageSighting", "ImportRun", "Ingredient", "InventoryEntry", "LedgerParty", "LedgerTransfer", "Location", "Meal", "Plant", "Planting", "Product", "ProductCategory", "Project", "Purchase", "Recipe", "Task", "Vendor", "VendorAccount", "Wish",
  "ProductImage", "LocationImage", "GardenEntryImage", "RecipeImage",
  "MealImage", "TaskImage", "PurchaseImage", "ProjectImage",
  "AuditLog", "SearchDocument", "EntityEmbedding", "PhotoGroupProposal"
IN EXCLUSIVE MODE;

-- 1. Identity.
CREATE TABLE "Entity" (
	"id" uuid PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"shortcode" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	"mergedIntoId" uuid,
	CONSTRAINT "Entity_id_shortcode_key" UNIQUE("id","shortcode"),
	CONSTRAINT "Entity_id_kind_key" UNIQUE("id","kind"),
	CONSTRAINT "Entity_kind_check" CHECK ("Entity"."kind" IN ('product', 'recipe', 'ingredient', 'cookbook', 'location', 'inventory', 'meal', 'ledgerParty', 'ledgerTransfer', 'project', 'task', 'vendor', 'purchase', 'financialAccount', 'financialTransaction', 'wish', 'expense', 'image', 'planting', 'gardenEntry', 'vendorAccount', 'productCategory', 'importRun', 'device', 'imageSighting', 'plant')),
	CONSTRAINT "Entity_shortcode_prefix_check" CHECK ("Entity"."shortcode" IS NULL OR CASE "Entity"."kind" WHEN 'product' THEN "Entity"."shortcode" LIKE 'PRD-%' WHEN 'recipe' THEN "Entity"."shortcode" LIKE 'RCP-%' WHEN 'ingredient' THEN "Entity"."shortcode" LIKE 'ING-%' WHEN 'cookbook' THEN "Entity"."shortcode" LIKE 'CKB-%' WHEN 'location' THEN "Entity"."shortcode" LIKE 'LOC-%' WHEN 'inventory' THEN "Entity"."shortcode" LIKE 'INV-%' WHEN 'meal' THEN "Entity"."shortcode" LIKE 'MEL-%' WHEN 'ledgerParty' THEN "Entity"."shortcode" LIKE 'LPY-%' WHEN 'ledgerTransfer' THEN "Entity"."shortcode" LIKE 'LTR-%' WHEN 'project' THEN "Entity"."shortcode" LIKE 'PRJ-%' WHEN 'task' THEN "Entity"."shortcode" LIKE 'TSK-%' WHEN 'vendor' THEN "Entity"."shortcode" LIKE 'VEN-%' WHEN 'purchase' THEN "Entity"."shortcode" LIKE 'PUR-%' WHEN 'financialAccount' THEN "Entity"."shortcode" LIKE 'FAC-%' WHEN 'financialTransaction' THEN "Entity"."shortcode" LIKE 'FTX-%' WHEN 'wish' THEN "Entity"."shortcode" LIKE 'WSH-%' WHEN 'expense' THEN "Entity"."shortcode" LIKE 'EXP-%' WHEN 'image' THEN "Entity"."shortcode" LIKE 'IMG-%' WHEN 'planting' THEN "Entity"."shortcode" LIKE 'PLT-%' WHEN 'gardenEntry' THEN "Entity"."shortcode" LIKE 'GDE-%' WHEN 'vendorAccount' THEN "Entity"."shortcode" LIKE 'VACCT-%' WHEN 'productCategory' THEN "Entity"."shortcode" LIKE 'CAT-%' WHEN 'importRun' THEN "Entity"."shortcode" LIKE 'RUN-%' WHEN 'device' THEN "Entity"."shortcode" LIKE 'DEV-%' WHEN 'imageSighting' THEN "Entity"."shortcode" LIKE 'IMS-%' WHEN 'plant' THEN "Entity"."shortcode" LIKE 'PLANT-%' ELSE false END),
	CONSTRAINT "Entity_merge_not_self_check" CHECK ("Entity"."mergedIntoId" IS NULL OR "Entity"."mergedIntoId" <> "Entity"."id"),
	CONSTRAINT "Entity_merged_is_deleted_check" CHECK ("Entity"."mergedIntoId" IS NULL OR "Entity"."deletedAt" IS NOT NULL),
	CONSTRAINT "Entity_live_has_shortcode_check" CHECK ("Entity"."deletedAt" IS NOT NULL OR "Entity"."shortcode" IS NOT NULL)
);

CREATE UNIQUE INDEX "Entity_shortcode_unique" ON "Entity" USING btree ("shortcode");
CREATE INDEX "Entity_mergedIntoId_idx" ON "Entity" USING btree ("mergedIntoId");

INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'cookbook', "shortcode", "createdAt", "deletedAt" FROM "Cookbook"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'device', "shortcode", "createdAt", "deletedAt" FROM "Device"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'expense', "shortcode", "createdAt", "deletedAt" FROM "Expense"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'financialAccount', "shortcode", "createdAt", "deletedAt" FROM "FinancialAccount"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'financialTransaction', "shortcode", "createdAt", "deletedAt" FROM "FinancialTransaction"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'gardenEntry', "shortcode", "createdAt", "deletedAt" FROM "GardenEntry"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'image', "shortcode", "createdAt", "deletedAt" FROM "Image"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'imageSighting', "shortcode", "createdAt", "deletedAt" FROM "ImageSighting"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'importRun', "shortcode", "createdAt", "deletedAt" FROM "ImportRun"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'ingredient', "shortcode", "createdAt", "deletedAt" FROM "Ingredient"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'inventory', "shortcode", "createdAt", "deletedAt" FROM "InventoryEntry"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'ledgerParty', "shortcode", "createdAt", "deletedAt" FROM "LedgerParty"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'ledgerTransfer', "shortcode", "createdAt", "deletedAt" FROM "LedgerTransfer"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'location', "shortcode", "createdAt", "deletedAt" FROM "Location"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'meal', "shortcode", "createdAt", "deletedAt" FROM "Meal"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'plant', "shortcode", "createdAt", "deletedAt" FROM "Plant"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'planting', "shortcode", "createdAt", "deletedAt" FROM "Planting"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'product', "shortcode", "createdAt", "deletedAt" FROM "Product"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'productCategory', "shortcode", "createdAt", "deletedAt" FROM "ProductCategory"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'project', "shortcode", "createdAt", "deletedAt" FROM "Project"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'purchase', "shortcode", "createdAt", "deletedAt" FROM "Purchase"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'recipe', "shortcode", "createdAt", "deletedAt" FROM "Recipe"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'task', "shortcode", "createdAt", "deletedAt" FROM "Task"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'vendor', "shortcode", "createdAt", "deletedAt" FROM "Vendor"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'vendorAccount', "shortcode", "createdAt", "deletedAt" FROM "VendorAccount"
  ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  SELECT "id", 'wish', "shortcode", "createdAt", "deletedAt" FROM "Wish"
  ON CONFLICT ("id") DO NOTHING;

-- Repair: an early-2026 import bug filed Product create and update entries
-- under 'inventory' with the Product's id. The id is authoritative; only the
-- kind label is wrong, and the identity FK would reject it.
UPDATE "AuditLog" a
SET "entityType" = 'product'
WHERE a."entityType" = 'inventory'
  AND (
    EXISTS (SELECT 1 FROM "Product" p WHERE p."id" = a."entityId")
    OR EXISTS (
      SELECT 1 FROM "AuditLog" b
      WHERE b."entityId" = a."entityId" AND b."entityType" = 'product'
    )
  );

-- History and projection rows that name an identity no payload holds any
-- more (a hard-deleted row) get a code-less tombstone rather than a
-- fabricated code, so their identity FK can be enforced.
INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
SELECT DISTINCT ON (x."id") x."id", x."kind", NULL, x."at", x."at"
FROM (
  SELECT "entityId" AS "id", "entityType" AS "kind", "createdAt" AS "at" FROM "AuditLog"
  UNION ALL
  SELECT "entityId", "entityType", "createdAt" FROM "SearchDocument"
  UNION ALL
  SELECT "entityId", "entityType", "createdAt" FROM "EntityEmbedding"
) x
WHERE x."kind" IN ('cookbook', 'device', 'expense', 'financialAccount', 'financialTransaction', 'gardenEntry', 'image', 'imageSighting', 'importRun', 'ingredient', 'inventory', 'ledgerParty', 'ledgerTransfer', 'location', 'meal', 'plant', 'planting', 'product', 'productCategory', 'project', 'purchase', 'recipe', 'task', 'vendor', 'vendorAccount', 'wish')
  AND NOT EXISTS (SELECT 1 FROM "Entity" e WHERE e."id" = x."id")
ORDER BY x."id", x."at";

ALTER TABLE "Entity" ADD CONSTRAINT "Entity_mergedIntoId_Entity_id_fk" FOREIGN KEY ("mergedIntoId") REFERENCES "public"."Entity"("id") ON DELETE no action ON UPDATE no action;

-- Merge redirects from the survivors' audit evidence: each merge writes an
-- update entry on the survivor whose `changes.mergedFrom.to` lists the loser
-- ids. Ingredient merges record alias strings and hard-delete their losers,
-- so they cannot be reconstructed and are left as plain tombstones.
UPDATE "Entity" e
SET "mergedIntoId" = a."entityId"
FROM "AuditLog" a
CROSS JOIN LATERAL jsonb_array_elements_text(
  CASE WHEN jsonb_typeof(a."changes"->'mergedFrom'->'to') = 'array'
    THEN a."changes"->'mergedFrom'->'to' ELSE '[]'::jsonb END
) loser
WHERE a."action" = 'update'
  AND a."changes" ? 'mergedFrom'
  AND loser ~ '^[0-9a-f-]{36}$'
  AND e."id" = loser::uuid
  AND e."kind" = a."entityType"
  AND e."id" <> a."entityId"
  AND e."deletedAt" IS NOT NULL
  AND e."mergedIntoId" IS NULL;

-- Path-compress so every redirect is one hop to the final survivor.
DO $$
DECLARE
  changed integer;
  rounds integer := 0;
BEGIN
  LOOP
    UPDATE "Entity" e
    SET "mergedIntoId" = s."mergedIntoId"
    FROM "Entity" s
    WHERE e."mergedIntoId" = s."id" AND s."mergedIntoId" IS NOT NULL;
    GET DIAGNOSTICS changed = ROW_COUNT;
    EXIT WHEN changed = 0;
    rounds := rounds + 1;
    IF rounds > 20 THEN
      RAISE EXCEPTION 'merge redirects do not converge: a cycle in merge evidence';
    END IF;
  END LOOP;
END $$;

-- 2. Attachments.
CREATE TABLE "EntityAttachment" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subjectEntityId" uuid NOT NULL,
	"imageId" uuid NOT NULL,
	"role" text DEFAULT 'attachment' NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"purpose" text,
	"documentKind" text,
	"idempotencyKey" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"deletedAt" timestamp,
	CONSTRAINT "EntityAttachment_role_check" CHECK ("EntityAttachment"."role" IN ('attachment', 'cover', 'logo')),
	CONSTRAINT "EntityAttachment_purpose_check" CHECK ("EntityAttachment"."purpose" IS NULL OR "EntityAttachment"."purpose" IN ('item', 'label'))
);

CREATE UNIQUE INDEX "EntityAttachment_subject_image_key" ON "EntityAttachment" USING btree ("subjectEntityId","imageId") WHERE "EntityAttachment"."deletedAt" IS NULL;
CREATE UNIQUE INDEX "EntityAttachment_subject_singular_role_key" ON "EntityAttachment" USING btree ("subjectEntityId","role") WHERE "EntityAttachment"."role" IN ('cover', 'logo') AND "EntityAttachment"."deletedAt" IS NULL;
CREATE UNIQUE INDEX "EntityAttachment_subject_idempotency_key" ON "EntityAttachment" USING btree ("subjectEntityId","idempotencyKey") WHERE "EntityAttachment"."idempotencyKey" IS NOT NULL AND "EntityAttachment"."deletedAt" IS NULL;
CREATE INDEX "EntityAttachment_subject_order_idx" ON "EntityAttachment" USING btree ("subjectEntityId","sortOrder");
CREATE INDEX "EntityAttachment_imageId_idx" ON "EntityAttachment" USING btree ("imageId");

ALTER TABLE "EntityAttachment" ADD CONSTRAINT "EntityAttachment_subjectEntityId_Entity_id_fk" FOREIGN KEY ("subjectEntityId") REFERENCES "public"."Entity"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "EntityAttachment" ADD CONSTRAINT "EntityAttachment_imageId_Image_id_fk" FOREIGN KEY ("imageId") REFERENCES "public"."Image"("id") ON DELETE no action ON UPDATE no action;

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."productId", j."imageId", 'attachment', j."sortOrder", j."purpose", NULL, j."createdAt", j."updatedAt"
FROM "ProductImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."productId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."locationId", j."imageId", 'attachment', j."sortOrder", NULL, NULL, j."createdAt", j."updatedAt"
FROM "LocationImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."locationId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."gardenEntryId", j."imageId", 'attachment', j."sortOrder", NULL, NULL, j."createdAt", j."updatedAt"
FROM "GardenEntryImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."gardenEntryId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."recipeId", j."imageId", 'attachment', j."sortOrder", NULL, NULL, j."createdAt", j."updatedAt"
FROM "RecipeImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."recipeId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."mealId", j."imageId", 'attachment', j."sortOrder", NULL, NULL, j."createdAt", j."updatedAt"
FROM "MealImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."mealId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."taskId", j."imageId", 'attachment', j."sortOrder", NULL, NULL, j."createdAt", j."updatedAt"
FROM "TaskImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."taskId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."purchaseId", j."imageId", 'attachment', j."sortOrder", NULL, j."documentKind", j."createdAt", j."updatedAt"
FROM "PurchaseImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."purchaseId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "purpose", "documentKind", "createdAt", "updatedAt")
SELECT j."projectId", j."imageId", 'attachment', j."sortOrder", NULL, NULL, j."createdAt", j."updatedAt"
FROM "ProjectImage" j
WHERE j."deletedAt" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = j."projectId" AND a."imageId" = j."imageId" AND a."deletedAt" IS NULL
  );

-- A tombstoned owner's cover is soft-deleted with it (ADR 0006).
INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "createdAt", "updatedAt", "deletedAt")
SELECT o."id", o."coverImageId", 'cover', 0, o."createdAt", o."updatedAt", o."deletedAt"
FROM "Cookbook" o
WHERE o."coverImageId" IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = o."id" AND a."role" = 'cover'
  );

-- A tombstoned owner's logo is soft-deleted with it (ADR 0006).
INSERT INTO "EntityAttachment"
  ("subjectEntityId", "imageId", "role", "sortOrder", "createdAt", "updatedAt", "deletedAt")
SELECT o."id", o."logoImageId", 'logo', 0, o."createdAt", o."updatedAt", o."deletedAt"
FROM "Vendor" o
WHERE o."logoImageId" IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM "EntityAttachment" a
    WHERE a."subjectEntityId" = o."id" AND a."role" = 'logo'
  );

-- A retry key moves only onto the live association it was scoped to; a
-- targeted-but-detached file keeps nothing.
UPDATE "EntityAttachment" a
SET "idempotencyKey" = i."idempotencyKey"
FROM "Image" i
WHERE i."id" = a."imageId"
  AND i."idempotencyKey" IS NOT NULL AND i."deletedAt" IS NULL
  AND i."targetId" = a."subjectEntityId"
  AND a."deletedAt" IS NULL AND a."idempotencyKey" IS NULL;

-- 3. Data exceptions.
CREATE TABLE "DataException" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"entityId" uuid NOT NULL,
	"entityKind" text NOT NULL,
	"check" text NOT NULL,
	"reason" text NOT NULL,
	"note" text NOT NULL,
	"fingerprint" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX "DataException_entity_check_key" ON "DataException" USING btree ("entityId","check");

ALTER TABLE "DataException" ADD CONSTRAINT "DataException_entity_fk" FOREIGN KEY ("entityId","entityKind") REFERENCES "public"."Entity"("id","kind") ON DELETE no action ON UPDATE no action;

INSERT INTO "DataException"
  ("entityId", "entityKind", "check", "reason", "note", "fingerprint", "createdAt", "updatedAt")
SELECT owner."id", owner."kind", x->>'check', x->>'reason', x->>'note', x->>'fingerprint', now(), now()
FROM (
  SELECT "id", 'product' AS "kind", "dataExceptions" FROM "Product"
  UNION ALL
  SELECT "id", 'purchase', "dataExceptions" FROM "Purchase"
) owner
CROSS JOIN LATERAL jsonb_array_elements(COALESCE(owner."dataExceptions", '[]'::jsonb)) x
ON CONFLICT ("entityId", "check") DO NOTHING;

-- 4. Photo-group proposal category and owner.
ALTER TABLE "PhotoGroupProposal" ADD COLUMN "productCreateCategoryId" uuid;
ALTER TABLE "PhotoGroupProposal" ADD COLUMN "inventoryOwnerPartyId" uuid;

UPDATE "PhotoGroupProposal" p
SET "productCreateCategoryId" = c."id"
FROM "ProductCategory" c
WHERE p."productCreateCategoryId" IS NULL
  AND c."shortcode" = p."productCreate"->>'categoryId';

UPDATE "PhotoGroupProposal" p
SET "inventoryOwnerPartyId" = l."id"
FROM "LedgerParty" l
WHERE p."inventoryOwnerPartyId" IS NULL
  AND l."shortcode" = p."inventory"->>'ownerPartyId';

-- The codes now live in the FK columns.
UPDATE "PhotoGroupProposal"
SET "productCreate" = "productCreate" - 'categoryId'
WHERE "productCreate" ? 'categoryId';
UPDATE "PhotoGroupProposal"
SET "inventory" = "inventory" - 'ownerPartyId'
WHERE "inventory" ? 'ownerPartyId';

ALTER TABLE "PhotoGroupProposal" ADD CONSTRAINT "PhotoGroupProposal_inventoryOwnerPartyId_LedgerParty_id_fk" FOREIGN KEY ("inventoryOwnerPartyId") REFERENCES "public"."LedgerParty"("id") NOT VALID;
ALTER TABLE "PhotoGroupProposal" VALIDATE CONSTRAINT "PhotoGroupProposal_inventoryOwnerPartyId_LedgerParty_id_fk";
ALTER TABLE "PhotoGroupProposal" ADD CONSTRAINT "PhotoGroupProposal_productCreateCategoryId_fk" FOREIGN KEY ("productCreateCategoryId") REFERENCES "public"."ProductCategory"("id") NOT VALID;
ALTER TABLE "PhotoGroupProposal" VALIDATE CONSTRAINT "PhotoGroupProposal_productCreateCategoryId_fk";

-- 5. Identity FKs: every payload binds to its row, and history/projection
-- rows name a real identity of the right kind.
ALTER TABLE "Cookbook" ADD CONSTRAINT "Cookbook_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Cookbook" VALIDATE CONSTRAINT "Cookbook_entity_identity_fk";
ALTER TABLE "Device" ADD CONSTRAINT "Device_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Device" VALIDATE CONSTRAINT "Device_entity_identity_fk";
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Expense" VALIDATE CONSTRAINT "Expense_entity_identity_fk";
ALTER TABLE "FinancialAccount" ADD CONSTRAINT "FinancialAccount_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "FinancialAccount" VALIDATE CONSTRAINT "FinancialAccount_entity_identity_fk";
ALTER TABLE "FinancialTransaction" ADD CONSTRAINT "FinancialTransaction_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "FinancialTransaction" VALIDATE CONSTRAINT "FinancialTransaction_entity_identity_fk";
ALTER TABLE "GardenEntry" ADD CONSTRAINT "GardenEntry_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "GardenEntry" VALIDATE CONSTRAINT "GardenEntry_entity_identity_fk";
ALTER TABLE "Image" ADD CONSTRAINT "Image_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Image" VALIDATE CONSTRAINT "Image_entity_identity_fk";
ALTER TABLE "ImageSighting" ADD CONSTRAINT "ImageSighting_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "ImageSighting" VALIDATE CONSTRAINT "ImageSighting_entity_identity_fk";
ALTER TABLE "ImportRun" ADD CONSTRAINT "ImportRun_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "ImportRun" VALIDATE CONSTRAINT "ImportRun_entity_identity_fk";
ALTER TABLE "Ingredient" ADD CONSTRAINT "Ingredient_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Ingredient" VALIDATE CONSTRAINT "Ingredient_entity_identity_fk";
ALTER TABLE "InventoryEntry" ADD CONSTRAINT "InventoryEntry_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "InventoryEntry" VALIDATE CONSTRAINT "InventoryEntry_entity_identity_fk";
ALTER TABLE "LedgerParty" ADD CONSTRAINT "LedgerParty_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "LedgerParty" VALIDATE CONSTRAINT "LedgerParty_entity_identity_fk";
ALTER TABLE "LedgerTransfer" ADD CONSTRAINT "LedgerTransfer_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "LedgerTransfer" VALIDATE CONSTRAINT "LedgerTransfer_entity_identity_fk";
ALTER TABLE "Location" ADD CONSTRAINT "Location_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Location" VALIDATE CONSTRAINT "Location_entity_identity_fk";
ALTER TABLE "Meal" ADD CONSTRAINT "Meal_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Meal" VALIDATE CONSTRAINT "Meal_entity_identity_fk";
ALTER TABLE "Plant" ADD CONSTRAINT "Plant_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Plant" VALIDATE CONSTRAINT "Plant_entity_identity_fk";
ALTER TABLE "Planting" ADD CONSTRAINT "Planting_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Planting" VALIDATE CONSTRAINT "Planting_entity_identity_fk";
ALTER TABLE "Product" ADD CONSTRAINT "Product_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Product" VALIDATE CONSTRAINT "Product_entity_identity_fk";
ALTER TABLE "ProductCategory" ADD CONSTRAINT "ProductCategory_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "ProductCategory" VALIDATE CONSTRAINT "ProductCategory_entity_identity_fk";
ALTER TABLE "Project" ADD CONSTRAINT "Project_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Project" VALIDATE CONSTRAINT "Project_entity_identity_fk";
ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Purchase" VALIDATE CONSTRAINT "Purchase_entity_identity_fk";
ALTER TABLE "Recipe" ADD CONSTRAINT "Recipe_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Recipe" VALIDATE CONSTRAINT "Recipe_entity_identity_fk";
ALTER TABLE "Task" ADD CONSTRAINT "Task_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Task" VALIDATE CONSTRAINT "Task_entity_identity_fk";
ALTER TABLE "Vendor" ADD CONSTRAINT "Vendor_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Vendor" VALIDATE CONSTRAINT "Vendor_entity_identity_fk";
ALTER TABLE "VendorAccount" ADD CONSTRAINT "VendorAccount_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "VendorAccount" VALIDATE CONSTRAINT "VendorAccount_entity_identity_fk";
ALTER TABLE "Wish" ADD CONSTRAINT "Wish_entity_identity_fk" FOREIGN KEY ("id","shortcode") REFERENCES "public"."Entity"("id","shortcode") NOT VALID;
ALTER TABLE "Wish" VALIDATE CONSTRAINT "Wish_entity_identity_fk";

ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_entity_fk" FOREIGN KEY ("entityId","entityType") REFERENCES "public"."Entity"("id","kind") NOT VALID;
ALTER TABLE "AuditLog" VALIDATE CONSTRAINT "AuditLog_entity_fk";
ALTER TABLE "EntityEmbedding" ADD CONSTRAINT "EntityEmbedding_entity_fk" FOREIGN KEY ("entityId","entityType") REFERENCES "public"."Entity"("id","kind") NOT VALID;
ALTER TABLE "EntityEmbedding" VALIDATE CONSTRAINT "EntityEmbedding_entity_fk";
ALTER TABLE "SearchDocument" ADD CONSTRAINT "SearchDocument_entity_fk" FOREIGN KEY ("entityId","entityType") REFERENCES "public"."Entity"("id","kind") NOT VALID;
ALTER TABLE "SearchDocument" VALIDATE CONSTRAINT "SearchDocument_entity_fk";

-- 6. Triggers that keep Entity in step with every payload write.
CREATE OR REPLACE FUNCTION "entity_identity_on_insert"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO "Entity" ("id", "kind", "shortcode", "createdAt", "deletedAt")
  VALUES (NEW."id", TG_ARGV[0], NEW."shortcode", NEW."createdAt", NEW."deletedAt");
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION "entity_identity_on_soft_delete"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE "Entity" SET "deletedAt" = NEW."deletedAt" WHERE "id" = NEW."id";
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION "entity_identity_on_delete"() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE "Entity"
  SET "deletedAt" = COALESCE("deletedAt", OLD."deletedAt", now())
  WHERE "id" = OLD."id";
  RETURN NULL;
END;
$$;

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Cookbook"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('cookbook');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Cookbook"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Cookbook"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Device"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('device');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Device"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Device"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Expense"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('expense');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Expense"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Expense"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "FinancialAccount"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('financialAccount');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "FinancialAccount"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "FinancialAccount"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "FinancialTransaction"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('financialTransaction');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "FinancialTransaction"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "FinancialTransaction"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "GardenEntry"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('gardenEntry');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "GardenEntry"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "GardenEntry"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Image"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('image');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Image"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Image"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "ImageSighting"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('imageSighting');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "ImageSighting"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "ImageSighting"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "ImportRun"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('importRun');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "ImportRun"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "ImportRun"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Ingredient"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('ingredient');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Ingredient"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Ingredient"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "InventoryEntry"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('inventory');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "InventoryEntry"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "InventoryEntry"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "LedgerParty"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('ledgerParty');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "LedgerParty"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "LedgerParty"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "LedgerTransfer"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('ledgerTransfer');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "LedgerTransfer"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "LedgerTransfer"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Location"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('location');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Location"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Location"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Meal"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('meal');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Meal"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Meal"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Plant"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('plant');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Plant"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Plant"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Planting"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('planting');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Planting"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Planting"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Product"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('product');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Product"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Product"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "ProductCategory"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('productCategory');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "ProductCategory"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "ProductCategory"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Project"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('project');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Project"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Project"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Purchase"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('purchase');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Purchase"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Purchase"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Recipe"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('recipe');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Recipe"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Recipe"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Task"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('task');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Task"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Task"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Vendor"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('vendor');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Vendor"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Vendor"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "VendorAccount"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('vendorAccount');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "VendorAccount"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "VendorAccount"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

CREATE OR REPLACE TRIGGER "Entity_identity_insert" AFTER INSERT ON "Wish"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_insert"('wish');
CREATE OR REPLACE TRIGGER "Entity_identity_soft_delete" AFTER UPDATE OF "deletedAt" ON "Wish"
  FOR EACH ROW WHEN (OLD."deletedAt" IS DISTINCT FROM NEW."deletedAt")
  EXECUTE FUNCTION "entity_identity_on_soft_delete"();
CREATE OR REPLACE TRIGGER "Entity_identity_delete" AFTER DELETE ON "Wish"
  FOR EACH ROW EXECUTE FUNCTION "entity_identity_on_delete"();

COMMIT;

-- Verify: every count pair is equal, and every other query returns no rows.
SELECT e."kind", count(*) FILTER (WHERE e."deletedAt" IS NULL) AS "liveIdentities"
FROM "Entity" e GROUP BY e."kind" ORDER BY e."kind";
SELECT count(*) AS "redirects" FROM "Entity" WHERE "mergedIntoId" IS NOT NULL;
SELECT count(*) AS "codelessTombstones" FROM "Entity" WHERE "shortcode" IS NULL;
SELECT
  (SELECT count(*) FROM "EntityAttachment" WHERE "deletedAt" IS NULL AND "role" = 'attachment') AS "galleryAttachments",
  ((SELECT count(*) FROM "ProductImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "LocationImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "GardenEntryImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "RecipeImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "MealImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "TaskImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "PurchaseImage" WHERE "deletedAt" IS NULL) + (SELECT count(*) FROM "ProjectImage" WHERE "deletedAt" IS NULL)) AS "legacyGalleryRows";
SELECT a."subjectEntityId" FROM "EntityAttachment" a
JOIN "Purchase" p ON p."id" = a."subjectEntityId"
WHERE a."documentKind" IS NULL;
SELECT tgrelid::regclass AS "table", count(*) AS "identityTriggers"
FROM pg_trigger WHERE tgname LIKE 'Entity\_identity\_%'
GROUP BY tgrelid HAVING count(*) <> 3;
