import { defineEntity } from "./definition.js";
import { plainDate } from "@cubby/schemas/base-entity";
import {
  costTypeSchema,
  signedProductQuantity,
} from "@cubby/schemas/expense-fields";
import {
  expenseLineBasisSchema,
  expenseLineKindSchema,
} from "@cubby/schemas/expense-line-kind";
import {
  expenseShortcode,
  productShortcode,
  projectShortcode,
  purchaseShortcode,
  vendorShortcode,
} from "../identifier-fields.js";
import { imageUrlSummary } from "@cubby/schemas/image-summary";
import { ledgerAttributions } from "@cubby/schemas/ledger-party-fields";
import {
  ledgerSourceClaims,
  ledgerSourceClaimsOut,
} from "@cubby/schemas/ledger-transfer-fields";
import { wholeCentAmount } from "@cubby/schemas/money";
import { tradeSchema } from "@cubby/schemas/task-fields";
import { z } from "zod";
export default defineEntity({
  key: "expense",
  names: { singular: "Expense", plural: "Expenses" },
  route: { basePath: "expenses", create: "dialog", list: true, detail: true },
  table: "Expense",
  identifiers: { brand: "ExpenseId", shortcode: "EXP-" },
  presentation: {
    titleField: "name",
    domain: "finance",
    description: "The authoritative record of household spend.",
    emptyState: {
      title: "No expenses yet",
      description:
        "Log what you've bought (or plan to) to keep a project's running cost honest.",
      actionLabel: "New Expense",
    },
    icons: { lucide: "ReceiptText", sfSymbol: "dollarsign.circle" },
    detail: {
      sections: [
        {
          kind: "fields",
          id: "overview",
          title: "Overview",
          fields: [
            "name",
            "cost",
            "date",
            "lineKind",
            "costType",
            "trade",
            "future",
            "url",
            "notes",
            "vendor",
            "orderId",
            "projectId",
            "productId",
            "lineBasis",
            "productQuantity",
          ],
        },
        {
          kind: "fields",
          id: "purchase",
          title: "Purchase",
          placement: "supporting",
          fields: ["purchaseId"],
        },
        {
          kind: "slot",
          id: "settlement",
          title: "Settlement",
          placement: "supporting",
        },
      ],
    },
    list: {
      views: [
        "table",
        {
          kind: "slot",
          id: "analytics",
          label: "Analytics",
          searchKeys: [
            "analyzeRows",
            "analyzeColumns",
            "analyzeMetric",
            "analyzeCompare",
            "analyzeShow",
          ],
        },
      ],
      actions: ["bulkEdit", "delete"],
    },
  },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        control: { kind: "text" },
        display: {
          list: true,
          detail: true,
          detailOrder: 10,
          standard: "name",
        },
        validation: {
          read: z.string().min(1),
          create: z.string().min(1),
          update: z.string().min(1).optional(),
        },
      },
      {
        key: "cost",
        kind: "number",
        nullable: true,
        control: { kind: "number", renderer: "money", section: "details" },
        display: {
          list: true,
          detail: true,
          detailOrder: 20,
          format: "currency",
          mobile: { slot: "trailing", priority: 1 },
        },
        validation: {
          read: wholeCentAmount.describe("Dollars").nullable(),
          create: wholeCentAmount.nullable().default(null),
          update: wholeCentAmount.nullable().optional(),
        },
      },
      {
        key: "date",
        kind: "date",
        control: { kind: "date", section: "schedule", initial: "today" },
        display: { list: true, detail: true, detailOrder: 30 },
        validation: {
          read: plainDate,
          create: plainDate,
          update: plainDate.optional(),
        },
      },
      {
        key: "lineKind",
        kind: "enum",
        label: "Line kind",
        control: { kind: "select", section: "details" },
        display: { list: true, detail: true, detailOrder: 40 },
        validation: {
          read: expenseLineKindSchema.describe(
            "Receipt role. Principal lines are the purchased item/service; every other value is a purchase-level adjustment.",
          ),
          create: expenseLineKindSchema.optional(),
          update: expenseLineKindSchema.optional(),
        },
      },
      {
        key: "lineBasis",
        kind: "enum",
        label: "Itemization",
        control: { kind: "select", section: "details" },
        display: {
          list: true,
          detail: true,
          detailOrder: 140,
          listHidden: true,
        },
        validation: {
          read: expenseLineBasisSchema.describe(
            "Whether this row is a line item or a slice of a total that was never itemized. 'allocation' means the money was cut by payment schedule (a deposit and a balance on one order) or by an estimated materials/labor split of a lump-sum contract — such a row can never carry a productId, and its costType may be an estimate rather than a vendor-stated fact.",
          ),
          create: expenseLineBasisSchema.default("item_line"),
          update: expenseLineBasisSchema.optional(),
        },
      },
      {
        key: "costType",
        kind: "enum",
        control: { kind: "select", section: "details" },
        display: { list: true, detail: true, detailOrder: 50 },
        validation: {
          read: costTypeSchema,
          create: costTypeSchema,
          update: costTypeSchema.optional(),
        },
      },
      {
        key: "trade",
        kind: "enum",
        control: { kind: "select", section: "details" },
        display: { list: true, detail: true, detailOrder: 60 },
        validation: {
          read: tradeSchema,
          create: tradeSchema,
          update: tradeSchema.optional(),
        },
      },
      {
        key: "url",
        kind: "text",
        nullable: true,
        label: "URL",
        control: { kind: "text", renderer: "url", section: "details" },
        display: { list: true, detail: true, detailOrder: 80 },
        validation: {
          read: z.string().nullable(),
          create: z.string().nullable().default(null),
          update: z.string().nullable().optional(),
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        control: { kind: "textarea", section: "details" },
        display: { list: true, detail: true, detailOrder: 90 },
        validation: {
          read: z.string().nullable(),
          create: z.string().nullable().default(null),
          update: z.string().nullable().optional(),
        },
      },
      {
        key: "future",
        kind: "boolean",
        label: "Planned",
        control: { kind: "checkbox", section: "details" },
        display: { list: true, detail: true, detailOrder: 70 },
        validation: {
          read: z.boolean(),
          create: z.boolean().default(false),
          update: z.boolean().optional(),
        },
      },
      {
        key: "projectId",
        kind: "identifier",
        nullable: true,
        label: "Project",
        reference: { entity: "project" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: {
          list: true,
          detail: true,
          detailOrder: 120,
          columnId: "project",
        },
        validation: {
          read: projectShortcode.nullable(),
          create: projectShortcode.nullable().default(null),
          update: projectShortcode.nullable().optional(),
        },
      },
      {
        key: "productId",
        kind: "identifier",
        nullable: true,
        label: "Product",
        reference: { entity: "product" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: {
          list: true,
          detail: true,
          detailOrder: 130,
          columnId: "product",
        },
        validation: {
          read: productShortcode
            .describe(
              "Optional link to the product this expense bought. A negative-cost expense on the same product records an exit (sale, return, or a 0-cost disposal).",
            )
            .nullable(),
          create: productShortcode.nullable().default(null),
          update: productShortcode.nullable().optional(),
        },
      },
      {
        key: "productQuantity",
        kind: "number",
        nullable: true,
        label: "Product quantity",
        control: { kind: "number", section: "details" },
        display: { list: true, detail: true, detailOrder: 150 },
        validation: {
          read: signedProductQuantity
            .describe(
              'Product units covered by this expense; fractional values are allowed (half a coil thrown away is -0.5). Null means the receipt does not establish quantity. Signed: money direction wins, so a positive-cost line is an acquisition of |qty| and a negative-cost line is an exit of |qty|. On a $0 line the sign IS the fact — a positive quantity is a free acquisition (promo pack, bundled accessory), a negative quantity is a discard/write-off. Zero is legal ONLY on a negative-cost line and means money came back but no unit left — a price concession with the item kept (Amazon "Account adjustment", a partial refund for shipping damage). Prefer 0 over null there: null says the count is unknown and gets reported as data-entry debt.',
            )
            .nullable(),
          create: signedProductQuantity
            .nullable()
            .default(null)
            .describe(
              'Product units covered by this expense; fractional values are allowed (half a coil thrown away is -0.5). Null means the receipt does not establish quantity. Signed: money direction wins, so a positive-cost line is an acquisition of |qty| and a negative-cost line is an exit of |qty|. On a $0 line the sign IS the fact — a positive quantity is a free acquisition (promo pack, bundled accessory), a negative quantity is a discard/write-off. Zero is legal ONLY on a negative-cost line and means money came back but no unit left — a price concession with the item kept (Amazon "Account adjustment", a partial refund for shipping damage). Prefer 0 over null there: null says the count is unknown and gets reported as data-entry debt.',
            ),
          update: signedProductQuantity.nullable().optional(),
        },
      },
      {
        key: "vendor",
        kind: "text",
        nullable: true,
        control: { kind: "text", section: "details" },
        display: { detail: true, detailOrder: 100 },
        validation: {
          read: z.string().nullable(),
          create: z.string().nullable().default(null),
          update: z.string().nullable().optional(),
        },
      },
      {
        key: "orderId",
        kind: "text",
        nullable: true,
        label: "Order #",
        control: { kind: "text", section: "details" },
        display: {
          list: true,
          detail: true,
          detailOrder: 110,
          listHidden: true,
        },
        validation: {
          read: z.string().nullable(),
          create: z.string().nullable().default(null),
          update: z.string().nullable().optional(),
        },
      },
      {
        key: "purchaseId",
        kind: "identifier",
        nullable: true,
        label: "Purchase",
        reference: { entity: "purchase" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: {
          list: true,
          detail: true,
          detailOrder: 160,
          columnId: "vendor",
        },
        validation: {
          read: purchaseShortcode.nullable(),
          create: purchaseShortcode.nullable().default(null),
          update: purchaseShortcode.nullable().optional(),
        },
      },
      {
        key: "beneficiaries",
        kind: "json",
        control: { kind: "specialized", renderer: "structured-field" },
        validation: {
          read: ledgerAttributions,
          create: ledgerAttributions.nullable().default([]),
          update: ledgerAttributions.nullable().optional(),
        },
      },
      {
        key: "funders",
        kind: "json",
        control: { kind: "specialized", renderer: "structured-field" },
        validation: {
          read: ledgerAttributions,
          create: ledgerAttributions.nullable().default([]),
          update: ledgerAttributions.nullable().optional(),
        },
      },
      {
        key: "sourceClaims",
        kind: "json",
        control: { kind: "specialized", renderer: "structured-field" },
        validation: {
          read: ledgerSourceClaimsOut,
          create: ledgerSourceClaims.nullable().default([]),
          update: ledgerSourceClaims.nullable().optional(),
        },
      },
      {
        key: "id",
        kind: "identifier",
        validation: {
          read: expenseShortcode,
          create: null,
          update: null,
        },
      },
      {
        key: "purchaseDate",
        kind: "date",
        nullable: true,
        validation: {
          read: plainDate.nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "purchaseDisplayLabel",
        kind: "text",
        nullable: true,
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "vendorId",
        kind: "identifier",
        nullable: true,
        label: "Vendor ID",
        reference: { entity: "vendor" },
        validation: {
          read: vendorShortcode.nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "vendorLogo",
        kind: "json",
        nullable: true,
        validation: {
          read: imageUrlSummary.nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "orderUrl",
        kind: "text",
        nullable: true,
        validation: {
          read: z.url().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "projectName",
        kind: "text",
        nullable: true,
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "productName",
        kind: "text",
        nullable: true,
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        validation: {
          read: z.date(),
          create: null,
          update: null,
        },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        validation: {
          read: z.date(),
          create: null,
          update: null,
        },
      },
      { key: "shortcode", kind: "text", readKey: null },
      {
        key: "notionPageId",
        kind: "text",
        nullable: true,
        label: "Notion Page ID",
        readKey: null,
      },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
    ],
    storage: [
      { key: "id", default: "generated", specialized: "primary-key:ExpenseId" },
      { key: "shortcode", specialized: "shortcode" },
      "name",
      { key: "cost", specialized: "double-precision" },
      "date",
      {
        key: "lineKind",
        default: "literal",
        defaultValue: "'principal'",
        specialized: "enum:lineKind",
      },
      {
        key: "lineBasis",
        default: "literal",
        defaultValue: "'item_line'",
        specialized: "enum:lineBasis",
      },
      { key: "costType", specialized: "enum:costType" },
      { key: "trade", specialized: "enum:trade" },
      "url",
      "notes",
      { key: "future", default: "literal", defaultValue: false },
      { key: "projectId", reference: "project" },
      { key: "productId", reference: "product" },
      { key: "productQuantity", specialized: "double-precision" },
      { key: "purchaseId", reference: "purchase" },
      "notionPageId",
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "vendor",
      "orderId",
      "purchaseId",
      "beneficiaries",
      "funders",
      "sourceClaims",
    ],
    update: [
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "vendor",
      "orderId",
      "purchaseId",
      "beneficiaries",
      "funders",
      "sourceClaims",
    ],
    bulk: ["projectId", "trade", "costType"],
    audit: [
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "purchaseId",
    ],
    sort: {
      fields: [
        "name",
        "cost",
        "lineKind",
        "productQuantity",
        "date",
        "costType",
        "trade",
        "project",
        "product",
        "vendor",
        "orderId",
        "createdAt",
        "updatedAt",
      ],
      default: "date",
      computed: ["project", "product"],
      groupable: ["costType"],
    },
    intents: {
      fields: {
        capture: [
          "name",
          "lineKind",
          "cost",
          "date",
          "future",
          "projectId",
          "productId",
          "productQuantity",
          "vendor",
          "orderId",
          "trade",
          "costType",
        ],
        full: [
          "name",
          "lineKind",
          "lineBasis",
          "cost",
          "date",
          "future",
          "projectId",
          "productId",
          "productQuantity",
          "vendor",
          "orderId",
          "trade",
          "costType",
          "url",
          "notes",
        ],
        planned: ["name", "cost", "date"],
        cost: ["cost"],
        date: ["date"],
        project: ["projectId"],
        product: ["productId"],
      },
      create: ["capture", "full"],
      update: ["full", "planned", "cost", "date", "project", "product"],
    },
    output: [
      "id",
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "vendor",
      "orderId",
      "purchaseId",
      "purchaseDate",
      "purchaseDisplayLabel",
      "vendorId",
      "vendorLogo",
      "orderUrl",
      "projectName",
      "productName",
      "beneficiaries",
      "funders",
      "sourceClaims",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/project", export: "expenseCreateInput" },
    update: { module: "@cubby/schemas/project", export: "expenseUpdateData" },
    output: { module: "@cubby/schemas/project", export: "expenseOut" },
    list: { module: "@cubby/schemas/project", export: "expenseListItemOut" },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/project", export: "expenseFilterFields" },
    descriptors: [
      {
        columnId: "name",
        field: "search",
        urlKey: "q",
        kind: "text",
        placeholder: "Search expenses...",
      },
      {
        columnId: "date",
        kind: "range",
        placeholder: "Filter by date...",
        deriveSchema: true,
        stored: true,
        range: {
          describe: {
            lower: "Inclusive lower bound on expense date",
            upper: "Inclusive upper bound on expense date",
          },
        },
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveDateRange",
        },
      },
      {
        columnId: "dateFrom",
        kind: "text",
        placeholder: "Expense date from...",
        urlOnly: true,
      },
      {
        columnId: "dateTo",
        kind: "text",
        placeholder: "Expense date to...",
        urlOnly: true,
      },
      {
        columnId: "dateRelative",
        kind: "select",
        placeholder: "Filter by relative date...",
        urlOnly: true,
      },
      {
        columnId: "costType",
        kind: "multiselect",
        placeholder: "Filter by cost type...",
        deriveSchema: true,
        stored: true,
        schemaRef: {
          module: "@cubby/schemas/expense-fields",
          export: "costTypeSchema",
        },
        options: [
          { value: "materials", label: "Materials", color: "var(--chart-1)" },
          { value: "tools", label: "Tools", color: "var(--chart-5)" },
          { value: "services", label: "Services", color: "var(--chart-2)" },
        ],
      },
      {
        columnId: "lineKind",
        kind: "multiselect",
        placeholder: "Filter by line kind...",
        deriveSchema: true,
        stored: true,
        schemaRef: {
          module: "@cubby/schemas/expense-line-kind",
          export: "expenseLineKindSchema",
        },
        options: [
          {
            value: "principal",
            label: "Item or service",
            color: "var(--slate)",
          },
          { value: "tax", label: "Tax", color: "var(--slate)" },
          {
            value: "shipping",
            label: "Shipping or delivery",
            color: "var(--slate)",
          },
          { value: "discount", label: "Discount", color: "var(--positive)" },
          { value: "fee", label: "Fee", color: "var(--warning)" },
          { value: "tip", label: "Tip", color: "var(--plum)" },
          {
            value: "other_adjustment",
            label: "Other adjustment",
            color: "var(--slate)",
          },
        ],
      },
      {
        columnId: "lineBasis",
        kind: "multiselect",
        placeholder: "Filter by itemization...",
        deriveSchema: true,
        stored: true,
        schemaRef: {
          module: "@cubby/schemas/expense-line-kind",
          export: "expenseLineBasisSchema",
        },
        options: [
          { value: "item_line", label: "Line item", color: "var(--slate)" },
          {
            value: "allocation",
            label: "Share of a lump sum",
            color: "var(--plum)",
          },
        ],
      },
      {
        columnId: "trade",
        kind: "multiselect",
        placeholder: "Filter by trade...",
        deriveSchema: true,
        stored: true,
        schemaRef: {
          module: "@cubby/schemas/task-fields",
          export: "tradeSchema",
        },
        optionsRef: {
          module: "~/app/projects/trade-options",
          export: "tradeOptions",
        },
      },
      {
        columnId: "future",
        kind: "boolean",
        placeholder: "Filter by status...",
        deriveSchema: true,
        stored: true,
        options: [
          { value: "true", label: "Planned" },
          { value: "false", label: "Already made" },
        ],
      },
      {
        columnId: "cost",
        kind: "range",
        placeholder: "Filter by cost...",
        deriveSchema: true,
        stored: true,
        // Signed money: `costMax: 0` is the credits-only worklist.
        range: {
          describe: {
            lower: "Inclusive lower bound on expense cost, in dollars",
            upper: "Inclusive upper bound on expense cost, in dollars",
          },
        },
        options: [
          { value: "has", label: "Has cost", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "gte500", label: "$500 and up" },
          { value: "gte200", label: "$200 and up" },
          { value: "gte100", label: "$100 and up" },
          { value: "credits", label: "Credits (≤ $0)" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveCostFilter",
        },
      },
      {
        columnId: "costMin",
        kind: "text",
        placeholder: "Minimum cost...",
        urlOnly: true,
      },
      {
        columnId: "costMax",
        kind: "text",
        placeholder: "Maximum cost...",
        urlOnly: true,
      },
      {
        columnId: "costSign",
        kind: "select",
        placeholder: "Filter by cost direction...",
        urlOnly: true,
      },
      {
        columnId: "disposalPurchasePresenceFilter",
        kind: "presence",
        placeholder: "Filter disposal purchase presence...",
        urlOnly: true,
      },
      {
        columnId: "productQuantity",
        kind: "range",
        placeholder: "Filter by quantity...",
        deriveSchema: true,
        stored: true,
        // Signed, like cost: a negative quantity is a real $0 discard, and
        // `productQuantityMax: -1` is the "everything written off" worklist.
        range: {
          describe: {
            lower: "Inclusive lower bound on recorded product quantity",
            upper: "Inclusive upper bound on recorded product quantity",
          },
        },
        options: [
          { value: "has", label: "Has quantity", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "exactly1", label: "Exactly 1" },
          { value: "gte2", label: "2+ units" },
          { value: "gte5", label: "5+ units" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveProductQuantityFilter",
        },
      },
      {
        columnId: "productQuantityMin",
        kind: "text",
        placeholder: "Minimum product quantity...",
        urlOnly: true,
      },
      {
        columnId: "productQuantityMax",
        kind: "text",
        placeholder: "Maximum product quantity...",
        urlOnly: true,
      },
      {
        // Its own field, never folded into `search`: notes carry an import's
        // provenance, and most rows have none, so ANDing it into the name
        // search would zero out expense search.
        columnId: "notesSearch",
        kind: "text",
        placeholder: "Search notes...",
        urlOnly: true,
        deriveSchema: true,
        schemaDescription: "Substring match on notes",
        stored: { columns: ["notes"] },
      },
      {
        columnId: "urlSearch",
        kind: "text",
        placeholder: "Search url...",
        urlOnly: true,
        deriveSchema: true,
        schemaDescription: "Substring match on url",
        stored: { columns: ["url"] },
      },
      {
        columnId: "project",
        field: "projectId",
        kind: "idMulti",
        placeholder: "Filter by project...",
        optionsKey: "project",
        brandRef: { entity: "project" },
        nullable: { field: "projectPresenceFilter", label: "project" },
      },
      {
        columnId: "includeSubProjects",
        urlKey: "subprojects",
        kind: "boolean",
        placeholder: "Include sub-projects...",
        urlOnly: true,
      },
      {
        columnId: "productId",
        kind: "id",
        placeholder: "Filter by product id...",
        brandRef: { entity: "product" },
        urlOnly: true,
      },
      {
        columnId: "product",
        field: "productPresenceFilter",
        kind: "presence",
        placeholder: "Filter by product...",
        options: [
          { value: "has", label: "Has product", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "vendor",
        field: "vendorId",
        kind: "idMulti",
        placeholder: "Filter by vendor...",
        optionsKey: "vendor",
        brandRef: { entity: "vendor" },
        nullable: { field: "vendorPresenceFilter", label: "purchase" },
      },
      {
        columnId: "orderId",
        field: "orderIdPresenceFilter",
        kind: "presence",
        placeholder: "Filter by order id...",
        options: [
          { value: "has", label: "Has order id", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "orderIdExact",
        field: "orderId",
        urlKey: "order",
        kind: "id",
        placeholder: "Filter by order id...",
        urlOnly: true,
      },
      {
        columnId: "purchaseId",
        kind: "id",
        placeholder: "Filter by purchase id...",
        brandRef: { entity: "purchase" },
        urlOnly: true,
      },
      {
        columnId: "related:expense.transactions",
        field: "financialTransactionSearch",
        urlKey: "related-financialTransaction",
        kind: "text",
        placeholder: "Search related purchase transactions...",
      },
      {
        columnId: "financialTransactionId",
        kind: "idMulti",
        placeholder: "Filter by related purchase transactions id...",
        brandRef: { entity: "financialTransaction" },
        urlOnly: true,
      },
      {
        columnId: "financialTransactionPresenceFilter",
        kind: "presence",
        placeholder: "Filter related purchase transactions presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "purchase",
      label: "Purchase",
      target: "purchase",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.purchaseId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Expense.purchaseId", direction: "incoming" }],
      },
    },
    {
      key: "project",
      label: "Project",
      target: "project",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.projectId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Expense.projectId", direction: "incoming" }],
      },
    },
    {
      key: "product",
      label: "Product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.productId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Expense.productId", direction: "incoming" }],
      },
    },
    {
      key: "transactions",
      label: "Purchase transactions",
      target: "financialTransaction",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.purchaseId", direction: "outgoing" },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "outgoing",
          },
          { edge: "Expense.purchaseId", direction: "incoming" },
        ],
      },
    },
  ],
  search: { enabled: true, embedding: false },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: { fields: ["projectId", "trade", "costType"] },
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete", "bulkUpdate"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/expense/entity-adapter",
        export: "expenseEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
