import {
  imageCaptureAttribution,
  imageCaptureLocation,
  imageProvenanceEvidence,
} from "../image-capture-fields.js";
import { optionalImageRepresentations } from "../image-summary.js";
import { defineEntity } from "./definition.js";
import { imageShortcode, ledgerPartyShortcode } from "../identifier-fields.js";
import { z } from "zod";
export const generatedImageStatusValues = [
  "PENDING",
  "UPLOADED",
  "FAILED",
] as const;
export const generatedImageRenderStatusValues = [
  "unverified",
  "verified",
  "failed",
] as const;
export const generatedImageStorageStatusValues = [
  "unverified",
  "available",
  "missing",
  "metadata_mismatch",
] as const;
export const imageSourceValues = [
  "own",
  "catalog",
  "unknown",
  "screenshot",
] as const;
export default defineEntity({
  key: "image",
  names: { singular: "Image", plural: "Images" },
  route: {
    basePath: "images",
    // The image list is not a kernel list (no create contract), so its index
    // route stays hand-written; the detail reads its own query.
    listOverride: null,
    detailOverride: {
      query: {
        module: "~/entities/image.functions",
        export: "imageDetailQuery",
      },
    },
  },
  table: "Image",
  identifiers: { brand: "ImageId", shortcode: "IMG-" },
  presentation: {
    titleField: "filename",
    domain: null,
    description: "Images attached to household records.",
    emptyState: {
      title: "No photos yet",
      description:
        "Add photos to attach them to recipes, products, and places.",
    },
    icons: { lucide: "Image", sfSymbol: "photo", emoji: "🖼️" },
    detail: {
      sectionOverrides: [
        {
          kind: "fields",
          id: "overview",
          title: "Overview",
          placement: "supporting",
          fields: [
            "filename",
            "url",
            "key",
            "size",
            "contentType",
            "status",
            "width",
            "height",
            "detectedContentType",
            "sha256",
            "renderStatus",
            "storageStatus",
            "useOriginal",
            "source",
            "sourcePageUrl",
            "sourceAssetUrl",
            "sourceName",
            "verifiedAt",
            "capturedAt",
            "capturedAtOffsetMinutes",
            "captureLocation",
            "capturePlaceName",
            "captureDeviceLabel",
            "capturedByPartyId",
            "captureAttribution",
            "provenanceEvidence",
            "createdAt",
            "updatedAt",
          ],
        },
        { kind: "slot", id: "associations", title: "Used by" },
        {
          kind: "relation",
          id: "sightings",
          title: "Sightings",
          relation: "sightings",
          filter: { descriptor: "imageId" },
          columns: ["ledgerPartyName", "deviceName", "capturedAt", "matchKind"],
          hideWhenEmpty: true,
          placement: "supporting",
        },
      ],
    },
  },
  model: {
    fields: [
      {
        key: "filename",
        kind: "text",
        control: { kind: "text" },
        display: { list: true, detail: true },
        validation: {
          read: z.string(),
          create: null,
          update: z.string().trim().min(1).max(255),
        },
      },
      {
        key: "id",
        kind: "identifier",
        validation: {
          read: imageShortcode,
          create: null,
          update: null,
        },
      },
      {
        key: "representations",
        kind: "json",
        provenance: {
          kind: "derived",
          sources: [{ label: "Original and validated image derivatives" }],
        },
        explanation: {
          ruleId: "image.representations",
          description:
            "The original is preserved. A validated transparent derivative of the current original is preferred unless Use original is selected.",
          resolver: "imageRepresentation",
          sourceDependencies: [
            { path: "representations.original", label: "Original image" },
            {
              path: "representations.transparent",
              label: "Validated transparent derivative",
            },
            {
              path: "representations.preferredKind",
              label: "Selected representation",
            },
            { path: "useOriginal", label: "Use original preference" },
          ],
        },
        validation: {
          read: optionalImageRepresentations,
          create: null,
          update: null,
        },
      },
      {
        key: "url",
        kind: "text",
        label: "URL",
        display: { list: true, detail: true, listHidden: true },
        provenance: { kind: "derived", sources: [{ label: "Image storage" }] },
        explanation: {
          ruleId: "image.url",
          description:
            "The public image URL is generated from this Image record's current object-storage key.",
          readPath: "url",
          sourceDependencies: [{ path: "key", label: "Image storage key" }],
        },
        validation: {
          read: z.url(),
          create: null,
          update: null,
        },
      },
      {
        key: "key",
        kind: "text",
        display: { list: true, detail: true, listHidden: true },
        validation: {
          read: z.string(),
          create: null,
          update: null,
        },
      },
      {
        key: "size",
        kind: "number",
        display: { list: true, detail: true },
        validation: {
          read: z.number().int().positive(),
          create: null,
          update: null,
        },
      },
      {
        key: "contentType",
        kind: "text",
        label: "Type",
        display: {
          list: true,
          detail: true,
          width: "sm",
          mobile: { slot: "subtitle", priority: 10 },
        },
        validation: {
          read: z.string(),
          create: null,
          update: null,
        },
      },
      {
        key: "status",
        kind: "enum",
        display: {
          list: true,
          detail: true,
          width: "sm",
          mobile: { slot: "meta", priority: 20 },
        },
        validation: {
          read: z.enum(generatedImageStatusValues),
          create: null,
          update: null,
        },
      },
      {
        key: "width",
        kind: "number",
        nullable: true,
        display: { list: true, detail: true, listHidden: true },
        validation: {
          read: z.number().int().positive().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "height",
        kind: "number",
        nullable: true,
        display: { list: true, detail: true, listHidden: true },
        validation: {
          read: z.number().int().positive().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "perceptualHash",
        kind: "text",
        nullable: true,
        readKey: null,
      },
      {
        key: "sourceFingerprint",
        kind: "json",
        nullable: true,
        readKey: null,
      },
      {
        key: "detectedContentType",
        kind: "text",
        label: "Detected type",
        nullable: true,
        // Hidden by default: it repeats Type except when sniffing disagrees
        // with the stored content type, which the detail page shows.
        display: { list: true, detail: true, listHidden: true },
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "sha256",
        kind: "text",
        nullable: true,
        display: { list: true, detail: true, listHidden: true },
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "renderStatus",
        kind: "enum",
        nullable: true,
        display: { list: true, detail: true },
        validation: {
          read: z.enum(generatedImageRenderStatusValues).nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "storageStatus",
        kind: "enum",
        nullable: true,
        display: { list: true, detail: true },
        validation: {
          read: z.enum(generatedImageStorageStatusValues).nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "source",
        kind: "enum",
        label: "Source",
        display: { list: true, detail: true },
        validation: {
          read: z.enum(imageSourceValues),
          create: null,
          update: z.enum(imageSourceValues).optional(),
        },
      },
      {
        key: "sourcePageUrl",
        kind: "text",
        nullable: true,
        label: "Source page",
        display: { detail: true },
        validation: {
          read: z.url().nullable(),
          create: null,
          update: z.url().nullable().optional(),
        },
      },
      {
        key: "sourceAssetUrl",
        kind: "text",
        nullable: true,
        label: "Source asset",
        display: { detail: true },
        validation: {
          read: z.url().nullable(),
          create: null,
          update: z.url().nullable().optional(),
        },
      },
      {
        key: "sourceName",
        kind: "text",
        nullable: true,
        label: "Source name",
        display: { detail: true },
        validation: {
          read: z.string().nullable(),
          create: null,
          update: z.string().trim().min(1).max(255).nullable().optional(),
        },
      },
      {
        key: "useOriginal",
        kind: "boolean",
        label: "Use original",
        display: { list: true, detail: true },
        validation: {
          read: z.boolean(),
          create: null,
          update: z.boolean().optional(),
        },
      },
      {
        key: "verifiedAt",
        kind: "timestamp",
        nullable: true,
        display: { list: true, detail: true },
        validation: {
          read: z.date().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "capturedAt",
        kind: "timestamp",
        nullable: true,
        label: "Captured at",
        display: { list: true, detail: true, format: "timestamp" },
        validation: {
          read: z.date().nullable(),
          create: null,
          update: z.coerce.date().nullable().optional(),
        },
      },
      {
        key: "capturedAtOffsetMinutes",
        kind: "number",
        nullable: true,
        label: "Captured at offset (minutes)",
        display: { detail: true },
        validation: {
          read: z.number().int().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "captureLocation",
        kind: "json",
        nullable: true,
        label: "Capture location",
        // Detail-only by design (no `list: true`) — GPS coordinates never
        // belong in a list column.
        display: {
          detail: true,
          renderer: { detail: "image-capture-location" },
        },
        validation: {
          read: imageCaptureLocation.nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "capturePlaceName",
        kind: "text",
        nullable: true,
        label: "Capture place",
        display: { detail: true },
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "captureDeviceLabel",
        kind: "text",
        nullable: true,
        label: "Capture device",
        display: { detail: true },
        validation: {
          read: z.string().nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "capturedByPartyId",
        kind: "identifier",
        nullable: true,
        label: "Captured by",
        reference: { entity: "ledgerParty" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true, columnId: "capturedByName" },
        explanation: {
          ruleId: "image.capturedBy",
          description:
            "The capturing member is derived by scoring the image's photo-library sightings, falling back to embedded EXIF evidence when there are none, and can always be set manually.",
          resolver: "imageCapture",
          readPath: "capturedByPartyId",
        },
        validation: {
          read: ledgerPartyShortcode.nullable(),
          create: null,
          update: ledgerPartyShortcode.nullable().optional(),
        },
      },
      {
        key: "capturedByName",
        kind: "text",
        nullable: true,
        provenance: {
          kind: "derived",
          sources: [
            { label: "Photo library sightings" },
            { label: "Embedded EXIF" },
            { label: "Manual" },
          ],
        },
        explanation: {
          ruleId: "image.capturedByName",
          description:
            "The current name of the derived capturing member, if set.",
        },
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "captureAttribution",
        kind: "enum",
        label: "Capture attribution",
        display: { list: true, detail: true, width: "sm" },
        validation: {
          read: imageCaptureAttribution,
          create: null,
          update: null,
        },
      },
      {
        key: "provenanceEvidence",
        kind: "json",
        nullable: true,
        label: "Provenance evidence",
        display: {
          detail: true,
          renderer: { detail: "image-provenance-evidence" },
        },
        validation: {
          read: imageProvenanceEvidence.nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "metadataRevision",
        kind: "number",
        nullable: true,
        readKey: null,
      },
      {
        key: "embeddedMetadata",
        kind: "json",
        nullable: true,
        readKey: null,
      },
      {
        key: "createdAt",
        kind: "timestamp",
        display: { detail: true },
        validation: {
          read: z.date(),
          create: null,
          update: null,
        },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        display: { detail: true },
        validation: {
          read: z.date(),
          create: null,
          update: null,
        },
      },
      { key: "shortcode", kind: "text", readKey: null },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
    ],
    storage: [
      { key: "id", default: "generated", specialized: "primary-key:ImageId" },
      { key: "shortcode", specialized: "shortcode" },
      "key",
      "filename",
      "size",
      "contentType",
      {
        key: "status",
        default: "literal",
        defaultValue: "'PENDING'",
        specialized: "enum:ImageStatus",
      },
      "width",
      "height",
      "perceptualHash",
      "sourceFingerprint",
      "detectedContentType",
      "sha256",
      { key: "renderStatus", specialized: "enum:ImageRenderStatus" },
      { key: "storageStatus", specialized: "enum:ImageStorageStatus" },
      {
        key: "source",
        specialized: "enum:source",
        default: "literal",
        defaultValue: "unknown",
      },
      "sourcePageUrl",
      "sourceAssetUrl",
      "sourceName",
      { key: "useOriginal", default: "literal", defaultValue: false },
      "verifiedAt",
      "capturedAt",
      "capturedAtOffsetMinutes",
      { key: "captureLocation", specialized: "json:captureLocation" },
      "capturePlaceName",
      "captureDeviceLabel",
      { key: "capturedByPartyId", reference: "ledgerParty" },
      {
        key: "captureAttribution",
        specialized: "enum:captureAttribution",
        default: "literal",
        defaultValue: "none",
      },
      {
        key: "provenanceEvidence",
        specialized: "json:provenanceEvidence",
      },
      "metadataRevision",
      { key: "embeddedMetadata", specialized: "json:embeddedMetadata" },
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [],
    update: [
      "filename",
      "source",
      "sourcePageUrl",
      "sourceAssetUrl",
      "sourceName",
      "useOriginal",
      "capturedByPartyId",
      "capturedAt",
    ],
    bulk: [],
    audit: [],
    sort: {
      fields: ["createdAt", "updatedAt", "filename", "size", "status"],
    },
    output: [
      "representations",
      "id",
      "url",
      "key",
      "filename",
      "size",
      "contentType",
      "status",
      "width",
      "height",
      "detectedContentType",
      "sha256",
      "renderStatus",
      "storageStatus",
      "source",
      "sourcePageUrl",
      "sourceAssetUrl",
      "sourceName",
      "useOriginal",
      "verifiedAt",
      "capturedAt",
      "capturedAtOffsetMinutes",
      "captureLocation",
      "capturePlaceName",
      "captureDeviceLabel",
      "capturedByPartyId",
      "capturedByName",
      "captureAttribution",
      "provenanceEvidence",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: null,
    update: { module: "@cubby/schemas/image", export: "imageUpdateInput" },
    output: { module: "@cubby/schemas/image", export: "imageOut" },
    list: {
      module: "@cubby/schemas/image",
      export: "imageWithEntitySchema",
    },
    detail: {
      module: "@cubby/schemas/image",
      export: "imageWithEntitySchema",
    },
  },
  filters: {
    schema: { module: "@cubby/schemas/image", export: "imageFilterFields" },
    descriptors: [
      {
        columnId: "filename",
        field: "nameFilter",
        kind: "text",
        placeholder: "Filter by filename...",
        deriveSchema: true,
        stored: true,
        schemaDescription: "Filter by filename (substring)",
      },
      {
        columnId: "status",
        kind: "multiselect",
        placeholder: "Filter by upload status...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        schemaDescription: "Filter by upload status",
        options: [
          { value: "PENDING", label: "Pending", color: "var(--slate)" },
          { value: "UPLOADED", label: "Uploaded", color: "var(--positive)" },
          { value: "FAILED", label: "Failed", color: "var(--destructive)" },
        ],
      },
      {
        columnId: "processingIssue",
        field: "processingIssue",
        kind: "multiselect",
        placeholder: "Filter processing issues...",
        options: [
          { value: "failed", label: "Failed", color: "var(--destructive)" },
          {
            value: "review_needed",
            label: "Needs review",
            color: "var(--warning)",
          },
        ],
      },
      {
        columnId: "entity",
        field: "referencePresenceFilter",
        kind: "presence",
        placeholder: "Filter references...",
        options: [
          { value: "has", label: "Has reference", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "createdAt",
        kind: "range",
        placeholder: "Filter by created date...",
        options: [
          { value: "olderThan1h", label: "Older than 1 hour" },
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveImageCreatedDate",
        },
      },
      {
        columnId: "updatedAt",
        kind: "range",
        placeholder: "Filter by updated date...",
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveUpdatedDate",
        },
      },
      {
        columnId: "importRunId",
        kind: "idMulti",
        placeholder: "Filter by import run...",
        brandRef: { entity: "importRun" },
        urlOnly: true,
      },
      {
        columnId: "targetState",
        kind: "multiselect",
        placeholder: "Filter by import-run target state...",
        options: [
          { value: "pending", label: "Pending", color: "var(--slate)" },
          { value: "prepared", label: "Prepared", color: "var(--info)" },
          {
            value: "completed",
            label: "Completed",
            color: "var(--positive)",
          },
          { value: "skipped", label: "Skipped", color: "var(--slate)" },
          {
            value: "unresolved",
            label: "Unresolved",
            color: "var(--warning)",
          },
          {
            value: "needs_evidence",
            label: "Needs evidence",
            color: "var(--warning)",
          },
          {
            value: "unavailable",
            label: "Unavailable",
            color: "var(--destructive)",
          },
        ],
      },
      {
        columnId: "source",
        kind: "multiselect",
        placeholder: "Filter by source...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        options: [
          { value: "own", label: "Own" },
          { value: "catalog", label: "Catalog" },
          { value: "unknown", label: "Unknown" },
          { value: "screenshot", label: "Screenshot" },
        ],
      },
      {
        columnId: "captureAttribution",
        kind: "multiselect",
        placeholder: "Filter by capture attribution...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        options: [
          { value: "none", label: "None" },
          { value: "derived", label: "Derived" },
          { value: "ambiguous", label: "Ambiguous" },
          { value: "confirmed", label: "Confirmed" },
        ],
      },
      {
        columnId: "capturedAt",
        kind: "range",
        placeholder: "Filter by captured date...",
        deriveSchema: true,
        stored: true,
        range: { kind: "date" },
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
      },
      {
        columnId: "capturedByPartyId",
        kind: "idMulti",
        placeholder: "Filter by captured by...",
        brandRef: { entity: "ledgerParty" },
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "captured-by",
      label: "Captured by",
      target: "ledgerParty",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Image.capturedByPartyId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Image.capturedByPartyId", direction: "incoming" }],
      },
    },
    {
      key: "sightings",
      label: "Sightings",
      target: "imageSighting",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImageSighting.imageId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "ImageSighting.imageId", direction: "outgoing" }],
      },
    },
  ],
  // Image filenames and the current preferred description/correction are
  // searchable. The shared search document loader adds only direct owners.
  search: { enabled: true },
  capabilities: {
    auditable: false,
    images: { storage: false },
    countable: true,
    softDelete: true,
    delete: { mode: "hard", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "update", "delete"],
    dataQuality: {
      checks: [
        {
          id: "image_provenance_unknown",
          facet: "provenance",
          weight: 3,
          label: "Source",
          message: "This image's origin is unknown.",
        },
        {
          id: "image_capture_attribution",
          facet: "provenance",
          kind: "defect",
          weight: 2,
          label: "Capture attribution",
          message:
            "Multiple household members could be the photographer; confirm who captured this.",
        },
        {
          id: "image_capture_date",
          facet: "content",
          weight: 1,
          label: "Capture date",
          message: "No capture date is recorded for this image.",
        },
        {
          id: "image_dimensions",
          facet: "integrity",
          weight: 1,
          label: "Dimensions",
          message: "Image width or height is missing.",
        },
        {
          id: "image_sighting_missing",
          facet: "provenance",
          weight: 1,
          label: "Sightings",
          message:
            "No live photo-library sighting is recorded for this own-sourced image.",
        },
      ],
    },
  },
  extensions: {
    ports: {
      repository: {
        module: "~/server/repo/image.entity-adapter",
        export: "imageEntityAdapter",
      },
    },
  },
});
