import { defineEntity } from "./definition.js";
import { plainDate } from "@cubby/schemas/base-entity";
import {
  imageShortcode,
  ingredientShortcode,
  locationShortcode,
  plantingShortcode,
  productShortcode,
} from "../identifier-fields.js";
import {
  plantingLocationStartKind,
  plantingStatus,
} from "@cubby/schemas/garden-fields";
import { imageOut } from "./field-primitives.js";
import { z } from "zod";

const optionalText = z.string().trim().min(1).nullable();
export default defineEntity({
  key: "planting",
  names: { singular: "Planting", plural: "Plantings" },
  route: { basePath: "plantings", list: null, detail: true },
  table: "Planting",
  identifiers: { brand: "PlantingId", shortcode: "PLT-" },
  presentation: {
    titleField: "displayName",
    domain: "house",
    description: "Crops growing now and planned for later.",
    emptyState: {
      title: "No plantings yet",
      description:
        "Record what is growing now or plan the next crop for one of your garden locations.",
    },
    icons: { lucide: "Sprout", sfSymbol: "leaf" },
    detail: {
      variant: "journal",
      hero: {
        chip: "status",
        images: false,
        actions: [
          "edit",
          "startPlanting",
          "movePlanting",
          "splitPlanting",
          "finishPlanting",
        ],
      },
      sections: [
        {
          kind: "relation",
          id: "garden-history",
          title: "Journal",
          relation: "entries",
          filter: { descriptor: "plantingId" },
          columns: [
            "kind",
            "observedOn",
            "locationId",
            "note",
            "harvestAmount",
          ],
          sort: { field: "observedOn", direction: "desc" },
        },
        {
          kind: "fields",
          id: "overview",
          title: "Planting details",
          placement: "supporting",
          fields: [
            "ingredientId",
            "variety",
            "status",
            "locationId",
            "intendedLocationId",
            "sourceProductId",
            "parentPlantingId",
            "quantity",
            "plannedWindow",
            "plannedDate",
            "sowedOn",
            "transplantedOn",
            "finishedOn",
            "notes",
          ],
        },
        {
          kind: "slot",
          id: "location-history",
          title: "Location history",
          placement: "supporting",
        },
        {
          kind: "slot",
          id: "planting-guide",
          title: "Local planting guide",
          placement: "supporting",
        },
      ],
    },
    list: {
      views: ["table", "timeline"],
      actions: ["delete"],
      timeline: {
        fields: ["plannedDate", "sowedOn", "transplantedOn", "finishedOn"],
        lifecycle: {
          start: "sowedOn",
          milestones: ["plannedDate", "transplantedOn"],
          end: "finishedOn",
        },
      },
    },
    edit: { readOnlyOnUpdate: ["status", "locationId"] },
  },
  model: {
    fields: [
      {
        key: "ingredientId",
        kind: "identifier",
        reference: { entity: "ingredient" },
        label: "Crop",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true, detailOrder: 0 },
        validation: {
          read: ingredientShortcode,
          create: ingredientShortcode,
          update: ingredientShortcode.optional(),
        },
      },
      {
        key: "sourceProductId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "product" },
        label: "Seed source",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { detail: true, detailOrder: 5 },
        validation: {
          read: productShortcode.nullable(),
          create: productShortcode.nullable().default(null),
          update: productShortcode.nullable().optional(),
        },
      },
      {
        key: "locationId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "location" },
        label: "Location",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true, detailOrder: 3 },
        validation: {
          read: locationShortcode.nullable(),
          create: locationShortcode.nullable().default(null),
          update: locationShortcode.nullable().optional(),
        },
      },
      {
        key: "intendedLocationId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "location" },
        label: "Intended location",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { detail: true, detailOrder: 4 },
        validation: {
          read: locationShortcode.nullable(),
          create: locationShortcode.nullable().default(null),
          update: locationShortcode.nullable().optional(),
        },
      },
      {
        key: "parentPlantingId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "planting" },
        label: "Split from",
        display: { detail: true, detailOrder: 6 },
        validation: {
          read: plantingShortcode.nullable(),
          create: null,
          update: null,
        },
      },
      {
        key: "status",
        kind: "enum",
        control: {
          kind: "select",
          options: [
            { value: "planned", label: "Planned" },
            { value: "growing", label: "Growing" },
            { value: "finished", label: "Finished" },
          ],
        },
        display: { list: true, detail: true, detailOrder: 2 },
        validation: {
          read: plantingStatus,
          create: plantingStatus.default("planned"),
          update: plantingStatus.optional(),
        },
      },
      {
        key: "variety",
        kind: "text",
        nullable: true,
        control: { kind: "text" },
        display: { list: true, detail: true, detailOrder: 1 },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "quantity",
        kind: "text",
        nullable: true,
        control: { kind: "text" },
        display: { detail: true, detailOrder: 7 },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        control: { kind: "textarea" },
        display: { detail: true, detailOrder: 13 },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "plannedWindow",
        kind: "text",
        nullable: true,
        control: { kind: "text" },
        display: { detail: true, detailOrder: 8 },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "plannedDate",
        kind: "date",
        nullable: true,
        control: { kind: "date" },
        display: { detail: true, detailOrder: 9, format: "plainDate" },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        key: "sowedOn",
        kind: "date",
        nullable: true,
        control: { kind: "date" },
        display: {
          list: true,
          detail: true,
          detailOrder: 10,
          format: "plainDate",
        },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        key: "transplantedOn",
        kind: "date",
        nullable: true,
        control: { kind: "date" },
        display: { detail: true, detailOrder: 11, format: "plainDate" },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        key: "finishedOn",
        kind: "date",
        nullable: true,
        control: { kind: "date" },
        display: {
          list: true,
          detail: true,
          detailOrder: 12,
          format: "plainDate",
        },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        // Create-only: the first location period's start. Must stay the same
        // Zod as `gardenCreatePlantingInput` (`packages/schemas/src/garden.ts`),
        // which `createPlanting` reads.
        key: "inLocationSince",
        kind: "date",
        nullable: true,
        readKey: null,
        label: "In location since",
        control: { kind: "date" },
        validation: {
          read: null,
          create: plainDate.nullable().optional(),
          update: null,
        },
      },
      {
        key: "inLocationSinceKind",
        kind: "enum",
        readKey: null,
        label: "Location start",
        control: {
          kind: "select",
          options: [
            { value: "actual", label: "Actual date" },
            { value: "recorded", label: "Recorded date" },
          ],
        },
        validation: {
          read: null,
          create: plantingLocationStartKind.default("actual"),
          update: null,
        },
      },
      {
        key: "ingredientName",
        kind: "text",
        validation: { read: z.string(), create: null, update: null },
      },
      {
        key: "sourceProductName",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "locationName",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "intendedLocationName",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        // The crop ingredient's guide key, for the `planting-guide` slot.
        key: "gardenGuideKey",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "pendingImageIds",
        kind: "identifier",
        readKey: null,
        reference: { entity: "image", multiple: true },
        validation: {
          read: null,
          create: z.array(imageShortcode).optional(),
          update: z.array(imageShortcode).optional(),
        },
      },
      {
        key: "removeImageIds",
        kind: "identifier",
        readKey: null,
        reference: { entity: "image", multiple: true },
        validation: {
          read: null,
          create: null,
          update: z.array(imageShortcode).optional(),
        },
      },
      {
        key: "imageOrder",
        kind: "text",
        readKey: null,
        validation: {
          read: null,
          create: null,
          update: z.array(imageShortcode).optional(),
        },
      },
      {
        key: "images",
        kind: "json",
        display: { list: true, standard: "image", columnId: "image" },
        validation: { read: z.array(imageOut), create: null, update: null },
      },
      {
        // `"<ingredient name>[ · <variety>]"` — the canonical non-null title;
        // `variety` alone is nullable and cannot serve as the title field.
        key: "displayName",
        kind: "text",
        validation: { read: z.string(), create: null, update: null },
      },
      {
        key: "id",
        kind: "identifier",
        validation: { read: plantingShortcode, create: null, update: null },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        validation: { read: z.date(), create: null, update: null },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        validation: { read: z.date(), create: null, update: null },
      },
      { key: "shortcode", kind: "text", readKey: null },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
    ],
    storage: [
      {
        key: "id",
        default: "generated",
        specialized: "primary-key:PlantingId",
      },
      { key: "shortcode", specialized: "shortcode" },
      { key: "ingredientId", reference: "ingredient" },
      { key: "sourceProductId", reference: "product" },
      { key: "locationId", reference: "location" },
      { key: "intendedLocationId", reference: "location" },
      { key: "parentPlantingId", reference: "planting" },
      {
        key: "status",
        specialized: "enum:status",
        default: "literal",
        defaultValue: "planned",
      },
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "plannedDate",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [
      "ingredientId",
      "sourceProductId",
      "locationId",
      "intendedLocationId",
      "status",
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "plannedDate",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
      "inLocationSince",
      "inLocationSinceKind",
      "pendingImageIds",
    ],
    update: [
      "ingredientId",
      "sourceProductId",
      "locationId",
      "intendedLocationId",
      "status",
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "plannedDate",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
      "pendingImageIds",
      "removeImageIds",
      "imageOrder",
    ],
    bulk: [],
    audit: ["status", "locationId"],
    sort: {
      fields: ["createdAt", "updatedAt", "status", "sowedOn", "finishedOn"],
      default: "createdAt",
    },
    intents: {
      fields: {
        capture: ["ingredientId", "locationId", "status", "pendingImageIds"],
        full: [
          "ingredientId",
          "sourceProductId",
          "locationId",
          "intendedLocationId",
          "status",
          "variety",
          "quantity",
          "notes",
          "plannedWindow",
          "plannedDate",
          "sowedOn",
          "transplantedOn",
          "inLocationSince",
          "inLocationSinceKind",
          "pendingImageIds",
          "removeImageIds",
          "imageOrder",
        ],
      },
      create: ["capture", "full"],
      update: ["full"],
    },
    output: [
      "id",
      "ingredientId",
      "sourceProductId",
      "locationId",
      "intendedLocationId",
      "parentPlantingId",
      "status",
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "plannedDate",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
      "images",
      "displayName",
      "ingredientName",
      "sourceProductName",
      "locationName",
      "intendedLocationName",
      "gardenGuideKey",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/garden", export: "plantingCreateInput" },
    update: { module: "@cubby/schemas/garden", export: "plantingUpdateData" },
    output: { module: "@cubby/schemas/garden", export: "plantingOut" },
    list: { module: "@cubby/schemas/garden", export: "plantingListItemOut" },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/garden", export: "plantingFilterFields" },
    descriptors: [
      {
        columnId: "status",
        kind: "multiselect",
        placeholder: "Filter by status...",
        options: [
          { value: "planned", label: "Planned" },
          { value: "growing", label: "Growing" },
          { value: "finished", label: "Finished" },
        ],
        deriveSchema: true,
        stored: true,
      },
      {
        columnId: "locationId",
        kind: "idMulti",
        placeholder: "Filter by location...",
        brandRef: { entity: "location", kind: "id" },
      },
      {
        columnId: "ingredientId",
        kind: "idMulti",
        placeholder: "Filter by crop...",
        brandRef: { entity: "ingredient", kind: "id" },
      },
    ],
  },
  relations: [
    {
      key: "ingredient",
      label: "Ingredient",
      target: "ingredient",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.ingredientId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.ingredientId", direction: "incoming" }],
      },
    },
    {
      key: "source-product",
      label: "Source product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.sourceProductId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.sourceProductId", direction: "incoming" }],
      },
    },
    {
      key: "location",
      label: "Current location",
      target: "location",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.locationId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.locationId", direction: "incoming" }],
      },
    },
    {
      key: "intended-location",
      label: "Intended location",
      target: "location",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.intendedLocationId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.intendedLocationId", direction: "incoming" }],
      },
    },
    {
      key: "parent-planting",
      label: "Parent planting",
      target: "planting",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.parentPlantingId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.parentPlantingId", direction: "incoming" }],
      },
    },
    {
      key: "images",
      label: "Images",
      target: "image",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "PlantingImage.plantingId", direction: "incoming" },
          { edge: "PlantingImage.imageId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "PlantingImage.imageId", direction: "incoming" },
          { edge: "PlantingImage.plantingId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "location-history",
      label: "Location history",
      target: "location",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "PlantingLocationPeriod.plantingId", direction: "incoming" },
          { edge: "PlantingLocationPeriod.locationId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "PlantingLocationPeriod.locationId", direction: "incoming" },
          { edge: "PlantingLocationPeriod.plantingId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "entries",
      label: "Journal entries",
      target: "gardenEntry",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "GardenEntry.plantingId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "GardenEntry.plantingId", direction: "outgoing" }],
      },
    },
    {
      key: "location-history-entries",
      label: "Location history entries",
      target: "gardenEntry",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "PlantingLocationPeriod.plantingId", direction: "incoming" },
          {
            edge: "PlantingLocationPeriod.sourceGardenEntryId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "PlantingLocationPeriod.sourceGardenEntryId",
            direction: "incoming",
          },
          { edge: "PlantingLocationPeriod.plantingId", direction: "outgoing" },
        ],
      },
    },
  ],
  // `displayName` is a non-null projected title (ingredient + variety), so
  // Cmd-K / `/search` can index plantings like every other named entity.
  search: { enabled: true },
  capabilities: {
    auditable: true,
    timeline: "default",
    images: "gallery",
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/garden/entity-adapters",
        export: "plantingEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: null,
      search: { projection: null, semanticText: null, dependentRefresh: null },
    },
  },
});
