import { defineEntity } from "./definition.js";
import { plainDate } from "@cubby/schemas/base-entity";
import {
  ingredientShortcode,
  locationShortcode,
  plantingShortcode,
  productShortcode,
  taskShortcode,
} from "../identifier-fields.js";
import { plantingStatus } from "@cubby/schemas/garden-fields";
import { z } from "zod";

const optionalText = z.string().trim().min(1).nullable();
export default defineEntity({
  key: "planting",
  names: { singular: "Planting", plural: "Plantings" },
  route: { basePath: "plantings", list: true, detail: true },
  table: "Planting",
  identifiers: { brand: "PlantingId", shortcode: "PLT-" },
  presentation: {
    titleField: "displayName",
    domain: "house",
    description: "Crops growing now and planned for later.",
    emptyState: {
      title: "No plantings yet",
      description:
        "Record what is growing now or plan the next crop for one of your garden locations.",
    },
    icons: { lucide: "Sprout", sfSymbol: "leaf" },
    detail: {
      variant: "journal",
      hero: {
        chip: "status",
      },
      sections: [
        {
          kind: "relation",
          id: "garden-history",
          title: "Journal",
          relation: "entries",
          filter: { descriptor: "journalPlantingId" },
          columns: [
            "kind",
            "observedOn",
            "locationId",
            "note",
            "harvestAmount",
          ],
          sort: { field: "observedOn", direction: "desc" },
        },
        {
          kind: "fields",
          id: "overview",
          title: "Planting details",
          placement: "supporting",
          fields: [
            "ingredientId",
            "variety",
            "status",
            "locationId",
            "sourceProductId",
            "quantity",
            "plannedWindow",
            "sowedOn",
            "transplantedOn",
            "finishedOn",
            "notes",
            "taskId",
            "guideSowWindow",
            "guideTransplantWindow",
          ],
        },
      ],
    },
    list: {
      views: ["table", "timeline"],
      actions: ["delete"],
      timeline: {
        fields: ["sowedOn", "transplantedOn", "finishedOn"],
        lifecycle: {
          start: ["sowedOn", "transplantedOn"],
          milestones: ["transplantedOn"],
          end: "finishedOn",
        },
      },
    },
  },
  model: {
    fields: [
      {
        key: "ingredientId",
        kind: "identifier",
        reference: { entity: "ingredient" },
        label: "Crop",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true },
        validation: {
          read: ingredientShortcode,
          create: ingredientShortcode,
          update: ingredientShortcode.optional(),
        },
      },
      {
        key: "sourceProductId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "product" },
        label: "Seed source",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { detail: true },
        validation: {
          read: productShortcode.nullable(),
          create: productShortcode.nullable().default(null),
          update: productShortcode.nullable().optional(),
        },
      },
      {
        key: "locationId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "location" },
        label: "Location",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true },
        validation: {
          read: locationShortcode.nullable(),
          create: locationShortcode.nullable().default(null),
          update: locationShortcode.nullable().optional(),
        },
      },
      {
        key: "taskId",
        kind: "identifier",
        nullable: true,
        reference: { entity: "task" },
        label: "Task",
        control: { kind: "specialized", renderer: "entity-select" },
        display: { detail: true },
        validation: {
          read: taskShortcode.nullable(),
          create: taskShortcode.nullable().default(null),
          update: taskShortcode.nullable().optional(),
        },
      },
      {
        key: "status",
        kind: "enum",
        control: {
          kind: "select",
          options: [
            { value: "planned", label: "Planned" },
            { value: "growing", label: "Growing" },
            { value: "finished", label: "Finished" },
          ],
        },
        display: { list: true, detail: true },
        validation: {
          read: plantingStatus,
          create: plantingStatus.default("planned"),
          update: plantingStatus.optional(),
        },
      },
      {
        key: "variety",
        kind: "text",
        nullable: true,
        control: { kind: "text" },
        display: { list: true, detail: true },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "quantity",
        kind: "text",
        nullable: true,
        control: { kind: "text" },
        display: { detail: true },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        control: { kind: "textarea" },
        display: { detail: true },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "plannedWindow",
        kind: "text",
        nullable: true,
        label: "Planned window",
        control: { kind: "text" },
        display: { detail: true },
        validation: {
          read: optionalText,
          create: optionalText.default(null),
          update: optionalText.optional(),
        },
      },
      {
        key: "sowedOn",
        kind: "date",
        nullable: true,
        label: "Sowed",
        control: { kind: "date" },
        display: {
          list: true,
          detail: true,
          format: "plainDate",
        },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        key: "transplantedOn",
        kind: "date",
        nullable: true,
        label: "Transplanted",
        control: { kind: "date" },
        display: { list: true, detail: true, format: "plainDate" },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        key: "finishedOn",
        kind: "date",
        nullable: true,
        label: "Finished",
        control: { kind: "date" },
        display: {
          list: true,
          detail: true,
          format: "plainDate",
        },
        validation: {
          read: plainDate.nullable(),
          create: plainDate.nullable().default(null),
          update: plainDate.nullable().optional(),
        },
      },
      {
        key: "ingredientName",
        kind: "text",
        validation: { read: z.string(), create: null, update: null },
      },
      {
        key: "sourceProductName",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "locationName",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "taskName",
        kind: "text",
        nullable: true,
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        // Derived on read from the crop ingredient's guide, for the household's
        // microclimate — formatted month range (e.g. "Feb–Apr") or null.
        key: "guideSowWindow",
        kind: "text",
        nullable: true,
        label: "Guide sow window",
        display: { detail: true },
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        key: "guideTransplantWindow",
        kind: "text",
        nullable: true,
        label: "Guide transplant window",
        display: { detail: true },
        validation: { read: z.string().nullable(), create: null, update: null },
      },
      {
        // `"<ingredient name>[ · <variety>]"` — the canonical non-null title;
        // `variety` alone is nullable and cannot serve as the title field.
        key: "displayName",
        kind: "text",
        validation: { read: z.string(), create: null, update: null },
      },
      {
        key: "id",
        kind: "identifier",
        validation: { read: plantingShortcode, create: null, update: null },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        validation: { read: z.date(), create: null, update: null },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        validation: { read: z.date(), create: null, update: null },
      },
      { key: "shortcode", kind: "text", readKey: null },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
    ],
    storage: [
      {
        key: "id",
        default: "generated",
        specialized: "primary-key:PlantingId",
      },
      { key: "shortcode", specialized: "shortcode" },
      { key: "ingredientId", reference: "ingredient" },
      { key: "sourceProductId", reference: "product" },
      { key: "locationId", reference: "location" },
      { key: "taskId", reference: "task" },
      {
        key: "status",
        specialized: "enum:status",
        default: "literal",
        defaultValue: "planned",
      },
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [
      "ingredientId",
      "sourceProductId",
      "locationId",
      "taskId",
      "status",
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
    ],
    update: [
      "ingredientId",
      "sourceProductId",
      "locationId",
      "taskId",
      "status",
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
    ],
    bulk: ["status", "finishedOn", "locationId"],
    audit: ["status", "locationId", "finishedOn", "taskId"],
    sort: {
      fields: ["createdAt", "updatedAt", "status", "sowedOn", "finishedOn"],
      default: "createdAt",
    },
    intents: {
      fields: {
        capture: ["ingredientId", "locationId", "status", "transplantedOn"],
        full: [
          "ingredientId",
          "sourceProductId",
          "locationId",
          "taskId",
          "status",
          "variety",
          "quantity",
          "notes",
          "plannedWindow",
          "sowedOn",
          "transplantedOn",
          "finishedOn",
        ],
      },
      create: ["capture", "full"],
      update: ["full"],
    },
    output: [
      "id",
      "ingredientId",
      "sourceProductId",
      "locationId",
      "taskId",
      "status",
      "variety",
      "quantity",
      "notes",
      "plannedWindow",
      "sowedOn",
      "transplantedOn",
      "finishedOn",
      "displayName",
      "ingredientName",
      "sourceProductName",
      "locationName",
      "taskName",
      "guideSowWindow",
      "guideTransplantWindow",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/planting",
      export: "plantingCreateInput",
    },
    update: { module: "@cubby/schemas/planting", export: "plantingUpdateData" },
    output: { module: "@cubby/schemas/planting", export: "plantingOut" },
    list: { module: "@cubby/schemas/planting", export: "plantingListItemOut" },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/planting",
      export: "plantingFilterFields",
    },
    descriptors: [
      {
        columnId: "status",
        kind: "multiselect",
        placeholder: "Filter by status...",
        options: [
          { value: "planned", label: "Planned" },
          { value: "growing", label: "Growing" },
          { value: "finished", label: "Finished" },
        ],
        deriveSchema: true,
        stored: true,
      },
      {
        columnId: "locationId",
        kind: "idMulti",
        placeholder: "Filter by location...",
        brandRef: { entity: "location" },
      },
      {
        columnId: "ingredientId",
        kind: "idMulti",
        placeholder: "Filter by crop...",
        brandRef: { entity: "ingredient" },
      },
      {
        columnId: "taskId",
        kind: "idMulti",
        placeholder: "Filter by task...",
        brandRef: { entity: "task" },
      },
      {
        columnId: "sourceProductId",
        kind: "idMulti",
        placeholder: "Filter by seed source...",
        brandRef: { entity: "product" },
      },
    ],
  },
  relations: [
    {
      key: "ingredient",
      label: "Ingredient",
      target: "ingredient",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.ingredientId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.ingredientId", direction: "incoming" }],
      },
    },
    {
      key: "source-product",
      label: "Source product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.sourceProductId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.sourceProductId", direction: "incoming" }],
      },
    },
    {
      key: "location",
      label: "Current location",
      target: "location",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.locationId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.locationId", direction: "incoming" }],
      },
    },
    {
      key: "task",
      label: "Task",
      target: "task",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Planting.taskId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Planting.taskId", direction: "incoming" }],
      },
    },
    {
      key: "entries",
      label: "Journal entries",
      target: "gardenEntry",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "GardenEntry.plantingId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "GardenEntry.plantingId", direction: "outgoing" }],
      },
    },
  ],
  // `displayName` is a non-null projected title (ingredient + variety), so
  // Cmd-K / `/search` can index plantings like every other named entity.
  search: { enabled: true },
  capabilities: {
    auditable: true,
    timeline: "custom",
    images: {
      storage: false,
      displaySources: [
        {
          relationPath: ["entries"],
          priority: 1,
          ordering: "newest",
          identityEvidence: false,
        },
        {
          relationPath: ["source-product"],
          priority: 2,
          ordering: "declared",
          identityEvidence: false,
        },
      ],
      ingress: [
        {
          kind: "existingRelated",
          routeId: "planting-garden-entry",
          relationPath: ["entries"],
          choice: "alternate",
        },
        {
          kind: "createRelated",
          routeId: "planting-new-garden-entry",
          relationPath: ["entries"],
          choice: "primary",
          bindings: [
            { field: "plantingId", from: "source-id" },
            {
              field: "locationId",
              from: "source-field",
              sourceField: "locationId",
            },
            { field: "observedOn", from: "capture-date" },
          ],
        },
      ],
      routing: {
        candidateFields: ["variety", "notes"],
        temporalFields: ["sowedOn", "transplantedOn", "finishedOn"],
        lifecycleFilters: [{ field: "status", equals: "growing" }],
        signals: {
          ocrFields: ["variety", "notes"],
          classifierLabels: ["plant", "garden"],
        },
        visualEvidence: [
          {
            relationPath: ["entries"],
            priority: 1,
            ordering: "newest",
          },
        ],
        abstention: { minimumScore: 0.76, minimumMargin: 0.14 },
      },
    },
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: { fields: ["status", "finishedOn", "locationId"] },
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "create", "update", "delete", "bulkUpdate"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/garden/entity-adapters",
        export: "plantingEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: null,
      search: { projection: null, semanticText: null, dependentRefresh: null },
      timeline: {
        module: "~/server/repo/garden/timeline",
        export: "plantingTimeline",
      },
    },
  },
});
