import { z } from "zod";

import {
  ledgerPartyShortcode,
  importRunShortcode,
  vendorAccountShortcode,
  vendorShortcode,
} from "../identifier-fields.js";
import {
  importRunPurpose,
  importRunStatus,
  importRunTrigger,
} from "../import-run-fields.js";
import { defineEntity } from "./definition.js";

const readOnly = <T extends z.ZodTypeAny>(read: T) => ({
  read,
  create: null,
  update: null,
});

/**
 * One run: a purchase-agent account sync, validation or enrichment, a
 * photo-inventory batch a member uploads for an agent to work, or a group of
 * AI calls (Jev suggestions on a page, one AI action, background work). The record is
 * written only by the run service and the writers; the manifest
 * exposes it read-only so the generic list, detail, inspector and MCP get/list
 * render it like any other record.
 */
export default defineEntity({
  key: "importRun",
  names: { singular: "Run", plural: "Runs" },
  route: {
    basePath: "runs",
    list: true,
    // The hand-written page stays until the generic detail carries its slots.
    detail: null,
  },
  table: "ImportRun",
  identifiers: { brand: "ImportRunId", shortcode: "RUN-" },
  presentation: {
    titleField: "displayName",
    domain: "finance",
    description:
      "Runs: purchase-agent syncs, validations, enrichments, photo-inventory batches and grouped AI work.",
    emptyState: {
      title: "No runs yet",
      description:
        "Runs appear when a vendor account syncs, a purchase is validated or photos are uploaded for inventory.",
    },
    icons: {
      lucide: "Bot",
      sfSymbol: "arrow.triangle.2.circlepath",
      emoji: "🤖",
    },
    detail: {
      hero: {
        chip: "status",
        stats: ["ordersSeen", "imported", "updated", "skipped"],
        breadcrumb: "vendorAccountId",
        actions: [],
      },
      sections: [
        {
          kind: "fields",
          id: "overview",
          title: "Overview",
          placement: "supporting",
          fields: [
            "status",
            "purpose",
            "trigger",
            "vendorAccountId",
            "vendorId",
            "ledgerPartyId",
            "actorName",
            "startedAt",
            "endedAt",
            "failureCode",
            "notes",
          ],
        },
        {
          kind: "fields",
          id: "counts",
          title: "Orders",
          placement: "supporting",
          fields: ["ordersSeen", "imported", "updated", "skipped"],
        },
        {
          kind: "fields",
          id: "runtime",
          title: "Runtime",
          placement: "supporting",
          collapsed: true,
          fields: [
            "coordinatorModel",
            "skillRevision",
            "runtimeRevision",
            "decisionRevision",
            "dispatchAttempts",
            "dispatchError",
            "coordinatorStartedAt",
            "auditedAt",
            "predecessorRunId",
            "createdAt",
            "updatedAt",
          ],
        },
      ],
    },
    list: { actions: [] },
  },
  model: {
    fields: [
      {
        key: "displayName",
        kind: "text",
        validation: readOnly(z.string().min(1)),
      },
      {
        key: "status",
        kind: "enum",
        control: {
          kind: "select",
          options: [
            { value: "running", label: "Running" },
            { value: "paused_auth", label: "Sign-in needed" },
            { value: "paused_offline", label: "Mac offline" },
            { value: "paused_approval", label: "Awaiting approval" },
            { value: "needs_review", label: "Needs review" },
            { value: "completed", label: "Completed" },
            { value: "failed", label: "Failed" },
            { value: "dispatch_failed", label: "Dispatch failed" },
          ],
        },
        display: { list: true, detail: true, width: "sm" },
        validation: readOnly(importRunStatus),
      },
      {
        key: "purpose",
        kind: "enum",
        control: {
          kind: "select",
          options: [
            { value: "account_sync", label: "Account sync" },
            { value: "purchase_validation", label: "Purchase validation" },
            { value: "product_enrichment", label: "Product enrichment" },
            { value: "photo_inventory", label: "Photo inventory" },
            { value: "ai_suggest", label: "AI suggestions" },
            { value: "ai_action", label: "AI action" },
            { value: "background", label: "Background" },
            { value: "file_import", label: "File import" },
            { value: "legacy", label: "Legacy" },
          ],
        },
        display: { list: true, detail: true, width: "sm" },
        validation: readOnly(importRunPurpose),
      },
      {
        key: "trigger",
        kind: "enum",
        control: {
          kind: "select",
          options: [
            { value: "foreground", label: "Foreground" },
            { value: "discovery", label: "Discovery" },
            { value: "manual", label: "Manual" },
            { value: "backfill", label: "Backfill" },
            { value: "ephemeral", label: "Ephemeral" },
          ],
        },
        display: { list: true, detail: true, width: "sm", listHidden: true },
        validation: readOnly(importRunTrigger),
      },
      {
        key: "vendorAccountId",
        kind: "identifier",
        label: "Vendor account",
        nullable: true,
        reference: { entity: "vendorAccount" },
        display: { list: true, detail: true, columnId: "vendorAccountLabel" },
        validation: readOnly(vendorAccountShortcode.nullable()),
      },
      {
        key: "vendorId",
        kind: "identifier",
        label: "Vendor",
        nullable: true,
        reference: { entity: "vendor" },
        display: { list: true, detail: true, columnId: "vendorName" },
        validation: readOnly(vendorShortcode.nullable()),
      },
      {
        key: "ledgerPartyId",
        kind: "identifier",
        label: "Member",
        reference: { entity: "ledgerParty" },
        display: { list: true, detail: true, columnId: "ledgerPartyName" },
        validation: readOnly(ledgerPartyShortcode),
      },
      {
        key: "actorName",
        kind: "text",
        label: "Actor",
        display: { detail: true },
        validation: readOnly(z.string()),
      },
      {
        key: "startedAt",
        kind: "timestamp",
        display: { list: true, detail: true, format: "timestamp" },
        validation: readOnly(z.date()),
      },
      {
        key: "endedAt",
        kind: "timestamp",
        nullable: true,
        display: { list: true, detail: true, format: "timestamp" },
        validation: readOnly(z.date().nullable()),
      },
      {
        key: "ordersSeen",
        kind: "number",
        display: { list: true, detail: true, width: "sm" },
        validation: readOnly(z.number().int().nonnegative()),
      },
      {
        key: "imported",
        kind: "number",
        display: { list: true, detail: true, width: "sm" },
        validation: readOnly(z.number().int().nonnegative()),
      },
      {
        key: "updated",
        kind: "number",
        display: { list: true, detail: true, width: "sm" },
        validation: readOnly(z.number().int().nonnegative()),
      },
      {
        key: "skipped",
        kind: "number",
        display: { list: true, detail: true, width: "sm" },
        validation: readOnly(z.number().int().nonnegative()),
      },
      {
        key: "failureCode",
        kind: "text",
        nullable: true,
        display: { detail: true },
        validation: readOnly(z.string().nullable()),
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        display: { detail: true },
        validation: readOnly(z.string().nullable()),
      },
      {
        key: "coordinatorModel",
        kind: "text",
        display: { detail: true },
        validation: readOnly(z.string()),
      },
      {
        key: "skillRevision",
        kind: "text",
        display: { detail: true },
        validation: readOnly(z.string()),
      },
      {
        key: "runtimeRevision",
        kind: "text",
        display: { detail: true },
        validation: readOnly(z.string()),
      },
      {
        key: "decisionRevision",
        kind: "number",
        display: { detail: true },
        validation: readOnly(z.number().int()),
      },
      {
        key: "dispatchAttempts",
        kind: "number",
        display: { detail: true },
        validation: readOnly(z.number().int().nonnegative()),
      },
      {
        key: "dispatchError",
        kind: "text",
        nullable: true,
        display: { detail: true },
        validation: readOnly(z.string().nullable()),
      },
      {
        key: "coordinatorStartedAt",
        kind: "timestamp",
        nullable: true,
        display: { detail: true, format: "timestamp" },
        validation: readOnly(z.date().nullable()),
      },
      {
        key: "auditedAt",
        kind: "timestamp",
        nullable: true,
        display: { detail: true, format: "timestamp" },
        validation: readOnly(z.date().nullable()),
      },
      {
        key: "predecessorRunId",
        kind: "identifier",
        label: "Predecessor",
        nullable: true,
        reference: { entity: "importRun" },
        display: { detail: true },
        validation: readOnly(importRunShortcode.nullable()),
      },
      {
        key: "vendorAccountLabel",
        kind: "text",
        nullable: true,
        validation: readOnly(z.string().nullable()),
      },
      {
        key: "vendorName",
        kind: "text",
        nullable: true,
        validation: readOnly(z.string().nullable()),
      },
      {
        key: "ledgerPartyName",
        kind: "text",
        validation: readOnly(z.string()),
      },
      {
        key: "id",
        kind: "identifier",
        validation: readOnly(importRunShortcode),
      },
      {
        key: "createdAt",
        kind: "timestamp",
        display: { detail: true },
        validation: readOnly(z.date()),
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        display: { detail: true },
        validation: readOnly(z.date()),
      },
      { key: "shortcode", kind: "text", readKey: null },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
    ],
    // The actor snapshot, dispatch fencing and history walk columns stay
    // hand-written on the table: they reference the auth user table, the run
    // itself, or are operational state no surface presents.
    storage: [
      {
        key: "id",
        default: "generated",
        specialized: "primary-key:ImportRunId",
      },
      { key: "shortcode", specialized: "shortcode" },
      { key: "ledgerPartyId", reference: "ledgerParty" },
      "actorName",
      { key: "vendorAccountId", reference: "vendorAccount" },
      { key: "vendorId", reference: "vendor" },
      {
        key: "purpose",
        default: "literal",
        defaultValue: "account_sync",
        specialized: "enum:purpose",
      },
      { key: "trigger", specialized: "enum:trigger" },
      {
        key: "status",
        default: "literal",
        defaultValue: "running",
        specialized: "enum:status",
      },
      {
        key: "coordinatorModel",
        default: "literal",
        defaultValue: "gpt-5.6-terra",
      },
      {
        key: "skillRevision",
        default: "literal",
        defaultValue: "purchase-import@1",
      },
      { key: "runtimeRevision", default: "literal", defaultValue: "flue@1" },
      { key: "decisionRevision", default: "literal", defaultValue: 1 },
      { key: "startedAt", default: "now" },
      "endedAt",
      { key: "ordersSeen", default: "literal", defaultValue: 0 },
      { key: "imported", default: "literal", defaultValue: 0 },
      { key: "updated", default: "literal", defaultValue: 0 },
      { key: "skipped", default: "literal", defaultValue: 0 },
      "auditedAt",
      "failureCode",
      "notes",
      { key: "dispatchAttempts", default: "literal", defaultValue: 0 },
      "dispatchError",
      "coordinatorStartedAt",
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [],
    update: [],
    output: [
      "id",
      "displayName",
      "status",
      "purpose",
      "trigger",
      "vendorAccountId",
      "vendorId",
      "ledgerPartyId",
      "actorName",
      "startedAt",
      "endedAt",
      "ordersSeen",
      "imported",
      "updated",
      "skipped",
      "failureCode",
      "notes",
      "coordinatorModel",
      "skillRevision",
      "runtimeRevision",
      "decisionRevision",
      "dispatchAttempts",
      "dispatchError",
      "coordinatorStartedAt",
      "auditedAt",
      "predecessorRunId",
      "vendorAccountLabel",
      "vendorName",
      "ledgerPartyName",
      "createdAt",
      "updatedAt",
    ],
    bulk: [],
    audit: [],
    sort: {
      fields: [
        "startedAt",
        "endedAt",
        "status",
        "purpose",
        "ordersSeen",
        "imported",
      ],
      default: "startedAt",
    },
  },
  fields: {
    create: null,
    update: null,
    output: {
      module: "@cubby/schemas/import-run",
      export: "importRunOut",
    },
  },
  filters: {
    schema: {
      module: "@cubby/schemas/import-run",
      export: "importRunFilterFields",
    },
    descriptors: [
      {
        columnId: "status",
        kind: "multiselect",
        placeholder: "Filter by status...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        options: [
          { value: "running", label: "Running", color: "var(--info)" },
          {
            value: "paused_auth",
            label: "Sign-in needed",
            color: "var(--warning)",
          },
          {
            value: "paused_offline",
            label: "Mac offline",
            color: "var(--warning)",
          },
          {
            value: "paused_approval",
            label: "Awaiting approval",
            color: "var(--warning)",
          },
          {
            value: "needs_review",
            label: "Needs review",
            color: "var(--warning)",
          },
          { value: "completed", label: "Completed", color: "var(--positive)" },
          { value: "failed", label: "Failed", color: "var(--destructive)" },
          {
            value: "dispatch_failed",
            label: "Dispatch failed",
            color: "var(--destructive)",
          },
        ],
      },
      {
        columnId: "purpose",
        kind: "multiselect",
        placeholder: "Filter by purpose...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        options: [
          { value: "account_sync", label: "Account sync" },
          { value: "purchase_validation", label: "Purchase validation" },
          { value: "product_enrichment", label: "Product enrichment" },
          { value: "photo_inventory", label: "Photo inventory" },
        ],
      },
      {
        columnId: "vendorAccountId",
        kind: "idMulti",
        placeholder: "Filter by vendor account...",
        brandRef: { entity: "vendorAccount" },
        urlOnly: true,
      },
      {
        columnId: "vendorId",
        kind: "idMulti",
        placeholder: "Filter by vendor...",
        brandRef: { entity: "vendor" },
        urlOnly: true,
      },
      {
        columnId: "ledgerPartyId",
        kind: "idMulti",
        placeholder: "Filter by member...",
        brandRef: { entity: "ledgerParty" },
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "vendor-account",
      label: "Vendor account",
      target: "vendorAccount",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImportRun.vendorAccountId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImportRun.vendorAccountId", direction: "incoming" }],
      },
    },
    {
      key: "vendor",
      label: "Vendor",
      target: "vendor",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImportRun.vendorId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImportRun.vendorId", direction: "incoming" }],
      },
    },
    {
      key: "ledger-party",
      label: "Member",
      target: "ledgerParty",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImportRun.ledgerPartyId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImportRun.ledgerPartyId", direction: "incoming" }],
      },
    },
    {
      key: "predecessor",
      label: "Predecessor",
      target: "importRun",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImportRun.predecessorRunId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImportRun.predecessorRunId", direction: "incoming" }],
      },
    },
    {
      key: "purchases",
      label: "Purchases",
      target: "purchase",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Purchase.importRunId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "Purchase.importRunId", direction: "outgoing" }],
      },
    },
  ],
  search: { enabled: false },
  capabilities: {
    auditable: false,
    images: { storage: false },
    countable: true,
    softDelete: false,
    delete: null,
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: null, merge: null },
    mcp: ["get", "list"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/import-run.entity-adapter",
        export: "importRunEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: { projection: null, semanticText: null, dependentRefresh: null },
    },
  },
});
