import { z } from "zod";

import {
  imageSightingCamera,
  imageSightingLocation,
  imageSightingMatchKind,
  imageSightingSourceType,
} from "../image-sighting-fields.js";
import {
  deviceShortcode,
  imageShortcode,
  imageSightingShortcode,
  ledgerPartyShortcode,
} from "../identifier-fields.js";
import { defineEntity } from "./definition.js";

export default defineEntity({
  key: "imageSighting",
  names: { singular: "Image Sighting", plural: "Image Sightings" },
  route: {
    basePath: "image-sightings",
    list: true,
    detail: true,
  },
  table: "ImageSighting",
  identifiers: { brand: "ImageSightingId", shortcode: "IMS-" },
  presentation: {
    titleField: "displayName",
    domain: null,
    description:
      "One report of a stored Image appearing in a member's photo library or cloud asset.",
    emptyState: {
      title: "No sightings yet",
      description:
        "A sighting is recorded automatically when a photo import or library scan reports an Image on a member's device.",
    },
    icons: { lucide: "Eye", sfSymbol: "eye", emoji: "👁️" },
    detail: {
      sections: [
        {
          kind: "fields",
          id: "overview",
          title: "Overview",
          placement: "supporting",
          fields: [
            "imageId",
            "ledgerPartyId",
            "deviceId",
            "assetKey",
            "sourceType",
            "mediaSubtypes",
            "originalFilename",
            "pixelWidth",
            "pixelHeight",
            "hasAdjustments",
            "capturedAt",
            "capturedAtOffsetMinutes",
            "addedAt",
            "location",
            "placeName",
            "camera",
            "matchKind",
            "hashDistance",
            "aspectGate",
            "observedAt",
            "createdAt",
            "updatedAt",
          ],
        },
      ],
    },
    list: { actions: ["delete"] },
  },
  model: {
    fields: [
      {
        key: "imageId",
        kind: "identifier",
        label: "Image",
        reference: { entity: "image" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: { detail: true },
        validation: {
          read: imageShortcode,
          create: imageShortcode,
          update: null,
        },
      },
      {
        key: "ledgerPartyId",
        kind: "identifier",
        label: "Library owner",
        reference: { entity: "ledgerParty" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true, columnId: "ledgerPartyName" },
        validation: {
          read: ledgerPartyShortcode,
          // Omittable on create: resolved from the acting login's linked
          // member party (`repo/member-login.ts`) when absent.
          create: ledgerPartyShortcode.optional(),
          update: null,
        },
      },
      {
        key: "deviceId",
        kind: "identifier",
        label: "Reporter",
        reference: { entity: "device" },
        control: { kind: "specialized", renderer: "entity-select" },
        display: { list: true, detail: true, columnId: "deviceName" },
        validation: {
          read: deviceShortcode,
          create: deviceShortcode,
          update: null,
        },
      },
      {
        key: "assetKey",
        kind: "text",
        label: "Asset key",
        display: { detail: true },
        validation: {
          read: z.string(),
          create: z.string().trim().min(1),
          update: null,
        },
      },
      {
        key: "cloudIdentifier",
        kind: "text",
        nullable: true,
        readKey: null,
        validation: {
          read: null,
          create: z.string().trim().min(1).nullable().optional(),
          update: null,
        },
      },
      {
        key: "localIdentifier",
        kind: "text",
        nullable: true,
        readKey: null,
        validation: {
          read: null,
          create: z.string().trim().min(1).nullable().optional(),
          update: null,
        },
      },
      {
        key: "sourceType",
        kind: "enum",
        label: "Source type",
        control: {
          kind: "select",
          options: [
            { value: "userLibrary", label: "User library" },
            { value: "cloudShared", label: "Cloud shared" },
            { value: "iTunesSynced", label: "iTunes synced" },
          ],
        },
        display: { list: true, detail: true, width: "sm" },
        validation: {
          read: imageSightingSourceType,
          create: imageSightingSourceType,
          update: null,
        },
      },
      {
        key: "mediaSubtypes",
        kind: "text-array",
        label: "Media subtypes",
        display: { detail: true },
        validation: {
          read: z.array(z.string()),
          create: z.array(z.string()).default([]),
          update: null,
        },
      },
      {
        key: "originalFilename",
        kind: "text",
        nullable: true,
        label: "Original filename",
        display: { detail: true },
        validation: {
          read: z.string().nullable(),
          create: z.string().trim().min(1).nullable().optional(),
          update: null,
        },
      },
      {
        key: "pixelWidth",
        kind: "number",
        nullable: true,
        label: "Pixel width",
        display: { detail: true },
        validation: {
          read: z.number().int().positive().nullable(),
          create: z.number().int().positive().nullable().optional(),
          update: null,
        },
      },
      {
        key: "pixelHeight",
        kind: "number",
        nullable: true,
        label: "Pixel height",
        display: { detail: true },
        validation: {
          read: z.number().int().positive().nullable(),
          create: z.number().int().positive().nullable().optional(),
          update: null,
        },
      },
      {
        key: "hasAdjustments",
        kind: "boolean",
        label: "Has adjustments",
        control: { kind: "checkbox" },
        display: { detail: true },
        validation: {
          read: z.boolean(),
          create: z.boolean().default(false),
          update: null,
        },
      },
      {
        key: "capturedAt",
        kind: "timestamp",
        nullable: true,
        label: "Captured at",
        display: { list: true, detail: true, format: "timestamp" },
        validation: {
          read: z.date().nullable(),
          create: z.coerce.date().nullable().optional(),
          update: z.coerce.date().nullable().optional(),
        },
      },
      {
        key: "capturedAtOffsetMinutes",
        kind: "number",
        nullable: true,
        label: "Captured at offset (minutes)",
        display: { detail: true },
        validation: {
          read: z.number().int().nullable(),
          create: z.number().int().nullable().optional(),
          update: null,
        },
      },
      {
        key: "addedAt",
        kind: "timestamp",
        nullable: true,
        label: "Added at",
        display: { detail: true, format: "timestamp" },
        validation: {
          read: z.date().nullable(),
          create: z.coerce.date().nullable().optional(),
          update: null,
        },
      },
      {
        key: "location",
        kind: "json",
        nullable: true,
        label: "Location",
        display: {
          detail: true,
          renderer: { detail: "image-sighting-location" },
        },
        validation: {
          read: imageSightingLocation.nullable(),
          create: imageSightingLocation.nullable().optional(),
          update: null,
        },
      },
      {
        key: "placeName",
        kind: "text",
        nullable: true,
        label: "Place name",
        display: { detail: true },
        validation: {
          read: z.string().nullable(),
          create: z.string().trim().min(1).nullable().optional(),
          update: z.string().trim().min(1).nullable().optional(),
        },
      },
      {
        key: "camera",
        kind: "json",
        nullable: true,
        label: "Camera",
        display: {
          detail: true,
          renderer: { detail: "image-sighting-camera" },
        },
        validation: {
          read: imageSightingCamera.nullable(),
          create: imageSightingCamera.nullable().optional(),
          update: null,
        },
      },
      {
        key: "matchKind",
        kind: "enum",
        label: "Match kind",
        control: {
          kind: "select",
          options: [
            { value: "import", label: "Import" },
            { value: "libraryMatch", label: "Library match" },
          ],
        },
        display: { list: true, detail: true, width: "sm" },
        validation: {
          read: imageSightingMatchKind,
          create: imageSightingMatchKind,
          update: null,
        },
      },
      {
        key: "hashDistance",
        kind: "number",
        nullable: true,
        label: "Hash distance",
        display: { detail: true },
        validation: {
          read: z.number().int().nonnegative().nullable(),
          create: z.number().int().nonnegative().nullable().optional(),
          update: null,
        },
      },
      {
        key: "aspectGate",
        kind: "boolean",
        nullable: true,
        label: "Aspect gate",
        display: { detail: true },
        validation: {
          read: z.boolean().nullable(),
          create: z.boolean().nullable().optional(),
          update: null,
        },
      },
      {
        key: "observedAt",
        kind: "timestamp",
        label: "Observed at",
        display: { detail: true, format: "timestamp" },
        validation: {
          read: z.date(),
          create: z.coerce.date(),
          update: null,
        },
      },
      {
        // "<owner name> · <device name> · <capturedAt or observedAt date>" —
        // the non-null title; no single stored column can serve alone.
        key: "displayName",
        kind: "text",
        validation: { read: z.string(), create: null, update: null },
      },
      {
        key: "id",
        kind: "identifier",
        validation: {
          read: imageSightingShortcode,
          create: null,
          update: null,
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        display: { detail: true },
        validation: { read: z.date(), create: null, update: null },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        display: { detail: true },
        validation: { read: z.date(), create: null, update: null },
      },
      { key: "shortcode", kind: "text", readKey: null },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
    ],
    storage: [
      {
        key: "id",
        default: "generated",
        specialized: "primary-key:ImageSightingId",
      },
      { key: "shortcode", specialized: "shortcode" },
      { key: "imageId", reference: "image" },
      { key: "ledgerPartyId", reference: "ledgerParty" },
      { key: "deviceId", reference: "device" },
      "assetKey",
      "cloudIdentifier",
      "localIdentifier",
      { key: "sourceType", specialized: "enum:sourceType" },
      {
        key: "mediaSubtypes",
        default: "literal",
        defaultValue: "'{}'::text[]",
        specialized: "text-array",
      },
      "originalFilename",
      "pixelWidth",
      "pixelHeight",
      { key: "hasAdjustments", default: "literal", defaultValue: false },
      "capturedAt",
      "capturedAtOffsetMinutes",
      "addedAt",
      { key: "location", specialized: "json:location" },
      "placeName",
      { key: "camera", specialized: "json:camera" },
      { key: "matchKind", specialized: "enum:matchKind" },
      "hashDistance",
      "aspectGate",
      "observedAt",
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [
      "imageId",
      "ledgerPartyId",
      "deviceId",
      "assetKey",
      "cloudIdentifier",
      "localIdentifier",
      "sourceType",
      "mediaSubtypes",
      "originalFilename",
      "pixelWidth",
      "pixelHeight",
      "hasAdjustments",
      "capturedAt",
      "capturedAtOffsetMinutes",
      "addedAt",
      "location",
      "placeName",
      "camera",
      "matchKind",
      "hashDistance",
      "aspectGate",
      "observedAt",
    ],
    // A repeat report re-upserts the observation columns rather than erroring
    // (`repo/image-sighting.ts`'s `create`), so only the two fields a member
    // can genuinely correct by hand are updatable through the generic path.
    update: ["placeName", "capturedAt"],
    bulk: [],
    audit: ["placeName", "capturedAt"],
    sort: {
      fields: ["observedAt", "capturedAt", "createdAt", "updatedAt"],
      default: "observedAt",
      direction: "desc",
    },
    intents: {
      fields: {
        full: [
          "imageId",
          "ledgerPartyId",
          "deviceId",
          "assetKey",
          "cloudIdentifier",
          "localIdentifier",
          "sourceType",
          "mediaSubtypes",
          "originalFilename",
          "pixelWidth",
          "pixelHeight",
          "hasAdjustments",
          "capturedAt",
          "capturedAtOffsetMinutes",
          "addedAt",
          "location",
          "placeName",
          "camera",
          "matchKind",
          "hashDistance",
          "aspectGate",
          "observedAt",
        ],
      },
      create: ["full"],
      update: ["full"],
    },
    output: [
      "id",
      "imageId",
      "ledgerPartyId",
      "deviceId",
      "assetKey",
      "sourceType",
      "mediaSubtypes",
      "originalFilename",
      "pixelWidth",
      "pixelHeight",
      "hasAdjustments",
      "capturedAt",
      "capturedAtOffsetMinutes",
      "addedAt",
      "location",
      "placeName",
      "camera",
      "matchKind",
      "hashDistance",
      "aspectGate",
      "observedAt",
      "displayName",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/image-sighting",
      export: "imageSightingCreateInput",
    },
    update: {
      module: "@cubby/schemas/image-sighting",
      export: "imageSightingUpdateData",
    },
    output: {
      module: "@cubby/schemas/image-sighting",
      export: "imageSightingOut",
    },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/image-sighting",
      export: "imageSightingFilterFields",
    },
    descriptors: [
      {
        columnId: "imageId",
        kind: "idMulti",
        placeholder: "Filter by image...",
        brandRef: { entity: "image" },
        urlOnly: true,
      },
      {
        columnId: "ledgerPartyId",
        kind: "idMulti",
        placeholder: "Filter by owner...",
        brandRef: { entity: "ledgerParty" },
        urlOnly: true,
      },
      {
        columnId: "deviceId",
        kind: "idMulti",
        placeholder: "Filter by reporter...",
        brandRef: { entity: "device" },
        urlOnly: true,
      },
      {
        columnId: "sourceType",
        kind: "multiselect",
        placeholder: "Filter by source type...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        options: [
          { value: "userLibrary", label: "User library" },
          { value: "cloudShared", label: "Cloud shared" },
          { value: "iTunesSynced", label: "iTunes synced" },
        ],
      },
      {
        columnId: "matchKind",
        kind: "multiselect",
        placeholder: "Filter by match kind...",
        deriveSchema: true,
        stored: true,
        schemaFromRead: true,
        options: [
          { value: "import", label: "Import" },
          { value: "libraryMatch", label: "Library match" },
        ],
      },
    ],
  },
  relations: [
    {
      key: "image",
      label: "Image",
      target: "image",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImageSighting.imageId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImageSighting.imageId", direction: "incoming" }],
      },
    },
    {
      key: "owner",
      label: "Owner",
      target: "ledgerParty",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImageSighting.ledgerPartyId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImageSighting.ledgerPartyId", direction: "incoming" }],
      },
    },
    {
      key: "reporter",
      label: "Reporter",
      target: "device",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "ImageSighting.deviceId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "ImageSighting.deviceId", direction: "incoming" }],
      },
    },
  ],
  search: { enabled: false },
  capabilities: {
    auditable: true,
    images: { storage: false },
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/image-sighting.entity-adapter",
        export: "imageSightingEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: { projection: null, semanticText: null, dependentRefresh: null },
    },
  },
});
