/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as PantryViewRouteImport } from './routes/pantry-view'
import { Route as LabelsRouteImport } from './routes/labels'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ShortcodeRouteImport } from './routes/$shortcode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsdaIndexRouteImport } from './routes/usda.index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients.index'
import { Route as ImagesIndexRouteImport } from './routes/images.index'
import { Route as UsdaIdRouteImport } from './routes/usda.$id'
import { Route as RecipesNewRouteImport } from './routes/recipes.new'
import { Route as RecipesCompareRouteImport } from './routes/recipes.compare'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as LocationsValidateRouteImport } from './routes/locations.validate'
import { Route as LocationsNewRouteImport } from './routes/locations.new'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as InventoryQuickCaptureRouteImport } from './routes/inventory.quick-capture'
import { Route as InventoryNewRouteImport } from './routes/inventory.new'
import { Route as InventoryBulkMoveRouteImport } from './routes/inventory.bulk-move'
import { Route as InventoryBulkEditRouteImport } from './routes/inventory.bulk-edit'
import { Route as InventoryIdRouteImport } from './routes/inventory.$id'
import { Route as IngredientsNewRouteImport } from './routes/ingredients.new'
import { Route as IngredientsIdRouteImport } from './routes/ingredients.$id'
import { Route as ImagesIdRouteImport } from './routes/images.$id'
import { Route as AuthAuthViewRouteImport } from './routes/auth.$authView'
import { Route as ApiPanelRouteImport } from './routes/api/panel'
import { Route as AccountAccountViewRouteImport } from './routes/account.$accountView'
import { Route as UsdaUpcCodeRouteImport } from './routes/usda.upc.$code'
import { Route as UsdaNdbCodeRouteImport } from './routes/usda.ndb.$code'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiDebugTimingRouteImport } from './routes/api/debug/timing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryViewRoute = PantryViewRouteImport.update({
  id: '/pantry-view',
  path: '/pantry-view',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsRoute = LabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcodeRoute = ShortcodeRouteImport.update({
  id: '/$shortcode',
  path: '/$shortcode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsdaIndexRoute = UsdaIndexRouteImport.update({
  id: '/usda/',
  path: '/usda/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsdaIdRoute = UsdaIdRouteImport.update({
  id: '/usda/$id',
  path: '/usda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCompareRoute = RecipesCompareRouteImport.update({
  id: '/recipes/compare',
  path: '/recipes/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsValidateRoute = LocationsValidateRouteImport.update({
  id: '/locations/validate',
  path: '/locations/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewRoute = LocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryQuickCaptureRoute = InventoryQuickCaptureRouteImport.update({
  id: '/inventory/quick-capture',
  path: '/inventory/quick-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBulkMoveRoute = InventoryBulkMoveRouteImport.update({
  id: '/inventory/bulk-move',
  path: '/inventory/bulk-move',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBulkEditRoute = InventoryBulkEditRouteImport.update({
  id: '/inventory/bulk-edit',
  path: '/inventory/bulk-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdRoute = InventoryIdRouteImport.update({
  id: '/inventory/$id',
  path: '/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsNewRoute = IngredientsNewRouteImport.update({
  id: '/ingredients/new',
  path: '/ingredients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIdRoute = IngredientsIdRouteImport.update({
  id: '/ingredients/$id',
  path: '/ingredients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIdRoute = ImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelRoute = ApiPanelRouteImport.update({
  id: '/api/panel',
  path: '/api/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const UsdaUpcCodeRoute = UsdaUpcCodeRouteImport.update({
  id: '/usda/upc/$code',
  path: '/usda/upc/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UsdaNdbCodeRoute = UsdaNdbCodeRouteImport.update({
  id: '/usda/ndb/$code',
  path: '/usda/ndb/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTimingRoute = ApiDebugTimingRouteImport.update({
  id: '/api/debug/timing',
  path: '/api/debug/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortcode': typeof ShortcodeRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/labels': typeof LabelsRoute
  '/pantry-view': typeof PantryViewRoute
  '/problems': typeof ProblemsRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/api/panel': typeof ApiPanelRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/images/$id': typeof ImagesIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/inventory/bulk-edit': typeof InventoryBulkEditRoute
  '/inventory/bulk-move': typeof InventoryBulkMoveRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/quick-capture': typeof InventoryQuickCaptureRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/locations/validate': typeof LocationsValidateRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/compare': typeof RecipesCompareRoute
  '/recipes/new': typeof RecipesNewRoute
  '/usda/$id': typeof UsdaIdRoute
  '/images/': typeof ImagesIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/usda/': typeof UsdaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/usda/ndb/$code': typeof UsdaNdbCodeRoute
  '/usda/upc/$code': typeof UsdaUpcCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortcode': typeof ShortcodeRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/labels': typeof LabelsRoute
  '/pantry-view': typeof PantryViewRoute
  '/problems': typeof ProblemsRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/api/panel': typeof ApiPanelRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/images/$id': typeof ImagesIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/inventory/bulk-edit': typeof InventoryBulkEditRoute
  '/inventory/bulk-move': typeof InventoryBulkMoveRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/quick-capture': typeof InventoryQuickCaptureRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/locations/validate': typeof LocationsValidateRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/compare': typeof RecipesCompareRoute
  '/recipes/new': typeof RecipesNewRoute
  '/usda/$id': typeof UsdaIdRoute
  '/images': typeof ImagesIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/search': typeof SearchIndexRoute
  '/usda': typeof UsdaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/usda/ndb/$code': typeof UsdaNdbCodeRoute
  '/usda/upc/$code': typeof UsdaUpcCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortcode': typeof ShortcodeRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/insights': typeof InsightsRoute
  '/labels': typeof LabelsRoute
  '/pantry-view': typeof PantryViewRoute
  '/problems': typeof ProblemsRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/api/panel': typeof ApiPanelRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/images/$id': typeof ImagesIdRoute
  '/ingredients/$id': typeof IngredientsIdRoute
  '/ingredients/new': typeof IngredientsNewRoute
  '/inventory/$id': typeof InventoryIdRoute
  '/inventory/bulk-edit': typeof InventoryBulkEditRoute
  '/inventory/bulk-move': typeof InventoryBulkMoveRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/quick-capture': typeof InventoryQuickCaptureRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/locations/validate': typeof LocationsValidateRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/new': typeof ProductsNewRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/compare': typeof RecipesCompareRoute
  '/recipes/new': typeof RecipesNewRoute
  '/usda/$id': typeof UsdaIdRoute
  '/images/': typeof ImagesIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/usda/': typeof UsdaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/usda/ndb/$code': typeof UsdaNdbCodeRoute
  '/usda/upc/$code': typeof UsdaUpcCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$shortcode'
    | '/activity'
    | '/dashboard'
    | '/docs'
    | '/insights'
    | '/labels'
    | '/pantry-view'
    | '/problems'
    | '/account/$accountView'
    | '/api/panel'
    | '/auth/$authView'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/quick-capture'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/validate'
    | '/products/$id'
    | '/products/new'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/new'
    | '/usda/$id'
    | '/images/'
    | '/ingredients/'
    | '/inventory/'
    | '/locations/'
    | '/products/'
    | '/recipes/'
    | '/search/'
    | '/usda/'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$shortcode'
    | '/activity'
    | '/dashboard'
    | '/docs'
    | '/insights'
    | '/labels'
    | '/pantry-view'
    | '/problems'
    | '/account/$accountView'
    | '/api/panel'
    | '/auth/$authView'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/quick-capture'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/validate'
    | '/products/$id'
    | '/products/new'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/new'
    | '/usda/$id'
    | '/images'
    | '/ingredients'
    | '/inventory'
    | '/locations'
    | '/products'
    | '/recipes'
    | '/search'
    | '/usda'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  id:
    | '__root__'
    | '/'
    | '/$shortcode'
    | '/activity'
    | '/dashboard'
    | '/docs'
    | '/insights'
    | '/labels'
    | '/pantry-view'
    | '/problems'
    | '/account/$accountView'
    | '/api/panel'
    | '/auth/$authView'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/quick-capture'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/validate'
    | '/products/$id'
    | '/products/new'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/new'
    | '/usda/$id'
    | '/images/'
    | '/ingredients/'
    | '/inventory/'
    | '/locations/'
    | '/products/'
    | '/recipes/'
    | '/search/'
    | '/usda/'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortcodeRoute: typeof ShortcodeRoute
  ActivityRoute: typeof ActivityRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  InsightsRoute: typeof InsightsRoute
  LabelsRoute: typeof LabelsRoute
  PantryViewRoute: typeof PantryViewRoute
  ProblemsRoute: typeof ProblemsRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  ApiPanelRoute: typeof ApiPanelRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  ImagesIdRoute: typeof ImagesIdRoute
  IngredientsIdRoute: typeof IngredientsIdRoute
  IngredientsNewRoute: typeof IngredientsNewRoute
  InventoryIdRoute: typeof InventoryIdRoute
  InventoryBulkEditRoute: typeof InventoryBulkEditRoute
  InventoryBulkMoveRoute: typeof InventoryBulkMoveRoute
  InventoryNewRoute: typeof InventoryNewRoute
  InventoryQuickCaptureRoute: typeof InventoryQuickCaptureRoute
  LocationsIdRoute: typeof LocationsIdRoute
  LocationsNewRoute: typeof LocationsNewRoute
  LocationsValidateRoute: typeof LocationsValidateRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesCompareRoute: typeof RecipesCompareRoute
  RecipesNewRoute: typeof RecipesNewRoute
  UsdaIdRoute: typeof UsdaIdRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  UsdaIndexRoute: typeof UsdaIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDebugTimingRoute: typeof ApiDebugTimingRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  UsdaNdbCodeRoute: typeof UsdaNdbCodeRoute
  UsdaUpcCodeRoute: typeof UsdaUpcCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry-view': {
      id: '/pantry-view'
      path: '/pantry-view'
      fullPath: '/pantry-view'
      preLoaderRoute: typeof PantryViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels': {
      id: '/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shortcode': {
      id: '/$shortcode'
      path: '/$shortcode'
      fullPath: '/$shortcode'
      preLoaderRoute: typeof ShortcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usda/': {
      id: '/usda/'
      path: '/usda'
      fullPath: '/usda/'
      preLoaderRoute: typeof UsdaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usda/$id': {
      id: '/usda/$id'
      path: '/usda/$id'
      fullPath: '/usda/$id'
      preLoaderRoute: typeof UsdaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/compare': {
      id: '/recipes/compare'
      path: '/recipes/compare'
      fullPath: '/recipes/compare'
      preLoaderRoute: typeof RecipesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new': {
      id: '/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/validate': {
      id: '/locations/validate'
      path: '/locations/validate'
      fullPath: '/locations/validate'
      preLoaderRoute: typeof LocationsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/new': {
      id: '/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof LocationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/quick-capture': {
      id: '/inventory/quick-capture'
      path: '/inventory/quick-capture'
      fullPath: '/inventory/quick-capture'
      preLoaderRoute: typeof InventoryQuickCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/bulk-move': {
      id: '/inventory/bulk-move'
      path: '/inventory/bulk-move'
      fullPath: '/inventory/bulk-move'
      preLoaderRoute: typeof InventoryBulkMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/bulk-edit': {
      id: '/inventory/bulk-edit'
      path: '/inventory/bulk-edit'
      fullPath: '/inventory/bulk-edit'
      preLoaderRoute: typeof InventoryBulkEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id': {
      id: '/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof InventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/new': {
      id: '/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof IngredientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$id': {
      id: '/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof IngredientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$id': {
      id: '/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof ImagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel': {
      id: '/api/panel'
      path: '/api/panel'
      fullPath: '/api/panel'
      preLoaderRoute: typeof ApiPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usda/upc/$code': {
      id: '/usda/upc/$code'
      path: '/usda/upc/$code'
      fullPath: '/usda/upc/$code'
      preLoaderRoute: typeof UsdaUpcCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usda/ndb/$code': {
      id: '/usda/ndb/$code'
      path: '/usda/ndb/$code'
      fullPath: '/usda/ndb/$code'
      preLoaderRoute: typeof UsdaNdbCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/timing': {
      id: '/api/debug/timing'
      path: '/api/debug/timing'
      fullPath: '/api/debug/timing'
      preLoaderRoute: typeof ApiDebugTimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortcodeRoute: ShortcodeRoute,
  ActivityRoute: ActivityRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  InsightsRoute: InsightsRoute,
  LabelsRoute: LabelsRoute,
  PantryViewRoute: PantryViewRoute,
  ProblemsRoute: ProblemsRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  ApiPanelRoute: ApiPanelRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  ImagesIdRoute: ImagesIdRoute,
  IngredientsIdRoute: IngredientsIdRoute,
  IngredientsNewRoute: IngredientsNewRoute,
  InventoryIdRoute: InventoryIdRoute,
  InventoryBulkEditRoute: InventoryBulkEditRoute,
  InventoryBulkMoveRoute: InventoryBulkMoveRoute,
  InventoryNewRoute: InventoryNewRoute,
  InventoryQuickCaptureRoute: InventoryQuickCaptureRoute,
  LocationsIdRoute: LocationsIdRoute,
  LocationsNewRoute: LocationsNewRoute,
  LocationsValidateRoute: LocationsValidateRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  RecipesIdRoute: RecipesIdRoute,
  RecipesCompareRoute: RecipesCompareRoute,
  RecipesNewRoute: RecipesNewRoute,
  UsdaIdRoute: UsdaIdRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  UsdaIndexRoute: UsdaIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDebugTimingRoute: ApiDebugTimingRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  UsdaNdbCodeRoute: UsdaNdbCodeRoute,
  UsdaUpcCodeRoute: UsdaUpcCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
