/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth.$authView'
import { Route as ApiPanelRouteImport } from './routes/api/panel'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedPantryViewRouteImport } from './routes/_authenticated/pantry-view'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedShortcodeRouteImport } from './routes/_authenticated/$shortcode'
import { Route as AuthenticatedUsdaIndexRouteImport } from './routes/_authenticated/usda.index'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search.index'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedIngredientsIndexRouteImport } from './routes/_authenticated/ingredients.index'
import { Route as AuthenticatedImagesIndexRouteImport } from './routes/_authenticated/images.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiDebugTimingRouteImport } from './routes/api/debug/timing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedUsdaIdRouteImport } from './routes/_authenticated/usda.$id'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes.new'
import { Route as AuthenticatedRecipesCompareRouteImport } from './routes/_authenticated/recipes.compare'
import { Route as AuthenticatedRecipesIdRouteImport } from './routes/_authenticated/recipes.$id'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedLocationsValidateRouteImport } from './routes/_authenticated/locations.validate'
import { Route as AuthenticatedLocationsNewRouteImport } from './routes/_authenticated/locations.new'
import { Route as AuthenticatedLocationsIdRouteImport } from './routes/_authenticated/locations.$id'
import { Route as AuthenticatedInventoryQuickCaptureRouteImport } from './routes/_authenticated/inventory.quick-capture'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory.new'
import { Route as AuthenticatedInventoryBulkMoveRouteImport } from './routes/_authenticated/inventory.bulk-move'
import { Route as AuthenticatedInventoryBulkEditRouteImport } from './routes/_authenticated/inventory.bulk-edit'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory.$id'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients.new'
import { Route as AuthenticatedIngredientsIdRouteImport } from './routes/_authenticated/ingredients.$id'
import { Route as AuthenticatedImagesIdRouteImport } from './routes/_authenticated/images.$id'
import { Route as AuthenticatedAccountAccountViewRouteImport } from './routes/_authenticated/account.$accountView'
import { Route as AuthenticatedUsdaUpcCodeRouteImport } from './routes/_authenticated/usda.upc.$code'
import { Route as AuthenticatedUsdaNdbCodeRouteImport } from './routes/_authenticated/usda.ndb.$code'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelRoute = ApiPanelRouteImport.update({
  id: '/api/panel',
  path: '/api/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPantryViewRoute = AuthenticatedPantryViewRouteImport.update({
  id: '/pantry-view',
  path: '/pantry-view',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShortcodeRoute = AuthenticatedShortcodeRouteImport.update({
  id: '/$shortcode',
  path: '/$shortcode',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsdaIndexRoute = AuthenticatedUsdaIndexRouteImport.update({
  id: '/usda/',
  path: '/usda/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIndexRoute =
  AuthenticatedIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIndexRoute =
  AuthenticatedImagesIndexRouteImport.update({
    id: '/images/',
    path: '/images/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTimingRoute = ApiDebugTimingRouteImport.update({
  id: '/api/debug/timing',
  path: '/api/debug/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsdaIdRoute = AuthenticatedUsdaIdRouteImport.update({
  id: '/usda/$id',
  path: '/usda/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesCompareRoute =
  AuthenticatedRecipesCompareRouteImport.update({
    id: '/recipes/compare',
    path: '/recipes/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesIdRoute = AuthenticatedRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocationsValidateRoute =
  AuthenticatedLocationsValidateRouteImport.update({
    id: '/locations/validate',
    path: '/locations/validate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsNewRoute =
  AuthenticatedLocationsNewRouteImport.update({
    id: '/locations/new',
    path: '/locations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIdRoute =
  AuthenticatedLocationsIdRouteImport.update({
    id: '/locations/$id',
    path: '/locations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryQuickCaptureRoute =
  AuthenticatedInventoryQuickCaptureRouteImport.update({
    id: '/inventory/quick-capture',
    path: '/inventory/quick-capture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryBulkMoveRoute =
  AuthenticatedInventoryBulkMoveRouteImport.update({
    id: '/inventory/bulk-move',
    path: '/inventory/bulk-move',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryBulkEditRoute =
  AuthenticatedInventoryBulkEditRouteImport.update({
    id: '/inventory/bulk-edit',
    path: '/inventory/bulk-edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/ingredients/new',
    path: '/ingredients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIdRoute =
  AuthenticatedIngredientsIdRouteImport.update({
    id: '/ingredients/$id',
    path: '/ingredients/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIdRoute = AuthenticatedImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountAccountViewRoute =
  AuthenticatedAccountAccountViewRouteImport.update({
    id: '/account/$accountView',
    path: '/account/$accountView',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsdaUpcCodeRoute =
  AuthenticatedUsdaUpcCodeRouteImport.update({
    id: '/usda/upc/$code',
    path: '/usda/upc/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsdaNdbCodeRoute =
  AuthenticatedUsdaNdbCodeRouteImport.update({
    id: '/usda/ndb/$code',
    path: '/usda/ndb/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/$shortcode': typeof AuthenticatedShortcodeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/pantry-view': typeof AuthenticatedPantryViewRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/panel': typeof ApiPanelRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/images/$id': typeof AuthenticatedImagesIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/bulk-edit': typeof AuthenticatedInventoryBulkEditRoute
  '/inventory/bulk-move': typeof AuthenticatedInventoryBulkMoveRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/inventory/quick-capture': typeof AuthenticatedInventoryQuickCaptureRoute
  '/locations/$id': typeof AuthenticatedLocationsIdRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/locations/validate': typeof AuthenticatedLocationsValidateRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/recipes/compare': typeof AuthenticatedRecipesCompareRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/usda/$id': typeof AuthenticatedUsdaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/images/': typeof AuthenticatedImagesIndexRoute
  '/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/usda/': typeof AuthenticatedUsdaIndexRoute
  '/usda/ndb/$code': typeof AuthenticatedUsdaNdbCodeRoute
  '/usda/upc/$code': typeof AuthenticatedUsdaUpcCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/$shortcode': typeof AuthenticatedShortcodeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/pantry-view': typeof AuthenticatedPantryViewRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/panel': typeof ApiPanelRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/images/$id': typeof AuthenticatedImagesIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/bulk-edit': typeof AuthenticatedInventoryBulkEditRoute
  '/inventory/bulk-move': typeof AuthenticatedInventoryBulkMoveRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/inventory/quick-capture': typeof AuthenticatedInventoryQuickCaptureRoute
  '/locations/$id': typeof AuthenticatedLocationsIdRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/locations/validate': typeof AuthenticatedLocationsValidateRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/recipes/compare': typeof AuthenticatedRecipesCompareRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/usda/$id': typeof AuthenticatedUsdaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/ingredients': typeof AuthenticatedIngredientsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/usda': typeof AuthenticatedUsdaIndexRoute
  '/usda/ndb/$code': typeof AuthenticatedUsdaNdbCodeRoute
  '/usda/upc/$code': typeof AuthenticatedUsdaUpcCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/docs': typeof DocsRoute
  '/_authenticated/$shortcode': typeof AuthenticatedShortcodeRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/pantry-view': typeof AuthenticatedPantryViewRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/panel': typeof ApiPanelRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/_authenticated/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/_authenticated/images/$id': typeof AuthenticatedImagesIdRoute
  '/_authenticated/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/_authenticated/inventory/bulk-edit': typeof AuthenticatedInventoryBulkEditRoute
  '/_authenticated/inventory/bulk-move': typeof AuthenticatedInventoryBulkMoveRoute
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/inventory/quick-capture': typeof AuthenticatedInventoryQuickCaptureRoute
  '/_authenticated/locations/$id': typeof AuthenticatedLocationsIdRoute
  '/_authenticated/locations/new': typeof AuthenticatedLocationsNewRoute
  '/_authenticated/locations/validate': typeof AuthenticatedLocationsValidateRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/_authenticated/recipes/compare': typeof AuthenticatedRecipesCompareRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/_authenticated/usda/$id': typeof AuthenticatedUsdaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/images/': typeof AuthenticatedImagesIndexRoute
  '/_authenticated/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/usda/': typeof AuthenticatedUsdaIndexRoute
  '/_authenticated/usda/ndb/$code': typeof AuthenticatedUsdaNdbCodeRoute
  '/_authenticated/usda/upc/$code': typeof AuthenticatedUsdaUpcCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/$shortcode'
    | '/activity'
    | '/ask'
    | '/capture'
    | '/dashboard'
    | '/insights'
    | '/labels'
    | '/pantry-view'
    | '/problems'
    | '/api/mcp'
    | '/api/panel'
    | '/auth/$authView'
    | '/account/$accountView'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/quick-capture'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/validate'
    | '/products/$id'
    | '/products/new'
    | '/projects/$id'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/new'
    | '/usda/$id'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/images/'
    | '/ingredients/'
    | '/inventory/'
    | '/locations/'
    | '/products/'
    | '/projects/'
    | '/recipes/'
    | '/search/'
    | '/usda/'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/$shortcode'
    | '/activity'
    | '/ask'
    | '/capture'
    | '/dashboard'
    | '/insights'
    | '/labels'
    | '/pantry-view'
    | '/problems'
    | '/api/mcp'
    | '/api/panel'
    | '/auth/$authView'
    | '/account/$accountView'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/new'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/quick-capture'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/validate'
    | '/products/$id'
    | '/products/new'
    | '/projects/$id'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/new'
    | '/usda/$id'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/images'
    | '/ingredients'
    | '/inventory'
    | '/locations'
    | '/products'
    | '/projects'
    | '/recipes'
    | '/search'
    | '/usda'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/docs'
    | '/_authenticated/$shortcode'
    | '/_authenticated/activity'
    | '/_authenticated/ask'
    | '/_authenticated/capture'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/labels'
    | '/_authenticated/pantry-view'
    | '/_authenticated/problems'
    | '/api/mcp'
    | '/api/panel'
    | '/auth/$authView'
    | '/_authenticated/account/$accountView'
    | '/_authenticated/images/$id'
    | '/_authenticated/ingredients/$id'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/inventory/$id'
    | '/_authenticated/inventory/bulk-edit'
    | '/_authenticated/inventory/bulk-move'
    | '/_authenticated/inventory/new'
    | '/_authenticated/inventory/quick-capture'
    | '/_authenticated/locations/$id'
    | '/_authenticated/locations/new'
    | '/_authenticated/locations/validate'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/projects/$id'
    | '/_authenticated/recipes/$id'
    | '/_authenticated/recipes/compare'
    | '/_authenticated/recipes/new'
    | '/_authenticated/usda/$id'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/_authenticated/images/'
    | '/_authenticated/ingredients/'
    | '/_authenticated/inventory/'
    | '/_authenticated/locations/'
    | '/_authenticated/products/'
    | '/_authenticated/projects/'
    | '/_authenticated/recipes/'
    | '/_authenticated/search/'
    | '/_authenticated/usda/'
    | '/_authenticated/usda/ndb/$code'
    | '/_authenticated/usda/upc/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DocsRoute: typeof DocsRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPanelRoute: typeof ApiPanelRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDebugTimingRoute: typeof ApiDebugTimingRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel': {
      id: '/api/panel'
      path: '/api/panel'
      fullPath: '/api/panel'
      preLoaderRoute: typeof ApiPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry-view': {
      id: '/_authenticated/pantry-view'
      path: '/pantry-view'
      fullPath: '/pantry-view'
      preLoaderRoute: typeof AuthenticatedPantryViewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$shortcode': {
      id: '/_authenticated/$shortcode'
      path: '/$shortcode'
      fullPath: '/$shortcode'
      preLoaderRoute: typeof AuthenticatedShortcodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/': {
      id: '/_authenticated/usda/'
      path: '/usda'
      fullPath: '/usda/'
      preLoaderRoute: typeof AuthenticatedUsdaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/': {
      id: '/_authenticated/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthenticatedIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/': {
      id: '/_authenticated/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof AuthenticatedImagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/timing': {
      id: '/api/debug/timing'
      path: '/api/debug/timing'
      fullPath: '/api/debug/timing'
      preLoaderRoute: typeof ApiDebugTimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usda/$id': {
      id: '/_authenticated/usda/$id'
      path: '/usda/$id'
      fullPath: '/usda/$id'
      preLoaderRoute: typeof AuthenticatedUsdaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/compare': {
      id: '/_authenticated/recipes/compare'
      path: '/recipes/compare'
      fullPath: '/recipes/compare'
      preLoaderRoute: typeof AuthenticatedRecipesCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$id': {
      id: '/_authenticated/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AuthenticatedRecipesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/validate': {
      id: '/_authenticated/locations/validate'
      path: '/locations/validate'
      fullPath: '/locations/validate'
      preLoaderRoute: typeof AuthenticatedLocationsValidateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/new': {
      id: '/_authenticated/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AuthenticatedLocationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/$id': {
      id: '/_authenticated/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof AuthenticatedLocationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/quick-capture': {
      id: '/_authenticated/inventory/quick-capture'
      path: '/inventory/quick-capture'
      fullPath: '/inventory/quick-capture'
      preLoaderRoute: typeof AuthenticatedInventoryQuickCaptureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/bulk-move': {
      id: '/_authenticated/inventory/bulk-move'
      path: '/inventory/bulk-move'
      fullPath: '/inventory/bulk-move'
      preLoaderRoute: typeof AuthenticatedInventoryBulkMoveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/bulk-edit': {
      id: '/_authenticated/inventory/bulk-edit'
      path: '/inventory/bulk-edit'
      fullPath: '/inventory/bulk-edit'
      preLoaderRoute: typeof AuthenticatedInventoryBulkEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/$id': {
      id: '/_authenticated/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/$id': {
      id: '/_authenticated/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof AuthenticatedIngredientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/$id': {
      id: '/_authenticated/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof AuthenticatedImagesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/$accountView': {
      id: '/_authenticated/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AuthenticatedAccountAccountViewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/upc/$code': {
      id: '/_authenticated/usda/upc/$code'
      path: '/usda/upc/$code'
      fullPath: '/usda/upc/$code'
      preLoaderRoute: typeof AuthenticatedUsdaUpcCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/ndb/$code': {
      id: '/_authenticated/usda/ndb/$code'
      path: '/usda/ndb/$code'
      fullPath: '/usda/ndb/$code'
      preLoaderRoute: typeof AuthenticatedUsdaNdbCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedShortcodeRoute: typeof AuthenticatedShortcodeRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedPantryViewRoute: typeof AuthenticatedPantryViewRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedAccountAccountViewRoute: typeof AuthenticatedAccountAccountViewRoute
  AuthenticatedImagesIdRoute: typeof AuthenticatedImagesIdRoute
  AuthenticatedIngredientsIdRoute: typeof AuthenticatedIngredientsIdRoute
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRoute
  AuthenticatedInventoryBulkEditRoute: typeof AuthenticatedInventoryBulkEditRoute
  AuthenticatedInventoryBulkMoveRoute: typeof AuthenticatedInventoryBulkMoveRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedInventoryQuickCaptureRoute: typeof AuthenticatedInventoryQuickCaptureRoute
  AuthenticatedLocationsIdRoute: typeof AuthenticatedLocationsIdRoute
  AuthenticatedLocationsNewRoute: typeof AuthenticatedLocationsNewRoute
  AuthenticatedLocationsValidateRoute: typeof AuthenticatedLocationsValidateRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedRecipesIdRoute: typeof AuthenticatedRecipesIdRoute
  AuthenticatedRecipesCompareRoute: typeof AuthenticatedRecipesCompareRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedUsdaIdRoute: typeof AuthenticatedUsdaIdRoute
  AuthenticatedImagesIndexRoute: typeof AuthenticatedImagesIndexRoute
  AuthenticatedIngredientsIndexRoute: typeof AuthenticatedIngredientsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedUsdaIndexRoute: typeof AuthenticatedUsdaIndexRoute
  AuthenticatedUsdaNdbCodeRoute: typeof AuthenticatedUsdaNdbCodeRoute
  AuthenticatedUsdaUpcCodeRoute: typeof AuthenticatedUsdaUpcCodeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShortcodeRoute: AuthenticatedShortcodeRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedPantryViewRoute: AuthenticatedPantryViewRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedAccountAccountViewRoute: AuthenticatedAccountAccountViewRoute,
  AuthenticatedImagesIdRoute: AuthenticatedImagesIdRoute,
  AuthenticatedIngredientsIdRoute: AuthenticatedIngredientsIdRoute,
  AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRoute,
  AuthenticatedInventoryBulkEditRoute: AuthenticatedInventoryBulkEditRoute,
  AuthenticatedInventoryBulkMoveRoute: AuthenticatedInventoryBulkMoveRoute,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedInventoryQuickCaptureRoute:
    AuthenticatedInventoryQuickCaptureRoute,
  AuthenticatedLocationsIdRoute: AuthenticatedLocationsIdRoute,
  AuthenticatedLocationsNewRoute: AuthenticatedLocationsNewRoute,
  AuthenticatedLocationsValidateRoute: AuthenticatedLocationsValidateRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedRecipesIdRoute: AuthenticatedRecipesIdRoute,
  AuthenticatedRecipesCompareRoute: AuthenticatedRecipesCompareRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedUsdaIdRoute: AuthenticatedUsdaIdRoute,
  AuthenticatedImagesIndexRoute: AuthenticatedImagesIndexRoute,
  AuthenticatedIngredientsIndexRoute: AuthenticatedIngredientsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedUsdaIndexRoute: AuthenticatedUsdaIndexRoute,
  AuthenticatedUsdaNdbCodeRoute: AuthenticatedUsdaNdbCodeRoute,
  AuthenticatedUsdaUpcCodeRoute: AuthenticatedUsdaUpcCodeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DocsRoute: DocsRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPanelRoute: ApiPanelRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDebugTimingRoute: ApiDebugTimingRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
