/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known.openid-configuration'
import { Route as AuthenticatedShortcodeRouteImport } from './routes/_authenticated/$shortcode'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAiSmokeTestRouteImport } from './routes/_authenticated/ai-smoke-test'
import { Route as AuthenticatedAiUsageRouteImport } from './routes/_authenticated/ai-usage'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedBackgroundJobsRouteImport } from './routes/_authenticated/background-jobs'
import { Route as AuthenticatedEntitiesRouteImport } from './routes/_authenticated/entities'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedMcpRouteImport } from './routes/_authenticated/mcp'
import { Route as AuthenticatedPantryViewRouteImport } from './routes/_authenticated/pantry-view'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AuthAuthViewRouteImport } from './routes/auth.$authView'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSectionRouteImport } from './routes/docs.$section'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AuthenticatedAccountAccountViewRouteImport } from './routes/_authenticated/account.$accountView'
import { Route as AuthenticatedCookbooksIndexRouteImport } from './routes/_authenticated/cookbooks.index'
import { Route as AuthenticatedCookbooksCookbookIdRouteImport } from './routes/_authenticated/cookbooks.$cookbookId'
import { Route as AuthenticatedImagesIndexRouteImport } from './routes/_authenticated/images.index'
import { Route as AuthenticatedImagesIdRouteImport } from './routes/_authenticated/images.$id'
import { Route as AuthenticatedIngredientsIndexRouteImport } from './routes/_authenticated/ingredients.index'
import { Route as AuthenticatedIngredientsIdRouteImport } from './routes/_authenticated/ingredients.$id'
import { Route as AuthenticatedIngredientsEquivalencesRouteImport } from './routes/_authenticated/ingredients.equivalences'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients.new'
import { Route as AuthenticatedIngredientsWorkbenchRouteImport } from './routes/_authenticated/ingredients.workbench'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedInventoryIdRouteImport } from './routes/_authenticated/inventory.$id'
import { Route as AuthenticatedInventoryBulkEditRouteImport } from './routes/_authenticated/inventory.bulk-edit'
import { Route as AuthenticatedInventoryBulkMoveRouteImport } from './routes/_authenticated/inventory.bulk-move'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory.new'
import { Route as AuthenticatedInventorySessionRouteImport } from './routes/_authenticated/inventory.session'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedLocationsIdRouteImport } from './routes/_authenticated/locations.$id'
import { Route as AuthenticatedLocationsArrangeRouteImport } from './routes/_authenticated/locations.arrange'
import { Route as AuthenticatedLocationsNewRouteImport } from './routes/_authenticated/locations.new'
import { Route as AuthenticatedMealsIndexRouteImport } from './routes/_authenticated/meals.index'
import { Route as AuthenticatedMealsIdRouteImport } from './routes/_authenticated/meals.$id'
import { Route as AuthenticatedMealsShoppingListRouteImport } from './routes/_authenticated/meals.shopping-list'
import { Route as AuthenticatedMealsSuggestionsRouteImport } from './routes/_authenticated/meals.suggestions'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases.index'
import { Route as AuthenticatedPurchasesIdRouteImport } from './routes/_authenticated/purchases.$id'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes.index'
import { Route as AuthenticatedRecipesIdRouteImport } from './routes/_authenticated/recipes.$id'
import { Route as AuthenticatedRecipesCompareRouteImport } from './routes/_authenticated/recipes.compare'
import { Route as AuthenticatedRecipesImportRouteImport } from './routes/_authenticated/recipes.import'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes.new'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search.index'
import { Route as AuthenticatedSearchDebugRouteImport } from './routes/_authenticated/search.debug'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks.$id'
import { Route as AuthenticatedUsdaIndexRouteImport } from './routes/_authenticated/usda.index'
import { Route as AuthenticatedUsdaIdRouteImport } from './routes/_authenticated/usda.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDebugTimingRouteImport } from './routes/api/debug/timing'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as DotwellKnownOauthAuthorizationServerApiAuthRouteImport } from './routes/[.]well-known.oauth-authorization-server.api.auth'
import { Route as DotwellKnownOauthProtectedResourceApiMcpRouteImport } from './routes/[.]well-known.oauth-protected-resource.api.mcp'
import { Route as AuthenticatedRecipesIdExportRouteImport } from './routes/_authenticated/recipes.$id_.export'
import { Route as AuthenticatedUsdaNdbCodeRouteImport } from './routes/_authenticated/usda.ndb.$code'
import { Route as AuthenticatedUsdaUpcCodeRouteImport } from './routes/_authenticated/usda.upc.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedShortcodeRoute = AuthenticatedShortcodeRouteImport.update({
  id: '/$shortcode',
  path: '/$shortcode',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiSmokeTestRoute =
  AuthenticatedAiSmokeTestRouteImport.update({
    id: '/ai-smoke-test',
    path: '/ai-smoke-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiUsageRoute = AuthenticatedAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackgroundJobsRoute =
  AuthenticatedBackgroundJobsRouteImport.update({
    id: '/background-jobs',
    path: '/background-jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEntitiesRoute = AuthenticatedEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMcpRoute = AuthenticatedMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPantryViewRoute = AuthenticatedPantryViewRouteImport.update({
  id: '/pantry-view',
  path: '/pantry-view',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSectionRoute = DocsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DocsRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountAccountViewRoute =
  AuthenticatedAccountAccountViewRouteImport.update({
    id: '/account/$accountView',
    path: '/account/$accountView',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCookbooksIndexRoute =
  AuthenticatedCookbooksIndexRouteImport.update({
    id: '/cookbooks/',
    path: '/cookbooks/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCookbooksCookbookIdRoute =
  AuthenticatedCookbooksCookbookIdRouteImport.update({
    id: '/cookbooks/$cookbookId',
    path: '/cookbooks/$cookbookId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIndexRoute =
  AuthenticatedImagesIndexRouteImport.update({
    id: '/images/',
    path: '/images/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagesIdRoute = AuthenticatedImagesIdRouteImport.update({
  id: '/images/$id',
  path: '/images/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIngredientsIndexRoute =
  AuthenticatedIngredientsIndexRouteImport.update({
    id: '/ingredients/',
    path: '/ingredients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsIdRoute =
  AuthenticatedIngredientsIdRouteImport.update({
    id: '/ingredients/$id',
    path: '/ingredients/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsEquivalencesRoute =
  AuthenticatedIngredientsEquivalencesRouteImport.update({
    id: '/ingredients/equivalences',
    path: '/ingredients/equivalences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/ingredients/new',
    path: '/ingredients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIngredientsWorkbenchRoute =
  AuthenticatedIngredientsWorkbenchRouteImport.update({
    id: '/ingredients/workbench',
    path: '/ingredients/workbench',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIdRoute =
  AuthenticatedInventoryIdRouteImport.update({
    id: '/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryBulkEditRoute =
  AuthenticatedInventoryBulkEditRouteImport.update({
    id: '/inventory/bulk-edit',
    path: '/inventory/bulk-edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryBulkMoveRoute =
  AuthenticatedInventoryBulkMoveRouteImport.update({
    id: '/inventory/bulk-move',
    path: '/inventory/bulk-move',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventorySessionRoute =
  AuthenticatedInventorySessionRouteImport.update({
    id: '/inventory/session',
    path: '/inventory/session',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIdRoute =
  AuthenticatedLocationsIdRouteImport.update({
    id: '/locations/$id',
    path: '/locations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsArrangeRoute =
  AuthenticatedLocationsArrangeRouteImport.update({
    id: '/locations/arrange',
    path: '/locations/arrange',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsNewRoute =
  AuthenticatedLocationsNewRouteImport.update({
    id: '/locations/new',
    path: '/locations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMealsIndexRoute = AuthenticatedMealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMealsIdRoute = AuthenticatedMealsIdRouteImport.update({
  id: '/meals/$id',
  path: '/meals/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMealsShoppingListRoute =
  AuthenticatedMealsShoppingListRouteImport.update({
    id: '/meals/shopping-list',
    path: '/meals/shopping-list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMealsSuggestionsRoute =
  AuthenticatedMealsSuggestionsRouteImport.update({
    id: '/meals/suggestions',
    path: '/meals/suggestions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesIdRoute =
  AuthenticatedPurchasesIdRouteImport.update({
    id: '/purchases/$id',
    path: '/purchases/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesIdRoute = AuthenticatedRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecipesCompareRoute =
  AuthenticatedRecipesCompareRouteImport.update({
    id: '/recipes/compare',
    path: '/recipes/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesImportRoute =
  AuthenticatedRecipesImportRouteImport.update({
    id: '/recipes/import',
    path: '/recipes/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSearchDebugRoute =
  AuthenticatedSearchDebugRouteImport.update({
    id: '/search/debug',
    path: '/search/debug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsdaIndexRoute = AuthenticatedUsdaIndexRouteImport.update({
  id: '/usda/',
  path: '/usda/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsdaIdRoute = AuthenticatedUsdaIdRouteImport.update({
  id: '/usda/$id',
  path: '/usda/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTimingRoute = ApiDebugTimingRouteImport.update({
  id: '/api/debug/timing',
  path: '/api/debug/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerApiAuthRoute =
  DotwellKnownOauthAuthorizationServerApiAuthRouteImport.update({
    id: '/api/auth',
    path: '/api/auth',
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any)
const DotwellKnownOauthProtectedResourceApiMcpRoute =
  DotwellKnownOauthProtectedResourceApiMcpRouteImport.update({
    id: '/api/mcp',
    path: '/api/mcp',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)
const AuthenticatedRecipesIdExportRoute =
  AuthenticatedRecipesIdExportRouteImport.update({
    id: '/recipes/$id_/export',
    path: '/recipes/$id/export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsdaNdbCodeRoute =
  AuthenticatedUsdaNdbCodeRouteImport.update({
    id: '/usda/ndb/$code',
    path: '/usda/ndb/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsdaUpcCodeRoute =
  AuthenticatedUsdaUpcCodeRouteImport.update({
    id: '/usda/upc/$code',
    path: '/usda/upc/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$shortcode': typeof AuthenticatedShortcodeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-smoke-test': typeof AuthenticatedAiSmokeTestRoute
  '/ai-usage': typeof AuthenticatedAiUsageRoute
  '/ask': typeof AuthenticatedAskRoute
  '/background-jobs': typeof AuthenticatedBackgroundJobsRoute
  '/entities': typeof AuthenticatedEntitiesRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/pantry-view': typeof AuthenticatedPantryViewRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/docs/$section': typeof DocsSectionRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/docs/': typeof DocsIndexRoute
  '/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/cookbooks/$cookbookId': typeof AuthenticatedCookbooksCookbookIdRoute
  '/images/$id': typeof AuthenticatedImagesIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/equivalences': typeof AuthenticatedIngredientsEquivalencesRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/ingredients/workbench': typeof AuthenticatedIngredientsWorkbenchRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/bulk-edit': typeof AuthenticatedInventoryBulkEditRoute
  '/inventory/bulk-move': typeof AuthenticatedInventoryBulkMoveRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/inventory/session': typeof AuthenticatedInventorySessionRoute
  '/locations/$id': typeof AuthenticatedLocationsIdRoute
  '/locations/arrange': typeof AuthenticatedLocationsArrangeRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/meals/$id': typeof AuthenticatedMealsIdRoute
  '/meals/shopping-list': typeof AuthenticatedMealsShoppingListRoute
  '/meals/suggestions': typeof AuthenticatedMealsSuggestionsRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/purchases/$id': typeof AuthenticatedPurchasesIdRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/recipes/compare': typeof AuthenticatedRecipesCompareRoute
  '/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/search/debug': typeof AuthenticatedSearchDebugRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/usda/$id': typeof AuthenticatedUsdaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/cookbooks/': typeof AuthenticatedCookbooksIndexRoute
  '/images/': typeof AuthenticatedImagesIndexRoute
  '/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/meals/': typeof AuthenticatedMealsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/usda/': typeof AuthenticatedUsdaIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/recipes/$id/export': typeof AuthenticatedRecipesIdExportRoute
  '/usda/ndb/$code': typeof AuthenticatedUsdaNdbCodeRoute
  '/usda/upc/$code': typeof AuthenticatedUsdaUpcCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/$shortcode': typeof AuthenticatedShortcodeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-smoke-test': typeof AuthenticatedAiSmokeTestRoute
  '/ai-usage': typeof AuthenticatedAiUsageRoute
  '/ask': typeof AuthenticatedAskRoute
  '/background-jobs': typeof AuthenticatedBackgroundJobsRoute
  '/entities': typeof AuthenticatedEntitiesRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/pantry-view': typeof AuthenticatedPantryViewRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/docs/$section': typeof DocsSectionRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/docs': typeof DocsIndexRoute
  '/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/cookbooks/$cookbookId': typeof AuthenticatedCookbooksCookbookIdRoute
  '/images/$id': typeof AuthenticatedImagesIdRoute
  '/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/ingredients/equivalences': typeof AuthenticatedIngredientsEquivalencesRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/ingredients/workbench': typeof AuthenticatedIngredientsWorkbenchRoute
  '/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/inventory/bulk-edit': typeof AuthenticatedInventoryBulkEditRoute
  '/inventory/bulk-move': typeof AuthenticatedInventoryBulkMoveRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/inventory/session': typeof AuthenticatedInventorySessionRoute
  '/locations/$id': typeof AuthenticatedLocationsIdRoute
  '/locations/arrange': typeof AuthenticatedLocationsArrangeRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/meals/$id': typeof AuthenticatedMealsIdRoute
  '/meals/shopping-list': typeof AuthenticatedMealsShoppingListRoute
  '/meals/suggestions': typeof AuthenticatedMealsSuggestionsRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/purchases/$id': typeof AuthenticatedPurchasesIdRoute
  '/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/recipes/compare': typeof AuthenticatedRecipesCompareRoute
  '/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/search/debug': typeof AuthenticatedSearchDebugRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/usda/$id': typeof AuthenticatedUsdaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/cookbooks': typeof AuthenticatedCookbooksIndexRoute
  '/images': typeof AuthenticatedImagesIndexRoute
  '/ingredients': typeof AuthenticatedIngredientsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/meals': typeof AuthenticatedMealsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/usda': typeof AuthenticatedUsdaIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/recipes/$id/export': typeof AuthenticatedRecipesIdExportRoute
  '/usda/ndb/$code': typeof AuthenticatedUsdaNdbCodeRoute
  '/usda/upc/$code': typeof AuthenticatedUsdaUpcCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design': typeof DesignRoute
  '/docs': typeof DocsRouteWithChildren
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_authenticated/$shortcode': typeof AuthenticatedShortcodeRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ai-smoke-test': typeof AuthenticatedAiSmokeTestRoute
  '/_authenticated/ai-usage': typeof AuthenticatedAiUsageRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/background-jobs': typeof AuthenticatedBackgroundJobsRoute
  '/_authenticated/entities': typeof AuthenticatedEntitiesRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/mcp': typeof AuthenticatedMcpRoute
  '/_authenticated/pantry-view': typeof AuthenticatedPantryViewRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/mcp': typeof ApiMcpRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/docs/$section': typeof DocsSectionRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/account/$accountView': typeof AuthenticatedAccountAccountViewRoute
  '/_authenticated/cookbooks/$cookbookId': typeof AuthenticatedCookbooksCookbookIdRoute
  '/_authenticated/images/$id': typeof AuthenticatedImagesIdRoute
  '/_authenticated/ingredients/$id': typeof AuthenticatedIngredientsIdRoute
  '/_authenticated/ingredients/equivalences': typeof AuthenticatedIngredientsEquivalencesRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/ingredients/workbench': typeof AuthenticatedIngredientsWorkbenchRoute
  '/_authenticated/inventory/$id': typeof AuthenticatedInventoryIdRoute
  '/_authenticated/inventory/bulk-edit': typeof AuthenticatedInventoryBulkEditRoute
  '/_authenticated/inventory/bulk-move': typeof AuthenticatedInventoryBulkMoveRoute
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/inventory/session': typeof AuthenticatedInventorySessionRoute
  '/_authenticated/locations/$id': typeof AuthenticatedLocationsIdRoute
  '/_authenticated/locations/arrange': typeof AuthenticatedLocationsArrangeRoute
  '/_authenticated/locations/new': typeof AuthenticatedLocationsNewRoute
  '/_authenticated/meals/$id': typeof AuthenticatedMealsIdRoute
  '/_authenticated/meals/shopping-list': typeof AuthenticatedMealsShoppingListRoute
  '/_authenticated/meals/suggestions': typeof AuthenticatedMealsSuggestionsRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/purchases/$id': typeof AuthenticatedPurchasesIdRoute
  '/_authenticated/recipes/$id': typeof AuthenticatedRecipesIdRoute
  '/_authenticated/recipes/compare': typeof AuthenticatedRecipesCompareRoute
  '/_authenticated/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/_authenticated/search/debug': typeof AuthenticatedSearchDebugRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/usda/$id': typeof AuthenticatedUsdaIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/timing': typeof ApiDebugTimingRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/cookbooks/': typeof AuthenticatedCookbooksIndexRoute
  '/_authenticated/images/': typeof AuthenticatedImagesIndexRoute
  '/_authenticated/ingredients/': typeof AuthenticatedIngredientsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/meals/': typeof AuthenticatedMealsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/usda/': typeof AuthenticatedUsdaIndexRoute
  '/.well-known/oauth-authorization-server/api/auth': typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/_authenticated/recipes/$id_/export': typeof AuthenticatedRecipesIdExportRoute
  '/_authenticated/usda/ndb/$code': typeof AuthenticatedUsdaNdbCodeRoute
  '/_authenticated/usda/upc/$code': typeof AuthenticatedUsdaUpcCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/docs'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/$shortcode'
    | '/activity'
    | '/ai-smoke-test'
    | '/ai-usage'
    | '/ask'
    | '/background-jobs'
    | '/entities'
    | '/labels'
    | '/mcp'
    | '/pantry-view'
    | '/problems'
    | '/settings'
    | '/api/mcp'
    | '/auth/$authView'
    | '/docs/$section'
    | '/oauth/consent'
    | '/docs/'
    | '/account/$accountView'
    | '/cookbooks/$cookbookId'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/equivalences'
    | '/ingredients/new'
    | '/ingredients/workbench'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/session'
    | '/locations/$id'
    | '/locations/arrange'
    | '/locations/new'
    | '/meals/$id'
    | '/meals/shopping-list'
    | '/meals/suggestions'
    | '/products/$id'
    | '/products/new'
    | '/projects/$id'
    | '/purchases/$id'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/import'
    | '/recipes/new'
    | '/search/debug'
    | '/tasks/$id'
    | '/usda/$id'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/cookbooks/'
    | '/images/'
    | '/ingredients/'
    | '/inventory/'
    | '/locations/'
    | '/meals/'
    | '/products/'
    | '/projects/'
    | '/purchases/'
    | '/recipes/'
    | '/search/'
    | '/tasks/'
    | '/usda/'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/recipes/$id/export'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/$shortcode'
    | '/activity'
    | '/ai-smoke-test'
    | '/ai-usage'
    | '/ask'
    | '/background-jobs'
    | '/entities'
    | '/labels'
    | '/mcp'
    | '/pantry-view'
    | '/problems'
    | '/settings'
    | '/api/mcp'
    | '/auth/$authView'
    | '/docs/$section'
    | '/oauth/consent'
    | '/docs'
    | '/account/$accountView'
    | '/cookbooks/$cookbookId'
    | '/images/$id'
    | '/ingredients/$id'
    | '/ingredients/equivalences'
    | '/ingredients/new'
    | '/ingredients/workbench'
    | '/inventory/$id'
    | '/inventory/bulk-edit'
    | '/inventory/bulk-move'
    | '/inventory/new'
    | '/inventory/session'
    | '/locations/$id'
    | '/locations/arrange'
    | '/locations/new'
    | '/meals/$id'
    | '/meals/shopping-list'
    | '/meals/suggestions'
    | '/products/$id'
    | '/products/new'
    | '/projects/$id'
    | '/purchases/$id'
    | '/recipes/$id'
    | '/recipes/compare'
    | '/recipes/import'
    | '/recipes/new'
    | '/search/debug'
    | '/tasks/$id'
    | '/usda/$id'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/cookbooks'
    | '/images'
    | '/ingredients'
    | '/inventory'
    | '/locations'
    | '/meals'
    | '/products'
    | '/projects'
    | '/purchases'
    | '/recipes'
    | '/search'
    | '/tasks'
    | '/usda'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/recipes/$id/export'
    | '/usda/ndb/$code'
    | '/usda/upc/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design'
    | '/docs'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/_authenticated/$shortcode'
    | '/_authenticated/activity'
    | '/_authenticated/ai-smoke-test'
    | '/_authenticated/ai-usage'
    | '/_authenticated/ask'
    | '/_authenticated/background-jobs'
    | '/_authenticated/entities'
    | '/_authenticated/labels'
    | '/_authenticated/mcp'
    | '/_authenticated/pantry-view'
    | '/_authenticated/problems'
    | '/_authenticated/settings'
    | '/api/mcp'
    | '/auth/$authView'
    | '/docs/$section'
    | '/oauth/consent'
    | '/docs/'
    | '/_authenticated/account/$accountView'
    | '/_authenticated/cookbooks/$cookbookId'
    | '/_authenticated/images/$id'
    | '/_authenticated/ingredients/$id'
    | '/_authenticated/ingredients/equivalences'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/ingredients/workbench'
    | '/_authenticated/inventory/$id'
    | '/_authenticated/inventory/bulk-edit'
    | '/_authenticated/inventory/bulk-move'
    | '/_authenticated/inventory/new'
    | '/_authenticated/inventory/session'
    | '/_authenticated/locations/$id'
    | '/_authenticated/locations/arrange'
    | '/_authenticated/locations/new'
    | '/_authenticated/meals/$id'
    | '/_authenticated/meals/shopping-list'
    | '/_authenticated/meals/suggestions'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/projects/$id'
    | '/_authenticated/purchases/$id'
    | '/_authenticated/recipes/$id'
    | '/_authenticated/recipes/compare'
    | '/_authenticated/recipes/import'
    | '/_authenticated/recipes/new'
    | '/_authenticated/search/debug'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/usda/$id'
    | '/api/auth/$'
    | '/api/debug/timing'
    | '/api/trpc/$'
    | '/_authenticated/cookbooks/'
    | '/_authenticated/images/'
    | '/_authenticated/ingredients/'
    | '/_authenticated/inventory/'
    | '/_authenticated/locations/'
    | '/_authenticated/meals/'
    | '/_authenticated/products/'
    | '/_authenticated/projects/'
    | '/_authenticated/purchases/'
    | '/_authenticated/recipes/'
    | '/_authenticated/search/'
    | '/_authenticated/tasks/'
    | '/_authenticated/usda/'
    | '/.well-known/oauth-authorization-server/api/auth'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/_authenticated/recipes/$id_/export'
    | '/_authenticated/usda/ndb/$code'
    | '/_authenticated/usda/upc/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignRoute: typeof DesignRoute
  DocsRoute: typeof DocsRouteWithChildren
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiMcpRoute: typeof ApiMcpRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDebugTimingRoute: typeof ApiDebugTimingRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$shortcode': {
      id: '/_authenticated/$shortcode'
      path: '/$shortcode'
      fullPath: '/$shortcode'
      preLoaderRoute: typeof AuthenticatedShortcodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-smoke-test': {
      id: '/_authenticated/ai-smoke-test'
      path: '/ai-smoke-test'
      fullPath: '/ai-smoke-test'
      preLoaderRoute: typeof AuthenticatedAiSmokeTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-usage': {
      id: '/_authenticated/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AuthenticatedAiUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/background-jobs': {
      id: '/_authenticated/background-jobs'
      path: '/background-jobs'
      fullPath: '/background-jobs'
      preLoaderRoute: typeof AuthenticatedBackgroundJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entities': {
      id: '/_authenticated/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AuthenticatedEntitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mcp': {
      id: '/_authenticated/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AuthenticatedMcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry-view': {
      id: '/_authenticated/pantry-view'
      path: '/pantry-view'
      fullPath: '/pantry-view'
      preLoaderRoute: typeof AuthenticatedPantryViewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$section': {
      id: '/docs/$section'
      path: '/$section'
      fullPath: '/docs/$section'
      preLoaderRoute: typeof DocsSectionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/$accountView': {
      id: '/_authenticated/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AuthenticatedAccountAccountViewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cookbooks/': {
      id: '/_authenticated/cookbooks/'
      path: '/cookbooks'
      fullPath: '/cookbooks/'
      preLoaderRoute: typeof AuthenticatedCookbooksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cookbooks/$cookbookId': {
      id: '/_authenticated/cookbooks/$cookbookId'
      path: '/cookbooks/$cookbookId'
      fullPath: '/cookbooks/$cookbookId'
      preLoaderRoute: typeof AuthenticatedCookbooksCookbookIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/': {
      id: '/_authenticated/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof AuthenticatedImagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/images/$id': {
      id: '/_authenticated/images/$id'
      path: '/images/$id'
      fullPath: '/images/$id'
      preLoaderRoute: typeof AuthenticatedImagesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/': {
      id: '/_authenticated/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof AuthenticatedIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/$id': {
      id: '/_authenticated/ingredients/$id'
      path: '/ingredients/$id'
      fullPath: '/ingredients/$id'
      preLoaderRoute: typeof AuthenticatedIngredientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/equivalences': {
      id: '/_authenticated/ingredients/equivalences'
      path: '/ingredients/equivalences'
      fullPath: '/ingredients/equivalences'
      preLoaderRoute: typeof AuthenticatedIngredientsEquivalencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients/workbench': {
      id: '/_authenticated/ingredients/workbench'
      path: '/ingredients/workbench'
      fullPath: '/ingredients/workbench'
      preLoaderRoute: typeof AuthenticatedIngredientsWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/$id': {
      id: '/_authenticated/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AuthenticatedInventoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/bulk-edit': {
      id: '/_authenticated/inventory/bulk-edit'
      path: '/inventory/bulk-edit'
      fullPath: '/inventory/bulk-edit'
      preLoaderRoute: typeof AuthenticatedInventoryBulkEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/bulk-move': {
      id: '/_authenticated/inventory/bulk-move'
      path: '/inventory/bulk-move'
      fullPath: '/inventory/bulk-move'
      preLoaderRoute: typeof AuthenticatedInventoryBulkMoveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/session': {
      id: '/_authenticated/inventory/session'
      path: '/inventory/session'
      fullPath: '/inventory/session'
      preLoaderRoute: typeof AuthenticatedInventorySessionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/$id': {
      id: '/_authenticated/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof AuthenticatedLocationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/arrange': {
      id: '/_authenticated/locations/arrange'
      path: '/locations/arrange'
      fullPath: '/locations/arrange'
      preLoaderRoute: typeof AuthenticatedLocationsArrangeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/new': {
      id: '/_authenticated/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AuthenticatedLocationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meals/': {
      id: '/_authenticated/meals/'
      path: '/meals'
      fullPath: '/meals/'
      preLoaderRoute: typeof AuthenticatedMealsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meals/$id': {
      id: '/_authenticated/meals/$id'
      path: '/meals/$id'
      fullPath: '/meals/$id'
      preLoaderRoute: typeof AuthenticatedMealsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meals/shopping-list': {
      id: '/_authenticated/meals/shopping-list'
      path: '/meals/shopping-list'
      fullPath: '/meals/shopping-list'
      preLoaderRoute: typeof AuthenticatedMealsShoppingListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meals/suggestions': {
      id: '/_authenticated/meals/suggestions'
      path: '/meals/suggestions'
      fullPath: '/meals/suggestions'
      preLoaderRoute: typeof AuthenticatedMealsSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/$id': {
      id: '/_authenticated/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof AuthenticatedPurchasesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$id': {
      id: '/_authenticated/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AuthenticatedRecipesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/compare': {
      id: '/_authenticated/recipes/compare'
      path: '/recipes/compare'
      fullPath: '/recipes/compare'
      preLoaderRoute: typeof AuthenticatedRecipesCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/import': {
      id: '/_authenticated/recipes/import'
      path: '/recipes/import'
      fullPath: '/recipes/import'
      preLoaderRoute: typeof AuthenticatedRecipesImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search/debug': {
      id: '/_authenticated/search/debug'
      path: '/search/debug'
      fullPath: '/search/debug'
      preLoaderRoute: typeof AuthenticatedSearchDebugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/': {
      id: '/_authenticated/usda/'
      path: '/usda'
      fullPath: '/usda/'
      preLoaderRoute: typeof AuthenticatedUsdaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/$id': {
      id: '/_authenticated/usda/$id'
      path: '/usda/$id'
      fullPath: '/usda/$id'
      preLoaderRoute: typeof AuthenticatedUsdaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/timing': {
      id: '/api/debug/timing'
      path: '/api/debug/timing'
      fullPath: '/api/debug/timing'
      preLoaderRoute: typeof ApiDebugTimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server/api/auth': {
      id: '/.well-known/oauth-authorization-server/api/auth'
      path: '/api/auth'
      fullPath: '/.well-known/oauth-authorization-server/api/auth'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRouteImport
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute
    }
    '/.well-known/oauth-protected-resource/api/mcp': {
      id: '/.well-known/oauth-protected-resource/api/mcp'
      path: '/api/mcp'
      fullPath: '/.well-known/oauth-protected-resource/api/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
    '/_authenticated/recipes/$id_/export': {
      id: '/_authenticated/recipes/$id_/export'
      path: '/recipes/$id/export'
      fullPath: '/recipes/$id/export'
      preLoaderRoute: typeof AuthenticatedRecipesIdExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/ndb/$code': {
      id: '/_authenticated/usda/ndb/$code'
      path: '/usda/ndb/$code'
      fullPath: '/usda/ndb/$code'
      preLoaderRoute: typeof AuthenticatedUsdaNdbCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usda/upc/$code': {
      id: '/_authenticated/usda/upc/$code'
      path: '/usda/upc/$code'
      fullPath: '/usda/upc/$code'
      preLoaderRoute: typeof AuthenticatedUsdaUpcCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedShortcodeRoute: typeof AuthenticatedShortcodeRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAiSmokeTestRoute: typeof AuthenticatedAiSmokeTestRoute
  AuthenticatedAiUsageRoute: typeof AuthenticatedAiUsageRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedBackgroundJobsRoute: typeof AuthenticatedBackgroundJobsRoute
  AuthenticatedEntitiesRoute: typeof AuthenticatedEntitiesRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedMcpRoute: typeof AuthenticatedMcpRoute
  AuthenticatedPantryViewRoute: typeof AuthenticatedPantryViewRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountAccountViewRoute: typeof AuthenticatedAccountAccountViewRoute
  AuthenticatedCookbooksCookbookIdRoute: typeof AuthenticatedCookbooksCookbookIdRoute
  AuthenticatedImagesIdRoute: typeof AuthenticatedImagesIdRoute
  AuthenticatedIngredientsIdRoute: typeof AuthenticatedIngredientsIdRoute
  AuthenticatedIngredientsEquivalencesRoute: typeof AuthenticatedIngredientsEquivalencesRoute
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedIngredientsWorkbenchRoute: typeof AuthenticatedIngredientsWorkbenchRoute
  AuthenticatedInventoryIdRoute: typeof AuthenticatedInventoryIdRoute
  AuthenticatedInventoryBulkEditRoute: typeof AuthenticatedInventoryBulkEditRoute
  AuthenticatedInventoryBulkMoveRoute: typeof AuthenticatedInventoryBulkMoveRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedInventorySessionRoute: typeof AuthenticatedInventorySessionRoute
  AuthenticatedLocationsIdRoute: typeof AuthenticatedLocationsIdRoute
  AuthenticatedLocationsArrangeRoute: typeof AuthenticatedLocationsArrangeRoute
  AuthenticatedLocationsNewRoute: typeof AuthenticatedLocationsNewRoute
  AuthenticatedMealsIdRoute: typeof AuthenticatedMealsIdRoute
  AuthenticatedMealsShoppingListRoute: typeof AuthenticatedMealsShoppingListRoute
  AuthenticatedMealsSuggestionsRoute: typeof AuthenticatedMealsSuggestionsRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedPurchasesIdRoute: typeof AuthenticatedPurchasesIdRoute
  AuthenticatedRecipesIdRoute: typeof AuthenticatedRecipesIdRoute
  AuthenticatedRecipesCompareRoute: typeof AuthenticatedRecipesCompareRoute
  AuthenticatedRecipesImportRoute: typeof AuthenticatedRecipesImportRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedSearchDebugRoute: typeof AuthenticatedSearchDebugRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedUsdaIdRoute: typeof AuthenticatedUsdaIdRoute
  AuthenticatedCookbooksIndexRoute: typeof AuthenticatedCookbooksIndexRoute
  AuthenticatedImagesIndexRoute: typeof AuthenticatedImagesIndexRoute
  AuthenticatedIngredientsIndexRoute: typeof AuthenticatedIngredientsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedMealsIndexRoute: typeof AuthenticatedMealsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsdaIndexRoute: typeof AuthenticatedUsdaIndexRoute
  AuthenticatedRecipesIdExportRoute: typeof AuthenticatedRecipesIdExportRoute
  AuthenticatedUsdaNdbCodeRoute: typeof AuthenticatedUsdaNdbCodeRoute
  AuthenticatedUsdaUpcCodeRoute: typeof AuthenticatedUsdaUpcCodeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShortcodeRoute: AuthenticatedShortcodeRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAiSmokeTestRoute: AuthenticatedAiSmokeTestRoute,
  AuthenticatedAiUsageRoute: AuthenticatedAiUsageRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedBackgroundJobsRoute: AuthenticatedBackgroundJobsRoute,
  AuthenticatedEntitiesRoute: AuthenticatedEntitiesRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedMcpRoute: AuthenticatedMcpRoute,
  AuthenticatedPantryViewRoute: AuthenticatedPantryViewRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountAccountViewRoute: AuthenticatedAccountAccountViewRoute,
  AuthenticatedCookbooksCookbookIdRoute: AuthenticatedCookbooksCookbookIdRoute,
  AuthenticatedImagesIdRoute: AuthenticatedImagesIdRoute,
  AuthenticatedIngredientsIdRoute: AuthenticatedIngredientsIdRoute,
  AuthenticatedIngredientsEquivalencesRoute:
    AuthenticatedIngredientsEquivalencesRoute,
  AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
  AuthenticatedIngredientsWorkbenchRoute:
    AuthenticatedIngredientsWorkbenchRoute,
  AuthenticatedInventoryIdRoute: AuthenticatedInventoryIdRoute,
  AuthenticatedInventoryBulkEditRoute: AuthenticatedInventoryBulkEditRoute,
  AuthenticatedInventoryBulkMoveRoute: AuthenticatedInventoryBulkMoveRoute,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedInventorySessionRoute: AuthenticatedInventorySessionRoute,
  AuthenticatedLocationsIdRoute: AuthenticatedLocationsIdRoute,
  AuthenticatedLocationsArrangeRoute: AuthenticatedLocationsArrangeRoute,
  AuthenticatedLocationsNewRoute: AuthenticatedLocationsNewRoute,
  AuthenticatedMealsIdRoute: AuthenticatedMealsIdRoute,
  AuthenticatedMealsShoppingListRoute: AuthenticatedMealsShoppingListRoute,
  AuthenticatedMealsSuggestionsRoute: AuthenticatedMealsSuggestionsRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedPurchasesIdRoute: AuthenticatedPurchasesIdRoute,
  AuthenticatedRecipesIdRoute: AuthenticatedRecipesIdRoute,
  AuthenticatedRecipesCompareRoute: AuthenticatedRecipesCompareRoute,
  AuthenticatedRecipesImportRoute: AuthenticatedRecipesImportRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedSearchDebugRoute: AuthenticatedSearchDebugRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedUsdaIdRoute: AuthenticatedUsdaIdRoute,
  AuthenticatedCookbooksIndexRoute: AuthenticatedCookbooksIndexRoute,
  AuthenticatedImagesIndexRoute: AuthenticatedImagesIndexRoute,
  AuthenticatedIngredientsIndexRoute: AuthenticatedIngredientsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedMealsIndexRoute: AuthenticatedMealsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsdaIndexRoute: AuthenticatedUsdaIndexRoute,
  AuthenticatedRecipesIdExportRoute: AuthenticatedRecipesIdExportRoute,
  AuthenticatedUsdaNdbCodeRoute: AuthenticatedUsdaNdbCodeRoute,
  AuthenticatedUsdaUpcCodeRoute: AuthenticatedUsdaUpcCodeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsSectionRoute: typeof DocsSectionRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSectionRoute: DocsSectionRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerApiAuthRoute: typeof DotwellKnownOauthAuthorizationServerApiAuthRoute
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerApiAuthRoute:
      DotwellKnownOauthAuthorizationServerApiAuthRoute,
  }

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  )

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceApiMcpRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceApiMcpRoute:
      DotwellKnownOauthProtectedResourceApiMcpRoute,
  }

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignRoute: DesignRoute,
  DocsRoute: DocsRouteWithChildren,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiMcpRoute: ApiMcpRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDebugTimingRoute: ApiDebugTimingRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
