import { product, productStreams } from "~/app/products/product.functions";
import { implementOperationDomain } from "~/server/operation-domain.server";
import { implementSubscriptionDomain } from "~/server/subscription-domain.server";
import {
  applyProductUpcDataWorkflow,
  attachProductComponentsWorkflow,
  backfillProductUpcImagesWorkflow,
  bulkSetProductStockTrackedWorkflow,
  createManyProductsWorkflow,
  detachProductComponentsWorkflow,
  discardProductWorkflow,
  findOrCreateProductByCodeWorkflow,
  findOrCreateProductByUpcWorkflow,
  getProductCategoryDistributionWorkflow,
  getProductExternalIdSourceOptionsWorkflow,
  getProductInventoryEntriesWorkflow,
  getProductManufacturerOptionsWorkflow,
  getProductMovementTimelineWorkflow,
  getProductQuantitySummariesWorkflow,
  getProductRelationshipRouteWorkflow,
  getProductSummariesWorkflow,
  getProductsByShortcodesWorkflow,
  getProductTagOptionsWorkflow,
  listKitComponentRowsWorkflow,
  listKitMembershipWorkflow,
  listProductComponentsWorkflow,
  listProductProjectUsesWorkflow,
  listProductPurchasesWorkflow,
  markProductsUsdaUnavailableWorkflow,
  mergeProductsWorkflow,
  quickCreateProductWorkflow,
  searchProductsWorkflow,
  setProductProjectUsesWorkflow,
} from "~/server/workflows/product.server";

export const productHandlers = implementOperationDomain(product, {
  search: searchProductsWorkflow,
  summaries: getProductSummariesWorkflow,
  quantitySummaries: getProductQuantitySummariesWorkflow,
  inventoryEntriesByIds: getProductInventoryEntriesWorkflow,
  quickCreate: quickCreateProductWorkflow,
  applyUpcData: applyProductUpcDataWorkflow,
  findOrCreateByUPC: findOrCreateProductByUpcWorkflow,
  findOrCreateByCode: findOrCreateProductByCodeWorkflow,
  tagOptions: getProductTagOptionsWorkflow,
  categoryDistribution: getProductCategoryDistributionWorkflow,
  manufacturerOptions: getProductManufacturerOptionsWorkflow,
  externalIdSourceOptions: getProductExternalIdSourceOptionsWorkflow,
  movementTimeline: getProductMovementTimelineWorkflow,
  getByShortcodes: getProductsByShortcodesWorkflow,
  merge: mergeProductsWorkflow,
  projectUses: listProductProjectUsesWorkflow,
  purchases: listProductPurchasesWorkflow,
  relationshipRoute: getProductRelationshipRouteWorkflow,
  components: listProductComponentsWorkflow,
  kitComponentRows: listKitComponentRowsWorkflow,
  kitMembership: listKitMembershipWorkflow,
  attachComponents: attachProductComponentsWorkflow,
  detachComponents: detachProductComponentsWorkflow,
  setProjectUses: setProductProjectUsesWorkflow,
  discard: discardProductWorkflow,
  bulkSetStockTracked: bulkSetProductStockTrackedWorkflow,
});

export const productStreamHandlers = implementSubscriptionDomain(
  productStreams,
  {
    createMany: (context, input) => createManyProductsWorkflow(context, input),
    markUsdaUnavailableMany: (context, input) =>
      markProductsUsdaUnavailableWorkflow(context, input),
    backfillUPCImages: (context) => backfillProductUpcImagesWorkflow(context),
  },
);
