import { product } from "~/app/products/product.functions";
import { implementOperationDomain } from "~/server/operation-domain.server";
import {
  applyProductUpcDataWorkflow,
  attachProductComponentsWorkflow,
  bulkSetProductStockTrackedWorkflow,
  detachProductComponentsWorkflow,
  discardProductWorkflow,
  findOrCreateProductByCodeWorkflow,
  findOrCreateProductByUpcWorkflow,
  getProductCategoryDistributionWorkflow,
  getProductExternalIdSourceOptionsWorkflow,
  getProductInventoryEntriesWorkflow,
  getProductManufacturerOptionsWorkflow,
  getProductMovementTimelineWorkflow,
  getProductQuantitySummariesWorkflow,
  getProductRelationshipRouteWorkflow,
  getProductSummariesWorkflow,
  getProductsByShortcodesWorkflow,
  getProductTagOptionsWorkflow,
  listKitComponentRowsWorkflow,
  listKitMembershipWorkflow,
  listProductComponentsWorkflow,
  listProductProjectUsesWorkflow,
  listProductPurchasesWorkflow,
  mergeProductsWorkflow,
  quickCreateProductWorkflow,
  searchProductsWorkflow,
  setProductProjectUsesWorkflow,
} from "~/server/workflows/product.server";

export const productHandlers = implementOperationDomain(product, {
  search: searchProductsWorkflow,
  summaries: getProductSummariesWorkflow,
  quantitySummaries: getProductQuantitySummariesWorkflow,
  inventoryEntriesByIds: getProductInventoryEntriesWorkflow,
  quickCreate: quickCreateProductWorkflow,
  applyUpcData: applyProductUpcDataWorkflow,
  findOrCreateByUPC: findOrCreateProductByUpcWorkflow,
  findOrCreateByCode: findOrCreateProductByCodeWorkflow,
  tagOptions: getProductTagOptionsWorkflow,
  categoryDistribution: getProductCategoryDistributionWorkflow,
  manufacturerOptions: getProductManufacturerOptionsWorkflow,
  externalIdSourceOptions: getProductExternalIdSourceOptionsWorkflow,
  movementTimeline: getProductMovementTimelineWorkflow,
  getByShortcodes: getProductsByShortcodesWorkflow,
  merge: mergeProductsWorkflow,
  projectUses: listProductProjectUsesWorkflow,
  purchases: listProductPurchasesWorkflow,
  relationshipRoute: getProductRelationshipRouteWorkflow,
  components: listProductComponentsWorkflow,
  kitComponentRows: listKitComponentRowsWorkflow,
  kitMembership: listKitMembershipWorkflow,
  attachComponents: attachProductComponentsWorkflow,
  detachComponents: detachProductComponentsWorkflow,
  setProjectUses: setProductProjectUsesWorkflow,
  discard: discardProductWorkflow,
  bulkSetStockTracked: bulkSetProductStockTrackedWorkflow,
});
