import type { Entity } from "@cubby/schemas/entity";
import { urlStringParam } from "~/lib/search-params";

/**
 * Dependency-light URL projection of the UI filter manifest.
 *
 * Route modules are part of TanStack Router's eager graph. Importing the full
 * icon/options/brand-bearing filter manifest there made every browser download
 * table UI and date helpers before hydration. The UI test suite asserts this
 * key projection stays identical to `getEntityFilters()`.
 */
const filterSearchKeys = {
  product: [
    "name",
    "manufacturer",
    "manufacturerSearch",
    "upc",
    "model",
    "modelPresence",
    "upcPresence",
    "category",
    "location",
    "ingredient",
    "expenses",
    "expenseTotal",
    "expectedQuantity",
    "quantityVariance",
    "notes",
    "notesPresence",
    "dataQuality",
    "dataGaps",
    "externalIds",
    "purchaseDate",
    "price",
    "food",
    "image",
    "unitMappingQuality",
    "stockTracked",
    "tags",
    "related-vendor",
    "related-project",
    "related-usedOnProject",
    "usedOnProjectId",
    "usedOnProjectPresenceFilter",
    "related-purchase",
    "related-expense",
    "expenseId",
    "expensePresenceFilter",
    "related-relatedInventory",
    "relatedInventoryId",
    "relatedInventoryPresenceFilter",
    "related:product.tasks",
    "taskId",
    "createdAt",
    "updatedAt",
  ],
  ingredient: ["name", "product", "appearsInRecipes", "createdAt", "updatedAt"],
  inventory: [
    "product",
    "location",
    "manufacturer",
    "category",
    "verifiedAt",
    "placement",
    "related-ingredient",
    "ingredientId",
    "ingredientPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  location: [
    "image",
    "children",
    "aiDescription",
    "name",
    "type",
    "parent",
    "inventoryEntries",
    "valuation",
    "related-ingredient",
    "ingredientId",
    "ingredientPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  recipe: [
    "name",
    "tags",
    "source",
    "meals",
    "image",
    "costTotal",
    "caloriesTotal",
    "related-ingredient",
    "related-meal",
    "mealId",
    "mealPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  meal: [
    "mealType",
    "mealKind",
    "related-recipe",
    "recipeId",
    "createdAt",
    "updatedAt",
  ],
  project: [
    "image",
    "name",
    "statuses",
    "kinds",
    "locations",
    "date",
    "completed",
    "parent",
    "related-project",
    "projectId",
    "projectPresenceFilter",
    "related-task",
    "taskId",
    "taskPresenceFilter",
    "related-expense",
    "expenseId",
    "expensePresenceFilter",
    "related-taskProduct",
    "taskProductId",
    "taskProductPresenceFilter",
    "related-purchasedProduct",
    "purchasedProductId",
    "purchasedProductPresenceFilter",
    "related-usedTool",
    "usedToolId",
    "usedToolPresenceFilter",
    "related-vendor",
    "vendorId",
    "vendorPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  task: [
    "name",
    "status",
    "trade",
    "dueDate",
    "project",
    "productId",
    "subjectProduct",
    "parentTask",
    "related-blockedByTask",
    "blockedByTaskId",
    "blockedByTaskPresenceFilter",
    "related-parentTask",
    "parentTaskId",
    "parentTaskPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  expense: [
    "q",
    "date",
    "costType",
    "lineKind",
    "lineBasis",
    "trade",
    "future",
    "cost",
    "costMin",
    "costMax",
    "productQuantity",
    "productQuantityMin",
    "productQuantityMax",
    "notesSearch",
    "urlSearch",
    "project",
    "subprojects",
    "productId",
    "product",
    "vendor",
    "orderId",
    "order",
    "purchaseId",
    "related-financialTransaction",
    "financialTransactionId",
    "financialTransactionPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  vendor: [
    "q",
    "purchaseCount",
    "spend",
    "latestPurchaseDate",
    "related-expense",
    "expenseId",
    "expensePresenceFilter",
    "related-purchase",
    "purchaseId",
    "purchasePresenceFilter",
    "related-product",
    "productId",
    "productPresenceFilter",
    "related-project",
    "projectId",
    "projectPresenceFilter",
    "related-financialTransaction",
    "financialTransactionId",
    "financialTransactionPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  purchase: [
    "q",
    "label",
    "vendor",
    "orderId",
    "date",
    "statedTotal",
    "lines",
    "lineTotal",
    "reconciliation",
    "documents",
    "transactions",
    "dataQuality",
    "dataGaps",
    "lineTotalMin",
    "lineTotalMax",
    "related-expense",
    "expenseId",
    "expensePresenceFilter",
    "related-financialTransaction",
    "financialTransactionId",
    "financialTransactionPresenceFilter",
    "related-product",
    "productId",
    "productPresenceFilter",
    "related-project",
    "projectId",
    "projectPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  financialAccount: [
    "q",
    "identity",
    "provisional",
    "aliases",
    "last4",
    "source",
    "externalAccountId",
    "related-financialTransaction",
    "financialTransactionId",
    "financialTransactionPresenceFilter",
    "related-purchase",
    "purchaseId",
    "purchasePresenceFilter",
    "related-vendor",
    "vendorId",
    "vendorPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  financialTransaction: [
    "q",
    "kind",
    "status",
    "postedDate",
    "accountId",
    "purchaseId",
    "purchasePresence",
    "source",
    "externalId",
    "merchant",
    "amount",
    "amountMin",
    "amountMax",
    "transactionDateFrom",
    "transactionDateTo",
    "postedDateFrom",
    "postedDateTo",
    "related-vendor",
    "vendorId",
    "vendorPresenceFilter",
    "related-expense",
    "expenseId",
    "expensePresenceFilter",
    "related-product",
    "productId",
    "productPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  wish: [
    "q",
    "acquired",
    "related-product",
    "productId",
    "productPresenceFilter",
    "createdAt",
    "updatedAt",
  ],
  image: ["filename", "createdAt", "updatedAt"],
  "usda-food": [],
  cookbook: [],
} as const satisfies Record<Entity, readonly string[]>;

export function entityFilterSearchFields(
  entity: Entity,
): Record<string, typeof urlStringParam> {
  const fields: Record<string, typeof urlStringParam> = {};
  for (const key of filterSearchKeys[entity]) fields[key] = urlStringParam;
  return fields;
}
