import type { Entity } from "@cubby/schemas/entity";
import {
  type BrowserRoutedEntity,
  browserRoutedEntities,
} from "@cubby/schemas/entity-manifest";

/**
 * Dependency-free client projection of the server sort contracts. Route
 * loaders only need these field names; importing every entity schema here
 * pulled validation graphs into the eager route tree. The drift test pins this
 * map to the canonical schema exports.
 */
export const sortableFields = {
  ingredient: ["createdAt", "updatedAt", "name", "appearsInRecipes", "product"],
  product: [
    "createdAt",
    "updatedAt",
    "name",
    "manufacturer",
    "model",
    "primaryGtin",
    "category",
    "fdc_id",
    "price",
    "notes",
    "location",
    "ingredient",
    "expenseTotal",
    "expenses",
    "expectedQuantity",
    "quantityVariance",
    "purchaseDate",
    "related:product.projects",
    "related:product.vendors",
    "related:product.purchases",
    "identity_strength",
  ],
  recipe: [
    "createdAt",
    "updatedAt",
    "name",
    "cookbook",
    "costTotal",
    "caloriesTotal",
    "source",
    "yield",
    "tags",
    "totalMinutes",
  ],
  cookbook: [],
  location: [
    "createdAt",
    "updatedAt",
    "name",
    "type",
    "parent",
    "lastBulkInventory",
    "valuation",
    "inventoryEntries",
  ],
  inventory: [
    "createdAt",
    "updatedAt",
    "name",
    "product",
    "location",
    "amount",
    "valuation",
    "verifiedAt",
  ],
  meal: ["date", "name", "mealType", "createdAt", "updatedAt"],
  project: [
    "name",
    "status",
    "kind",
    "startDate",
    "costEstimate",
    "createdAt",
    "updatedAt",
  ],
  task: [
    "name",
    "status",
    "dueDate",
    "trade",
    "project",
    "subjectProduct",
    "createdAt",
    "updatedAt",
  ],
  vendor: [
    "name",
    "purchaseCount",
    "spend",
    "latestPurchaseDate",
    "createdAt",
    "updatedAt",
  ],
  purchase: [
    "orderId",
    "displayLabel",
    "date",
    "statedTotal",
    "vendor",
    "expenseCount",
    "expenseTotal",
    "reconciliationGap",
    "documentCount",
    "createdAt",
    "updatedAt",
  ],
  expense: [
    "name",
    "cost",
    "lineKind",
    "productQuantity",
    "date",
    "costType",
    "trade",
    "project",
    "product",
    "vendor",
    "orderId",
    "createdAt",
    "updatedAt",
  ],
  financialAccount: [
    "name",
    "provisional",
    "transactionCount",
    "createdAt",
    "updatedAt",
  ],
  financialTransaction: [
    "transactionDate",
    "postedDate",
    "amount",
    "merchant",
    "kind",
    "status",
    "createdAt",
    "updatedAt",
  ],
  wish: ["name", "acquiredAt", "priceRange", "createdAt", "updatedAt"],
  "usda-food": [
    "fdc_id",
    "description",
    "data_type",
    "relevance",
    "linkedProducts",
  ],
  image: ["createdAt", "updatedAt", "filename", "size", "status"],
} as const satisfies Record<BrowserRoutedEntity, readonly string[]>;

export const getSortableFields = (entity: Entity): readonly string[] =>
  (browserRoutedEntities as readonly string[]).includes(entity)
    ? sortableFields[entity as BrowserRoutedEntity]
    : [];
