import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "product",
  names: { singular: "Product", plural: "Products" },
  route: { basePath: "products" },
  table: "Product",
  identifiers: { brand: "ProductId", shortcode: "PRD-", legacy: "P-" },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "identity-name",
        },
        display: { list: true, detail: true, standard: "name", detailOrder: 0 },
        validation: {
          read: {
            kind: "string",
            description: "Product name",
            mock: "commerce.productName",
          },
          create: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Product name is required",
            description: "Product name",
            mock: "commerce.productName",
          },
          update: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Product name is required",
            optional: true,
            description: "Product name",
            mock: "commerce.productName",
          },
        },
      },
      {
        key: "aliases",
        kind: "text-array",
        nullable: false,
        label: "Aliases",
        description: null,
        readKey: "aliases",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: false, detail: false },
        validation: {
          read: { kind: "array", item: { kind: "string" } },
          create: { kind: "array", item: { kind: "string" }, defaultValue: [] },
          update: { kind: "array", item: { kind: "string" }, optional: true },
        },
      },
      {
        key: "tags",
        kind: "text-array",
        nullable: false,
        label: "Tags",
        description: null,
        readKey: "tags",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: false, detail: true, detailOrder: 10 },
        validation: {
          read: { kind: "array", item: { kind: "string" } },
          create: { kind: "array", item: { kind: "string" }, defaultValue: [] },
          update: { kind: "array", item: { kind: "string" }, optional: true },
        },
      },
      {
        key: "upc",
        kind: "text",
        nullable: true,
        label: "Upc",
        description: null,
        readKey: null,
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: false, detail: false },
        validation: {
          create: {
            kind: "source",
            source: { module: "@cubby/schemas/external-id", export: "gtin" },
            nullable: true,
          },
          update: {
            kind: "source",
            source: { module: "@cubby/schemas/external-id", export: "gtin" },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "isbn",
        kind: "text",
        nullable: true,
        label: "Isbn",
        description: null,
        readKey: null,
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: false, detail: false },
        validation: {
          create: {
            kind: "source",
            source: { module: "@cubby/schemas/isbn", export: "isbn" },
            nullable: true,
            optional: true,
          },
          update: {
            kind: "source",
            source: { module: "@cubby/schemas/isbn", export: "isbn" },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "fdc_id",
        kind: "number",
        nullable: true,
        label: "USDA FDC ID",
        description: null,
        readKey: "fdc_id",
        reference: null,
        control: { kind: "number", renderer: null, options: null },
        display: { list: true, detail: true, detailOrder: 7 },
        validation: {
          read: {
            kind: "source",
            source: { module: "@cubby/usda-schemas", export: "fdcId" },
            nullable: true,
          },
          create: {
            kind: "source",
            source: { module: "@cubby/usda-schemas", export: "fdcId" },
            nullable: true,
            optional: true,
          },
          update: {
            kind: "source",
            source: { module: "@cubby/usda-schemas", export: "fdcId" },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "manufacturer",
        kind: "text",
        nullable: false,
        label: "Manufacturer",
        description: null,
        readKey: "manufacturer",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "manufacturer",
        },
        display: { list: true, detail: true, detailOrder: 2 },
        validation: {
          read: { kind: "string" },
          create: { kind: "string" },
          update: { kind: "string", optional: true },
        },
      },
      {
        key: "model",
        kind: "text",
        nullable: true,
        label: "Model",
        description: null,
        readKey: "model",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "identity-model",
        },
        display: { list: true, detail: true, detailOrder: 3 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, optional: true },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: {
          kind: "textarea",
          renderer: null,
          options: null,
          section: "notes",
        },
        display: { list: true, detail: false },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, optional: true },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "expectedQuantity",
        kind: "number",
        nullable: true,
        label: "Expected Quantity",
        description: null,
        readKey: "expectedQuantity",
        reference: null,
        control: { kind: "number", renderer: null, options: null },
        display: { list: true, detail: false },
        validation: {
          read: { kind: "number", nullable: true },
          create: { kind: "number", nullable: true },
          update: { kind: "number", nullable: true, optional: true },
        },
      },
      {
        key: "category",
        kind: "enum",
        nullable: true,
        label: "Category",
        description: null,
        readKey: "category",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: { list: true, detail: true, detailOrder: 5 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "productCategory",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "productCategory",
            },
            nullable: true,
            optional: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "productCategory",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "ingredientId",
        kind: "identifier",
        nullable: true,
        label: "Ingredient",
        description: null,
        readKey: null,
        reference: { entity: "ingredient", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: false, detail: true, detailOrder: 8 },
        validation: {
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ingredientShortcode",
            },
            nullable: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ingredientShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "price",
        kind: "number",
        nullable: true,
        label: "Valuation price",
        description: null,
        readKey: "price",
        reference: null,
        control: { kind: "number", renderer: "money", options: null },
        display: { list: true, detail: true, detailOrder: 4 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "moneyNullable",
            },
            description:
              "Manual per-item valuation/replacement-price override; null resumes the Expense-derived fallback.",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "positiveMoneyNullable",
            },
            optional: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "positiveMoneyNullable",
            },
            optional: true,
          },
        },
      },
      {
        key: "unitMappings",
        kind: "json",
        nullable: false,
        label: "Unit Mappings",
        description: null,
        readKey: null,
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/unitmapping",
                export: "unitMappingInput",
              },
            },
            defaultValue: [],
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/unitmapping",
                export: "unitMappingInput",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "externalIds",
        kind: "text-array",
        nullable: false,
        label: "External IDs",
        description: null,
        readKey: "externalIds",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: false, detail: true, detailOrder: 9 },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/external-id",
                export: "externalIdOut",
              },
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/external-id",
              export: "externalIdInputs",
            },
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/external-id",
              export: "externalIdInputs",
            },
            optional: true,
          },
        },
      },
      {
        key: "usdaUnavailable",
        kind: "boolean",
        nullable: true,
        label: "Usda Unavailable",
        description: null,
        readKey: "usdaUnavailable",
        reference: null,
        control: { kind: "checkbox", renderer: null, options: null },
        display: { list: true, detail: false },
        validation: {
          read: { kind: "boolean", nullable: true },
          create: { kind: "boolean", nullable: true, optional: true },
          update: { kind: "boolean", nullable: true, optional: true },
        },
      },
      {
        key: "stockTracked",
        kind: "boolean",
        nullable: true,
        label: "Stock Tracked",
        description: null,
        readKey: "stockTracked",
        reference: null,
        control: { kind: "checkbox", renderer: null, options: null },
        display: { list: true, detail: false },
        validation: {
          read: { kind: "boolean", nullable: true },
          create: { kind: "boolean", nullable: true, optional: true },
          update: { kind: "boolean", nullable: true, optional: true },
        },
      },
      {
        key: "pendingImageIds",
        kind: "identifier",
        nullable: false,
        label: "Pending Image IDs",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "removeImageIds",
        kind: "identifier",
        nullable: false,
        label: "Remove Image IDs",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "imageOrder",
        kind: "text",
        nullable: false,
        label: "Image Order",
        description: null,
        readKey: null,
        reference: null,
        control: {
          kind: "specialized",
          renderer: "image-order",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: true, detailOrder: 1 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
          },
        },
      },
      {
        key: "primaryGtin",
        kind: "text",
        nullable: true,
        label: "UPC",
        description: null,
        readKey: "primaryGtin",
        reference: null,
        control: null,
        display: { list: true, detail: true, detailOrder: 6 },
        validation: {
          read: {
            kind: "source",
            source: { module: "@cubby/schemas/external-id", export: "gtin" },
            nullable: true,
          },
        },
      },
      {
        key: "images",
        kind: "json",
        nullable: false,
        label: "Images",
        description: null,
        readKey: "images",
        reference: null,
        control: null,
        display: {
          list: true,
          detail: false,
          standard: "image",
          columnId: "image",
        },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: { module: "@cubby/schemas/image", export: "imageOut" },
            },
          },
        },
      },
      {
        key: "pricing",
        kind: "json",
        nullable: false,
        label: "Pricing",
        description: null,
        readKey: "pricing",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/product-fields",
              export: "productPricingOut",
            },
          },
        },
      },
      {
        key: "dataQuality",
        kind: "json",
        nullable: false,
        label: "Data Quality",
        description: null,
        readKey: "dataQuality",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/data-quality",
              export: "dataQuality",
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "dataExceptions",
        kind: "json",
        nullable: false,
        label: "Data Exceptions",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:ProductId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "aliases",
        column: "aliases",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "manufacturer",
        column: "manufacturer",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "fdc_id",
        column: "fdc_id",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "model",
        column: "model",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "expectedQuantity",
        column: "expectedQuantity",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "ingredientId",
        column: "ingredientId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "ingredient",
        specialized: null,
      },
      {
        key: "category",
        column: "category",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:category",
      },
      {
        key: "tags",
        column: "tags",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "price",
        column: "price",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "real",
      },
      {
        key: "usdaUnavailable",
        column: "usdaUnavailable",
        kind: "boolean",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "stockTracked",
        column: "stockTracked",
        kind: "boolean",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "dataExceptions",
        column: "dataExceptions",
        kind: "json",
        nullable: false,
        default: "literal",
        defaultValue: "'[]'::jsonb",
        reference: null,
        specialized: "json:dataExceptions",
      },
    ],
    create: [
      "name",
      "aliases",
      "tags",
      "upc",
      "isbn",
      "fdc_id",
      "manufacturer",
      "model",
      "notes",
      "expectedQuantity",
      "category",
      "ingredientId",
      "price",
      "unitMappings",
      "externalIds",
      "usdaUnavailable",
      "stockTracked",
      "pendingImageIds",
    ],
    update: [
      "name",
      "aliases",
      "tags",
      "upc",
      "isbn",
      "fdc_id",
      "manufacturer",
      "model",
      "notes",
      "expectedQuantity",
      "category",
      "ingredientId",
      "price",
      "unitMappings",
      "externalIds",
      "usdaUnavailable",
      "stockTracked",
      "pendingImageIds",
      "removeImageIds",
      "imageOrder",
    ],
    bulk: ["stockTracked"],
    audit: [
      "name",
      "aliases",
      "tags",
      "manufacturer",
      "category",
      "externalIds",
      "fdc_id",
      "model",
      "expectedQuantity",
      "ingredientId",
      "price",
    ],
    output: [
      "id",
      "name",
      "aliases",
      "tags",
      "primaryGtin",
      "fdc_id",
      "manufacturer",
      "model",
      "notes",
      "expectedQuantity",
      "category",
      "images",
      "externalIds",
      "price",
      "pricing",
      "usdaUnavailable",
      "stockTracked",
      "dataQuality",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/product", export: "productCreateInput" },
    update: { module: "@cubby/schemas/product", export: "productUpdateData" },
    output: { module: "@cubby/schemas/product", export: "productTopLevelOut" },
    list: { module: "@cubby/schemas/product", export: "productListItemOut" },
    detail: { module: "@cubby/schemas/product", export: "productWithFoodOut" },
    mcpOutput: {
      module: "@cubby/schemas/product",
      export: "productTopLevelMcpEntityOut",
    },
    mcpList: {
      module: "@cubby/schemas/product",
      export: "productListItemMcpEntityOut",
    },
    mcpDetail: {
      module: "@cubby/schemas/product",
      export: "productWithFoodMcpEntityOut",
    },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/product", export: "productFilterFields" },
    descriptors: [
      {
        columnId: "name",
        field: "nameFilter",
        kind: "text",
        placeholder: "Filter by name...",
        deriveSchema: true,
        schemaDescription: "Filter by product name",
      },
      {
        columnId: "manufacturer",
        field: "manufacturerExact",
        kind: "multiselect",
        placeholder: "Filter by manufacturer...",
        deriveSchema: true,
        optionsKey: "manufacturers",
      },
      {
        columnId: "manufacturerSearch",
        field: "manufacturerFilter",
        kind: "text",
        placeholder: "Search manufacturer...",
        urlOnly: true,
      },
      {
        columnId: "primaryGtin",
        field: "upcFilter",
        kind: "text",
        placeholder: "Filter by UPC...",
        deriveSchema: true,
        schemaDescription:
          "Filter by UPC/barcode — matches ANY of the product's barcodes",
      },
      {
        columnId: "model",
        field: "modelFilter",
        kind: "text",
        placeholder: "Filter by model...",
        deriveSchema: true,
        schemaDescription:
          "Filter by model number — a tool's real identity when the name is generic.",
      },
      {
        columnId: "modelPresence",
        field: "modelPresenceFilter",
        kind: "presence",
        placeholder: "Filter model presence...",
        options: [
          { value: "has", label: "Has model", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "upcPresence",
        field: "upcPresenceFilter",
        kind: "presence",
        placeholder: "Filter UPC presence...",
        options: [
          { value: "has", label: "Has UPC", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "category",
        field: "categoryFilter",
        kind: "multiselect",
        placeholder: "Filter by category...",
        deriveSchema: true,
        schemaDescription: "Filter by category",
        optionsRef: {
          module: "~/app/_components/products/product-category-icons",
          export: "productCategoryOptionsWithTheme",
        },
        nullable: { field: "categoryPresenceFilter", label: "category" },
      },
      {
        columnId: "location",
        field: "locationIdFilter",
        kind: "idMulti",
        placeholder: "Filter locations...",
        optionsKey: "productLocations",
        brandRef: { entity: "location", kind: "id" },
        nullable: { field: "inventoryPresenceFilter", label: "inventory" },
      },
      {
        columnId: "servingAsLocations",
        field: "servingAsLocationPresenceFilter",
        kind: "presence",
        placeholder: "Filter in service...",
        options: [
          { value: "has", label: "Has in service as a location", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "ingredient",
        field: "ingredientIdFilter",
        kind: "idMulti",
        placeholder: "Filter ingredient...",
        optionsKey: "productIngredients",
        brandRef: { entity: "ingredient", kind: "id" },
        nullable: { field: "ingredientPresenceFilter", label: "ingredient" },
      },
      {
        columnId: "expenses",
        kind: "range",
        placeholder: "Filter expenses...",
        options: [
          { value: "has", label: "Has expenses", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "1", label: "1+ expenses" },
          { value: "2", label: "2+ expenses" },
          { value: "5", label: "5+ expenses" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveExpenseCount",
        },
      },
      {
        columnId: "expenseTotal",
        kind: "range",
        placeholder: "Filter net basis...",
        options: [
          { value: "positive", label: "Positive basis" },
          { value: "zero", label: "Zero basis" },
          { value: "negative", label: "Credit / negative" },
          { value: "gte100", label: "$100 and up" },
          { value: "gte500", label: "$500 and up" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveNetBasis",
        },
      },
      {
        columnId: "expectedQuantity",
        kind: "range",
        placeholder: "Filter expected quantity...",
        deriveSchema: true,
        options: [
          { value: "negative", label: "Negative (sold more than bought)" },
          { value: "zero", label: "Zero (none expected)" },
          { value: "positive", label: "One or more expected" },
          { value: "gte5", label: "5 or more expected" },
          { value: "unknown", label: "Has lines with no quantity" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveExpectedQuantity",
        },
      },
      {
        columnId: "quantityVariance",
        kind: "range",
        placeholder: "Filter shelf vs. ledger...",
        options: [
          { value: "mismatched", label: "Shelf disagrees with ledger" },
          { value: "matched", label: "Shelf matches ledger" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveQuantityVariance",
        },
      },
      {
        columnId: "notes",
        field: "notesFilter",
        kind: "text",
        placeholder: "Search notes...",
        deriveSchema: true,
      },
      {
        columnId: "notesPresence",
        field: "notesPresenceFilter",
        kind: "presence",
        placeholder: "Filter notes presence...",
        options: [
          { value: "has", label: "Has notes", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "dataQuality",
        field: "dataStatus",
        kind: "select",
        placeholder: "Filter data quality...",
        options: [
          { value: "complete", label: "Complete", color: "var(--slate)" },
          { value: "needs_data", label: "Needs data", color: "var(--warning)" },
          { value: "defect", label: "Defect", color: "var(--destructive)" },
        ],
      },
      {
        columnId: "dataGaps",
        field: "dataGap",
        kind: "multiselect",
        placeholder: "Filter data gaps...",
        options: [
          { value: "product_manufacturer", label: "Manufacturer" },
          { value: "product_category", label: "Category" },
          { value: "product_model", label: "Model" },
          { value: "product_image", label: "No image (stocked)" },
          { value: "amazon_asin", label: "Amazon ASIN" },
          { value: "duplicate_external_id", label: "Duplicate external ID" },
        ],
      },
      {
        columnId: "externalIds",
        field: "externalIdSource",
        kind: "multiselect",
        placeholder: "Filter by external ID source...",
        optionsKey: "externalIdSources",
        nullable: { field: "externalIdPresenceFilter", label: "external ID" },
      },
      {
        columnId: "purchaseDate",
        kind: "range",
        placeholder: "Filter by purchase date...",
        options: [
          { value: "has", label: "Has purchase date", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveProductPurchaseDateFilter",
        },
      },
      {
        columnId: "price",
        kind: "range",
        placeholder: "Filter price...",
        options: [
          { value: "has", label: "Has price", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "none-real", label: "No price (excluding buckets)" },
          { value: "none-bucket", label: "No price (buckets only)" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolvePrice",
        },
      },
      {
        columnId: "food",
        field: "usdaPresenceFilter",
        kind: "presence",
        placeholder: "Filter USDA...",
        options: [
          { value: "has", label: "Has USDA key", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "image",
        field: "imagePresenceFilter",
        kind: "presence",
        placeholder: "Filter images...",
        options: [
          { value: "has", label: "Has image", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "inventoryMultiplicity",
        field: "inventoryMultiplicity",
        kind: "select",
        placeholder: "Filter inventory multiplicity...",
        options: [
          {
            value: "duplicate_within_placement",
            label: "Duplicate within placement",
          },
        ],
      },
      {
        columnId: "kitAccounting",
        field: "kitAccounting",
        kind: "select",
        placeholder: "Filter kit accounting...",
        options: [{ value: "double_counted", label: "Counted twice" }],
      },
      {
        columnId: "ownershipReconciliation",
        field: "ownershipReconciliation",
        kind: "select",
        placeholder: "Filter ownership reconciliation...",
        options: [
          {
            value: "disposed_still_on_hand",
            label: "Disposed but still on hand",
          },
        ],
      },
      {
        columnId: "conversionCoverage",
        field: "conversionCoverage",
        kind: "select",
        placeholder: "Filter conversion coverage...",
        options: [{ value: "partial", label: "Partial coverage" }],
      },
      {
        columnId: "conversionTopology",
        field: "conversionTopology",
        kind: "select",
        placeholder: "Filter conversion topology...",
        options: [{ value: "islanded", label: "Islanded mappings" }],
      },
      {
        columnId: "unitMappingQuality",
        field: "unitMappingPresenceFilter",
        kind: "presence",
        placeholder: "Filter mappings...",
        options: [
          { value: "has", label: "Has mappings", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "stockTracked",
        field: "stockTrackedPresenceFilter",
        kind: "presence",
        placeholder: "Filter stock tracking...",
        options: [
          { value: "none", label: "Undecided" },
          { value: "has", label: "Reviewed" },
        ],
      },
      {
        columnId: "components",
        field: "componentPresenceFilter",
        kind: "presence",
        placeholder: "Filter kits...",
        options: [
          { value: "has", label: "Is a kit" },
          { value: "none", label: "Not a kit" },
        ],
      },
      {
        columnId: "tags",
        field: "tagFilters",
        kind: "multiselect",
        placeholder: "Filter by tag...",
        optionsKey: "tags",
        nullable: { field: "tagsPresenceFilter", label: "tags" },
      },
      {
        columnId: "related:product.vendors",
        field: "vendorId",
        urlKey: "related-vendor",
        kind: "idMulti",
        placeholder: "Filter by vendor...",
        optionsKey: "productVendors",
        brandRef: { entity: "vendor", kind: "id" },
        nullable: { field: "vendorPresenceFilter", label: "vendor" },
      },
      {
        columnId: "related:product.projects",
        field: "projectId",
        urlKey: "related-project",
        kind: "idMulti",
        placeholder: "Filter by project...",
        optionsKey: "project",
        brandRef: { entity: "project", kind: "id" },
        nullable: { field: "projectPresenceFilter", label: "project" },
      },
      {
        columnId: "related:product.usedOnProjects",
        field: "usedOnProjectSearch",
        urlKey: "related-usedOnProject",
        kind: "text",
        placeholder: "Search related used on projects...",
      },
      {
        columnId: "usedOnProjectId",
        kind: "idMulti",
        placeholder: "Filter by related used on projects id...",
        urlOnly: true,
      },
      {
        columnId: "usedOnProjectPresenceFilter",
        kind: "presence",
        placeholder: "Filter related used on projects presence...",
        urlOnly: true,
      },
      {
        columnId: "related:product.purchases",
        field: "purchaseId",
        urlKey: "related-purchase",
        kind: "idMulti",
        placeholder: "Filter by purchase...",
        optionsKey: "productPurchases",
        brandRef: { entity: "purchase", kind: "id" },
        nullable: { field: "purchasePresenceFilter", label: "purchase" },
      },
      {
        columnId: "related:product.expenses",
        field: "expenseSearch",
        urlKey: "related-expense",
        kind: "text",
        placeholder: "Search related expenses...",
      },
      {
        columnId: "expenseId",
        kind: "idMulti",
        placeholder: "Filter by related expenses id...",
        urlOnly: true,
      },
      {
        columnId: "expensePresenceFilter",
        kind: "presence",
        placeholder: "Filter related expenses presence...",
        urlOnly: true,
      },
      {
        columnId: "related:product.inventory",
        field: "relatedInventorySearch",
        urlKey: "related-relatedInventory",
        kind: "text",
        placeholder: "Search related inventory...",
      },
      {
        columnId: "relatedInventoryId",
        kind: "idMulti",
        placeholder: "Filter by related inventory id...",
        urlOnly: true,
      },
      {
        columnId: "relatedInventoryPresenceFilter",
        kind: "presence",
        placeholder: "Filter related inventory presence...",
        urlOnly: true,
      },
      {
        columnId: "related:product.wishes",
        field: "wishSearch",
        urlKey: "related-wish",
        kind: "text",
        placeholder: "Search related wishlist candidates...",
      },
      {
        columnId: "wishId",
        kind: "idMulti",
        placeholder: "Filter by related wishlist candidates id...",
        urlOnly: true,
      },
      {
        columnId: "wishPresenceFilter",
        kind: "presence",
        placeholder: "Filter related wishlist candidates presence...",
        urlOnly: true,
      },
      {
        columnId: "related:product.tasks",
        kind: "range",
        placeholder: "Filter tasks...",
        options: [
          { value: "has", label: "Has task", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "open", label: "Has open task" },
          {
            value: "not_started",
            label: "Not started",
            color: "var(--chart-neutral)",
          },
          { value: "later", label: "Later", color: "var(--chart-2)" },
          {
            value: "in_progress",
            label: "In progress",
            color: "var(--chart-1)",
          },
          {
            value: "blocked",
            label: "Blocked",
            color: "var(--chart-negative)",
          },
          { value: "done", label: "Done", color: "var(--chart-positive)" },
          { value: "overdue", label: "Overdue" },
          { value: "week", label: "Due this week" },
          { value: "30d", label: "Due in 30 days" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveProductTaskFilter",
        },
      },
      {
        columnId: "taskId",
        kind: "idMulti",
        placeholder: "Filter by related tasks id...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "ingredient",
      label: "Ingredient",
      target: "ingredient",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Product.ingredientId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Product.ingredientId", direction: "incoming" }],
      },
    },
    {
      key: "project-uses",
      label: "Used on projects",
      target: "project",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ProjectToolUsage.productId", direction: "incoming" },
          { edge: "ProjectToolUsage.projectId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "ProjectToolUsage.projectId", direction: "incoming" },
          { edge: "ProjectToolUsage.productId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "vendors",
      label: "Vendors",
      target: "vendor",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.productId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "outgoing" },
          { edge: "Purchase.vendorId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Purchase.vendorId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "incoming" },
          { edge: "Expense.productId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "purchased-projects",
      label: "Projects",
      target: "project",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.productId", direction: "incoming" },
          { edge: "Expense.projectId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Expense.projectId", direction: "incoming" },
          { edge: "Expense.productId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "purchases",
      label: "Purchases",
      target: "purchase",
      cardinality: "many",
      sourceKey: "expense",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.productId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Expense.purchaseId", direction: "incoming" },
          { edge: "Expense.productId", direction: "outgoing" },
        ],
      },
      sources: [
        {
          key: "explicit",
          label: "Explicit purchase link",
          provenance: {
            kind: "local-path",
            steps: [
              { edge: "PurchaseProduct.productId", direction: "incoming" },
              {
                edge: "PurchaseProduct.purchaseId",
                direction: "outgoing",
              },
            ],
          },
          inverse: {
            steps: [
              { edge: "PurchaseProduct.purchaseId", direction: "incoming" },
              { edge: "PurchaseProduct.productId", direction: "outgoing" },
            ],
          },
        },
      ],
    },
    {
      key: "expenses",
      label: "Expenses",
      target: "expense",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.productId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "Expense.productId", direction: "outgoing" }],
      },
    },
    {
      key: "inventory",
      label: "Inventory",
      target: "inventory",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "InventoryEntry.productId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "InventoryEntry.productId", direction: "outgoing" }],
      },
    },
    {
      key: "tasks",
      label: "Tasks",
      target: "task",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Task.subjectProductId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "Task.subjectProductId", direction: "outgoing" }],
      },
    },
    {
      key: "wishes",
      label: "Wishlist candidates",
      target: "wish",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "WishCandidate.productId", direction: "incoming" },
          { edge: "WishCandidate.wishId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "WishCandidate.wishId", direction: "incoming" },
          { edge: "WishCandidate.productId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "locations",
      label: "Serving as locations",
      target: "location",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Location.productId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "Location.productId", direction: "outgoing" }],
      },
    },
    {
      key: "images",
      label: "Images",
      target: "image",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ProductImage.productId", direction: "incoming" },
          { edge: "ProductImage.imageId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "ProductImage.imageId", direction: "incoming" },
          { edge: "ProductImage.productId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "components",
      label: "Components",
      target: "product",
      cardinality: "many",
      sourceKey: "explicit",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ProductComponent.parentProductId", direction: "incoming" },
          {
            edge: "ProductComponent.componentProductId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "ProductComponent.componentProductId",
            direction: "incoming",
          },
          { edge: "ProductComponent.parentProductId", direction: "outgoing" },
        ],
      },
      mutation: {
        source: "explicit",
        itemSchema: {
          module: "@cubby/schemas/common",
          export: "productComponentRelationItemSchema",
        },
        adapter: {
          module: "~/server/repo/product-components",
          export: "productComponentsRelationAdapter",
        },
        audiences: ["browser", "mcp"],
      },
    },
    {
      key: "containing-kits",
      label: "Containing kits",
      target: "product",
      cardinality: "many",
      sourceKey: "explicit",
      provenance: {
        kind: "local-path",
        steps: [
          {
            edge: "ProductComponent.componentProductId",
            direction: "incoming",
          },
          { edge: "ProductComponent.parentProductId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "ProductComponent.parentProductId", direction: "incoming" },
          {
            edge: "ProductComponent.componentProductId",
            direction: "outgoing",
          },
        ],
      },
    },
    {
      key: "usda-food",
      label: "USDA food",
      target: "usda-food",
      cardinality: "one",
      provenance: {
        kind: "external",
        system: "usda-api",
        sourceColumns: ["ProductExternalId.externalId", "Product.fdc_id"],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: true,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: { fields: ["stockTracked"] },
    merge: true,
    operationOwners: { delete: "kernel", merge: "kernel" },
    mcp: [
      "get",
      "list",
      "search",
      "create",
      "update",
      "delete",
      "bulkUpdate",
      "merge",
    ],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: [
      {
        kind: "semantic",
        label: "Similar meaning",
        pair: "product_to_product",
        weight: 1,
        limit: 8,
      },
      {
        kind: "scalarOverlap",
        label: "Shared tag",
        pair: "product_to_product",
        column: "Product.tags",
        popularityCap: 24,
        scoring: "displayOnly",
      },
    ],
    mcpNames: { overrides: { list: "search_products" } },
    ports: {
      repository: {
        module: "~/server/repo/product/entity-adapter",
        export: "productEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
