import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "ingredient",
  names: { singular: "Ingredient", plural: "Ingredients" },
  route: { basePath: "ingredients" },
  table: "Ingredient",
  identifiers: { brand: "IngredientId", shortcode: "ING-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "identity",
        },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "string",
            description: "Ingredient name",
            mock: "food.ingredient",
          },
          create: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Ingredient name is required",
            description: "Ingredient name",
            mock: "food.ingredient",
          },
          update: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Ingredient name is required",
            optional: true,
            description: "New name",
            mock: "food.ingredient",
          },
        },
      },
      {
        key: "aliases",
        kind: "text-array",
        nullable: false,
        label: "Aliases",
        description: null,
        readKey: "aliases",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "array",
            item: { kind: "string" },
            description: "Alternate names for this ingredient",
          },
          create: {
            kind: "array",
            item: { kind: "string" },
            defaultValue: [],
            description: "Alternate names for this ingredient",
          },
          update: {
            kind: "array",
            item: { kind: "string" },
            optional: true,
            description: "New aliases (replaces existing list)",
            descriptionAfter: true,
          },
        },
      },
      {
        key: "naKinds",
        kind: "text-array",
        nullable: false,
        label: "Enrichment exclusions",
        description: null,
        readKey: "naKinds",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: { module: "@cubby/schemas/problems", export: "baseKind" },
            },
          },
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: { module: "@cubby/schemas/problems", export: "baseKind" },
            },
            optional: true,
            defaultValue: [],
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: { module: "@cubby/schemas/problems", export: "baseKind" },
            },
            optional: true,
          },
        },
      },
      {
        key: "usuallyOnHand",
        kind: "boolean",
        nullable: false,
        label: "Usually on hand",
        description:
          "Assume I have enough for recipe planning. Recorded inventory stays separate.",
        readKey: "usuallyOnHand",
        reference: null,
        control: { kind: "checkbox", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "boolean" },
          create: { kind: "boolean", optional: true, defaultValue: false },
          update: { kind: "boolean", optional: true },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ingredientShortcode",
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "recipeId",
        kind: "identifier",
        nullable: true,
        label: "Recipe ID",
        description: null,
        readKey: null,
        reference: { entity: "recipe", multiple: false },
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:IngredientId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "aliases",
        column: "aliases",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "naKinds",
        column: "naKinds",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "usuallyOnHand",
        column: "usuallyOnHand",
        kind: "boolean",
        nullable: false,
        default: "literal",
        defaultValue: false,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "recipeId",
        column: "recipeId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "recipe",
        specialized: null,
      },
    ],
    create: ["name", "aliases", "naKinds", "usuallyOnHand"],
    update: ["naKinds", "usuallyOnHand", "name", "aliases"],
    bulk: ["usuallyOnHand"],
    audit: ["name", "aliases", "naKinds", "usuallyOnHand"],
    output: [
      "id",
      "name",
      "aliases",
      "naKinds",
      "usuallyOnHand",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientCreateInput",
    },
    update: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientUpdateData",
    },
    output: { module: "@cubby/schemas/ingredient", export: "ingredientOut" },
    list: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientListItemOut",
    },
    detail: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientWithFoodOut",
    },
    mcpList: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientListItemMcpEntityOut",
    },
    mcpDetail: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientWithFoodMcpEntityOut",
    },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/ingredient",
      export: "ingredientFilterFields",
    },
    descriptors: [
      {
        columnId: "name",
        field: "nameFilter",
        kind: "text",
        placeholder: "Filter by ingredient name...",
        deriveSchema: true,
        schemaDescription: "Filter by ingredient name (substring)",
      },
      {
        columnId: "product",
        field: "productPresenceFilter",
        kind: "presence",
        placeholder: "Filter product...",
        options: [
          { value: "has", label: "Has product", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "usuallyOnHand",
        field: "usuallyOnHand",
        kind: "boolean",
        placeholder: "Filter pantry staples...",
        deriveSchema: true,
        schemaDescription: "Filter by ingredients usually kept on hand",
        options: [
          { value: "true", label: "Usually on hand" },
          { value: "false", label: "Not usually on hand" },
        ],
      },
      {
        columnId: "ownRecipes",
        field: "ownRecipePresenceFilter",
        kind: "presence",
        placeholder: "Filter own recipes...",
        options: [
          { value: "has", label: "Has own recipes", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "appearsInRecipes",
        field: "recipePresenceFilter",
        kind: "presence",
        placeholder: "Filter recipes...",
        options: [
          { value: "has", label: "Has recipes", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
    ],
  },
  relations: [
    {
      key: "recipe",
      label: "Recipe",
      target: "recipe",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Ingredient.recipeId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Ingredient.recipeId", direction: "incoming" }],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: { fields: ["usuallyOnHand"] },
    merge: true,
    operationOwners: { delete: "kernel", merge: "kernel" },
    mcp: [
      "get",
      "list",
      "search",
      "create",
      "update",
      "delete",
      "merge",
      "bulkUpdate",
    ],
  },
  extensions: {
    countFilter: "recipeIdNull",
    relatednessSignals: null,
    mcpNames: { overrides: { list: "search_ingredients" } },
    ports: {
      repository: {
        module: "~/server/repo/ingredient/entity-adapter",
        export: "ingredientEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
