import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "cookbook",
  names: { singular: "Cookbook", plural: "Cookbooks" },
  route: { basePath: "cookbooks" },
  table: "Cookbook",
  identifiers: { brand: "CookbookId", shortcode: "CKB-", legacy: null },
  presentation: { titleField: "book" },
  model: {
    fields: [
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "cookbookShortcode",
            },
          },
        },
      },
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "book",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string" } },
      },
      {
        key: "author",
        kind: "text-array",
        nullable: false,
        label: "Author",
        description: null,
        readKey: "author",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: { kind: "array", item: { kind: "string" } },
        },
      },
      {
        key: "subjects",
        kind: "text-array",
        nullable: false,
        label: "Subjects",
        description: null,
        readKey: "subjects",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: { kind: "array", item: { kind: "string" } },
        },
      },
      {
        key: "sourceLabel",
        kind: "text",
        nullable: false,
        label: "Source Label",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "rawJson",
        kind: "json",
        nullable: false,
        label: "Raw Json",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "coverImageId",
        kind: "identifier",
        nullable: true,
        label: "Cover Image ID",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: false },
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "productId",
        kind: "identifier",
        nullable: true,
        label: "Product ID",
        description: null,
        readKey: null,
        reference: { entity: "product", multiple: false },
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "importedAt",
        kind: "timestamp",
        nullable: false,
        label: "Imported At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "recipeCount",
        kind: "number",
        nullable: false,
        label: "Recipes",
        description: null,
        readKey: "recipeCount",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: { kind: "number", integer: true, min: 0 },
        },
      },
      {
        key: "coverUrl",
        kind: "text",
        nullable: true,
        label: "Cover",
        description: null,
        readKey: "coverUrl",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "sourceRecipeCount",
        kind: "number",
        nullable: false,
        label: "Source recipes",
        description: null,
        readKey: "sourceRecipeCount",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: {
          read: { kind: "number", integer: true, min: 0 },
        },
      },
      {
        key: "product",
        kind: "json",
        nullable: true,
        label: "Physical copy",
        description: null,
        readKey: "product",
        reference: { entity: "product", multiple: false },
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/cookbook-fields",
              export: "cookbookProductSummary",
            },
            nullable: true,
          },
        },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:CookbookId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "author",
        column: "author",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "subjects",
        column: "subjects",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "sourceLabel",
        column: "sourceLabel",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "rawJson",
        column: "rawJson",
        kind: "json",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "json:rawJson",
      },
      {
        key: "coverImageId",
        column: "coverImageId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "image",
        specialized: null,
      },
      {
        key: "productId",
        column: "productId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "product",
        specialized: null,
      },
      {
        key: "importedAt",
        column: "importedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [],
    update: [],
    bulk: [],
    audit: [],
    output: [
      "shortcode",
      "name",
      "author",
      "subjects",
      "recipeCount",
      "coverUrl",
      "sourceRecipeCount",
      "product",
    ],
  },
  fields: {
    create: null,
    update: null,
    output: { module: "@cubby/schemas/recipe", export: "cookbookSummary" },
    list: { module: "@cubby/schemas/recipe", export: "cookbookSummary" },
    detail: { module: "@cubby/schemas/recipe", export: "cookbookSummary" },
  },
  filters: { descriptors: [] },
  relations: [
    {
      key: "cover",
      label: "Cover image",
      target: "image",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Cookbook.coverImageId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Cookbook.coverImageId", direction: "incoming" }],
      },
    },
    {
      key: "product",
      label: "Product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Cookbook.productId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Cookbook.productId", direction: "incoming" }],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: true,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: false },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "workflow", merge: null },
    mcp: ["list"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: null,
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
