import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "cookbook",
  names: { singular: "Cookbook", plural: "Cookbooks" },
  route: { basePath: "cookbooks" },
  table: "Cookbook",
  identifiers: { brand: "CookbookId", shortcode: "CKB-", legacy: null },
  presentation: { titleField: "book" },
  model: {
    fields: [
      { key: "id", kind: "identifier", readKey: null },
      {
        key: "shortcode",
        kind: "text",
        readKey: "id",
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "cookbookShortcode",
            },
          },
        },
      },
      {
        key: "name",
        kind: "text",
        readKey: "book",
        display: { list: true, detail: true },
        validation: { read: { kind: "string" } },
      },
      {
        key: "author",
        kind: "text-array",
        display: { list: true, detail: true },
        validation: { read: { kind: "array", item: { kind: "string" } } },
      },
      {
        key: "subjects",
        kind: "text-array",
        display: { list: true, detail: true },
        validation: { read: { kind: "array", item: { kind: "string" } } },
      },
      { key: "sourceLabel", kind: "text", readKey: null },
      { key: "rawJson", kind: "json", readKey: null },
      {
        key: "coverImageId",
        kind: "identifier",
        nullable: true,
        label: "Cover Image ID",
        readKey: null,
        reference: { entity: "image" },
      },
      {
        key: "productId",
        kind: "identifier",
        nullable: true,
        label: "Product ID",
        readKey: null,
        reference: { entity: "product" },
      },
      { key: "importedAt", kind: "timestamp", readKey: null },
      { key: "createdAt", kind: "timestamp", readKey: null },
      { key: "updatedAt", kind: "timestamp", readKey: null },
      { key: "deletedAt", kind: "timestamp", nullable: true, readKey: null },
      {
        key: "recipeCount",
        kind: "number",
        label: "Recipes",
        display: { list: true, detail: true },
        validation: { read: { kind: "number", integer: true, min: 0 } },
      },
      {
        key: "coverUrl",
        kind: "text",
        nullable: true,
        label: "Cover",
        display: { list: true, detail: true },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "sourceRecipeCount",
        kind: "number",
        label: "Source recipes",
        display: { detail: true },
        validation: { read: { kind: "number", integer: true, min: 0 } },
      },
      {
        key: "product",
        kind: "json",
        nullable: true,
        label: "Physical copy",
        reference: { entity: "product" },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/cookbook-fields",
              export: "cookbookProductSummary",
            },
            nullable: true,
          },
        },
      },
    ],
    storage: [
      {
        key: "id",
        default: "generated",
        specialized: "primary-key:CookbookId",
      },
      { key: "shortcode", specialized: "shortcode" },
      "name",
      {
        key: "author",
        default: "literal",
        defaultValue: "'{}'::text[]",
        specialized: "text-array",
      },
      {
        key: "subjects",
        default: "literal",
        defaultValue: "'{}'::text[]",
        specialized: "text-array",
      },
      "sourceLabel",
      { key: "rawJson", specialized: "json:rawJson" },
      { key: "coverImageId", reference: "image" },
      { key: "productId", reference: "product" },
      { key: "importedAt", default: "now" },
      { key: "createdAt", default: "now" },
      { key: "updatedAt", default: "now", specialized: "updated-at" },
      "deletedAt",
    ],
    create: [],
    update: [],
    bulk: [],
    audit: [],
    output: [
      "shortcode",
      "name",
      "author",
      "subjects",
      "recipeCount",
      "coverUrl",
      "sourceRecipeCount",
      "product",
    ],
  },
  fields: {
    create: null,
    update: null,
    output: { module: "@cubby/schemas/recipe", export: "cookbookSummary" },
    list: { module: "@cubby/schemas/recipe", export: "cookbookSummary" },
    detail: { module: "@cubby/schemas/recipe", export: "cookbookSummary" },
  },
  filters: { descriptors: [] },
  relations: [
    {
      key: "cover",
      label: "Cover image",
      target: "image",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Cookbook.coverImageId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Cookbook.coverImageId", direction: "incoming" }],
      },
    },
    {
      key: "product",
      label: "Product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Cookbook.productId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Cookbook.productId", direction: "incoming" }],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: true,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: false },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "workflow", merge: null },
    mcp: ["list"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: null,
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
