import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "location",
  names: { singular: "Location", plural: "Locations" },
  route: { basePath: "locations" },
  table: "Location",
  identifiers: { brand: "LocationId", shortcode: "LOC-", legacy: "L-" },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: false },
        validation: {
          read: { kind: "string", description: "name of location" },
          create: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Location name is required",
            description: "name of location",
          },
          update: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Location name is required",
            optional: true,
            description: "name of location",
          },
        },
      },
      {
        key: "aliases",
        kind: "text-array",
        nullable: false,
        label: "Aliases",
        description: null,
        readKey: "aliases",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: false, detail: true },
        validation: {
          read: {
            kind: "array",
            item: { kind: "string" },
            defaultValue: [],
            description:
              "Alternate names for this location (searched + embedded)",
            descriptionAfter: true,
          },
          create: {
            kind: "array",
            item: { kind: "string" },
            defaultValue: [],
            description:
              "Alternate names for this location — searched alongside the name. Replaces the existing list when provided.",
            descriptionAfter: true,
          },
          update: {
            kind: "array",
            item: { kind: "string" },
            optional: true,
          },
        },
      },
      {
        key: "tags",
        kind: "text-array",
        nullable: false,
        label: "Tags",
        description: null,
        readKey: "tags",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: { list: false, detail: true },
        validation: {
          read: {
            kind: "array",
            item: { kind: "string" },
            optional: true,
            description:
              "Namespaced Collection tags assigned directly to this location",
            descriptionAfter: true,
          },
          create: {
            kind: "array",
            item: { kind: "string" },
            optional: true,
            description: "Tags assigned directly to this location",
          },
          update: {
            kind: "array",
            item: { kind: "string" },
            optional: true,
            description: "Tags assigned directly to this location",
          },
        },
      },
      {
        key: "type",
        kind: "enum",
        nullable: true,
        label: "Type",
        description: null,
        readKey: "type",
        reference: null,
        control: {
          kind: "select",
          renderer: null,
          options: null,
          section: "classification",
        },
        display: { list: true, detail: true, detailOrder: 1 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/location-fields",
              export: "locationType",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/location-fields",
              export: "locationType",
            },
            optional: true,
            nullable: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/location-fields",
              export: "locationType",
            },
            optional: true,
            nullable: true,
          },
        },
      },
      {
        key: "productId",
        kind: "identifier",
        nullable: true,
        label: "Is a",
        description: null,
        readKey: "product",
        reference: { entity: "product", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: false, detail: true, detailOrder: 2 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            optional: true,
            nullable: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            optional: true,
            nullable: true,
          },
        },
      },
      {
        key: "parentId",
        kind: "identifier",
        nullable: true,
        label: "Parent Location",
        description: null,
        readKey: null,
        reference: { entity: "location", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: false, detail: true, detailOrder: 3 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "locationShortcode",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "locationShortcode",
            },
            optional: true,
            nullable: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "locationShortcode",
            },
            optional: true,
            nullable: true,
          },
        },
      },
      {
        key: "pendingImageIds",
        kind: "identifier",
        nullable: false,
        label: "Pending Image IDs",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
          },
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "removeImageIds",
        kind: "identifier",
        nullable: false,
        label: "Remove Image IDs",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "imageOrder",
        kind: "text",
        nullable: false,
        label: "Image Order",
        description: null,
        readKey: null,
        reference: null,
        control: {
          kind: "specialized",
          renderer: "image-order",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: true, detailOrder: 0 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "locationShortcode",
            },
          },
        },
      },
      {
        key: "product",
        kind: "json",
        nullable: true,
        label: "Product",
        description: null,
        readKey: "product",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/location-fields",
              export: "locationIdentityProductOut",
            },
            nullable: true,
          },
        },
      },
      {
        key: "lastBulkInventory",
        kind: "timestamp",
        nullable: true,
        label: "Last recount",
        description: null,
        readKey: "lastBulkInventory",
        reference: null,
        control: null,
        display: { list: true, detail: true, detailOrder: 4 },
        validation: { read: { kind: "timestamp", nullable: true } },
      },
      {
        key: "aiDescription",
        kind: "text",
        nullable: true,
        label: "Ai Description",
        description: null,
        readKey: "aiDescription",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "images",
        kind: "json",
        nullable: false,
        label: "Images",
        description: null,
        readKey: "images",
        reference: null,
        control: null,
        display: { list: true, detail: true, columnId: "image" },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: { module: "@cubby/schemas/image", export: "imageOut" },
            },
          },
        },
      },
      {
        key: "valuation",
        kind: "json",
        nullable: true,
        label: "Valuation",
        description: null,
        readKey: "valuation",
        reference: null,
        control: null,
        display: { list: true, detail: true, columnId: "valuation" },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/location-fields",
              export: "locationValuation",
            },
            nullable: true,
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:LocationId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "aliases",
        column: "aliases",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "tags",
        column: "tags",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "lastBulkInventory",
        column: "lastBulkInventory",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "parentId",
        column: "parentId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "location",
        specialized: null,
      },
      {
        key: "productId",
        column: "productId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "product",
        specialized: null,
      },
      {
        key: "type",
        column: "type",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:type",
      },
      {
        key: "aiDescription",
        column: "aiDescription",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "valuation",
        column: "valuation",
        kind: "json",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "json:valuation",
      },
    ],
    create: [
      "name",
      "aliases",
      "tags",
      "type",
      "productId",
      "parentId",
      "pendingImageIds",
    ],
    update: [
      "name",
      "aliases",
      "tags",
      "type",
      "productId",
      "parentId",
      "pendingImageIds",
      "removeImageIds",
      "imageOrder",
    ],
    bulk: ["parentId"],
    audit: ["name", "aliases", "tags", "type", "parentId"],
    output: [
      "id",
      "name",
      "aliases",
      "tags",
      "type",
      "product",
      "lastBulkInventory",
      "aiDescription",
      "images",
      "valuation",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/location",
      export: "locationCreateInput",
    },
    update: { module: "@cubby/schemas/location", export: "locationUpdateData" },
    output: { module: "@cubby/schemas/location", export: "locationOut" },
    list: { module: "@cubby/schemas/location", export: "locationListItemOut" },
    detail: { module: "@cubby/schemas/location", export: "infLocation" },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/location",
      export: "locationFilterFields",
    },
    descriptors: [
      {
        columnId: "image",
        field: "imagePresenceFilter",
        kind: "presence",
        placeholder: "Filter images...",
        options: [
          { value: "has", label: "Has image", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "lastBulkInventory",
        kind: "range",
        placeholder: "Filter recounts...",
        options: [
          { value: "30", label: "Not counted in 30 days" },
          { value: "60", label: "Not counted in 60 days" },
          { value: "90", label: "Not counted in 90 days" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveRecountAge",
        },
      },
      {
        columnId: "children",
        field: "childPresenceFilter",
        kind: "presence",
        placeholder: "Filter children...",
        options: [
          { value: "has", label: "Has children", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "aiDescription",
        field: "aiDescriptionPresenceFilter",
        kind: "presence",
        placeholder: "Filter descriptions...",
        options: [
          { value: "has", label: "Has description", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "name",
        field: "nameFilter",
        kind: "text",
        placeholder: "Filter by location name...",
        deriveSchema: true,
        schemaDescription: "Filter by location name (substring)",
      },
      {
        columnId: "type",
        field: "itemTypeFilter",
        kind: "multiselect",
        placeholder: "Filter by type...",
        deriveSchema: true,
        optionsRef: {
          module: "~/app/_components/locations/location-icons",
          export: "locationTypeOptionsWithTheme",
        },
      },
      {
        columnId: "product",
        field: "productId",
        kind: "idMulti",
        placeholder: "Filter product...",
        optionsKey: "locationProducts",
        brandRef: { entity: "product", kind: "id" },
        nullable: { field: "productPresenceFilter", label: "product" },
      },
      {
        columnId: "parent",
        field: "parentId",
        kind: "idMulti",
        placeholder: "Filter parent...",
        optionsKey: "parentLocation",
        brandRef: { entity: "location", kind: "id" },
        nullable: { field: "parentPresenceFilter", label: "parent" },
      },
      {
        columnId: "inventoryEntries",
        kind: "range",
        placeholder: "Filter inventory...",
        options: [
          { value: "has", label: "Has items", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "1", label: "1+ items" },
          { value: "2", label: "2+ items" },
          { value: "5", label: "5+ items" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveLocationItems",
        },
      },
      {
        columnId: "valuation",
        kind: "range",
        placeholder: "Filter valuation...",
        options: [
          { value: "positive", label: "Positive basis" },
          { value: "zero", label: "Zero basis" },
          { value: "negative", label: "Credit / negative" },
          { value: "gte100", label: "$100 and up" },
          { value: "gte500", label: "$500 and up" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveLocationValuation",
        },
      },
      {
        columnId: "related:location.ingredients",
        field: "ingredientSearch",
        urlKey: "related-ingredient",
        kind: "text",
        placeholder: "Search related ingredients...",
      },
      {
        columnId: "ingredientId",
        kind: "idMulti",
        placeholder: "Filter by related ingredients id...",
        urlOnly: true,
      },
      {
        columnId: "ingredientPresenceFilter",
        kind: "presence",
        placeholder: "Filter related ingredients presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "parent",
      label: "Parent location",
      target: "location",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Location.parentId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Location.parentId", direction: "incoming" }],
      },
    },
    {
      key: "product",
      label: "Product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Location.productId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Location.productId", direction: "incoming" }],
      },
    },
    {
      key: "ingredients",
      label: "Ingredients",
      target: "ingredient",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "InventoryEntry.locationId", direction: "incoming" },
          { edge: "InventoryEntry.productId", direction: "outgoing" },
          { edge: "Product.ingredientId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Product.ingredientId", direction: "incoming" },
          { edge: "InventoryEntry.productId", direction: "incoming" },
          { edge: "InventoryEntry.locationId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "images",
      label: "Images",
      target: "image",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "LocationImage.locationId", direction: "incoming" },
          { edge: "LocationImage.imageId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "LocationImage.imageId", direction: "incoming" },
          { edge: "LocationImage.locationId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: true,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: { fields: ["parentId"] },
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete", "bulkUpdate"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/location/entity-adapter",
        export: "locationEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
