import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "meal",
  names: { singular: "Meal", plural: "Meals" },
  route: { basePath: "meals" },
  table: "Meal",
  identifiers: { brand: "MealId", shortcode: "MEL-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "date",
        kind: "date",
        nullable: false,
        label: "Date",
        description: null,
        readKey: "date",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-shared",
              export: "mealDate",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-shared",
              export: "mealDate",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-shared",
              export: "mealDate",
            },
            optional: true,
          },
        },
      },
      {
        key: "name",
        kind: "text",
        nullable: true,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, optional: true },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "sortOrder",
        kind: "number",
        nullable: true,
        label: "Sort Order",
        description: null,
        readKey: "sortOrder",
        reference: null,
        control: {
          kind: "number",
          renderer: null,
          options: null,
          section: "ordering",
        },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "number", integer: true, nullable: true },
          create: {
            kind: "number",
            integer: true,
            nullable: true,
            optional: true,
          },
          update: {
            kind: "number",
            integer: true,
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "mealType",
        kind: "enum",
        nullable: true,
        label: "Meal Type",
        description: null,
        readKey: "mealType",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-classification",
              export: "mealTypeSchema",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-classification",
              export: "mealTypeSchema",
            },
            nullable: true,
            optional: true,
            description:
              "Which eating occasion of the day this is. Null when unslotted; the planning calendar orders a day's meals by it.",
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-classification",
              export: "mealTypeSchema",
            },
            nullable: true,
            optional: true,
            description:
              "Which eating occasion of the day this is. Null when unslotted; the planning calendar orders a day's meals by it.",
          },
        },
      },
      {
        key: "mealKind",
        kind: "enum",
        nullable: false,
        label: "Meal Kind",
        description: null,
        readKey: "mealKind",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-classification",
              export: "mealKindSchema",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-classification",
              export: "mealKindSchema",
            },
            optional: true,
            description:
              "How the meal is eaten. Defaults to `cooked`. Use `eating_out`/`takeout` for a placeholder meal that intentionally has no recipes; only `cooked` meals feed the shopping list.",
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-classification",
              export: "mealKindSchema",
            },
            optional: true,
            description:
              "How the meal is eaten. Defaults to `cooked`. Use `eating_out`/`takeout` for a placeholder meal that intentionally has no recipes; only `cooked` meals feed the shopping list.",
          },
        },
      },
      {
        key: "recipes",
        kind: "json",
        nullable: false,
        label: "Recipes",
        description: null,
        readKey: "recipes",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: false, detail: true },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/meal-fields",
                export: "mealRecipeOut",
              },
            },
          },
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/meal-fields",
                export: "mealRecipeInput",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "mealShortcode",
            },
          },
        },
      },
      {
        key: "totals",
        kind: "json",
        nullable: false,
        label: "Totals",
        description: null,
        readKey: "totals",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/meal-fields",
              export: "mealTotals",
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:MealId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "date",
        column: "date",
        kind: "date",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "sortOrder",
        column: "sortOrder",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "mealType",
        column: "mealType",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:mealType",
      },
      {
        key: "mealKind",
        column: "mealKind",
        kind: "enum",
        nullable: false,
        default: "literal",
        defaultValue: "'cooked'",
        reference: null,
        specialized: "enum:mealKind",
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: ["date", "name", "sortOrder", "mealType", "mealKind", "recipes"],
    update: ["date", "name", "sortOrder", "mealType", "mealKind"],
    bulk: [],
    audit: [],
    output: [
      "id",
      "date",
      "name",
      "sortOrder",
      "mealType",
      "mealKind",
      "recipes",
      "totals",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/meal", export: "mealCreateInput" },
    update: { module: "@cubby/schemas/meal", export: "mealUpdateData" },
    output: { module: "@cubby/schemas/meal", export: "mealOut" },
    mcpOutput: {
      module: "@cubby/schemas/meal",
      export: "mealMcpEntityOut",
    },
    mcpList: {
      module: "@cubby/schemas/meal",
      export: "mealMcpEntityOut",
    },
    mcpDetail: {
      module: "@cubby/schemas/meal",
      export: "mealMcpEntityOut",
    },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/meal", export: "mealFilterFields" },
    descriptors: [
      {
        columnId: "mealType",
        kind: "multiselect",
        placeholder: "Filter by meal type...",
        deriveSchema: true,
        options: [
          { value: "breakfast", label: "Breakfast" },
          { value: "brunch", label: "Brunch" },
          { value: "lunch", label: "Lunch" },
          { value: "snack", label: "Snack" },
          { value: "dinner", label: "Dinner" },
          { value: "dessert", label: "Dessert" },
        ],
        nullable: { field: "mealTypePresenceFilter", label: "meal type" },
      },
      {
        columnId: "mealKind",
        kind: "multiselect",
        placeholder: "Filter by kind...",
        deriveSchema: true,
        options: [
          { value: "cooked", label: "Cooked", color: "var(--slate)" },
          { value: "leftovers", label: "Leftovers", color: "var(--slate)" },
          { value: "eating_out", label: "Eating out", color: "var(--primary)" },
          {
            value: "takeout",
            label: "Takeout / delivery",
            color: "var(--primary)",
          },
          { value: "other", label: "Other", color: "var(--slate)" },
        ],
      },
      {
        columnId: "recipeCostCoverage",
        field: "recipeCostCoverage",
        kind: "select",
        placeholder: "Filter recipe cost coverage...",
        options: [{ value: "understated", label: "Understated" }],
      },
      {
        columnId: "related:meal.recipes",
        field: "recipePresenceFilter",
        urlKey: "related-recipe",
        kind: "presence",
        placeholder: "Filter recipes...",
        options: [
          { value: "has", label: "Has recipes", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "recipeId",
        kind: "idMulti",
        placeholder: "Filter by related recipe id...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "recipes",
      label: "Recipes",
      target: "recipe",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "MealRecipe.mealId", direction: "incoming" },
          { edge: "MealRecipe.recipeId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "MealRecipe.recipeId", direction: "incoming" },
          { edge: "MealRecipe.mealId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/meal/entity-adapter",
        export: "mealEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
