import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "ledgerParty",
  names: { singular: "Ledger Party", plural: "Ledger Parties" },
  route: { basePath: "ledger-parties" },
  table: "LedgerParty",
  identifiers: { brand: "LedgerPartyId", shortcode: "LPY-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string" },
          create: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Ledger party name is required",
          },
          update: {
            kind: "string",
            trim: true,
            min: 1,
            minMessage: "Ledger party name is required",
            optional: true,
          },
        },
      },
      {
        key: "kind",
        kind: "enum",
        nullable: false,
        label: "Kind",
        description: null,
        readKey: "kind",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerPartyKind",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerPartyKind",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerPartyKind",
            },
            optional: true,
          },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: { kind: "textarea", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:LedgerPartyId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "kind",
        column: "kind",
        kind: "enum",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:kind",
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: ["name", "kind", "notes"],
    update: ["name", "kind", "notes"],
    bulk: [],
    audit: ["name", "kind", "notes"],
    output: ["id", "name", "kind", "notes", "createdAt", "updatedAt"],
  },
  fields: {
    create: {
      module: "@cubby/schemas/ledger-party",
      export: "ledgerPartyCreateInput",
    },
    update: {
      module: "@cubby/schemas/ledger-party",
      export: "ledgerPartyUpdateData",
    },
    output: { module: "@cubby/schemas/ledger-party", export: "ledgerPartyOut" },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/ledger-party",
      export: "ledgerPartyFilterFields",
    },
    descriptors: [
      {
        columnId: "name",
        field: "search",
        urlKey: "q",
        kind: "text",
        placeholder: "Search ledger parties...",
        deriveSchema: true,
      },
      {
        columnId: "kind",
        kind: "multiselect",
        placeholder: "Filter by kind...",
        deriveSchema: true,
        options: [
          { value: "member", label: "Member" },
          { value: "guest", label: "Guest" },
          { value: "household", label: "Household" },
        ],
      },
    ],
  },
  relations: [
    {
      key: "expenses",
      label: "Attributed expenses",
      target: "expense",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ExpenseAttribution.ledgerPartyId", direction: "incoming" },
          { edge: "ExpenseAttribution.expenseId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "ExpenseAttribution.expenseId", direction: "incoming" },
          { edge: "ExpenseAttribution.ledgerPartyId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "financial-accounts",
      label: "Financial accounts",
      target: "financialAccount",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "FinancialAccount.ledgerPartyId", direction: "incoming" },
        ],
      },
      inverse: {
        steps: [
          { edge: "FinancialAccount.ledgerPartyId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "outgoing-transfers",
      label: "Outgoing transfers",
      target: "ledgerTransfer",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "LedgerTransfer.fromPartyId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "LedgerTransfer.fromPartyId", direction: "outgoing" }],
      },
    },
    {
      key: "incoming-transfers",
      label: "Incoming transfers",
      target: "ledgerTransfer",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "LedgerTransfer.toPartyId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "LedgerTransfer.toPartyId", direction: "outgoing" }],
      },
    },
  ],
  search: { enabled: false },
  capabilities: {
    auditable: true,
    images: false,
    countable: false,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: true,
    operationOwners: { delete: "kernel", merge: "kernel" },
    mcp: ["get", "list", "create", "update", "delete", "merge"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: { plural: "ledger_parties" },
    ports: {
      repository: {
        module: "~/server/repo/ledger-party.entity-adapter",
        export: "ledgerPartyEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: { projection: null, semanticText: null, dependentRefresh: null },
    },
  },
});
