import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "ledgerTransfer",
  names: { singular: "Ledger Transfer", plural: "Transfers" },
  route: { basePath: "ledger-transfers" },
  table: "LedgerTransfer",
  identifiers: { brand: "LedgerTransferId", shortcode: "LTR-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "fromPartyId",
        kind: "identifier",
        nullable: false,
        label: "From",
        description: null,
        readKey: "fromPartyId",
        reference: { entity: "ledgerParty", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
            optional: true,
          },
        },
      },
      {
        key: "toPartyId",
        kind: "identifier",
        nullable: false,
        label: "To",
        description: null,
        readKey: "toPartyId",
        reference: { entity: "ledgerParty", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
            optional: true,
          },
        },
      },
      {
        key: "fromPartyName",
        kind: "text",
        nullable: false,
        label: "From Party Name",
        description: null,
        readKey: "fromPartyName",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string" }, create: null, update: null },
      },
      {
        key: "toPartyName",
        kind: "text",
        nullable: false,
        label: "To Party Name",
        description: null,
        readKey: "toPartyName",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string" }, create: null, update: null },
      },
      {
        key: "amount",
        kind: "number",
        nullable: false,
        label: "Amount",
        description: null,
        readKey: "amount",
        reference: null,
        control: { kind: "number", renderer: "money", options: null },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerTransferAmount",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerTransferAmount",
            },
            optional: true,
          },
        },
      },
      {
        key: "date",
        kind: "date",
        nullable: false,
        label: "Date",
        description: null,
        readKey: "date",
        reference: null,
        control: { kind: "date", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            optional: true,
          },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: { kind: "textarea", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "sourceClaims",
        kind: "json",
        nullable: false,
        label: "Source Claims",
        description: null,
        readKey: "sourceClaims",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerSourceClaimsOut",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerSourceClaims",
            },
            nullable: true,
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerSourceClaims",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "evidenceTransactionIds",
        kind: "identifier",
        nullable: false,
        label: "Evidence",
        description: null,
        readKey: "evidenceTransactionIds",
        reference: { entity: "financialTransaction", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: true, columnId: "evidenceCount", detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "financialTransactionShortcode",
              },
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerTransferEvidenceTransactionIds",
            },
            nullable: true,
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerTransferEvidenceTransactionIds",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerTransferShortcode",
            },
          },
        },
      },
      {
        key: "classification",
        kind: "json",
        nullable: false,
        label: "Classification",
        description: null,
        readKey: "classification",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerTransferClassification",
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:LedgerTransferId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "fromPartyId",
        column: "fromPartyId",
        kind: "identifier",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: "ledgerParty",
        specialized: null,
      },
      {
        key: "toPartyId",
        column: "toPartyId",
        kind: "identifier",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: "ledgerParty",
        specialized: null,
      },
      {
        key: "amount",
        column: "amount",
        kind: "number",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "double-precision",
      },
      {
        key: "date",
        column: "date",
        kind: "date",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [
      "fromPartyId",
      "toPartyId",
      "amount",
      "date",
      "notes",
      "sourceClaims",
      "evidenceTransactionIds",
    ],
    update: [
      "fromPartyId",
      "toPartyId",
      "amount",
      "date",
      "notes",
      "sourceClaims",
      "evidenceTransactionIds",
    ],
    bulk: [],
    audit: [
      "fromPartyId",
      "toPartyId",
      "amount",
      "date",
      "notes",
      "sourceClaims",
      "evidenceTransactionIds",
    ],
    output: [
      "id",
      "fromPartyId",
      "toPartyId",
      "fromPartyName",
      "toPartyName",
      "amount",
      "date",
      "notes",
      "classification",
      "sourceClaims",
      "evidenceTransactionIds",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/ledger-transfer",
      export: "ledgerTransferCreateInput",
    },
    update: {
      module: "@cubby/schemas/ledger-transfer",
      export: "ledgerTransferUpdateData",
    },
    output: {
      module: "@cubby/schemas/ledger-transfer",
      export: "ledgerTransferOut",
    },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/ledger-transfer",
      export: "ledgerTransferFilterFields",
    },
    descriptors: [
      {
        columnId: "fromPartyId",
        kind: "idMulti",
        placeholder: "Filter by from party...",
        brandRef: { entity: "ledgerParty", kind: "id" },
        urlOnly: true,
      },
      {
        columnId: "toPartyId",
        kind: "idMulti",
        placeholder: "Filter by to party...",
        brandRef: { entity: "ledgerParty", kind: "id" },
        urlOnly: true,
      },
      {
        columnId: "dateFrom",
        kind: "text",
        placeholder: "Transfer date from...",
        urlOnly: true,
      },
      {
        columnId: "dateTo",
        kind: "text",
        placeholder: "Transfer date to...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "from-party",
      label: "From party",
      target: "ledgerParty",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "LedgerTransfer.fromPartyId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "LedgerTransfer.fromPartyId", direction: "incoming" }],
      },
    },
    {
      key: "to-party",
      label: "To party",
      target: "ledgerParty",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "LedgerTransfer.toPartyId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "LedgerTransfer.toPartyId", direction: "incoming" }],
      },
    },
    {
      key: "evidence-transactions",
      label: "Evidence transactions",
      target: "financialTransaction",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          {
            edge: "FinancialTransaction.ledgerTransferId",
            direction: "incoming",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "FinancialTransaction.ledgerTransferId",
            direction: "outgoing",
          },
        ],
      },
    },
  ],
  search: { enabled: false },
  capabilities: {
    auditable: true,
    images: false,
    countable: false,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/ledger-transfer.entity-adapter",
        export: "ledgerTransferEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: { projection: null, semanticText: null, dependentRefresh: null },
    },
  },
});
