import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "project",
  names: { singular: "Project", plural: "Projects" },
  route: { basePath: "projects" },
  table: "Project",
  identifiers: { brand: "ProjectId", shortcode: "PRJ-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: {
          list: true,
          detail: true,
          detailOrder: 10,
          detailSection: "overview",
          standard: "name",
        },
        validation: {
          read: { kind: "string", min: 1 },
          create: { kind: "string", min: 1 },
          update: { kind: "string", min: 1, optional: true },
        },
      },
      {
        key: "status",
        kind: "enum",
        nullable: false,
        label: "Status",
        description: null,
        readKey: "status",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: {
          list: true,
          detail: true,
          detailOrder: 30,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "projectStatusSchema",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "projectStatusSchema",
            },
            defaultValue: "planning",
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "projectStatusSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "kind",
        kind: "enum",
        nullable: true,
        label: "Kind",
        description: null,
        readKey: "kind",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: {
          list: true,
          detail: true,
          detailOrder: 40,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "projectKindSchema",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "projectKindSchema",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "projectKindSchema",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "locations",
        kind: "text-array",
        nullable: false,
        label: "Locations",
        description: null,
        readKey: "locations",
        reference: null,
        control: { kind: "specialized", renderer: "tag-list", options: null },
        display: {
          list: false,
          detail: true,
          detailOrder: 90,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "array",
            item: { kind: "string" },
            description: "House/site names, free-form",
          },
          create: { kind: "array", item: { kind: "string" }, defaultValue: [] },
          update: { kind: "array", item: { kind: "string" }, optional: true },
        },
      },
      {
        key: "costEstimate",
        kind: "number",
        nullable: true,
        label: "Estimate",
        description: null,
        readKey: "costEstimate",
        reference: null,
        control: { kind: "number", renderer: "money", options: null },
        display: {
          list: true,
          detail: true,
          detailOrder: 70,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "positiveMoneyNullable",
            },
            nullable: true,
            description: "Budget estimate in dollars",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "positiveMoneyNullable",
            },
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "positiveMoneyNullable",
            },
            optional: true,
          },
        },
      },
      {
        key: "parentProjectId",
        kind: "identifier",
        nullable: true,
        label: "Parent project",
        description: null,
        readKey: "parentProjectId",
        reference: { entity: "project", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 80,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "startDate",
        kind: "date",
        nullable: true,
        label: "Start date",
        description: null,
        readKey: "startDate",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 50,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            description: "Manual start override; usually null",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "endDate",
        kind: "date",
        nullable: true,
        label: "End date",
        description: null,
        readKey: "endDate",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 60,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            description: "Manual end override; usually null",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "icon",
        kind: "text",
        nullable: true,
        label: "Icon",
        description: null,
        readKey: "icon",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "details",
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 20,
          detailSection: "overview",
        },
        validation: {
          read: {
            kind: "string",
            nullable: true,
            description: "Emoji shown next to the name",
          },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: {
          kind: "textarea",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "string",
            nullable: true,
            description: "Freeform markdown",
          },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "googleDriveFolderUrl",
        kind: "text",
        nullable: true,
        label: "Google Drive folder",
        description: null,
        readKey: "googleDriveFolderUrl",
        reference: null,
        control: {
          kind: "text",
          renderer: "url",
          options: null,
          section: "details",
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 10,
          detailSection: "resources",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "googleDriveFolderUrl",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "googleDriveFolderUrl",
            },
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "googleDriveFolderUrl",
            },
            optional: true,
          },
        },
      },
      {
        key: "notionPageUrl",
        kind: "text",
        nullable: true,
        label: "Notion page",
        description: null,
        readKey: "notionPageUrl",
        reference: null,
        control: {
          kind: "text",
          renderer: "url",
          options: null,
          section: "details",
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 20,
          detailSection: "resources",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "notionPageUrl",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "notionPageUrl",
            },
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-fields",
              export: "notionPageUrl",
            },
            optional: true,
          },
        },
      },
      {
        key: "blockedByIds",
        kind: "identifier",
        nullable: false,
        label: "Blocked By IDs",
        description: null,
        readKey: "blockedByIds",
        reference: { entity: "task", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "projectShortcode",
              },
            },
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "projectShortcode",
              },
            },
            optional: true,
            description: "Full replacement set of blocking-project ids",
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
          },
        },
      },
      {
        key: "parentProjectName",
        kind: "text",
        nullable: true,
        label: "Parent Project Name",
        description: null,
        readKey: "parentProjectName",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "childProjectIds",
        kind: "identifier",
        nullable: false,
        label: "Child Project IDs",
        description: null,
        readKey: "childProjectIds",
        reference: { entity: "project", multiple: true },
        control: null,
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "projectShortcode",
              },
            },
          },
        },
      },
      {
        key: "blockingIds",
        kind: "identifier",
        nullable: false,
        label: "Blocking IDs",
        description: null,
        readKey: "blockingIds",
        reference: { entity: "task", multiple: true },
        control: null,
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "projectShortcode",
              },
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Last updated",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: {
          list: false,
          detail: true,
          detailOrder: 100,
          detailSection: "overview",
        },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "rollup",
        kind: "json",
        nullable: false,
        label: "Rollup",
        description: null,
        readKey: "rollup",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-output-fields",
              export: "projectRollup",
            },
          },
        },
      },
      {
        key: "dates",
        kind: "json",
        nullable: false,
        label: "Dates",
        description: null,
        readKey: "dates",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/project-output-fields",
              export: "projectDateWindow",
            },
          },
        },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "notionPageId",
        kind: "text",
        nullable: true,
        label: "Notion Page ID",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:ProjectId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "status",
        column: "status",
        kind: "enum",
        nullable: false,
        default: "literal",
        defaultValue: "'planning'",
        reference: null,
        specialized: "enum:status",
      },
      {
        key: "kind",
        column: "kind",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:kind",
      },
      {
        key: "locations",
        column: "locations",
        kind: "text-array",
        nullable: false,
        default: "literal",
        defaultValue: "'{}'::text[]",
        reference: null,
        specialized: "text-array",
      },
      {
        key: "costEstimate",
        column: "costEstimate",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "double-precision",
      },
      {
        key: "parentProjectId",
        column: "parentProjectId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "project",
        specialized: null,
      },
      {
        key: "startDate",
        column: "startDate",
        kind: "date",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "endDate",
        column: "endDate",
        kind: "date",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "icon",
        column: "icon",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "googleDriveFolderUrl",
        column: "googleDriveFolderUrl",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notionPageUrl",
        column: "notionPageUrl",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notionPageId",
        column: "notionPageId",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [
      "name",
      "status",
      "kind",
      "locations",
      "costEstimate",
      "parentProjectId",
      "startDate",
      "endDate",
      "icon",
      "notes",
      "googleDriveFolderUrl",
      "notionPageUrl",
    ],
    update: [
      "name",
      "status",
      "kind",
      "locations",
      "costEstimate",
      "parentProjectId",
      "startDate",
      "endDate",
      "icon",
      "notes",
      "googleDriveFolderUrl",
      "notionPageUrl",
      "blockedByIds",
    ],
    bulk: [],
    audit: [
      "name",
      "status",
      "kind",
      "locations",
      "costEstimate",
      "parentProjectId",
      "startDate",
      "endDate",
      "icon",
      "notes",
      "googleDriveFolderUrl",
      "notionPageUrl",
    ],
    output: [
      "id",
      "name",
      "status",
      "kind",
      "locations",
      "costEstimate",
      "parentProjectId",
      "startDate",
      "endDate",
      "icon",
      "notes",
      "googleDriveFolderUrl",
      "notionPageUrl",
      "parentProjectName",
      "childProjectIds",
      "blockedByIds",
      "blockingIds",
      "createdAt",
      "updatedAt",
      "rollup",
      "dates",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/project", export: "projectCreateInput" },
    update: { module: "@cubby/schemas/project", export: "projectUpdateData" },
    output: { module: "@cubby/schemas/project", export: "projectOut" },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/project", export: "projectFilterFields" },
    descriptors: [
      {
        columnId: "image",
        field: "imagePresenceFilter",
        kind: "presence",
        placeholder: "Filter images...",
        options: [
          { value: "has", label: "Has image", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "name",
        field: "search",
        kind: "text",
        placeholder: "Filter by project name...",
        deriveSchema: true,
      },
      {
        columnId: "status",
        urlKey: "statuses",
        kind: "multiselect",
        placeholder: "Filter by status...",
        deriveSchema: true,
        options: [
          { value: "planning", label: "Planning", color: "var(--chart-5)" },
          {
            value: "not_started",
            label: "Not started",
            color: "var(--chart-neutral)",
          },
          {
            value: "in_progress",
            label: "In progress",
            color: "var(--chart-1)",
          },
          { value: "done", label: "Done", color: "var(--chart-positive)" },
        ],
      },
      {
        columnId: "kind",
        urlKey: "kinds",
        kind: "multiselect",
        placeholder: "Filter by kind...",
        deriveSchema: true,
        options: [
          { value: "furniture", label: "Furniture" },
          { value: "workshop", label: "Workshop" },
          { value: "household", label: "Household" },
          { value: "renovation", label: "Renovation" },
          { value: "garden", label: "Garden" },
          { value: "trip", label: "Trip" },
        ],
      },
      {
        columnId: "attention",
        kind: "select",
        placeholder: "Filter tracker attention...",
        options: [
          { value: "stalled", label: "Stalled" },
          { value: "missing_budget", label: "Missing budget" },
          {
            value: "blocked_no_next_action",
            label: "Blocked with no next action",
          },
        ],
      },
      {
        columnId: "locations",
        field: "location",
        urlKey: "locations",
        kind: "multiselect",
        placeholder: "Filter by location...",
        deriveSchema: true,
        schemaDescription: "Any exact match against locations[]",
        optionsKey: "projectLocations",
      },
      {
        columnId: "dateRange",
        urlKey: "date",
        kind: "range",
        placeholder: "Filter by project activity...",
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveDateRange",
        },
        urlOnly: true,
      },
      {
        columnId: "completionYear",
        urlKey: "completed",
        kind: "select",
        placeholder: "Filter by completion year...",
        optionsKey: "projectCompletionYears",
        urlOnly: true,
      },
      {
        columnId: "parent",
        field: "parentProjectId",
        kind: "idMulti",
        placeholder: "Filter by parent project...",
        optionsKey: "project",
        brandRef: { entity: "project", kind: "id" },
        nullable: {
          field: "parentProjectPresenceFilter",
          label: "parent project",
        },
      },
      {
        columnId: "related:project.blockedBy",
        field: "projectSearch",
        urlKey: "related-project",
        kind: "text",
        placeholder: "Search related blocked by...",
      },
      {
        columnId: "projectId",
        kind: "idMulti",
        placeholder: "Filter by related blocked by id...",
        urlOnly: true,
      },
      {
        columnId: "projectPresenceFilter",
        kind: "presence",
        placeholder: "Filter related blocked by presence...",
        urlOnly: true,
      },
      {
        columnId: "related:project.tasks",
        field: "taskSearch",
        urlKey: "related-task",
        kind: "text",
        placeholder: "Search related tasks...",
      },
      {
        columnId: "taskId",
        kind: "idMulti",
        placeholder: "Filter by related tasks id...",
        urlOnly: true,
      },
      {
        columnId: "taskPresenceFilter",
        kind: "presence",
        placeholder: "Filter related tasks presence...",
        urlOnly: true,
      },
      {
        columnId: "related:project.expenses",
        field: "expenseSearch",
        urlKey: "related-expense",
        kind: "text",
        placeholder: "Search related expenses...",
      },
      {
        columnId: "expenseId",
        kind: "idMulti",
        placeholder: "Filter by related expenses id...",
        urlOnly: true,
      },
      {
        columnId: "expensePresenceFilter",
        kind: "presence",
        placeholder: "Filter related expenses presence...",
        urlOnly: true,
      },
      {
        columnId: "related:project.taskProducts",
        field: "taskProductSearch",
        urlKey: "related-taskProduct",
        kind: "text",
        placeholder: "Search related task products...",
      },
      {
        columnId: "taskProductId",
        kind: "idMulti",
        placeholder: "Filter by related task products id...",
        urlOnly: true,
      },
      {
        columnId: "taskProductPresenceFilter",
        kind: "presence",
        placeholder: "Filter related task products presence...",
        urlOnly: true,
      },
      {
        columnId: "related:project.purchasedProducts",
        field: "purchasedProductSearch",
        urlKey: "related-purchasedProduct",
        kind: "text",
        placeholder: "Search related purchased products...",
      },
      {
        columnId: "purchasedProductId",
        kind: "idMulti",
        placeholder: "Filter by related purchased products id...",
        urlOnly: true,
      },
      {
        columnId: "purchasedProductPresenceFilter",
        kind: "presence",
        placeholder: "Filter related purchased products presence...",
        urlOnly: true,
      },
      {
        columnId: "related:project.usedTools",
        field: "usedToolSearch",
        urlKey: "related-usedTool",
        kind: "text",
        placeholder: "Search related reusable resources...",
      },
      {
        columnId: "usedToolId",
        kind: "idMulti",
        placeholder: "Filter by related reusable resources id...",
        urlOnly: true,
      },
      {
        columnId: "usedToolPresenceFilter",
        kind: "presence",
        placeholder: "Filter related reusable resources presence...",
        urlOnly: true,
      },
      {
        columnId: "related:project.vendors",
        field: "vendorSearch",
        urlKey: "related-vendor",
        kind: "text",
        placeholder: "Search related vendors...",
      },
      {
        columnId: "vendorId",
        kind: "idMulti",
        placeholder: "Filter by related vendors id...",
        urlOnly: true,
      },
      {
        columnId: "vendorPresenceFilter",
        kind: "presence",
        placeholder: "Filter related vendors presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "parent",
      label: "Parent project",
      target: "project",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Project.parentProjectId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Project.parentProjectId", direction: "incoming" }],
      },
    },
    {
      key: "blocked-by",
      label: "Blocked by",
      target: "project",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ProjectDependency.projectId", direction: "incoming" },
          {
            edge: "ProjectDependency.blockedByProjectId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "ProjectDependency.blockedByProjectId",
            direction: "incoming",
          },
          { edge: "ProjectDependency.projectId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "resources",
      label: "Reusable resources",
      target: "product",
      cardinality: "many",
      sourceKey: "explicit",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ProjectToolUsage.projectId", direction: "incoming" },
          { edge: "ProjectToolUsage.productId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "ProjectToolUsage.productId", direction: "incoming" },
          { edge: "ProjectToolUsage.projectId", direction: "outgoing" },
        ],
      },
      mutation: {
        source: "explicit",
        itemSchema: {
          module: "@cubby/schemas/common",
          export: "entityRelationReferenceItemSchema",
        },
        adapter: {
          module: "~/server/repo/project/tools",
          export: "projectResourcesRelationAdapter",
        },
        audiences: ["browser", "mcp"],
      },
    },
    {
      key: "tasks",
      label: "Tasks",
      target: "task",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Task.projectId", direction: "incoming" }],
      },
      inverse: { steps: [{ edge: "Task.projectId", direction: "outgoing" }] },
    },
    {
      key: "expenses",
      label: "Expenses",
      target: "expense",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.projectId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "Expense.projectId", direction: "outgoing" }],
      },
    },
    {
      key: "task-products",
      label: "Task products",
      target: "product",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Task.projectId", direction: "incoming" },
          { edge: "Task.subjectProductId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Task.subjectProductId", direction: "incoming" },
          { edge: "Task.projectId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "purchased-products",
      label: "Purchased products",
      target: "product",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.projectId", direction: "incoming" },
          { edge: "Expense.productId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Expense.productId", direction: "incoming" },
          { edge: "Expense.projectId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "vendors",
      label: "Vendors",
      target: "vendor",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.projectId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "outgoing" },
          { edge: "Purchase.vendorId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Purchase.vendorId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "incoming" },
          { edge: "Expense.projectId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "images",
      label: "Images",
      target: "image",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "ProjectImage.projectId", direction: "incoming" },
          { edge: "ProjectImage.imageId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "ProjectImage.imageId", direction: "incoming" },
          { edge: "ProjectImage.projectId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: true,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/project/entity-adapter",
        export: "projectEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
