import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "task",
  names: { singular: "Task", plural: "Tasks" },
  route: { basePath: "tasks" },
  table: "Task",
  identifiers: { brand: "TaskId", shortcode: "TSK-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: true, standard: "name", detailOrder: 0 },
        validation: {
          read: { kind: "string", min: 1 },
          create: { kind: "string", min: 1 },
          update: { kind: "string", min: 1, optional: true },
        },
      },
      {
        key: "status",
        kind: "enum",
        nullable: false,
        label: "Status",
        description: null,
        readKey: "status",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: { list: true, detail: true, detailOrder: 1 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "taskStatusSchema",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "taskStatusSchema",
            },
            defaultValue: "not_started",
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "taskStatusSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "projectId",
        kind: "identifier",
        nullable: true,
        label: "Project",
        description: null,
        readKey: "projectId",
        reference: { entity: "project", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: true, detailOrder: 5 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "subjectProductId",
        kind: "identifier",
        nullable: true,
        label: "For",
        description: null,
        readKey: "subjectProductId",
        reference: { entity: "product", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: true, detailOrder: 6 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "parentTaskId",
        kind: "identifier",
        nullable: true,
        label: "Parent Task ID",
        description: null,
        readKey: "parentTaskId",
        reference: { entity: "task", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "taskShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "taskShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "taskShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "dueDate",
        kind: "date",
        nullable: true,
        label: "Due Date",
        description: null,
        readKey: "dueDate",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: { list: true, detail: true, detailOrder: 3 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "dueEndDate",
        kind: "date",
        nullable: true,
        label: "Due End Date",
        description: null,
        readKey: "dueEndDate",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: { list: true, detail: true, detailOrder: 4 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            description: "End of a due-date range",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            description: "End of a due-date range",
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
            description: "End of a due-date range",
            optional: true,
          },
        },
      },
      {
        key: "trade",
        kind: "enum",
        nullable: false,
        label: "Trade",
        description: null,
        readKey: "trade",
        reference: null,
        control: { kind: "select", renderer: null, options: null },
        display: { list: true, detail: true, detailOrder: 2 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "tradeSchema",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "tradeSchema",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "tradeSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "sortOrder",
        kind: "number",
        nullable: true,
        label: "Sort Order",
        description: null,
        readKey: "sortOrder",
        reference: null,
        control: {
          kind: "number",
          renderer: null,
          options: null,
          section: "ordering",
        },
        display: { list: true, detail: false },
        validation: {
          read: { kind: "number", nullable: true },
          create: { kind: "number", nullable: true, defaultValue: null },
          update: { kind: "number", nullable: true, optional: true },
        },
      },
      {
        key: "blockedByIds",
        kind: "identifier",
        nullable: false,
        label: "Blocked By IDs",
        description: null,
        readKey: "blockedByIds",
        reference: { entity: "task", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "taskShortcode",
              },
            },
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "taskShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "taskShortcode",
            },
          },
        },
      },
      {
        key: "projectName",
        kind: "text",
        nullable: true,
        label: "Project Name",
        description: null,
        readKey: "projectName",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "subjectProductName",
        kind: "text",
        nullable: true,
        label: "Subject Product Name",
        description: null,
        readKey: "subjectProductName",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "parentTaskName",
        kind: "text",
        nullable: true,
        label: "Parent Task Name",
        description: null,
        readKey: "parentTaskName",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "blockingIds",
        kind: "identifier",
        nullable: false,
        label: "Blocking IDs",
        description: null,
        readKey: "blockingIds",
        reference: { entity: "task", multiple: true },
        control: null,
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "taskShortcode",
              },
            },
          },
        },
      },
      {
        key: "subtaskCount",
        kind: "number",
        nullable: false,
        label: "Subtask Count",
        description: null,
        readKey: "subtaskCount",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "number", integer: true } },
      },
      {
        key: "doneSubtaskCount",
        kind: "number",
        nullable: false,
        label: "Done Subtask Count",
        description: null,
        readKey: "doneSubtaskCount",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "number", integer: true } },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "notionPageId",
        kind: "text",
        nullable: true,
        label: "Notion Page ID",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:TaskId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "status",
        column: "status",
        kind: "enum",
        nullable: false,
        default: "literal",
        defaultValue: "'not_started'",
        reference: null,
        specialized: "enum:status",
      },
      {
        key: "projectId",
        column: "projectId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "project",
        specialized: null,
      },
      {
        key: "subjectProductId",
        column: "subjectProductId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "product",
        specialized: null,
      },
      {
        key: "parentTaskId",
        column: "parentTaskId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "task",
        specialized: null,
      },
      {
        key: "dueDate",
        column: "dueDate",
        kind: "date",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "dueEndDate",
        column: "dueEndDate",
        kind: "date",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "trade",
        column: "trade",
        kind: "enum",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:trade",
      },
      {
        key: "sortOrder",
        column: "sortOrder",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "double-precision",
      },
      {
        key: "notionPageId",
        column: "notionPageId",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [
      "name",
      "status",
      "projectId",
      "subjectProductId",
      "parentTaskId",
      "dueDate",
      "dueEndDate",
      "trade",
      "sortOrder",
    ],
    update: [
      "name",
      "status",
      "projectId",
      "subjectProductId",
      "parentTaskId",
      "dueDate",
      "dueEndDate",
      "trade",
      "sortOrder",
      "blockedByIds",
    ],
    bulk: ["projectId", "status", "trade", "dueDate", "dueEndDate"],
    audit: [
      "name",
      "status",
      "projectId",
      "subjectProductId",
      "parentTaskId",
      "dueDate",
      "dueEndDate",
      "trade",
    ],
    output: [
      "id",
      "name",
      "status",
      "projectId",
      "subjectProductId",
      "parentTaskId",
      "dueDate",
      "dueEndDate",
      "trade",
      "sortOrder",
      "projectName",
      "subjectProductName",
      "parentTaskName",
      "blockedByIds",
      "blockingIds",
      "subtaskCount",
      "doneSubtaskCount",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/project", export: "taskCreateInput" },
    update: { module: "@cubby/schemas/project", export: "taskUpdateData" },
    output: { module: "@cubby/schemas/project", export: "taskOut" },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/project", export: "taskFilterFields" },
    descriptors: [
      {
        columnId: "name",
        field: "search",
        kind: "text",
        placeholder: "Search tasks...",
        deriveSchema: true,
      },
      {
        columnId: "status",
        kind: "multiselect",
        placeholder: "Filter by status...",
        deriveSchema: true,
        options: [
          {
            value: "not_started",
            label: "Not started",
            color: "var(--chart-neutral)",
          },
          { value: "later", label: "Later", color: "var(--chart-2)" },
          {
            value: "in_progress",
            label: "In progress",
            color: "var(--chart-1)",
          },
          {
            value: "blocked",
            label: "Blocked",
            color: "var(--chart-negative)",
          },
          { value: "done", label: "Done", color: "var(--chart-positive)" },
        ],
      },
      {
        columnId: "trade",
        kind: "multiselect",
        placeholder: "Filter by trade...",
        deriveSchema: true,
        optionsRef: {
          module: "~/app/projects/trade-options",
          export: "tradeOptions",
        },
      },
      {
        columnId: "dueDate",
        kind: "range",
        placeholder: "Filter by due date...",
        options: [
          { value: "has", label: "Has due date", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "overdue", label: "Overdue" },
          { value: "week", label: "Due this week" },
          { value: "30d", label: "Due in 30 days" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveTaskDueFilter",
        },
      },
      {
        columnId: "dueRelative",
        kind: "select",
        placeholder: "Filter by relative due date...",
        options: [{ value: "beforeToday", label: "Before today" }],
        urlOnly: true,
      },
      {
        columnId: "completion",
        kind: "select",
        placeholder: "Filter task completion...",
        options: [
          { value: "open", label: "Open" },
          { value: "done", label: "Done" },
        ],
        urlOnly: true,
      },
      {
        columnId: "project",
        field: "projectId",
        kind: "idMulti",
        placeholder: "Filter by project...",
        optionsKey: "project",
        brandRef: { entity: "project", kind: "id" },
        nullable: { field: "projectPresenceFilter", label: "project" },
      },
      {
        columnId: "productId",
        field: "subjectProductId",
        urlKey: "productId",
        kind: "id",
        placeholder: "Filter by product id...",
        brandRef: { entity: "product", kind: "id" },
        urlOnly: true,
      },
      {
        columnId: "subjectProduct",
        field: "subjectProductId",
        kind: "idMulti",
        placeholder: "Filter by product...",
        optionsKey: "taskProducts",
        brandRef: { entity: "product", kind: "id" },
        nullable: { field: "subjectProductPresenceFilter", label: "product" },
      },
      {
        columnId: "parentTask",
        field: "parentTaskId",
        kind: "idMulti",
        placeholder: "Filter by parent task...",
        optionsKey: "parentTask",
        brandRef: { entity: "task", kind: "id" },
        nullable: { field: "parentTaskPresenceFilter", label: "parent task" },
      },
      {
        columnId: "related:task.blockedBy",
        field: "blockedByTaskSearch",
        urlKey: "related-blockedByTask",
        kind: "text",
        placeholder: "Search related blocked by...",
      },
      {
        columnId: "blockedByTaskId",
        kind: "idMulti",
        placeholder: "Filter by related blocked by id...",
        urlOnly: true,
      },
      {
        columnId: "blockedByTaskPresenceFilter",
        kind: "presence",
        placeholder: "Filter related blocked by presence...",
        urlOnly: true,
      },
      {
        columnId: "related:task.parent",
        field: "parentTaskSearch",
        urlKey: "related-parentTask",
        kind: "text",
        placeholder: "Search related parent task...",
      },
      {
        columnId: "parentTaskId",
        kind: "idMulti",
        placeholder: "Filter by related parent task id...",
        urlOnly: true,
      },
      {
        columnId: "parentTaskPresenceFilter",
        kind: "presence",
        placeholder: "Filter related parent task presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "project",
      label: "Project",
      target: "project",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Task.projectId", direction: "outgoing" }],
      },
      inverse: { steps: [{ edge: "Task.projectId", direction: "incoming" }] },
    },
    {
      key: "subject",
      label: "Subject product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Task.subjectProductId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Task.subjectProductId", direction: "incoming" }],
      },
    },
    {
      key: "parent",
      label: "Parent task",
      target: "task",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Task.parentTaskId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Task.parentTaskId", direction: "incoming" }],
      },
    },
    {
      key: "blocked-by",
      label: "Blocked by",
      target: "task",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "TaskDependency.taskId", direction: "incoming" },
          { edge: "TaskDependency.blockedByTaskId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "TaskDependency.blockedByTaskId", direction: "incoming" },
          { edge: "TaskDependency.taskId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: {
      fields: ["projectId", "status", "trade", "dueDate", "dueEndDate"],
    },
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete", "bulkUpdate"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/task/entity-adapter",
        export: "taskEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
