import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "purchase",
  names: { singular: "Purchase", plural: "Purchases" },
  route: { basePath: "purchases" },
  table: "Purchase",
  identifiers: { brand: "PurchaseId", shortcode: "PUR-", legacy: null },
  presentation: { titleField: "displayLabel" },
  model: {
    fields: [
      {
        key: "vendorId",
        kind: "identifier",
        nullable: false,
        label: "Vendor",
        description: null,
        readKey: "vendorId",
        reference: { entity: "vendor", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 0,
          columnId: "vendor",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "vendorShortcode",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "vendorShortcode",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "vendorShortcode",
            },
            optional: true,
          },
        },
      },
      {
        key: "orderId",
        kind: "text",
        nullable: true,
        label: "Order #",
        description: null,
        readKey: "orderId",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "identity",
        },
        display: { list: true, detail: true, detailOrder: 1 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "displayLabel",
        kind: "text",
        nullable: true,
        label: "Display label",
        description: null,
        readKey: "displayLabel",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "identity",
        },
        display: { list: true, detail: true, detailOrder: 2 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, optional: true },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "date",
        kind: "date",
        nullable: false,
        label: "Date",
        description: null,
        readKey: "date",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: { list: true, detail: true, detailOrder: 3 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            description: "The vendor order or receipt date",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            optional: true,
          },
        },
      },
      {
        key: "statedTotal",
        kind: "number",
        nullable: true,
        label: "Stated total",
        description: null,
        readKey: "statedTotal",
        reference: null,
        control: { kind: "number", renderer: "money", options: null },
        display: { list: true, detail: true, detailOrder: 4 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: { kind: "textarea", renderer: null, options: null },
        display: { list: true, detail: true, detailOrder: 5 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "pendingImageIds",
        kind: "identifier",
        nullable: false,
        label: "Pending Image IDs",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "removeImageIds",
        kind: "identifier",
        nullable: false,
        label: "Remove Image IDs",
        description: null,
        readKey: null,
        reference: { entity: "image", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "imageOrder",
        kind: "text",
        nullable: false,
        label: "Image Order",
        description: null,
        readKey: null,
        reference: null,
        control: {
          kind: "specialized",
          renderer: "image-order",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "imageShortcode",
              },
            },
            optional: true,
            description: "existing document ids in display order",
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "purchaseShortcode",
            },
          },
        },
      },
      {
        key: "vendorName",
        kind: "text",
        nullable: true,
        label: "Vendor Name",
        description: null,
        readKey: "vendorName",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "vendorLogo",
        kind: "json",
        nullable: true,
        label: "Vendor Logo",
        description: null,
        readKey: "vendorLogo",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/image-summary",
              export: "imageUrlSummary",
            },
            nullable: true,
          },
        },
      },
      {
        key: "orderUrl",
        kind: "text",
        nullable: true,
        label: "Order Url",
        description: null,
        readKey: "orderUrl",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "url", nullable: true } },
      },
      {
        key: "expenseCount",
        kind: "number",
        nullable: false,
        label: "Expense Count",
        description: null,
        readKey: "expenseCount",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "number", integer: true } },
      },
      {
        key: "unpricedExpenseCount",
        kind: "number",
        nullable: false,
        label: "Unpriced Expense Count",
        description: null,
        readKey: "unpricedExpenseCount",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "number", integer: true } },
      },
      {
        key: "expenseTotal",
        kind: "number",
        nullable: false,
        label: "Expense Total",
        description: null,
        readKey: "expenseTotal",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: {
          read: {
            kind: "source",
            source: { module: "@cubby/schemas/money", export: "money" },
          },
        },
      },
      {
        key: "reconciliation",
        kind: "json",
        nullable: false,
        label: "Reconciliation",
        description: null,
        readKey: "reconciliation",
        reference: null,
        control: null,
        display: { list: true, detail: false, columnId: "reconciliation" },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/purchase-fields",
              export: "purchaseReconciliation",
            },
          },
        },
      },
      {
        key: "financialReconciliation",
        kind: "json",
        nullable: false,
        label: "Financial Reconciliation",
        description: null,
        readKey: "financialReconciliation",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-reconciliation",
              export: "financialReconciliationSummary",
            },
          },
        },
      },
      {
        key: "documentCount",
        kind: "number",
        nullable: false,
        label: "Document Count",
        description: null,
        readKey: "documentCount",
        reference: null,
        control: null,
        display: { list: true, detail: false },
        validation: { read: { kind: "number", integer: true } },
      },
      {
        key: "images",
        kind: "json",
        nullable: false,
        label: "Images",
        description: null,
        readKey: "images",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/purchase-fields",
              export: "purchaseImages",
            },
          },
        },
      },
      {
        key: "dataQuality",
        kind: "json",
        nullable: false,
        label: "Data Quality",
        description: null,
        readKey: "dataQuality",
        reference: null,
        control: null,
        display: { list: true, detail: false, columnId: "dataQuality" },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/data-quality",
              export: "dataQuality",
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "dataExceptions",
        kind: "json",
        nullable: false,
        label: "Data Exceptions",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:PurchaseId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "vendorId",
        column: "vendorId",
        kind: "identifier",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: "vendor",
        specialized: null,
      },
      {
        key: "orderId",
        column: "orderId",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "displayLabel",
        column: "displayLabel",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "date",
        column: "date",
        kind: "date",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "statedTotal",
        column: "statedTotal",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "double-precision",
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "dataExceptions",
        column: "dataExceptions",
        kind: "json",
        nullable: false,
        default: "literal",
        defaultValue: "'[]'::jsonb",
        reference: null,
        specialized: "json:dataExceptions",
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [
      "vendorId",
      "orderId",
      "displayLabel",
      "date",
      "statedTotal",
      "notes",
      "pendingImageIds",
    ],
    update: [
      "vendorId",
      "orderId",
      "displayLabel",
      "date",
      "statedTotal",
      "notes",
      "pendingImageIds",
      "removeImageIds",
      "imageOrder",
    ],
    bulk: [],
    audit: [
      "vendorId",
      "orderId",
      "displayLabel",
      "date",
      "statedTotal",
      "notes",
    ],
    output: [
      "id",
      "vendorId",
      "orderId",
      "displayLabel",
      "date",
      "statedTotal",
      "notes",
      "vendorName",
      "vendorLogo",
      "orderUrl",
      "expenseCount",
      "unpricedExpenseCount",
      "expenseTotal",
      "reconciliation",
      "financialReconciliation",
      "documentCount",
      "images",
      "dataQuality",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/purchase",
      export: "purchaseCreateInput",
    },
    update: { module: "@cubby/schemas/purchase", export: "purchaseUpdateData" },
    output: { module: "@cubby/schemas/purchase", export: "purchaseOut" },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/purchase",
      export: "purchaseFilterFields",
    },
    descriptors: [
      {
        columnId: "financialReconciliation",
        kind: "select",
        placeholder: "Filter financial reconciliation...",
        urlOnly: true,
      },
      {
        columnId: "purchase",
        field: "search",
        urlKey: "q",
        kind: "text",
        placeholder: "Search order id or label...",
      },
      {
        columnId: "displayLabel",
        field: "displayLabelSearch",
        urlKey: "label",
        kind: "text",
        placeholder: "Search display label...",
        deriveSchema: true,
        schemaDescription: "Substring match on the human display label only",
      },
      {
        columnId: "vendor",
        field: "vendorId",
        kind: "idMulti",
        placeholder: "Filter by vendor...",
        optionsKey: "vendor",
        brandRef: { entity: "vendor", kind: "id" },
      },
      {
        columnId: "orderId",
        field: "orderIdPresenceFilter",
        kind: "presence",
        placeholder: "Filter by order id...",
        options: [
          { value: "has", label: "Has order id", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "date",
        kind: "range",
        placeholder: "Filter by date...",
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveDateRange",
        },
      },
      {
        columnId: "statedTotal",
        field: "statedTotalPresenceFilter",
        kind: "presence",
        placeholder: "Filter by stated total...",
        options: [
          { value: "has", label: "Has stated total", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "expenseCount",
        field: "expenseStatus",
        urlKey: "lines",
        kind: "multiselect",
        placeholder: "Filter by expense status...",
        options: [
          { value: "empty", label: "No expenses" },
          { value: "unpriced", label: "Has unpriced expenses" },
          { value: "priced", label: "Fully priced" },
        ],
      },
      {
        columnId: "expenseTotal",
        urlKey: "lineTotal",
        kind: "range",
        placeholder: "Filter by expense total...",
        deriveSchema: true,
        options: [
          { value: "gte500", label: "$500 and up" },
          { value: "gte200", label: "$200 and up" },
          { value: "gte100", label: "$100 and up" },
          { value: "nonpositive", label: "Non-positive (≤ $0)" },
        ],
        expandRef: {
          module: "~/app/purchases/purchase-options",
          export: "resolvePurchaseExpenseTotalFilter",
        },
      },
      {
        columnId: "reconciliation",
        kind: "multiselect",
        placeholder: "Filter reconciliation...",
        options: [
          { value: "match", label: "Reconciles" },
          { value: "refund_adjusted", label: "Refund-adjusted" },
          { value: "mismatch", label: "Needs review" },
          { value: "unknown", label: "No stated total" },
        ],
      },
      {
        columnId: "documentCount",
        field: "documentPresenceFilter",
        urlKey: "documents",
        kind: "presence",
        placeholder: "Filter by documents...",
        options: [
          { value: "has", label: "Has documents", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "transactionCount",
        field: "financialTransactionPresenceFilter",
        urlKey: "transactions",
        kind: "presence",
        placeholder: "Filter by transactions...",
        options: [
          { value: "has", label: "Has transactions", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "dataQuality",
        field: "dataStatus",
        kind: "select",
        placeholder: "Filter data quality...",
        options: [
          { value: "complete", label: "Complete", color: "var(--slate)" },
          { value: "needs_data", label: "Needs data", color: "var(--warning)" },
          { value: "defect", label: "Defect", color: "var(--destructive)" },
        ],
      },
      {
        columnId: "dataGaps",
        field: "dataGap",
        kind: "multiselect",
        placeholder: "Filter data gaps...",
        options: [
          { value: "settlement_reference", label: "No settlement evidence" },
          { value: "purchase_date", label: "Missing date" },
          { value: "order_id", label: "Missing order ID" },
          { value: "stated_total", label: "Missing stated total" },
          { value: "empty_expenses", label: "No expense lines" },
          { value: "unpriced_expense", label: "Unpriced expense line" },
          { value: "paperwork_mismatch", label: "Paperwork mismatch" },
        ],
      },
      {
        columnId: "expenseTotalMin",
        urlKey: "lineTotalMin",
        kind: "text",
        placeholder: "Minimum expense total...",
        urlOnly: true,
      },
      {
        columnId: "expenseTotalMax",
        urlKey: "lineTotalMax",
        kind: "text",
        placeholder: "Maximum expense total...",
        urlOnly: true,
      },
      {
        columnId: "related:purchase.expenses",
        field: "expenseSearch",
        urlKey: "related-expense",
        kind: "text",
        placeholder: "Search related expenses...",
      },
      {
        columnId: "expenseId",
        kind: "idMulti",
        placeholder: "Filter by related expenses id...",
        urlOnly: true,
      },
      {
        columnId: "expensePresenceFilter",
        kind: "presence",
        placeholder: "Filter related expenses presence...",
        urlOnly: true,
      },
      {
        columnId: "related:purchase.transactions",
        field: "financialTransactionSearch",
        urlKey: "related-financialTransaction",
        kind: "text",
        placeholder: "Search related financial transactions...",
      },
      {
        columnId: "financialTransactionId",
        kind: "idMulti",
        placeholder: "Filter by related financial transactions id...",
        urlOnly: true,
      },
      {
        columnId: "financialTransactionPresenceFilter",
        kind: "presence",
        placeholder: "Filter related financial transactions presence...",
        urlOnly: true,
      },
      {
        columnId: "related:purchase.products",
        field: "productSearch",
        urlKey: "related-product",
        kind: "text",
        placeholder: "Search related products...",
      },
      {
        columnId: "productId",
        kind: "idMulti",
        placeholder: "Filter by related products id...",
        urlOnly: true,
      },
      {
        columnId: "productPresenceFilter",
        kind: "presence",
        placeholder: "Filter related products presence...",
        urlOnly: true,
      },
      {
        columnId: "related:purchase.projects",
        field: "projectId",
        urlKey: "related-project",
        kind: "idMulti",
        placeholder: "Filter by project...",
        optionsKey: "project",
        brandRef: { entity: "project", kind: "id" },
        nullable: { field: "projectPresenceFilter", label: "project" },
      },
      {
        columnId: "projectId",
        kind: "idMulti",
        placeholder: "Filter by project id...",
        brandRef: { entity: "project", kind: "id" },
        urlOnly: true,
      },
      {
        columnId: "projectPresenceFilter",
        kind: "presence",
        placeholder: "Filter project presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "vendor",
      label: "Vendor",
      target: "vendor",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Purchase.vendorId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Purchase.vendorId", direction: "incoming" }],
      },
    },
    {
      key: "images",
      label: "Images",
      target: "image",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "PurchaseImage.purchaseId", direction: "incoming" },
          { edge: "PurchaseImage.imageId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "PurchaseImage.imageId", direction: "incoming" },
          { edge: "PurchaseImage.purchaseId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "financial-transactions",
      label: "Financial transactions",
      target: "financialTransaction",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "outgoing",
          },
        ],
      },
    },
    {
      key: "expenses",
      label: "Expenses",
      target: "expense",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.purchaseId", direction: "incoming" }],
      },
      inverse: {
        steps: [{ edge: "Expense.purchaseId", direction: "outgoing" }],
      },
    },
    {
      key: "products",
      label: "Products",
      target: "product",
      cardinality: "many",
      sourceKey: "expense",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.purchaseId", direction: "incoming" },
          { edge: "Expense.productId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Expense.productId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "outgoing" },
        ],
      },
      sources: [
        {
          key: "explicit",
          label: "Explicit product link",
          provenance: {
            kind: "local-path",
            steps: [
              { edge: "PurchaseProduct.purchaseId", direction: "incoming" },
              { edge: "PurchaseProduct.productId", direction: "outgoing" },
            ],
          },
          inverse: {
            steps: [
              { edge: "PurchaseProduct.productId", direction: "incoming" },
              { edge: "PurchaseProduct.purchaseId", direction: "outgoing" },
            ],
          },
        },
      ],
      mutation: {
        source: "explicit",
        itemSchema: {
          module: "@cubby/schemas/common",
          export: "entityRelationReferenceItemSchema",
        },
        adapter: {
          module: "~/server/repo/purchase-products",
          export: "purchaseProductsRelationAdapter",
        },
        audiences: ["browser", "mcp"],
      },
    },
    {
      key: "projects",
      label: "Projects",
      target: "project",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.purchaseId", direction: "incoming" },
          { edge: "Expense.projectId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Expense.projectId", direction: "incoming" },
          { edge: "Expense.purchaseId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: true,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: true,
    operationOwners: { delete: "kernel", merge: "kernel" },
    mcp: ["get", "list", "search", "create", "update", "delete", "merge"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/purchase.entity-adapter",
        export: "purchaseEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
