import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "financialAccount",
  names: { singular: "Financial Account", plural: "Accounts" },
  route: { basePath: "financial-accounts" },
  table: "FinancialAccount",
  identifiers: { brand: "FinancialAccountId", shortcode: "FAC-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string", min: 1 },
          create: { kind: "string", min: 1 },
          update: { kind: "string", min: 1, optional: true },
        },
      },
      {
        key: "identity",
        kind: "json",
        nullable: false,
        label: "Identity",
        description: null,
        readKey: "identity",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-account-fields",
              export: "financialAccountIdentity",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-account-fields",
              export: "financialAccountIdentity",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-account-fields",
              export: "financialAccountIdentity",
            },
            optional: true,
          },
        },
      },
      {
        key: "provisional",
        kind: "boolean",
        nullable: false,
        label: "Provisional",
        description: null,
        readKey: "provisional",
        reference: null,
        control: {
          kind: "checkbox",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "boolean" },
          create: { kind: "boolean", defaultValue: false },
          update: { kind: "boolean", optional: true },
        },
      },
      {
        key: "sourceAliases",
        kind: "json",
        nullable: false,
        label: "Aliases",
        description: null,
        readKey: "sourceAliases",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: true, detail: true, columnId: "aliases" },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-account-fields",
              export: "financialAccountSourceAliases",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-account-fields",
              export: "financialAccountSourceAliases",
            },
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/financial-account-fields",
              export: "financialAccountSourceAliases",
            },
            optional: true,
          },
        },
      },
      {
        key: "ledgerPartyId",
        kind: "identifier",
        nullable: true,
        label: "Owner",
        description: null,
        readKey: "ledgerPartyId",
        reference: { entity: "ledgerParty", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: true, columnId: "ledgerPartyName" },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "ledgerPartyShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: { kind: "textarea", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "financialAccountShortcode",
            },
          },
        },
      },
      {
        key: "ledgerPartyName",
        kind: "text",
        nullable: true,
        label: "Ledger Party Name",
        description: null,
        readKey: "ledgerPartyName",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "transactionCount",
        kind: "number",
        nullable: false,
        label: "Transactions",
        description: null,
        readKey: "transactionCount",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: { kind: "number", integer: true, nonnegative: true },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:FinancialAccountId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "identity",
        column: "identity",
        kind: "json",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "json:identity",
      },
      {
        key: "provisional",
        column: "provisional",
        kind: "boolean",
        nullable: false,
        default: "literal",
        defaultValue: false,
        reference: null,
        specialized: null,
      },
      {
        key: "sourceAliases",
        column: "sourceAliases",
        kind: "json",
        nullable: false,
        default: "literal",
        defaultValue: "'[]'::jsonb",
        reference: null,
        specialized: "json:sourceAliases",
      },
      {
        key: "ledgerPartyId",
        column: "ledgerPartyId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "ledgerParty",
        specialized: null,
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [
      "name",
      "identity",
      "provisional",
      "sourceAliases",
      "ledgerPartyId",
      "notes",
    ],
    update: [
      "name",
      "identity",
      "provisional",
      "sourceAliases",
      "ledgerPartyId",
      "notes",
    ],
    bulk: [],
    audit: [
      "name",
      "identity",
      "provisional",
      "sourceAliases",
      "notes",
      "ledgerPartyId",
    ],
    output: [
      "id",
      "name",
      "identity",
      "provisional",
      "sourceAliases",
      "ledgerPartyId",
      "notes",
      "ledgerPartyName",
      "transactionCount",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: {
      module: "@cubby/schemas/financial-account",
      export: "financialAccountCreateInput",
    },
    update: {
      module: "@cubby/schemas/financial-account",
      export: "financialAccountUpdateData",
    },
    output: {
      module: "@cubby/schemas/financial-account",
      export: "financialAccountOut",
    },
  },
  filters: {
    audit: true,
    schema: {
      module: "@cubby/schemas/financial-account",
      export: "financialAccountFilterFields",
    },
    descriptors: [
      {
        columnId: "name",
        field: "search",
        urlKey: "q",
        kind: "text",
        placeholder: "Search accounts...",
        deriveSchema: true,
      },
      {
        columnId: "identity",
        field: "identityKind",
        kind: "multiselect",
        placeholder: "Filter by account type...",
        options: [
          { value: "credit_card", label: "Credit card" },
          { value: "bank_account", label: "Bank account" },
          { value: "stored_value", label: "Stored value" },
          { value: "cash", label: "Cash" },
          { value: "other", label: "Other" },
        ],
      },
      {
        columnId: "provisional",
        kind: "boolean",
        placeholder: "Filter by status...",
        deriveSchema: true,
        options: [
          { value: "false", label: "Known" },
          { value: "true", label: "Provisional" },
        ],
      },
      {
        columnId: "aliases",
        field: "sourceAliasPresenceFilter",
        kind: "presence",
        placeholder: "Filter aliases...",
        options: [
          { value: "has", label: "Has aliases", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "last4",
        kind: "text",
        placeholder: "Filter by last four digits...",
        urlOnly: true,
      },
      {
        columnId: "source",
        kind: "multiselect",
        placeholder: "Filter by source...",
        urlOnly: true,
      },
      {
        columnId: "externalAccountId",
        kind: "multiselect",
        placeholder: "Filter by external account id...",
        urlOnly: true,
      },
      {
        columnId: "related:financialAccount.transactions",
        field: "financialTransactionSearch",
        urlKey: "related-financialTransaction",
        kind: "text",
        placeholder: "Search related transactions...",
      },
      {
        columnId: "financialTransactionId",
        kind: "idMulti",
        placeholder: "Filter by related transactions id...",
        urlOnly: true,
      },
      {
        columnId: "financialTransactionPresenceFilter",
        kind: "presence",
        placeholder: "Filter related transactions presence...",
        urlOnly: true,
      },
      {
        columnId: "related:financialAccount.purchases",
        field: "purchaseSearch",
        urlKey: "related-purchase",
        kind: "text",
        placeholder: "Search related purchases...",
      },
      {
        columnId: "purchaseId",
        kind: "idMulti",
        placeholder: "Filter by related purchases id...",
        urlOnly: true,
      },
      {
        columnId: "purchasePresenceFilter",
        kind: "presence",
        placeholder: "Filter related purchases presence...",
        urlOnly: true,
      },
      {
        columnId: "related:financialAccount.vendors",
        field: "vendorSearch",
        urlKey: "related-vendor",
        kind: "text",
        placeholder: "Search related vendors...",
      },
      {
        columnId: "vendorId",
        kind: "idMulti",
        placeholder: "Filter by related vendors id...",
        urlOnly: true,
      },
      {
        columnId: "vendorPresenceFilter",
        kind: "presence",
        placeholder: "Filter related vendors presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "ledger-party",
      label: "Ledger party",
      target: "ledgerParty",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "FinancialAccount.ledgerPartyId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "FinancialAccount.ledgerPartyId", direction: "incoming" },
        ],
      },
    },
    {
      key: "transactions",
      label: "Transactions",
      target: "financialTransaction",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "FinancialTransaction.accountId", direction: "incoming" },
        ],
      },
      inverse: {
        steps: [
          { edge: "FinancialTransaction.accountId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "purchases",
      label: "Purchases",
      target: "purchase",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "FinancialTransaction.accountId", direction: "incoming" },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "outgoing",
          },
          { edge: "FinancialTransaction.accountId", direction: "outgoing" },
        ],
      },
    },
    {
      key: "vendors",
      label: "Vendors",
      target: "vendor",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "FinancialTransaction.accountId", direction: "incoming" },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "outgoing",
          },
          { edge: "Purchase.vendorId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "Purchase.vendorId", direction: "incoming" },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "outgoing",
          },
          { edge: "FinancialTransaction.accountId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/financial-account.entity-adapter",
        export: "financialAccountEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
