import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "wish",
  names: { singular: "Wish", plural: "Wishlist" },
  route: { basePath: "wishes" },
  table: "Wish",
  identifiers: { brand: "WishId", shortcode: "WSH-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: true, standard: "name" },
        validation: {
          read: { kind: "string", trim: true, min: 1, max: 200 },
          create: { kind: "string", trim: true, min: 1, max: 200 },
          update: {
            kind: "string",
            trim: true,
            min: 1,
            max: 200,
            optional: true,
          },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: { kind: "textarea", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "candidateProductIds",
        kind: "identifier",
        nullable: false,
        label: "Candidate Product IDs",
        description: null,
        readKey: null,
        reference: { entity: "product", multiple: true },
        control: {
          kind: "specialized",
          renderer: "entity-multi-select",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          create: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "productShortcode",
              },
            },
            defaultValue: [],
          },
          update: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/identifiers",
                export: "productShortcode",
              },
            },
            optional: true,
          },
        },
      },
      {
        key: "acquired",
        kind: "boolean",
        nullable: false,
        label: "Acquired",
        description: null,
        readKey: null,
        reference: null,
        control: {
          kind: "checkbox",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: false, detail: false },
        validation: {
          update: { kind: "boolean", optional: true },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "wishShortcode",
            },
          },
        },
      },
      {
        key: "acquiredAt",
        kind: "timestamp",
        nullable: true,
        label: "Acquired At",
        description: null,
        readKey: "acquiredAt",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "timestamp", nullable: true } },
      },
      {
        key: "candidates",
        kind: "json",
        nullable: false,
        label: "Candidates",
        description: null,
        readKey: "candidates",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "array",
            item: {
              kind: "source",
              source: {
                module: "@cubby/schemas/wish-fields",
                export: "wishCandidateOut",
              },
            },
          },
        },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:WishId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "acquiredAt",
        column: "acquiredAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: ["name", "notes", "candidateProductIds"],
    update: ["name", "notes", "candidateProductIds", "acquired"],
    bulk: [],
    audit: ["name", "notes", "acquiredAt", "candidateProductIds"],
    output: [
      "id",
      "name",
      "notes",
      "acquiredAt",
      "candidates",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/wish", export: "wishCreateInput" },
    update: { module: "@cubby/schemas/wish", export: "wishUpdateData" },
    output: { module: "@cubby/schemas/wish", export: "wishOut" },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/wish", export: "wishFilterFields" },
    descriptors: [
      {
        columnId: "name",
        field: "search",
        urlKey: "q",
        kind: "text",
        placeholder: "Search wishlist...",
        deriveSchema: true,
        schemaFromRead: true,
      },
      {
        columnId: "acquired",
        kind: "boolean",
        placeholder: "Filter by status...",
        deriveSchema: true,
        options: [
          { value: "false", label: "Wanted" },
          { value: "true", label: "Acquired" },
        ],
      },
      {
        columnId: "related:wish.candidates",
        field: "candidateProductId",
        urlKey: "related-product",
        kind: "idMulti",
        placeholder: "Filter by candidate product...",
        optionsKey: "wishCandidates",
        nullable: { field: "productPresenceFilter", label: "candidate" },
      },
      {
        columnId: "productId",
        kind: "idMulti",
        placeholder: "Filter by candidate product id...",
        urlOnly: true,
      },
      {
        columnId: "productPresenceFilter",
        kind: "presence",
        placeholder: "Filter candidate presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "candidates",
      label: "Tool candidates",
      target: "product",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "WishCandidate.wishId", direction: "incoming" },
          { edge: "WishCandidate.productId", direction: "outgoing" },
        ],
      },
      inverse: {
        steps: [
          { edge: "WishCandidate.productId", direction: "incoming" },
          { edge: "WishCandidate.wishId", direction: "outgoing" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: { plural: "wishes" },
    ports: {
      repository: {
        module: "~/server/repo/wish.entity-adapter",
        export: "wishEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
