import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "expense",
  names: { singular: "Expense", plural: "Expenses" },
  route: { basePath: "expenses" },
  table: "Expense",
  identifiers: { brand: "ExpenseId", shortcode: "EXP-", legacy: null },
  presentation: { titleField: "name" },
  model: {
    fields: [
      {
        key: "name",
        kind: "text",
        nullable: false,
        label: "Name",
        description: null,
        readKey: "name",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: {
          list: true,
          detail: true,
          detailOrder: 10,
          standard: "name",
        },
        validation: {
          read: { kind: "string", min: 1 },
          create: { kind: "string", min: 1 },
          update: { kind: "string", min: 1, optional: true },
        },
      },
      {
        key: "cost",
        kind: "number",
        nullable: true,
        label: "Cost",
        description: null,
        readKey: "cost",
        reference: null,
        control: {
          kind: "number",
          renderer: "money",
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 20 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
            nullable: true,
            description: "Dollars",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/money",
              export: "wholeCentAmount",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "date",
        kind: "date",
        nullable: false,
        label: "Date",
        description: null,
        readKey: "date",
        reference: null,
        control: {
          kind: "date",
          renderer: null,
          options: null,
          section: "schedule",
        },
        display: { list: true, detail: true, detailOrder: 30 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            optional: true,
          },
        },
      },
      {
        key: "lineKind",
        kind: "enum",
        nullable: false,
        label: "Line kind",
        description: null,
        readKey: "lineKind",
        reference: null,
        control: {
          kind: "select",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 40 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-line-kind",
              export: "expenseLineKindSchema",
            },
            description:
              "Receipt role. Principal lines are the purchased item/service; every other value is a purchase-level adjustment.",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-line-kind",
              export: "expenseLineKindSchema",
            },
            optional: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-line-kind",
              export: "expenseLineKindSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "lineBasis",
        kind: "enum",
        nullable: false,
        label: "Itemization",
        description: null,
        readKey: "lineBasis",
        reference: null,
        control: {
          kind: "select",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 140 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-line-kind",
              export: "expenseLineBasisSchema",
            },
            description:
              "Whether this row is a line item or a slice of a total that was never itemized. 'allocation' means the money was cut by payment schedule (a deposit and a balance on one order) or by an estimated materials/labor split of a lump-sum contract — such a row can never carry a productId, and its costType may be an estimate rather than a vendor-stated fact.",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-line-kind",
              export: "expenseLineBasisSchema",
            },
            defaultValue: "item_line",
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-line-kind",
              export: "expenseLineBasisSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "costType",
        kind: "enum",
        nullable: false,
        label: "Cost Type",
        description: null,
        readKey: "costType",
        reference: null,
        control: {
          kind: "select",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 50 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-fields",
              export: "costTypeSchema",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-fields",
              export: "costTypeSchema",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-fields",
              export: "costTypeSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "trade",
        kind: "enum",
        nullable: false,
        label: "Trade",
        description: null,
        readKey: "trade",
        reference: null,
        control: {
          kind: "select",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 60 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "tradeSchema",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "tradeSchema",
            },
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/task-fields",
              export: "tradeSchema",
            },
            optional: true,
          },
        },
      },
      {
        key: "url",
        kind: "text",
        nullable: true,
        label: "URL",
        description: null,
        readKey: "url",
        reference: null,
        control: {
          kind: "text",
          renderer: "url",
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 80 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "notes",
        kind: "text",
        nullable: true,
        label: "Notes",
        description: null,
        readKey: "notes",
        reference: null,
        control: {
          kind: "textarea",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 90 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "future",
        kind: "boolean",
        nullable: false,
        label: "Planned",
        description: null,
        readKey: "future",
        reference: null,
        control: {
          kind: "checkbox",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 70 },
        validation: {
          read: { kind: "boolean" },
          create: { kind: "boolean", defaultValue: false },
          update: { kind: "boolean", optional: true },
        },
      },
      {
        key: "projectId",
        kind: "identifier",
        nullable: true,
        label: "Project",
        description: null,
        readKey: "projectId",
        reference: { entity: "project", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 120,
          columnId: "project",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "projectShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "productId",
        kind: "identifier",
        nullable: true,
        label: "Product",
        description: null,
        readKey: "productId",
        reference: { entity: "product", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: {
          list: true,
          detail: true,
          detailOrder: 130,
          columnId: "product",
        },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            nullable: true,
            description:
              "Optional link to the product this expense bought. A negative-cost expense on the same product records an exit (sale, return, or a 0-cost disposal).",
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "productShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "productQuantity",
        kind: "number",
        nullable: true,
        label: "Product quantity",
        description: null,
        readKey: "productQuantity",
        reference: null,
        control: {
          kind: "number",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 150 },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-fields",
              export: "signedProductQuantity",
            },
            nullable: true,
            description:
              'Product units covered by this expense; fractional values are allowed (half a coil thrown away is -0.5). Null means the receipt does not establish quantity. Signed: money direction wins, so a positive-cost line is an acquisition of |qty| and a negative-cost line is an exit of |qty|. On a $0 line the sign IS the fact — a positive quantity is a free acquisition (promo pack, bundled accessory), a negative quantity is a discard/write-off. Zero is legal ONLY on a negative-cost line and means money came back but no unit left — a price concession with the item kept (Amazon "Account adjustment", a partial refund for shipping damage). Prefer 0 over null there: null says the count is unknown and gets reported as data-entry debt.',
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-fields",
              export: "signedProductQuantity",
            },
            nullable: true,
            defaultValue: null,
            description:
              'Product units covered by this expense; fractional values are allowed (half a coil thrown away is -0.5). Null means the receipt does not establish quantity. Signed: money direction wins, so a positive-cost line is an acquisition of |qty| and a negative-cost line is an exit of |qty|. On a $0 line the sign IS the fact — a positive quantity is a free acquisition (promo pack, bundled accessory), a negative quantity is a discard/write-off. Zero is legal ONLY on a negative-cost line and means money came back but no unit left — a price concession with the item kept (Amazon "Account adjustment", a partial refund for shipping damage). Prefer 0 over null there: null says the count is unknown and gets reported as data-entry debt.',
            descriptionAfter: true,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/expense-fields",
              export: "signedProductQuantity",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "vendor",
        kind: "text",
        nullable: true,
        label: "Vendor",
        description: null,
        readKey: "vendor",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: false, detail: true, detailOrder: 100 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "orderId",
        kind: "text",
        nullable: true,
        label: "Order #",
        description: null,
        readKey: "orderId",
        reference: null,
        control: {
          kind: "text",
          renderer: null,
          options: null,
          section: "details",
        },
        display: { list: true, detail: true, detailOrder: 110 },
        validation: {
          read: { kind: "string", nullable: true },
          create: { kind: "string", nullable: true, defaultValue: null },
          update: { kind: "string", nullable: true, optional: true },
        },
      },
      {
        key: "purchaseId",
        kind: "identifier",
        nullable: true,
        label: "Purchase",
        description: null,
        readKey: "purchaseId",
        reference: { entity: "purchase", multiple: false },
        control: {
          kind: "specialized",
          renderer: "entity-select",
          options: null,
        },
        display: { list: true, detail: false, columnId: "vendor" },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "purchaseShortcode",
            },
            nullable: true,
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "purchaseShortcode",
            },
            nullable: true,
            defaultValue: null,
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "purchaseShortcode",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "beneficiaries",
        kind: "json",
        nullable: false,
        label: "Beneficiaries",
        description: null,
        readKey: "beneficiaries",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerAttributions",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerAttributions",
            },
            nullable: true,
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerAttributions",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "funders",
        kind: "json",
        nullable: false,
        label: "Funders",
        description: null,
        readKey: "funders",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerAttributions",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerAttributions",
            },
            nullable: true,
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-party-fields",
              export: "ledgerAttributions",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "sourceClaims",
        kind: "json",
        nullable: false,
        label: "Source Claims",
        description: null,
        readKey: "sourceClaims",
        reference: null,
        control: {
          kind: "specialized",
          renderer: "structured-field",
          options: null,
        },
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerSourceClaimsOut",
            },
          },
          create: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerSourceClaims",
            },
            nullable: true,
            defaultValue: [],
          },
          update: {
            kind: "source",
            source: {
              module: "@cubby/schemas/ledger-transfer-fields",
              export: "ledgerSourceClaims",
            },
            nullable: true,
            optional: true,
          },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "expenseShortcode",
            },
          },
        },
      },
      {
        key: "purchaseDate",
        kind: "date",
        nullable: true,
        label: "Purchase Date",
        description: null,
        readKey: "purchaseDate",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/base-entity",
              export: "plainDate",
            },
            nullable: true,
          },
        },
      },
      {
        key: "purchaseDisplayLabel",
        kind: "text",
        nullable: true,
        label: "Purchase Display Label",
        description: null,
        readKey: "purchaseDisplayLabel",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "vendorId",
        kind: "identifier",
        nullable: true,
        label: "Vendor ID",
        description: null,
        readKey: "vendorId",
        reference: { entity: "vendor", multiple: false },
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "vendorShortcode",
            },
            nullable: true,
          },
        },
      },
      {
        key: "vendorLogo",
        kind: "json",
        nullable: true,
        label: "Vendor Logo",
        description: null,
        readKey: "vendorLogo",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/image-summary",
              export: "imageUrlSummary",
            },
            nullable: true,
          },
        },
      },
      {
        key: "orderUrl",
        kind: "text",
        nullable: true,
        label: "Order Url",
        description: null,
        readKey: "orderUrl",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "url", nullable: true } },
      },
      {
        key: "projectName",
        kind: "text",
        nullable: true,
        label: "Project Name",
        description: null,
        readKey: "projectName",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "productName",
        kind: "text",
        nullable: true,
        label: "Product Name",
        description: null,
        readKey: "productName",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "notionPageId",
        kind: "text",
        nullable: true,
        label: "Notion Page ID",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:ExpenseId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "name",
        column: "name",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "cost",
        column: "cost",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "double-precision",
      },
      {
        key: "date",
        column: "date",
        kind: "date",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "lineKind",
        column: "lineKind",
        kind: "enum",
        nullable: false,
        default: "literal",
        defaultValue: "'principal'",
        reference: null,
        specialized: "enum:lineKind",
      },
      {
        key: "lineBasis",
        column: "lineBasis",
        kind: "enum",
        nullable: false,
        default: "literal",
        defaultValue: "'item_line'",
        reference: null,
        specialized: "enum:lineBasis",
      },
      {
        key: "costType",
        column: "costType",
        kind: "enum",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:costType",
      },
      {
        key: "trade",
        column: "trade",
        kind: "enum",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:trade",
      },
      {
        key: "url",
        column: "url",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "notes",
        column: "notes",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "future",
        column: "future",
        kind: "boolean",
        nullable: false,
        default: "literal",
        defaultValue: false,
        reference: null,
        specialized: null,
      },
      {
        key: "projectId",
        column: "projectId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "project",
        specialized: null,
      },
      {
        key: "productId",
        column: "productId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "product",
        specialized: null,
      },
      {
        key: "productQuantity",
        column: "productQuantity",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "double-precision",
      },
      {
        key: "purchaseId",
        column: "purchaseId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: "purchase",
        specialized: null,
      },
      {
        key: "notionPageId",
        column: "notionPageId",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "vendor",
      "orderId",
      "purchaseId",
      "beneficiaries",
      "funders",
      "sourceClaims",
    ],
    update: [
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "vendor",
      "orderId",
      "purchaseId",
      "beneficiaries",
      "funders",
      "sourceClaims",
    ],
    bulk: ["projectId", "trade", "costType"],
    audit: [
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "purchaseId",
    ],
    output: [
      "id",
      "name",
      "cost",
      "date",
      "lineKind",
      "lineBasis",
      "costType",
      "trade",
      "url",
      "notes",
      "future",
      "projectId",
      "productId",
      "productQuantity",
      "vendor",
      "orderId",
      "purchaseId",
      "purchaseDate",
      "purchaseDisplayLabel",
      "vendorId",
      "vendorLogo",
      "orderUrl",
      "projectName",
      "productName",
      "beneficiaries",
      "funders",
      "sourceClaims",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: { module: "@cubby/schemas/project", export: "expenseCreateInput" },
    update: { module: "@cubby/schemas/project", export: "expenseUpdateData" },
    output: { module: "@cubby/schemas/project", export: "expenseOut" },
  },
  filters: {
    audit: true,
    schema: { module: "@cubby/schemas/project", export: "expenseFilterFields" },
    descriptors: [
      {
        columnId: "name",
        field: "search",
        urlKey: "q",
        kind: "text",
        placeholder: "Search expenses...",
      },
      {
        columnId: "date",
        kind: "range",
        placeholder: "Filter by date...",
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveDateRange",
        },
      },
      {
        columnId: "dateFrom",
        kind: "text",
        placeholder: "Expense date from...",
        urlOnly: true,
      },
      {
        columnId: "dateTo",
        kind: "text",
        placeholder: "Expense date to...",
        urlOnly: true,
      },
      {
        columnId: "dateRelative",
        kind: "select",
        placeholder: "Filter by relative date...",
        urlOnly: true,
      },
      {
        columnId: "costType",
        kind: "multiselect",
        placeholder: "Filter by cost type...",
        deriveSchema: true,
        options: [
          { value: "materials", label: "Materials", color: "var(--chart-1)" },
          { value: "tools", label: "Tools", color: "var(--chart-5)" },
          { value: "services", label: "Services", color: "var(--chart-2)" },
        ],
      },
      {
        columnId: "lineKind",
        kind: "multiselect",
        placeholder: "Filter by line kind...",
        deriveSchema: true,
        options: [
          {
            value: "principal",
            label: "Item or service",
            color: "var(--slate)",
          },
          { value: "tax", label: "Tax", color: "var(--slate)" },
          {
            value: "shipping",
            label: "Shipping or delivery",
            color: "var(--slate)",
          },
          { value: "discount", label: "Discount", color: "var(--positive)" },
          { value: "fee", label: "Fee", color: "var(--warning)" },
          { value: "tip", label: "Tip", color: "var(--plum)" },
          {
            value: "other_adjustment",
            label: "Other adjustment",
            color: "var(--slate)",
          },
        ],
      },
      {
        columnId: "lineBasis",
        kind: "multiselect",
        placeholder: "Filter by itemization...",
        deriveSchema: true,
        options: [
          { value: "item_line", label: "Line item", color: "var(--slate)" },
          {
            value: "allocation",
            label: "Share of a lump sum",
            color: "var(--plum)",
          },
        ],
      },
      {
        columnId: "trade",
        kind: "multiselect",
        placeholder: "Filter by trade...",
        deriveSchema: true,
        optionsRef: {
          module: "~/app/projects/trade-options",
          export: "tradeOptions",
        },
      },
      {
        columnId: "future",
        kind: "boolean",
        placeholder: "Filter by status...",
        deriveSchema: true,
        options: [
          { value: "true", label: "Planned" },
          { value: "false", label: "Already made" },
        ],
      },
      {
        columnId: "cost",
        kind: "range",
        placeholder: "Filter by cost...",
        options: [
          { value: "has", label: "Has cost", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "gte500", label: "$500 and up" },
          { value: "gte200", label: "$200 and up" },
          { value: "gte100", label: "$100 and up" },
          { value: "credits", label: "Credits (≤ $0)" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveCostFilter",
        },
      },
      {
        columnId: "costMin",
        kind: "text",
        placeholder: "Minimum cost...",
        urlOnly: true,
      },
      {
        columnId: "costMax",
        kind: "text",
        placeholder: "Maximum cost...",
        urlOnly: true,
      },
      {
        columnId: "costSign",
        kind: "select",
        placeholder: "Filter by cost direction...",
        urlOnly: true,
      },
      {
        columnId: "disposalPurchasePresenceFilter",
        kind: "presence",
        placeholder: "Filter disposal purchase presence...",
        urlOnly: true,
      },
      {
        columnId: "productQuantity",
        kind: "range",
        placeholder: "Filter by quantity...",
        options: [
          { value: "has", label: "Has quantity", meta: true },
          { value: "none", label: "(none)", meta: true },
          { value: "exactly1", label: "Exactly 1" },
          { value: "gte2", label: "2+ units" },
          { value: "gte5", label: "5+ units" },
        ],
        expandRef: {
          module: "~/app/expenses/expense-options",
          export: "resolveProductQuantityFilter",
        },
      },
      {
        columnId: "productQuantityMin",
        kind: "text",
        placeholder: "Minimum product quantity...",
        urlOnly: true,
      },
      {
        columnId: "productQuantityMax",
        kind: "text",
        placeholder: "Maximum product quantity...",
        urlOnly: true,
      },
      {
        columnId: "notesSearch",
        kind: "text",
        placeholder: "Search notes...",
        urlOnly: true,
      },
      {
        columnId: "urlSearch",
        kind: "text",
        placeholder: "Search url...",
        urlOnly: true,
      },
      {
        columnId: "project",
        field: "projectId",
        kind: "idMulti",
        placeholder: "Filter by project...",
        optionsKey: "project",
        brandRef: { entity: "project", kind: "id" },
        nullable: { field: "projectPresenceFilter", label: "project" },
      },
      {
        columnId: "includeSubProjects",
        urlKey: "subprojects",
        kind: "boolean",
        placeholder: "Include sub-projects...",
        urlOnly: true,
      },
      {
        columnId: "productId",
        kind: "id",
        placeholder: "Filter by product id...",
        brandRef: { entity: "product", kind: "id" },
        urlOnly: true,
      },
      {
        columnId: "product",
        field: "productPresenceFilter",
        kind: "presence",
        placeholder: "Filter by product...",
        options: [
          { value: "has", label: "Has product", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "vendor",
        field: "vendorId",
        kind: "idMulti",
        placeholder: "Filter by vendor...",
        optionsKey: "vendor",
        brandRef: { entity: "vendor", kind: "id" },
        nullable: { field: "vendorPresenceFilter", label: "purchase" },
      },
      {
        columnId: "orderId",
        field: "orderIdPresenceFilter",
        kind: "presence",
        placeholder: "Filter by order id...",
        options: [
          { value: "has", label: "Has order id", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "orderIdExact",
        field: "orderId",
        urlKey: "order",
        kind: "id",
        placeholder: "Filter by order id...",
        urlOnly: true,
      },
      {
        columnId: "purchaseId",
        kind: "id",
        placeholder: "Filter by purchase id...",
        brandRef: { entity: "purchase", kind: "id" },
        urlOnly: true,
      },
      {
        columnId: "related:expense.transactions",
        field: "financialTransactionSearch",
        urlKey: "related-financialTransaction",
        kind: "text",
        placeholder: "Search related purchase transactions...",
      },
      {
        columnId: "financialTransactionId",
        kind: "idMulti",
        placeholder: "Filter by related purchase transactions id...",
        urlOnly: true,
      },
      {
        columnId: "financialTransactionPresenceFilter",
        kind: "presence",
        placeholder: "Filter related purchase transactions presence...",
        urlOnly: true,
      },
    ],
  },
  relations: [
    {
      key: "purchase",
      label: "Purchase",
      target: "purchase",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.purchaseId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Expense.purchaseId", direction: "incoming" }],
      },
    },
    {
      key: "project",
      label: "Project",
      target: "project",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.projectId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Expense.projectId", direction: "incoming" }],
      },
    },
    {
      key: "product",
      label: "Product",
      target: "product",
      cardinality: "one",
      provenance: {
        kind: "local-path",
        steps: [{ edge: "Expense.productId", direction: "outgoing" }],
      },
      inverse: {
        steps: [{ edge: "Expense.productId", direction: "incoming" }],
      },
    },
    {
      key: "transactions",
      label: "Purchase transactions",
      target: "financialTransaction",
      cardinality: "many",
      provenance: {
        kind: "local-path",
        steps: [
          { edge: "Expense.purchaseId", direction: "outgoing" },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "outgoing",
          },
        ],
      },
      inverse: {
        steps: [
          {
            edge: "FinancialTransactionAllocation.transactionId",
            direction: "incoming",
          },
          {
            edge: "FinancialTransactionAllocation.purchaseId",
            direction: "outgoing",
          },
          { edge: "Expense.purchaseId", direction: "incoming" },
        ],
      },
    },
  ],
  search: { enabled: true },
  capabilities: {
    auditable: true,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "soft", bulk: true },
    bulkUpdate: { fields: ["projectId", "trade", "costType"] },
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "search", "create", "update", "delete", "bulkUpdate"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/expense/entity-adapter",
        export: "expenseEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: {
        projection: {
          module: "~/server/repo/search-document",
          export: "refreshSearchDocument",
        },
        semanticText: {
          module: "~/server/repo/search-document",
          export: "getSearchDocumentEmbeddingText",
        },
        dependentRefresh: {
          module: "~/server/services/mutation-side-effects",
          export: "runMutationSideEffects",
        },
      },
    },
  },
});
