import { literalEntity } from "../literal.js";

export default literalEntity({
  key: "image",
  names: { singular: "Image", plural: "Images" },
  route: { basePath: "images" },
  table: "Image",
  identifiers: { brand: "ImageId", shortcode: "IMG-", legacy: null },
  presentation: { titleField: "filename" },
  model: {
    fields: [
      {
        key: "filename",
        kind: "text",
        nullable: false,
        label: "Filename",
        description: null,
        readKey: "filename",
        reference: null,
        control: { kind: "text", renderer: null, options: null },
        display: { list: true, detail: true },
        validation: {
          read: { kind: "string" },
          update: { kind: "string", trim: true, min: 1, max: 255 },
        },
      },
      {
        key: "id",
        kind: "identifier",
        nullable: false,
        label: "Id",
        description: null,
        readKey: "id",
        reference: null,
        control: null,
        display: { list: false, detail: false },
        validation: {
          read: {
            kind: "source",
            source: {
              module: "@cubby/schemas/identifiers",
              export: "imageShortcode",
            },
          },
        },
      },
      {
        key: "url",
        kind: "text",
        nullable: false,
        label: "Url",
        description: null,
        readKey: "url",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "url" } },
      },
      {
        key: "key",
        kind: "text",
        nullable: false,
        label: "Key",
        description: null,
        readKey: "key",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string" } },
      },
      {
        key: "size",
        kind: "number",
        nullable: false,
        label: "Size",
        description: null,
        readKey: "size",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: { kind: "number", integer: true, positive: true },
        },
      },
      {
        key: "contentType",
        kind: "text",
        nullable: false,
        label: "Content Type",
        description: null,
        readKey: "contentType",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string" } },
      },
      {
        key: "status",
        kind: "enum",
        nullable: false,
        label: "Status",
        description: null,
        readKey: "status",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "enum",
            values: ["PENDING", "UPLOADED", "FAILED"],
          },
        },
      },
      {
        key: "width",
        kind: "number",
        nullable: true,
        label: "Width",
        description: null,
        readKey: "width",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "number",
            integer: true,
            positive: true,
            nullable: true,
          },
        },
      },
      {
        key: "height",
        kind: "number",
        nullable: true,
        label: "Height",
        description: null,
        readKey: "height",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "number",
            integer: true,
            positive: true,
            nullable: true,
          },
        },
      },
      {
        key: "detectedContentType",
        kind: "text",
        nullable: true,
        label: "Detected Content Type",
        description: null,
        readKey: "detectedContentType",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "sha256",
        kind: "text",
        nullable: true,
        label: "Sha256",
        description: null,
        readKey: "sha256",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "string", nullable: true } },
      },
      {
        key: "renderStatus",
        kind: "enum",
        nullable: true,
        label: "Render Status",
        description: null,
        readKey: "renderStatus",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "enum",
            values: ["unverified", "verified", "failed"],
            nullable: true,
          },
        },
      },
      {
        key: "storageStatus",
        kind: "enum",
        nullable: true,
        label: "Storage Status",
        description: null,
        readKey: "storageStatus",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: {
          read: {
            kind: "enum",
            values: ["unverified", "available", "missing", "metadata_mismatch"],
            nullable: true,
          },
        },
      },
      {
        key: "verifiedAt",
        kind: "timestamp",
        nullable: true,
        label: "Verified At",
        description: null,
        readKey: "verifiedAt",
        reference: null,
        control: null,
        display: { list: true, detail: true },
        validation: { read: { kind: "timestamp", nullable: true } },
      },
      {
        key: "createdAt",
        kind: "timestamp",
        nullable: false,
        label: "Created At",
        description: null,
        readKey: "createdAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "updatedAt",
        kind: "timestamp",
        nullable: false,
        label: "Updated At",
        description: null,
        readKey: "updatedAt",
        reference: null,
        control: null,
        display: { list: false, detail: true },
        validation: { read: { kind: "timestamp" } },
      },
      {
        key: "shortcode",
        kind: "text",
        nullable: false,
        label: "Shortcode",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "targetType",
        kind: "enum",
        nullable: true,
        label: "Target Type",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "targetId",
        kind: "identifier",
        nullable: true,
        label: "Target ID",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "idempotencyKey",
        kind: "text",
        nullable: true,
        label: "Idempotency Key",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
      {
        key: "deletedAt",
        kind: "timestamp",
        nullable: true,
        label: "Deleted At",
        description: null,
        readKey: null,
        reference: null,
        control: null,
        display: { list: false, detail: false },
      },
    ],
    storage: [
      {
        key: "id",
        column: "id",
        kind: "identifier",
        nullable: false,
        default: "generated",
        defaultValue: null,
        reference: null,
        specialized: "primary-key:ImageId",
      },
      {
        key: "shortcode",
        column: "shortcode",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "shortcode",
      },
      {
        key: "key",
        column: "key",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "filename",
        column: "filename",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "size",
        column: "size",
        kind: "number",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "contentType",
        column: "contentType",
        kind: "text",
        nullable: false,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "status",
        column: "status",
        kind: "enum",
        nullable: false,
        default: "literal",
        defaultValue: "'PENDING'",
        reference: null,
        specialized: "enum:ImageStatus",
      },
      {
        key: "width",
        column: "width",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "height",
        column: "height",
        kind: "number",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "detectedContentType",
        column: "detectedContentType",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "sha256",
        column: "sha256",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "renderStatus",
        column: "renderStatus",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:ImageRenderStatus",
      },
      {
        key: "storageStatus",
        column: "storageStatus",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:ImageStorageStatus",
      },
      {
        key: "verifiedAt",
        column: "verifiedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "targetType",
        column: "targetType",
        kind: "enum",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: "enum:targetType",
      },
      {
        key: "targetId",
        column: "targetId",
        kind: "identifier",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "idempotencyKey",
        column: "idempotencyKey",
        kind: "text",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "createdAt",
        column: "createdAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
      {
        key: "updatedAt",
        column: "updatedAt",
        kind: "timestamp",
        nullable: false,
        default: "now",
        defaultValue: null,
        reference: null,
        specialized: "updated-at",
      },
      {
        key: "deletedAt",
        column: "deletedAt",
        kind: "timestamp",
        nullable: true,
        default: "none",
        defaultValue: null,
        reference: null,
        specialized: null,
      },
    ],
    create: [],
    update: ["filename"],
    bulk: [],
    audit: [],
    output: [
      "id",
      "url",
      "key",
      "filename",
      "size",
      "contentType",
      "status",
      "width",
      "height",
      "detectedContentType",
      "sha256",
      "renderStatus",
      "storageStatus",
      "verifiedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  fields: {
    create: null,
    update: { module: "@cubby/schemas/image", export: "imageUpdateInput" },
    output: { module: "@cubby/schemas/image", export: "imageOut" },
    list: {
      module: "@cubby/schemas/image",
      export: "imageWithEntitySchema",
    },
    detail: {
      module: "@cubby/schemas/image",
      export: "imageWithEntitySchema",
    },
  },
  filters: {
    schema: { module: "@cubby/schemas/image", export: "imageFilterFields" },
    descriptors: [
      {
        columnId: "filename",
        field: "nameFilter",
        kind: "text",
        placeholder: "Filter by filename...",
        deriveSchema: true,
        schemaDescription: "Filter by filename (substring)",
      },
      {
        columnId: "status",
        kind: "multiselect",
        placeholder: "Filter by upload status...",
        deriveSchema: true,
        schemaDescription: "Filter by upload status",
        options: [
          { value: "PENDING", label: "Pending", color: "var(--slate)" },
          { value: "UPLOADED", label: "Uploaded", color: "var(--positive)" },
          { value: "FAILED", label: "Failed", color: "var(--destructive)" },
        ],
      },
      {
        columnId: "entity",
        field: "referencePresenceFilter",
        kind: "presence",
        placeholder: "Filter references...",
        options: [
          { value: "has", label: "Has reference", meta: true },
          { value: "none", label: "(none)", meta: true },
        ],
      },
      {
        columnId: "createdAt",
        kind: "range",
        placeholder: "Filter by created date...",
        options: [
          { value: "olderThan1h", label: "Older than 1 hour" },
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveImageCreatedDate",
        },
      },
      {
        columnId: "updatedAt",
        kind: "range",
        placeholder: "Filter by updated date...",
        options: [
          { value: "30d", label: "Last 30 days" },
          { value: "90d", label: "Last 90 days" },
          { value: "ytd", label: "Year to date" },
          { value: "1y", label: "Last 12 months" },
        ],
        expandRef: {
          module: "~/entities/filter-behavior",
          export: "resolveUpdatedDate",
        },
      },
    ],
  },
  relations: [],
  search: { enabled: false },
  capabilities: {
    auditable: false,
    images: false,
    countable: true,
    softDelete: true,
    delete: { mode: "hard", bulk: true },
    bulkUpdate: null,
    merge: false,
    operationOwners: { delete: "kernel", merge: null },
    mcp: ["get", "list", "update", "delete"],
  },
  extensions: {
    countFilter: null,
    relatednessSignals: null,
    mcpNames: null,
    ports: {
      repository: {
        module: "~/server/repo/image.entity-adapter",
        export: "imageEntityAdapter",
      },
      references: {
        label: { module: "~/entities/entities", export: "entityLabel" },
        resolver: {
          module: "~/server/repo/shortcode-resolver",
          export: "resolveLiveShortcode",
        },
      },
      filters: {
        module: "~/entities/filter-manifest",
        export: "getEntityFilters",
      },
      search: { projection: null, semanticText: null, dependentRefresh: null },
    },
  },
});
