// Fontsource variable fonts - loaded via bundler for better performance
import "@fontsource-variable/fraunces";
import "@fontsource-variable/nunito";

import { TanStackDevtools } from "@tanstack/react-devtools";
import type { QueryClient } from "@tanstack/react-query";
import {
  createRootRouteWithContext,
  HeadContent,
  Link,
  Outlet,
  Scripts,
} from "@tanstack/react-router";
import { TanStackRouterDevtoolsPanel } from "@tanstack/react-router-devtools";
import type { TRPCOptionsProxy } from "@trpc/tanstack-react-query";
import * as React from "react";
import { AppFooter } from "~/app/_components/footer";
import { MainNav } from "~/app/_components/MainNav";
import { BottomNav } from "~/app/_components/navigation/bottom-nav";
import { RouteErrorComponent } from "~/components/route-error";
import { Toaster } from "~/components/ui/sonner";
import { DebugContextProvider, useDebug } from "~/hooks/useDebug";
import type { TRPCRouter } from "~/integrations/trpc/router";
import { useFlag } from "~/lib/flags";
import { PerfProfiler } from "~/lib/perf/PerfProfiler";
import TanStackQueryDevtools from "../integrations/tanstack-query/devtools";
import { Provider } from "../integrations/tanstack-query/root-provider";
import appCss from "../styles.css?url";

// Lazy: the command menu pulls in cmdk + react-markdown + the agent stream,
// none of which is needed for first paint. Loaded on first ⌘K / search click.
const GlobalCommandMenu = React.lazy(() =>
  import("~/app/_components/command-menu").then((m) => ({
    default: m.GlobalCommandMenu,
  })),
);

// Lazy + flag-gated: the perf overlay and its web-vitals collector only load when
// the `perfOverlay` flag is on (flippable on /settings, any environment).
const PerfOverlay = React.lazy(() =>
  import("~/app/_components/perf-overlay").then((m) => ({
    default: m.PerfOverlay,
  })),
);

function PerfOverlayMount() {
  const enabled = useFlag("perfOverlay");
  if (!enabled) return null;
  return (
    <React.Suspense fallback={null}>
      <PerfOverlay />
    </React.Suspense>
  );
}

interface MyRouterContext {
  queryClient: QueryClient;
  trpc: TRPCOptionsProxy<TRPCRouter>;
}

export const Route = createRootRouteWithContext<MyRouterContext>()({
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        name: "viewport",
        content:
          "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover",
      },
      {
        title: "Cubby",
      },
      {
        name: "theme-color",
        content: "#3a3530",
      },
      {
        name: "apple-mobile-web-app-title",
        content: "Cubby",
      },
      {
        name: "apple-mobile-web-app-capable",
        content: "yes",
      },
      {
        name: "apple-mobile-web-app-status-bar-style",
        content: "black-translucent",
      },
    ],
    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },
      {
        rel: "manifest",
        href: "/manifest.json",
      },
      {
        rel: "icon",
        type: "image/svg+xml",
        href: "/favicon.svg",
      },
      {
        rel: "apple-touch-icon",
        href: "/apple-touch-icon.png",
      },
      // Apple splash screens — generated by `pnpm run gen:pwa-splash`
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-750x1334.png",
        media:
          "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-828x1792.png",
        media:
          "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1125x2436.png",
        media:
          "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1170x2532.png",
        media:
          "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1179x2556.png",
        media:
          "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1206x2622.png",
        media:
          "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1284x2778.png",
        media:
          "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1290x2796.png",
        media:
          "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1320x2868.png",
        media:
          "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1620x2160.png",
        media:
          "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1668x2388.png",
        media:
          "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-2048x2732.png",
        media:
          "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)",
      },
    ],
  }),

  component: RootComponent,
  shellComponent: RootDocument,
  notFoundComponent: NotFoundComponent,
  errorComponent: RouteErrorComponent,
});

function RootComponent() {
  const { queryClient } = Route.useRouteContext();
  const [commandMenuOpen, setCommandMenuOpen] = React.useState(false);
  // Only mount (and thus fetch the chunk for) the command menu once it's first
  // requested. `mounted` latches true so it stays mounted after the first open.
  const [commandMenuMounted, setCommandMenuMounted] = React.useState(false);

  const openCommandMenu = React.useCallback(() => {
    setCommandMenuMounted(true);
    setCommandMenuOpen(true);
  }, []);

  // Shell-owned ⌘K hotkey (toggles), so the shortcut works before the lazily
  // loaded menu has mounted. The menu no longer registers its own listener.
  React.useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setCommandMenuMounted(true);
        setCommandMenuOpen((prev) => !prev);
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, []);

  return (
    <Provider queryClient={queryClient}>
      <DebugContextProvider>
        <div className="flex min-h-dvh flex-col">
          <div className="border-b">
            <div className="mx-auto flex h-16 w-full max-w-7xl items-center px-4 md:px-6">
              <MainNav className="mx-0" onSearchClick={openCommandMenu} />
            </div>
          </div>
          <main className="w-full flex-1 px-4 pt-4 pb-20 md:px-6 md:pb-4">
            {/* biome-ignore lint/correctness/useUniqueElementIds: React <Profiler> id, not a DOM id */}
            <PerfProfiler id="route">
              <Outlet />
            </PerfProfiler>
          </main>
          <AppFooter />
        </div>
        <BottomNav />
        {commandMenuMounted && (
          <React.Suspense fallback={null}>
            <GlobalCommandMenu
              open={commandMenuOpen}
              onOpenChange={setCommandMenuOpen}
            />
          </React.Suspense>
        )}
        <Toaster />
        <PerfOverlayMount />
        <DevtoolsWrapper />
      </DebugContextProvider>
    </Provider>
  );
}

function DevtoolsWrapper() {
  const { isDevtoolsVisible } = useDebug();

  if (!isDevtoolsVisible) {
    return null;
  }

  // Wrapped in a Fragment so the JSX is still valid after
  // @tanstack/devtools-vite strips <TanStackDevtools/> from production builds
  // (the stripped return collapses to `return (<></>);`, not `return ();`).
  return (
    // biome-ignore lint/complexity/noUselessFragments: load-bearing — removing it breaks the production build (see comment above).
    <>
      <TanStackDevtools
        config={{
          position: "bottom-right",
          openHotkey: [],
        }}
        plugins={[
          {
            name: "Tanstack Router",
            render: <TanStackRouterDevtoolsPanel />,
          },
          TanStackQueryDevtools,
        ]}
      />
    </>
  );
}

function NotFoundComponent() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center space-y-6 p-4">
      <div className="flex items-center space-x-3">
        <svg viewBox="0 0 64 64" className="h-12 w-12" aria-hidden="true">
          <rect x="0" y="0" width="64" height="64" rx="10" fill="#3a3530" />
          <rect x="8" y="10" width="48" height="3" rx="1" fill="#5c5550" />
          <rect x="8" y="30" width="48" height="3" rx="1" fill="#5c5550" />
          <rect x="8" y="50" width="48" height="3" rx="1" fill="#5c5550" />
          <rect x="12" y="15" width="10" height="13" rx="2" fill="#c2603d" />
          <circle cx="32" cy="22" r="6" fill="#d98a68" />
          <rect x="42" y="17" width="10" height="11" rx="2" fill="#fdfbf7" />
          <circle cx="16" cy="42" r="5" fill="#d98a68" />
          <rect x="26" y="35" width="12" height="13" rx="2" fill="#c2603d" />
          <rect x="44" y="38" width="8" height="10" rx="2" fill="#fdfbf7" />
        </svg>
        <h1 className="font-bold text-4xl">404</h1>
      </div>
      <div className="space-y-2 text-center">
        <h2 className="font-semibold text-2xl">Page Not Found</h2>
        <p className="max-w-md text-muted-foreground">
          The page you're looking for doesn't exist or has been moved.
        </p>
      </div>
      <Link
        to="/"
        className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 font-medium text-primary-foreground text-sm shadow transition-colors hover:bg-primary/90"
      >
        Return Home
      </Link>
    </div>
  );
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}
