// Fontsource variable fonts - loaded via bundler for better performance.
// Warm-Paper Ledger type system: Space Grotesk (geometric sans) for headings,
// JetBrains Mono for all data/metrics, Inter for body/UI prose. Fraunces retired.
import "../fonts.css";

import { TanStackDevtools } from "@tanstack/react-devtools";
import type { QueryClient } from "@tanstack/react-query";
import {
  createRootRouteWithContext,
  HeadContent,
  Outlet,
  Scripts,
} from "@tanstack/react-router";
import { TanStackRouterDevtoolsPanel } from "@tanstack/react-router-devtools";
import type { TRPCOptionsProxy } from "@trpc/tanstack-react-query";
import * as React from "react";
import { AppFooter } from "~/app/_components/footer";
import { MainNav } from "~/app/_components/MainNav";
import { BottomNav } from "~/app/_components/navigation/bottom-nav";
import { RouteErrorComponent } from "~/components/route-error";
import { RouteNotFound } from "~/components/route-not-found";
import { Toaster } from "~/components/ui/sonner";
import { DebugContextProvider, useDebug } from "~/hooks/useDebug";
import type { TRPCRouter } from "~/integrations/trpc/router";
import { getClientAuthed, getGuardSession } from "~/lib/auth-guard";
import { useFlag } from "~/lib/flags";
import { PerfProfiler } from "~/lib/perf/PerfProfiler";
import TanStackQueryDevtools from "../integrations/tanstack-query/devtools";
import { Provider } from "../integrations/tanstack-query/root-provider";
import appCss from "../styles.css?url";

// Lazy: the command menu pulls in cmdk + react-markdown + the agent stream,
// none of which is needed for first paint. Loaded on first ⌘K / search click.
const GlobalCommandMenu = React.lazy(() =>
  import("~/app/_components/command-menu").then((m) => ({
    default: m.GlobalCommandMenu,
  })),
);

// Lazy + flag-gated: the perf overlay and its web-vitals collector only load when
// the `perfOverlay` flag is on (flippable on /settings, any environment).
const PerfOverlay = React.lazy(() =>
  import("~/app/_components/perf-overlay").then((m) => ({
    default: m.PerfOverlay,
  })),
);

function PerfOverlayMount() {
  const enabled = useFlag("perfOverlay");
  if (!enabled) return null;
  return (
    <React.Suspense fallback={null}>
      <PerfOverlay />
    </React.Suspense>
  );
}

interface MyRouterContext {
  queryClient: QueryClient;
  trpc: TRPCOptionsProxy<TRPCRouter>;
}

export const Route = createRootRouteWithContext<MyRouterContext>()({
  // Resolve `isAuthed` for nav chrome (MainNav, BottomNav) + the child guards
  // (`/`, `_authenticated`). On the SERVER (SSR / direct + refresh loads) read
  // the signed session cookie in-process so the first paint isn't a flash and
  // direct loads to protected routes gate server-side (the security path). On
  // CLIENT navigations read better-auth's in-memory session store synchronously
  // instead — `import.meta.env.SSR` is statically replaced, so the server-fn is
  // dead-code-eliminated from the client bundle and an in-app navigation no
  // longer pays a `/_serverFn/` round-trip.
  beforeLoad: async () => {
    if (import.meta.env.SSR) {
      const session = await getGuardSession();
      return { isAuthed: !!session };
    }
    return { isAuthed: getClientAuthed() };
  },
  head: () => ({
    meta: [
      {
        charSet: "utf-8",
      },
      {
        // Allow pinch-zoom (no maximum-scale / user-scalable=no) — locking zoom
        // is an accessibility anti-pattern and the PWA doesn't rely on it.
        name: "viewport",
        content: "width=device-width, initial-scale=1, viewport-fit=cover",
      },
      {
        title: "Cubby",
      },
      {
        // Warm-Paper Ledger: the iOS status-bar tint matches the paper-surface
        // sticky header (bg-card) instead of the old dark chrome.
        name: "theme-color",
        content: "#fcfaf4",
      },
      {
        name: "apple-mobile-web-app-title",
        content: "Cubby",
      },
      {
        name: "apple-mobile-web-app-capable",
        content: "yes",
      },
      {
        name: "apple-mobile-web-app-status-bar-style",
        content: "black-translucent",
      },
    ],
    links: [
      {
        rel: "stylesheet",
        href: appCss,
      },
      {
        rel: "manifest",
        href: "/manifest.json",
      },
      {
        rel: "icon",
        type: "image/svg+xml",
        // Localhost gets a hot-magenta variant so the dev tab is obvious
        // among prod tabs; build-time DEV flag → no hydration mismatch.
        href: import.meta.env.DEV ? "/favicon-dev.svg" : "/favicon.svg",
      },
      {
        rel: "apple-touch-icon",
        href: "/apple-touch-icon.png",
      },
      // Apple splash screens — generated by `pnpm run gen:pwa-splash`
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-750x1334.png",
        media:
          "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-828x1792.png",
        media:
          "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1125x2436.png",
        media:
          "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1170x2532.png",
        media:
          "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1179x2556.png",
        media:
          "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1206x2622.png",
        media:
          "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1284x2778.png",
        media:
          "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1290x2796.png",
        media:
          "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1320x2868.png",
        media:
          "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1620x2160.png",
        media:
          "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-1668x2388.png",
        media:
          "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)",
      },
      {
        rel: "apple-touch-startup-image",
        href: "/splash/apple-splash-2048x2732.png",
        media:
          "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)",
      },
    ],
  }),

  component: RootComponent,
  shellComponent: RootDocument,
  notFoundComponent: RouteNotFound,
  errorComponent: RouteErrorComponent,
});

function RootComponent() {
  const { queryClient } = Route.useRouteContext();
  const [commandMenuOpen, setCommandMenuOpen] = React.useState(false);
  // Only mount (and thus fetch the chunk for) the command menu once it's first
  // requested. `mounted` latches true so it stays mounted after the first open.
  const [commandMenuMounted, setCommandMenuMounted] = React.useState(false);

  const openCommandMenu = React.useCallback(() => {
    setCommandMenuMounted(true);
    setCommandMenuOpen(true);
  }, []);

  // Shell-owned ⌘K hotkey (toggles), so the shortcut works before the lazily
  // loaded menu has mounted. The menu no longer registers its own listener.
  React.useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setCommandMenuMounted(true);
        setCommandMenuOpen((prev) => !prev);
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, []);

  return (
    <Provider queryClient={queryClient}>
      <DebugContextProvider>
        <div className="flex min-h-dvh flex-col">
          <div className="sticky top-0 z-40 border-b-[3px] border-b-foreground bg-card print:hidden">
            <div className="mx-auto flex h-12 w-full max-w-7xl items-center px-2 md:px-6">
              <MainNav className="mx-0" onSearchClick={openCommandMenu} />
            </div>
          </div>
          <main className="w-full flex-1 px-2 pt-4 pb-20 md:px-6 md:pb-4">
            {/* biome-ignore lint/correctness/useUniqueElementIds: React <Profiler> id, not a DOM id */}
            <PerfProfiler id="route">
              <Outlet />
            </PerfProfiler>
          </main>
          <AppFooter />
        </div>
        <BottomNav />
        {commandMenuMounted && (
          <React.Suspense fallback={null}>
            <GlobalCommandMenu
              open={commandMenuOpen}
              onOpenChange={setCommandMenuOpen}
            />
          </React.Suspense>
        )}
        <Toaster />
        <PerfOverlayMount />
        <DevtoolsWrapper />
      </DebugContextProvider>
    </Provider>
  );
}

function DevtoolsWrapper() {
  const { isDevtoolsVisible } = useDebug();

  if (!isDevtoolsVisible) {
    return null;
  }

  // Wrapped in a Fragment so the JSX is still valid after
  // @tanstack/devtools-vite strips <TanStackDevtools/> from production builds
  // (the stripped return collapses to `return (<></>);`, not `return ();`).
  return (
    // biome-ignore lint/complexity/noUselessFragments: load-bearing — removing it breaks the production build (see comment above).
    <>
      <TanStackDevtools
        config={{
          position: "bottom-right",
          openHotkey: [],
        }}
        plugins={[
          {
            name: "Tanstack Router",
            render: <TanStackRouterDevtoolsPanel />,
          },
          TanStackQueryDevtools,
        ]}
      />
    </>
  );
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}
