import { createFileRoute } from "@tanstack/react-router";

import { LegalPage } from "~/app/legal/legal-page";
import { pageTitle } from "~/lib/page-title";

// Public by design: Google's OAuth consent screen requires an unauthenticated
// privacy-policy URL on an authorized domain, and the restricted `gmail.readonly`
// scope requires the Limited Use disclosure below.
export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: pageTitle("Privacy") }] }),
  component: PrivacyRoute,
});

function PrivacyRoute() {
  return (
    <LegalPage title="Privacy policy" updated="September 2026">
      <p>
        Cubby is a private household inventory app run as a single instance for
        one household. There are no other users and no public sign-up.
      </p>
      <p>
        <strong>What it stores.</strong> Records the household enters —
        products, purchases, receipts, photos, recipes, meals and tasks — plus
        the account name and email address of each member login.
      </p>
      <p>
        <strong>Google data.</strong> With the member&rsquo;s consent, Cubby
        reads Gmail messages read-only for the sole purpose of finding order and
        receipt emails and importing their contents as purchases. It never sends
        email, never modifies a mailbox, and reads nothing else. Access and
        refresh tokens are stored encrypted and are used only for that import.
      </p>
      <p>
        <strong>Limited Use.</strong> Cubby&rsquo;s use of information received
        from Google APIs adheres to the{" "}
        <a
          href="https://developers.google.com/terms/api-services-user-data-policy"
          target="_blank"
          rel="noreferrer"
        >
          Google API Services User Data Policy
        </a>
        , including the Limited Use requirements. Google user data is never
        sold, never transferred to third parties except as needed to provide the
        app, never used for advertising, and never read by humans except with
        the member&rsquo;s explicit consent or as required by law.
      </p>
      <p>
        <strong>Where it lives.</strong> Data is held in the household&rsquo;s
        own database and object storage. Image descriptions are generated by
        sending the image to a model provider through an API gateway. No
        analytics or advertising trackers are used, and nothing is sold.
      </p>
      <p>
        <strong>Deletion.</strong> A member may revoke Google access at any time
        at{" "}
        <a
          href="https://myaccount.google.com/permissions"
          target="_blank"
          rel="noreferrer"
        >
          myaccount.google.com/permissions
        </a>
        , and may ask the operator to delete their login and its imported data.
      </p>
      <p>Questions: the household operator who gave you this link.</p>
    </LegalPage>
  );
}
