/**
 * Maps every E2E spec file to the source globs it exercises, so
 * `scripts/e2e-affected.ts` can select only the specs a change affects for
 * fast local iteration (see `pnpm --dir apps/web test:e2e:affected`).
 *
 * Two layers, merged into `SPEC_AREAS`:
 *
 * - `DERIVED_SPEC_GLOBS` (`spec-areas.derived.ts`, generated by
 *   `scripts/generate-spec-areas.ts`): the route files a spec visits and the
 *   `src/app/<feature>/**` directories those routes import. A new route, or a
 *   spec that starts visiting a new URL, needs no edit here; the generator's
 *   drift check in `e2e-affected.unit.test.ts` says when to rerun it.
 * - `SPEC_EXTRA_GLOBS` (below, hand-written): what a spec's text cannot reveal
 *   - the server repositories, operations, contracts, shared libs, and
 *   `_components` areas its flows reach. Add a glob here when a change to
 *   that file should rerun the spec.
 *
 * Every glob is relative to the repository root (matching the changed-file
 * list), e.g. `apps/web/src/routes/__root.tsx`. When unsure, prefer a broader
 * glob (or ALL_SPECS_TRIGGERS) over missing one -- the affected script fails
 * safe to "run everything" for anything it can't place, but a stale narrow
 * entry silently skips a spec that should run.
 */

import type { SpecGlobMap } from "../../scripts/generate-spec-areas.ts";
import { DERIVED_SPEC_GLOBS } from "./spec-areas.derived.ts";

const WEB = "apps/web";

/**
 * Shared seams: a change to any of these selects every spec, because they
 * are load-bearing for the whole suite (test harness plumbing) or are the
 * generic foundation nearly every route/spec renders through (the entity
 * kernel, the entity display/editing spine, and the app shell).
 */
export const ALL_SPECS_TRIGGERS: readonly string[] = [
  `${WEB}/tests/e2e/e2e-*.ts`,
  `${WEB}/tests/e2e/fixtures-*.ts`,
  `${WEB}/tests/e2e/harness-services/**`,
  `${WEB}/tests/e2e/dnd-helpers.ts`,
  `${WEB}/playwright.config.ts`,
  `${WEB}/tooling/**`,
  `${WEB}/scripts/**`,
  `${WEB}/wrangler*.{json,jsonc,toml}`,
  `${WEB}/tsconfig*.json`,
  `${WEB}/project.json`,
  "scripts/**",
  "package.json",
  "nx.json",
  "pnpm-workspace.yaml",
  "tsconfig*.json",
  `${WEB}/src/routes/__root.tsx`,
  `${WEB}/src/routes/_authenticated.tsx`,
  // App shell / global navigation, rendered on every authenticated page.
  `${WEB}/src/app/_components/navigation/**`,
  `${WEB}/src/app/_components/navbar/**`,
  // The generic entity kernel (server) and its browser-side counterpart
  // (list/detail/editing/filters/manifest) that most routes render through.
  `${WEB}/src/server/entity-kernel/**`,
  `${WEB}/src/entities/**`,
  `${WEB}/src/app/_components/entity-list/**`,
  `${WEB}/src/app/_components/entity-detail/**`,
  `${WEB}/src/app/_components/actions/**`,
  `${WEB}/src/app/_components/table/**`,
  `${WEB}/src/app/_components/forms/**`,
  `${WEB}/src/app/_components/form-fields.ts`,
  `${WEB}/src/app/_components/form-utils*.ts*`,
  `${WEB}/src/app/_components/combobox/**`,
  `${WEB}/src/app/_components/merge/**`,
  `${WEB}/src/app/_components/relatedness/**`,
  `${WEB}/src/app/_components/relationships/**`,
  `${WEB}/src/app/_components/entity-media/**`,
  `${WEB}/src/app/_components/entity-workbench-inspector.tsx`,
  `${WEB}/src/app/_components/inspector-frame.tsx`,
  `${WEB}/src/server/db/**`,
  `${WEB}/src/server.ts`,
  `${WEB}/src/cf-server.ts`,
  `${WEB}/src/integrations/tanstack-query/start-transport.ts`,
  `${WEB}/src/integrations/tanstack-query/browser-operation-transport.ts`,
  `${WEB}/src/server/browser-operation-dispatch.ts`,
  `${WEB}/src/server/start-operation-dispatch.server.ts`,
  `${WEB}/vite.config.ts`,
  `${WEB}/package.json`,
  "pnpm-lock.yaml",
  "packages/**",
];

export interface SpecAreaEntry {
  /** Spec file path relative to `apps/web/tests/e2e/`. */
  file: string;
  /** Repo-root-relative globs whose change should select this spec. */
  globs: readonly string[];
}

/** Hand-written globs per spec; see the header for what belongs here. */
export const SPEC_EXTRA_GLOBS: SpecGlobMap = {
  "activity.spec.ts": [
    `${WEB}/src/routes/_authenticated/activities.tsx`,
    `${WEB}/src/app/runs/**`,
    `${WEB}/src/server/repo/activity.ts`,
    `${WEB}/src/server/repo/activity-input.ts`,
  ],
  "browser-operation-dispatch.spec.ts": [
    `${WEB}/src/lib/browser-operation-path.ts`,
    `${WEB}/src/lib/superjson-wire.ts`,
    `${WEB}/src/routes/api/browser/dispatch.ts`,
    `${WEB}/src/server.ts`,
    `${WEB}/src/server/start-operation-dispatch.contract.ts`,
    `${WEB}/src/server/start-operation.contract.ts`,
    `${WEB}/src/server/operations/audit-log.ts`,
    `${WEB}/src/server/repo/vendor.ts`,
  ],
  "bulk-edit.spec.ts": [
    `${WEB}/src/app/tasks/**`,
    `${WEB}/src/server/repo/task/**`,
    `${WEB}/src/server/repo/garden/**`,
  ],
  "list-delete.spec.ts": [
    `${WEB}/src/app/_components/hooks/useOptimisticDelete.tsx`,
    `${WEB}/src/app/_components/hooks/useEntityListPresentation.tsx`,
    `${WEB}/src/app/tasks/**`,
    `${WEB}/src/server/repo/task/**`,
  ],
  "calendar.spec.ts": [
    `${WEB}/src/server/repo/calendar.ts`,
    `${WEB}/src/server/repo/calendar-caldav.ts`,
    `${WEB}/src/server/repo/calendar-plantings.ts`,
    `${WEB}/src/server/repo/task/**`,
  ],
  "console-ledger-overhaul.spec.ts": [`${WEB}/src/app/_components/home/**`],
  "cookbook-edit.spec.ts": [
    `${WEB}/src/app/cookbooks/**`,
    `${WEB}/src/app/_components/recipe/recipe-form/**`,
    `${WEB}/src/app/_components/entity-detail/detail-edit-overrides.tsx`,
    `${WEB}/src/entities/list-columns/cookbook.tsx`,
    `${WEB}/src/server/repo/cookbook.ts`,
    `${WEB}/src/server/repo/cookbook.repository.ts`,
    `${WEB}/src/server/repo/recipe/update-helpers.ts`,
    `${WEB}/src/server/operations/cookbook.server.ts`,
    `${WEB}/src/contracts/cookbook.contract.ts`,
  ],
  "cookbook-photos.spec.ts": [
    `${WEB}/src/routes/_authenticated/cookbooks.$shortcode.tsx`,
    `${WEB}/src/routes/_authenticated/cookbooks.index.tsx`,
    `${WEB}/src/routes/_authenticated/recipes.$shortcode.tsx`,
    `${WEB}/src/app/cookbooks/**`,
    `${WEB}/src/app/recipes/**`,
    `${WEB}/src/app/images/**`,
    `${WEB}/src/server/repo/cookbook.ts`,
    `${WEB}/src/server/repo/recipe/**`,
    `${WEB}/src/server/repo/image.ts`,
    `${WEB}/src/server/repo/import-recipe-convert.ts`,
    `${WEB}/src/contracts/cookbook.contract.ts`,
  ],
  "create-recipe-full-flow.spec.ts": [
    `${WEB}/src/app/recipes/**`,
    `${WEB}/src/server/repo/recipe/**`,
    `${WEB}/src/server/repo/ingredient/**`,
  ],
  "recipe-flow.spec.ts": [
    `${WEB}/src/app/recipes/**`,
    `${WEB}/src/server/repo/recipe/**`,
    `${WEB}/src/server/ai/features.ts`,
    `${WEB}/src/server/ai/**`,
    `${WEB}/tests/e2e/build-constants.ts`,
  ],
  "database-socket-lifecycle.spec.ts": [
    `${WEB}/src/server/db.ts`,
    `${WEB}/src/server/db-runtime-resolver.ts`,
    `${WEB}/src/server/database-freshness/**`,
    `${WEB}/src/server/background-tasks/**`,
    `${WEB}/src/server/services/mutation-side-effects.ts`,
  ],
  "declared-record-lists.spec.ts": [
    `${WEB}/src/app/purchases/**`,
    `${WEB}/src/app/expenses/**`,
    `${WEB}/src/app/locations/**`,
    `${WEB}/src/server/repo/purchase.ts`,
    `${WEB}/src/server/repo/expense/**`,
    `${WEB}/src/server/repo/location/**`,
  ],
  "dnd-interactions.spec.ts": [
    `${WEB}/src/app/tasks/**`,
    `${WEB}/src/server/repo/task/**`,
  ],
  "enrichment-workflow.spec.ts": [
    `${WEB}/src/routes/api/workflow-stream/**`,
    `${WEB}/src/app/ingredients/**`,
    `${WEB}/src/server/repo/ingredient/**`,
  ],
  "entity-card-layout.spec.ts": [
    `${WEB}/src/app/products/**`,
    `${WEB}/src/app/cookbooks/**`,
    `${WEB}/src/server/repo/product/**`,
    `${WEB}/src/server/repo/cookbook.ts`,
  ],
  "entity-dependency-graph.spec.ts": [
    `${WEB}/src/server/repo/entity-graph.ts`,
    `${WEB}/src/server/repo/entity-graph-explore.ts`,
    `${WEB}/src/server/repo/entity-graph-paths.ts`,
    `${WEB}/src/server/repo/entity-graph-path-search.ts`,
  ],
  "entity-editor-lifecycle.spec.ts": [
    `${WEB}/src/app/vendors/**`,
    `${WEB}/src/server/repo/vendor.ts`,
    `${WEB}/src/server/repo/vendor.entity-adapter.ts`,
  ],
  "field-guide-mobile.spec.ts": [
    `${WEB}/src/app/_components/data-table/shelf.tsx`,
    `${WEB}/src/components/layouts/page-hero.tsx`,
    `${WEB}/src/styles.css`,
    `${WEB}/src/server/repo/product/**`,
  ],
  "garden.spec.ts": [
    `${WEB}/src/routes/_authenticated/garden-entries.$shortcode.tsx`,
    `${WEB}/src/routes/_authenticated/garden-entries.index.tsx`,
    `${WEB}/src/app/locations/**`,
    `${WEB}/src/app/ingredients/**`,
    `${WEB}/src/server/repo/garden/**`,
    `${WEB}/src/server/repo/calendar-plantings.ts`,
    `${WEB}/src/server/repo/location/**`,
    `${WEB}/src/server/repo/ingredient/**`,
    `${WEB}/src/server/garden-guides/**`,
  ],
  "http-api.spec.ts": [
    `${WEB}/src/routes/api/v1/**`,
    `${WEB}/src/routes/api/auth/**`,
    `${WEB}/src/lib/http-api/**`,
    `${WEB}/tests/e2e/http-api-client.ts`,
    `${WEB}/src/server/repo/vendor.ts`,
  ],
  "http-resource-api.spec.ts": [
    `${WEB}/src/routes/api/v1/**`,
    `${WEB}/src/routes/api/auth/**`,
    `${WEB}/src/lib/http-api/**`,
    `${WEB}/tests/e2e/http-api-client.ts`,
  ],
  "inheritance.spec.ts": [
    `${WEB}/tests/e2e/inheritance-contract.ts`,
    `${WEB}/src/server/repo/task-inheritance.ts`,
    `${WEB}/src/server/repo/purchase-inheritance.ts`,
    `${WEB}/src/server/repo/expense-inheritance.ts`,
    `${WEB}/src/server/repo/calendar-inheritance.integration.test.ts`,
    `${WEB}/src/server/repo/inheritance-validation.ts`,
  ],
  "inspect-contract.spec.ts": [
    `${WEB}/src/app/products/**`,
    `${WEB}/src/server/repo/product/**`,
  ],
  "inventory-session.spec.ts": [
    `${WEB}/src/routes/_authenticated/inventory.index.tsx`,
    `${WEB}/src/routes/_authenticated/inventory.$shortcode.tsx`,
    `${WEB}/src/server/repo/inventory/**`,
  ],
  "inventory-session-photo-capture.spec.ts": [
    `${WEB}/src/app/inventory/session/**`,
    `${WEB}/src/contracts/product.contract.ts`,
    `${WEB}/src/contracts/image-upload.contract.ts`,
    `${WEB}/src/server/operations/product.server.ts`,
    `${WEB}/src/server/operations/image.server.ts`,
    `${WEB}/src/server/repo/product/capture.ts`,
    `${WEB}/src/lib/presigned-upload.ts`,
    "packages/schemas/src/product-capture.ts",
    "packages/schemas/src/image.ts",
  ],
  "mcp-worklist.spec.ts": [
    `${WEB}/src/app/_components/dev/mcp-usage-dashboard.tsx`,
  ],
  "meal-copy.spec.ts": [
    `${WEB}/src/app/meals/**`,
    `${WEB}/src/app/calendar/**`,
    `${WEB}/src/server/repo/meal/**`,
    `${WEB}/src/server/operations/meal.server.ts`,
    `${WEB}/src/contracts/meal.contract.ts`,
  ],
  "meal-nutrition.spec.ts": [
    `${WEB}/src/app/_components/nutrition/**`,
    `${WEB}/src/server/repo/meal/**`,
    `${WEB}/src/server/services/meal-nutrition.service.ts`,
    `${WEB}/src/lib/meal-food-nutrition.ts`,
  ],
  "nutrition.spec.ts": [
    `${WEB}/src/app/recipes/**`,
    `${WEB}/src/app/_components/nutrition/**`,
    `${WEB}/src/server/repo/recipe/**`,
    `${WEB}/src/server/services/recipe-costing.service.ts`,
    `${WEB}/src/lib/nutrition-estimates.ts`,
    `${WEB}/src/lib/nutrition-format.ts`,
    `${WEB}/src/lib/nutrition-intel.ts`,
  ],
  "pantry-staples.spec.ts": [
    `${WEB}/src/routes/_authenticated/pantry-view.tsx`,
    `${WEB}/src/app/ingredients/**`,
    `${WEB}/src/app/pantry-view/**`,
    `${WEB}/src/server/repo/ingredient/**`,
    `${WEB}/src/server/repo/meal/**`,
  ],
  "performance.spec.ts": [
    `${WEB}/src/routes/_authenticated/locations.index.tsx`,
    `${WEB}/src/app/_components/home/**`,
    `${WEB}/src/app/locations/**`,
  ],
  "photo-group-review.spec.ts": [
    `${WEB}/src/routes/_authenticated/runs.index.tsx`,
    `${WEB}/src/app/runs/**`,
    `${WEB}/src/app/images/**`,
    `${WEB}/src/server/repo/run.ts`,
    `${WEB}/src/server/repo/image-sighting.ts`,
    `${WEB}/src/server/repo/photo-import.ts`,
    `${WEB}/src/server/services/photo-import-stage.service.ts`,
    `${WEB}/src/server/services/photo-import-finalize.service.ts`,
    `${WEB}/src/server/services/photo-import-reconcile.service.ts`,
  ],
  "product-bulk-workflow.spec.ts": [
    `${WEB}/src/routes/api/workflow-stream/**`,
    `${WEB}/src/routes/_authenticated/products.index.tsx`,
    `${WEB}/src/app/products/**`,
    `${WEB}/src/server/repo/product/**`,
  ],
  "product-photo-first.spec.ts": [
    `${WEB}/src/routes/_authenticated/products.$shortcode.tsx`,
    `${WEB}/src/app/products/**`,
    `${WEB}/src/app/_components/PendingImageUpload.tsx`,
    `${WEB}/src/app/_components/entity-media/**`,
    `${WEB}/src/server/repo/product/**`,
    `${WEB}/src/server/repo/image.ts`,
    `${WEB}/src/server/services/image-storage.service.ts`,
    `${WEB}/src/contracts/image-upload.contract.ts`,
  ],
  "product-ssr.spec.ts": [
    `${WEB}/src/app/products/**`,
    `${WEB}/src/server/repo/product/**`,
  ],
  "project-tracker.spec.ts": [
    `${WEB}/src/routes/_authenticated/projects.$shortcode.tsx`,
    `${WEB}/src/routes/_authenticated/projects.index.tsx`,
    `${WEB}/src/app/projects/**`,
    `${WEB}/src/app/tasks/**`,
    `${WEB}/src/server/repo/project/**`,
    `${WEB}/src/server/repo/task/**`,
    `${WEB}/src/app/_components/command-menu.tsx`,
    `${WEB}/src/app/_components/command-menu-loader.ts`,
    `${WEB}/src/app/_components/command-menu-search-groups.unit.test.tsx`,
  ],
  "finance-category-display.spec.ts": [
    `${WEB}/src/entities/**`,
    `${WEB}/src/app/_components/hooks/progressive-list.ts`,
    `${WEB}/src/app/_components/data-table/**`,
    `${WEB}/src/server/entity-list-runtime.server.ts`,
    `${WEB}/src/server/repo/financial-transaction.ts`,
    `${WEB}/src/server/repo/spending-category.ts`,
    "packages/schemas/src/entity-definitions/14-financialTransaction.entity.ts",
    "scripts/generator/entities/**",
  ],
  "finance-evidence-journey.spec.ts": [
    `${WEB}/src/app/finance/**`,
    `${WEB}/src/server/repo/financial-*.ts`,
    `${WEB}/src/server/repo/expense/**`,
    `${WEB}/src/server/repo/purchase.ts`,
    `${WEB}/src/server/repo/spending-category.ts`,
    `${WEB}/src/contracts/financial-*.contract.ts`,
    `${WEB}/src/server/operations/financial-*.server.ts`,
  ],
  "spending-classification-review.spec.ts": [
    `${WEB}/src/app/finance/**`,
    `${WEB}/src/server/repo/expense*`,
    `${WEB}/src/server/repo/spending-classification*`,
    `${WEB}/src/server/repo/product-category.ts`,
    `${WEB}/src/server/repo/vendor.ts`,
  ],
  "financial-booking-review.spec.ts": [
    `${WEB}/src/routes/_authenticated/financial-transactions*`,
    `${WEB}/src/app/finance/**`,
    `${WEB}/src/server/repo/financial-*.ts`,
    `${WEB}/src/server/repo/expense/**`,
    `${WEB}/src/server/repo/purchase.ts`,
    `${WEB}/src/server/repo/expense-inheritance.ts`,
    `${WEB}/src/contracts/financial-*.contract.ts`,
    `${WEB}/src/server/operations/financial-*.server.ts`,
  ],
  "import-order-convergence.spec.ts": [
    `${WEB}/tests/e2e/import-order-convergence.helpers.ts`,
    `${WEB}/src/routes/_authenticated/statement-rows*`,
    `${WEB}/src/routes/_authenticated/runs*`,
    `${WEB}/src/routes/_authenticated/problems*`,
    `${WEB}/src/routes/_authenticated/vendors*`,
    `${WEB}/src/routes/_authenticated/products*`,
    `${WEB}/src/routes/_authenticated/purchases*`,
    `${WEB}/src/app/runs/**`,
    `${WEB}/src/app/problems/**`,
    `${WEB}/src/app/vendors/**`,
    `${WEB}/src/app/products/**`,
    `${WEB}/src/app/purchases/**`,
    `${WEB}/src/server/statement-csv-import.ts`,
    `${WEB}/src/server/repo/statement-row*.ts`,
    `${WEB}/src/server/repo/financial-*.ts`,
    `${WEB}/src/server/repo/photo-import*.ts`,
    `${WEB}/src/server/repo/image-processing*.ts`,
    `${WEB}/src/server/repo/import-quality/**`,
    `${WEB}/src/server/purchase-import/**`,
    `${WEB}/src/server/services/image-*.service.ts`,
    `${WEB}/src/contracts/statement-row.contract.ts`,
    `${WEB}/src/contracts/financial-*.contract.ts`,
    `${WEB}/src/contracts/photo-import.contract.ts`,
    `${WEB}/src/server/operations/statement-row.server.ts`,
    `${WEB}/src/server/operations/financial-*.server.ts`,
    `${WEB}/src/server/operations/photo-import.server.ts`,
  ],
  "finance-itemization.spec.ts": [
    `${WEB}/src/entities/list-columns/finance.tsx`,
    `${WEB}/src/server/repo/financial-transaction.ts`,
    `${WEB}/src/server/repo/financial-reconciliation.ts`,
  ],
  "purchase-split-settlement.spec.ts": [
    `${WEB}/src/app/purchases/**`,
    `${WEB}/src/server/repo/financial-transaction.ts`,
    `${WEB}/src/server/repo/purchase.ts`,
  ],
  "relationship-discovery.spec.ts": [
    `${WEB}/tests/e2e/relationship-discovery-contract.ts`,
    `${WEB}/src/routes/_authenticated/purchases.$shortcode.tsx`,
    `${WEB}/src/routes/_authenticated/tasks.index.tsx`,
    `${WEB}/src/routes/_authenticated/plantings.index.tsx`,
    `${WEB}/src/server/repo/relatedness/**`,
    `${WEB}/src/server/repo/merge/**`,
    `${WEB}/src/server/repo/relation-mutation-adapter.ts`,
    `${WEB}/src/server/repo/relation-preflight.ts`,
    `${WEB}/src/server/services/relatedness.service.ts`,
    `${WEB}/src/server/services/relatedness-ledger.ts`,
    `${WEB}/src/server/services/placement-recommendation.service.ts`,
  ],
  "connected-records.spec.ts": [
    `${WEB}/tests/e2e/connected-records-contract.ts`,
    `${WEB}/src/routes/_authenticated/connections.tsx`,
    `${WEB}/src/server/repo/connected-records.ts`,
    `${WEB}/src/server/repo/relatedness/**`,
  ],
  "shortcode-routes.spec.ts": [
    `${WEB}/src/server/repo/shortcode-resolver.ts`,
    `${WEB}/src/server/repo/shortcode-tables.ts`,
    `${WEB}/src/server/repo/shortcode-utils.ts`,
  ],
  "start-entity-transport.spec.ts": [`${WEB}/src/server/entity-kernel/**`],
  "statement-import.spec.ts": [
    `${WEB}/src/app/finance/statement-csv.ts`,
    `${WEB}/src/server/repo/statement-row.ts`,
    `${WEB}/src/server/repo/financial-transaction.ts`,
    `${WEB}/src/server/operations/statement-row.server.ts`,
  ],
  "vendor-order-mail-review.spec.ts": [
    `${WEB}/src/app/vendors/**`,
    `${WEB}/src/app/purchases/**`,
    `${WEB}/src/server/purchase-import/gmail/**`,
  ],
  "tools-flow.spec.ts": [
    `${WEB}/src/server/repo/project-tools.integration.test.ts`,
    `${WEB}/src/server/repo/product/**`,
  ],
  "unauth.pages.spec.ts": [
    `${WEB}/src/app/_components/home/**`,
    `${WEB}/src/app/_components/footer.tsx`,
  ],
  "unknown-expense-dates.spec.ts": [
    `${WEB}/tests/e2e/unknown-expense-date-flow.ts`,
    `${WEB}/src/app/expenses/**`,
    `${WEB}/src/server/repo/expense/**`,
    `${WEB}/src/server/repo/expense-attribution.ts`,
  ],
  "wardrobe-preparation.spec.ts": [
    `${WEB}/src/routes/_authenticated/collections.wardrobe.$owner.tsx`,
    `${WEB}/src/app/products/**`,
    `${WEB}/src/app/collections/**`,
    `${WEB}/src/server/repo/product-category.ts`,
    `${WEB}/src/server/repo/product/**`,
  ],
  "wardrobe-owner.spec.ts": [
    `${WEB}/src/app/inventory/**`,
    `${WEB}/src/server/repo/inventory/**`,
    `${WEB}/src/server/repo/smart-collection-membership.ts`,
  ],
  "browser-workflows.spec.ts": [
    `${WEB}/src/routes/_authenticated/products.index.tsx`,
    `${WEB}/src/routes/_authenticated/recipes*`,
    `${WEB}/src/routes/_authenticated/expenses*`,
    `${WEB}/src/app/_components/search/**`,
    `${WEB}/src/app/locations/**`,
    `${WEB}/src/app/products/**`,
    `${WEB}/src/app/recipes/**`,
    `${WEB}/src/app/expenses/**`,
    `${WEB}/src/server/repo/location/**`,
    `${WEB}/src/server/repo/product/**`,
    `${WEB}/src/server/repo/expense/**`,
    `${WEB}/src/server/repo/meal/**`,
  ],
};

export const SPEC_AREAS: readonly SpecAreaEntry[] = Object.keys(
  DERIVED_SPEC_GLOBS,
).map((file) => ({
  file,
  globs: [
    ...new Set([
      ...(DERIVED_SPEC_GLOBS[file] ?? []),
      ...(SPEC_EXTRA_GLOBS[file] ?? []),
    ]),
  ],
}));
