import { type Entity, entityRefKey } from "@cubby/schemas/entity";
import { entityManifest } from "@cubby/schemas/entity-manifest";
import type {
  RelatedBranchInput,
  RelatedBranchOutput,
  RelatedOptionsInput,
  RelatedOptionsOutput,
  RelatedPreviewGroup,
  RelatedPreviewInput,
  RelatedSummaryInput,
  RelatedSummaryOutput,
  RelatedSummaryRelationKey,
  RelatedViewKey,
} from "@cubby/schemas/related-view";
import {
  relatedFilterPrefix,
  relatedViewPath,
  relatedViewRegistry,
} from "@cubby/schemas/related-view";
import { parseShortcode } from "@cubby/shared";
import { and, or, type SQL, type SQLWrapper, sql } from "drizzle-orm";
import { uniq } from "es-toolkit";
import { z } from "zod";

import type { Database } from "~/server/db";
import { getDb } from "~/server/repo/database-helpers";
import { resolveEntityDisplayImages } from "~/server/repo/entity-display-image";
import { expenseAcquisitionSql } from "~/server/repo/expense-aggregate-sql";
import { expenseProjectAllocationSql } from "~/server/repo/expense-project-allocation";
import { compileTraversal } from "~/server/repo/relatedness/traversal";
import { getR2PublicUrl } from "~/server/utils/r2-public-url";

interface RelatedViewSqlPresentation {
  label: string;
  sort: string;
  sortDirection: "ASC" | "DESC";
  /**
   * Extra restriction on which traversal rows the view admits, ANDed into
   * EVERY consumer below — preview, branch, options, and the list filter — so
   * a view can never mean one thing in a cell and another in a sort.
   *
   * Written against the stable `s` (source) and `t` (target) aliases only.
   * Intermediate hop aliases are generated by `compileTraversal` and are not
   * part of any contract.
   */
  where?: string;
}

const named = (sort = `lower(t."name")`) => ({
  label: `t."name"`,
  sort,
  sortDirection: "ASC" as const,
});
const dated = (label = `t."name"`, sort = `t."createdAt"`) => ({
  label,
  sort,
  sortDirection: "DESC" as const,
});

/**
 * Server-owned SQL realization of the curated schema registry. All identifiers
 * below are constants; caller data is parameterized separately.
 */
/**
 * Did this Purchase ACQUIRE this Product, rather than dispose of it?
 *
 * A product-linked Expense reaches a Purchase in BOTH directions: a sale,
 * return, or disposal is a Purchase whose Expenses sum negative
 * (`repo/product/ownership.ts`). Without this, `product.purchases` filed 181
 * eBay-sale orders under a product's "Purchases", and its transpose
 * `purchase.products` listed the items 172 pure-disposal orders SOLD as things
 * they bought — both disagreeing with the detail cards beside them, which have
 * always filtered via `expensePairPredicate` (`repo/purchase-products.ts`).
 *
 * One expression for both directions, since it is one question about one
 * Expense row: only the aliases swap. Written against `s`/`t` alone —
 * intermediate hop aliases come from `compileTraversal` and are not a contract.
 */
const purchaseAcquiredProduct = (alias: {
  product: "s" | "t";
  purchase: "s" | "t";
}): string =>
  `EXISTS (SELECT 1 FROM "Expense" pap_e
            WHERE pap_e."productId" = ${alias.product}."id"
              AND pap_e."purchaseId" = ${alias.purchase}."id"
              AND pap_e."deletedAt" IS NULL
              AND pap_e."future" = false
              AND ${expenseAcquisitionSql("pap_e")})`;

const SQL_RELATED_VIEWS = {
  "product.vendors": named(),
  "product.projects": named(),
  "product.usedOnProjects": named(),
  "product.purchases": {
    ...dated(
      `COALESCE(NULLIF(t."orderId", ''), t."shortcode")`,
      `COALESCE(t."date"::timestamp, t."createdAt")`,
    ),
    where: purchaseAcquiredProduct({ product: "s", purchase: "t" }),
  },
  "product.expenses": dated(
    `t."name"`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  // includes-installed: this is a related-records view keyed off product
  // identity — a fixture must stay listed among "this product's inventory".
  "product.inventory": dated(`t."shortcode"`, `t."createdAt"`),
  "product.wishes": named(),
  "product.tasks": named(
    `format('%s|%s|%s', CASE WHEN t."status" = 'done' THEN 1 ELSE 0 END, COALESCE(t."dueDate"::text, '9999-12-31'), lower(t."name"))`,
  ),
  "product.meals": dated(
    `COALESCE(NULLIF(t."name", ''), t."date"::text, t."shortcode")`,
    `t."date"`,
  ),
  "product.eaters": named(),
  "ingredient.meals": dated(
    `COALESCE(NULLIF(t."name", ''), t."date"::text, t."shortcode")`,
    `t."date"`,
  ),
  "ingredient.eaters": named(),
  "recipe.ingredients": named(),
  "recipe.meals": dated(
    `COALESCE(NULLIF(t."name", ''), t."date"::text, t."shortcode")`,
    `t."date"`,
  ),
  "meal.recipes": named(),
  "meal.foodProducts": named(),
  "meal.foodIngredients": named(),
  // The `eaters` list column reads only the primary (food-entry) source; the
  // `portions` (served-portion) source is graph-only (`relatedViewPath`
  // compiles `provenance.steps`, never `sources`).
  "meal.eaters": named(),
  // includes-installed: identity/relation views, not a browse/count surface
  // — a fixture's related ingredient must stay reachable either direction.
  "location.ingredients": named(),
  "inventory.ingredient": named(),
  "project.blockedBy": named(),
  "project.tasks": named(
    `format('%s|%s|%s', CASE WHEN t."status" = 'done' THEN 1 ELSE 0 END, COALESCE(t."dueDate"::text, '9999-12-31'), lower(t."name"))`,
  ),
  "project.expenses": dated(
    `t."name"`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  "project.taskProducts": named(),
  "project.purchasedProducts": named(),
  // KNOWN ASYMMETRY, deliberately left: the project's "Reusable resources" card
  // (`repo/project/tools.ts` `listProjectResources`) additionally restricts to
  // `product.category IN ('tools','software')`; this column does not. Zero live
  // edges differ today, and that card's own comment explains why it filters —
  // `ProjectToolUsage` is durable history that may predate a legitimate
  // category correction. It will diverge the first time a product with
  // tool-usage history is recategorized; that is the accepted trade, not an
  // oversight.
  "project.usedTools": named(),
  "project.vendors": named(),
  "task.blockedBy": named(
    `format('%s|%s|%s', CASE WHEN t."status" = 'done' THEN 1 ELSE 0 END, COALESCE(t."dueDate"::text, '9999-12-31'), lower(t."name"))`,
  ),
  "task.parent": named(
    `format('%s|%s|%s', CASE WHEN t."status" = 'done' THEN 1 ELSE 0 END, COALESCE(t."dueDate"::text, '9999-12-31'), lower(t."name"))`,
  ),
  "vendor.expenses": dated(
    `t."name"`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  "vendor.purchases": dated(
    `COALESCE(NULLIF(t."orderId", ''), t."shortcode")`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  "vendor.products": named(),
  "vendor.projects": named(),
  "vendor.transactions": dated(
    `COALESCE(NULLIF(t."merchant", ''), NULLIF(t."rawDescription", ''), t."shortcode")`,
    `COALESCE(t."postedDate", t."transactionDate", t."createdAt"::date)`,
  ),
  "purchase.expenses": dated(
    `t."name"`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  "purchase.transactions": dated(
    `COALESCE(NULLIF(t."merchant", ''), NULLIF(t."rawDescription", ''), t."shortcode")`,
    `COALESCE(t."postedDate", t."transactionDate", t."createdAt"::date)`,
  ),
  // Via-spend, exactly like its mirror `product.purchases`: reached through a
  // money row, and only an acquiring one. The 10 pairs whose sole evidence is a
  // `PurchaseProduct` link with no qualifying Expense stay out of this view on
  // purpose — `listPurchaseProducts` (repo/purchase-products.ts) unions that
  // second leg for the detail card, which is where an allocation-based order's
  // goods belong.
  "purchase.products": {
    ...named(),
    where: purchaseAcquiredProduct({ purchase: "s", product: "t" }),
  },
  "purchase.projects": named(),
  "expense.transactions": dated(
    `COALESCE(NULLIF(t."merchant", ''), NULLIF(t."rawDescription", ''), t."shortcode")`,
    `COALESCE(t."postedDate", t."transactionDate", t."createdAt"::date)`,
  ),
  "financialAccount.transactions": dated(
    `COALESCE(NULLIF(t."merchant", ''), NULLIF(t."rawDescription", ''), t."shortcode")`,
    `COALESCE(t."postedDate", t."transactionDate", t."createdAt"::date)`,
  ),
  "financialAccount.purchases": dated(
    `COALESCE(NULLIF(t."orderId", ''), t."shortcode")`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  "financialAccount.vendors": named(),
  "financialTransaction.vendor": named(),
  "financialTransaction.expenses": dated(
    `t."name"`,
    `COALESCE(t."date"::timestamp, t."createdAt")`,
  ),
  "financialTransaction.products": named(),
  "wish.candidates": named(),
  // The `meals` list column reads only the primary (food-entry) source; the
  // `portions` (served-portion) source is graph-only (`relatedViewPath`
  // compiles `provenance.steps`, never `sources`).
  "ledgerParty.meals": dated(
    `COALESCE(NULLIF(t."name", ''), t."date"::text, t."shortcode")`,
    `t."date"`,
  ),
  "ledgerParty.recipesEaten": named(),
} as const satisfies Record<RelatedViewKey, RelatedViewSqlPresentation>;

/** The view's own restriction as an ANDable clause, or nothing. */
const viewWhere = (view: RelatedViewSqlPresentation): SQL =>
  view.where ? sql`AND ${sql.raw(view.where)}` : sql``;

const relatedViewsByKey = new Map(
  relatedViewRegistry.map((view) => [view.key, view]),
);

/**
 * Presentation SQL belongs here; endpoint identity and table ownership remain
 * in the manifest-backed related-view registry.
 */
const sqlRelatedView = (key: RelatedViewKey) => {
  const definition = relatedViewsByKey.get(key);
  if (!definition) throw new Error(`Unknown related view: ${key}`);
  return {
    ...SQL_RELATED_VIEWS[key],
    sourceTable: entityManifest[definition.source].dbTable,
    targetEntity: definition.target,
  };
};

/**
 * The curated registry supplies presentation only; traversal joins are compiled
 * from its declared graph path with the aliases this repository query expects.
 */
const COMPILED_RELATED_JOINS = new Map<RelatedViewKey, SQL>(
  relatedViewRegistry.map((view) => [
    view.key,
    compileTraversal(view.source, relatedViewPath(view), "related", {
      root: "s",
      leaf: "t",
    }).joins,
  ]),
);

const compiledRelatedJoins = (key: RelatedViewKey): SQL => {
  const joins = COMPILED_RELATED_JOINS.get(key);
  if (!joins) throw new Error(`Missing compiled traversal for ${key}`);
  return joins;
};

const previewRowSchema = z.object({
  sourceId: z.string(),
  targetEntityId: z.string(),
  id: z.string(),
  label: z.string(),
  totalCount: z.coerce.number().int().nonnegative(),
});

const branchRowSchema = previewRowSchema.omit({ sourceId: true });

const optionRowSchema = z.object({
  id: z.string(),
  label: z.string(),
  count: z.coerce.number().int().nonnegative(),
});

const relatedIdsFilterSchema = z.union([z.string(), z.array(z.string())]);
const relatedSearchFilterSchema = z.string().trim().min(1);

const summaryTotalsRowSchema = z.object({
  count: z.coerce.number().int().nonnegative(),
  totalExpenseCount: z.coerce.number().int().nonnegative(),
  totalPurchaseCount: z.coerce.number().int().nonnegative(),
  totalUnpricedExpenseCount: z.coerce.number().int().nonnegative(),
  totalItemSpend: z.coerce.number(),
  totalSharedChargeSpend: z.coerce.number(),
  totalNetSpend: z.coerce.number(),
  totalIncomplete: z.coerce.boolean(),
  totalKnownAcquiredUnits: z.coerce.number().nonnegative(),
  totalUnknownAcquisitionQuantityCount: z.coerce.number().int().nonnegative(),
});

const summaryPageFields = {
  targetId: z.string().nullable(),
  targetLabel: z.string().nullable(),
  imageId: z.string().nullable(),
  imageKey: z.string().nullable(),
  imageFilename: z.string().nullable(),
  imageContentType: z.string().nullable(),
  expenseCount: z.coerce.number().int().nonnegative(),
  purchaseCount: z.coerce.number().int().nonnegative(),
  unpricedExpenseCount: z.coerce.number().int().nonnegative(),
  itemSpend: z.coerce.number(),
  sharedChargeSpend: z.coerce.number(),
  netSpend: z.coerce.number(),
  incomplete: z.coerce.boolean(),
  latestActivity: z.string().nullable(),
  knownAcquiredUnits: z.coerce.number().nonnegative(),
  unknownAcquisitionQuantityCount: z.coerce.number().int().nonnegative(),
};

const summaryPageRowSchema = summaryTotalsRowSchema.extend({
  ...summaryPageFields,
  isPageRow: z.literal(true),
});

const summaryEmptyRowSchema = summaryTotalsRowSchema.extend({
  targetId: z.null(),
  targetLabel: z.null(),
  imageId: z.null(),
  imageKey: z.null(),
  imageFilename: z.null(),
  imageContentType: z.null(),
  expenseCount: z.null(),
  purchaseCount: z.null(),
  unpricedExpenseCount: z.null(),
  itemSpend: z.null(),
  sharedChargeSpend: z.null(),
  netSpend: z.null(),
  incomplete: z.null(),
  latestActivity: z.null(),
  knownAcquiredUnits: z.null(),
  unknownAcquisitionQuantityCount: z.null(),
  isPageRow: z.null(),
});

const summaryRowSchema = z.discriminatedUnion("isPageRow", [
  summaryPageRowSchema,
  summaryEmptyRowSchema,
]);

type PreviewRow = z.infer<typeof previewRowSchema>;

async function loadOneRows(
  db: Database,
  relationKey: RelatedViewKey,
  sourceIds: string[],
): Promise<PreviewRow[]> {
  const view = sqlRelatedView(relationKey);
  const ids = sql.join(
    sourceIds.map((id) => sql`${id}`),
    sql`, `,
  );
  const query = sql`
    WITH related AS (
      SELECT DISTINCT
        s."shortcode" AS "sourceId",
        t."id"::text AS "targetEntityId",
        t."shortcode" AS "id",
        ${sql.raw(view.label)}::text AS "label",
        ${sql.raw(view.sort)} AS "sortValue"
      FROM ${sql.raw(`"${view.sourceTable}"`)} s
      ${compiledRelatedJoins(relationKey)}
      WHERE s."shortcode" IN (${ids}) AND s."deletedAt" IS NULL
        ${viewWhere(view)}
    ), ranked AS (
      SELECT *,
        count(*) OVER (PARTITION BY "sourceId")::int AS "totalCount",
        row_number() OVER (
          PARTITION BY "sourceId"
          ORDER BY "sortValue" ${sql.raw(view.sortDirection)}, "label", "id"
        ) AS rn
      FROM related
    )
    SELECT "sourceId", "targetEntityId", "id", "label", "totalCount"
    FROM ranked
    WHERE rn <= 3
    ORDER BY "sourceId", rn
  `;
  const result = await getDb(db).execute(query);
  return previewRowSchema.array().parse(result.rows);
}

export async function loadRelatedPreviews(
  db: Database,
  input: RelatedPreviewInput,
): Promise<RelatedPreviewGroup[]> {
  const allowed = new Set(
    relatedViewRegistry
      .filter((view) => view.source === input.source)
      .map((view) => view.key),
  );
  const relationKeys = uniq(input.relationKeys).filter((key) =>
    allowed.has(key),
  );
  if (input.sourceIds.length === 0 || relationKeys.length === 0) return [];
  const loaded = await Promise.all(
    relationKeys.map(async (key) => ({
      relationKey: key,
      rows: await loadOneRows(db, key, uniq(input.sourceIds)),
    })),
  );
  const displayImages = await resolveEntityDisplayImages(
    db,
    loaded.flatMap(({ relationKey, rows }) => {
      const targetEntity = sqlRelatedView(relationKey).targetEntity;
      return rows.map((row) => ({
        entityType: targetEntity,
        entityId: row.targetEntityId,
      }));
    }),
  );
  return loaded.flatMap(({ relationKey, rows }) => {
    const targetEntity = sqlRelatedView(relationKey).targetEntity;
    const grouped = new Map<string, RelatedPreviewGroup>();
    for (const row of rows) {
      const group = grouped.get(row.sourceId) ?? {
        sourceId: row.sourceId,
        relationKey,
        totalCount: Number(row.totalCount),
        items: [],
      };
      group.items.push({
        entity: targetEntity,
        id: row.id,
        label: row.label,
        displayImage:
          displayImages.get(entityRefKey(targetEntity, row.targetEntityId)) ??
          null,
      });
      grouped.set(row.sourceId, group);
    }
    return [...grouped.values()];
  });
}

/**
 * Load a single, paginated branch for the relationship outline. This shares
 * the exact SQL realization used by table previews and predicates, so there
 * is no parallel interpretation of a relationship in the UI layer.
 */
export async function loadRelatedBranch(
  db: Database,
  input: RelatedBranchInput,
): Promise<RelatedBranchOutput> {
  const view = sqlRelatedView(input.relationKey);
  const query = sql`
    WITH related AS (
      SELECT DISTINCT
        t."id"::text AS "targetEntityId",
        t."shortcode" AS "id",
        ${sql.raw(view.label)}::text AS "label",
        ${sql.raw(view.sort)} AS "sortValue"
      FROM ${sql.raw(`"${view.sourceTable}"`)} s
      ${compiledRelatedJoins(input.relationKey)}
      WHERE s."shortcode" = ${input.sourceId} AND s."deletedAt" IS NULL
        ${viewWhere(view)}
    ), ranked AS (
      SELECT *, count(*) OVER ()::int AS "totalCount"
      FROM related
    )
    SELECT "targetEntityId", "id", "label", "sortValue", "totalCount"
    FROM ranked
    ORDER BY "sortValue" ${sql.raw(view.sortDirection)}, "label", "id"
    LIMIT ${input.limit} OFFSET ${input.offset}
  `;
  const result = await getDb(db).execute(query);
  const rows = branchRowSchema.array().parse(result.rows);
  const displayImages = await resolveEntityDisplayImages(
    db,
    rows.map((row) => ({
      entityType: view.targetEntity,
      entityId: row.targetEntityId,
    })),
  );
  const totalCount = rows.length ? Number(rows[0]?.totalCount) : 0;
  const consumed = input.offset + rows.length;
  return {
    sourceId: input.sourceId,
    relationKey: input.relationKey,
    totalCount,
    items: rows.map((row) => ({
      entity: view.targetEntity,
      id: row.id,
      label: row.label,
      displayImage:
        displayImages.get(
          entityRefKey(view.targetEntity, row.targetEntityId),
        ) ?? null,
    })),
    nextOffset: consumed < totalCount ? consumed : null,
  };
}

/** Search targets for a relation, including the number of distinct sources. */
/**
 * ORDER BY expression for a `related:<key>` column, built from the SAME joins,
 * sort expression, and `where` the cell reads — so a change to the view moves
 * the sort with it.
 *
 * Before this, `product/crud.ts` restated all three of its related traversals
 * by hand. That is how `product.purchases` came to need a second, manual edit
 * the moment the view gained its acquisition predicate: the sort would
 * otherwise have ranked rows by a disposal date absent from every cell it
 * sorts.
 *
 * The aggregate follows the view's own `sortDirection`, which makes it "rank by
 * the FIRST chip the cell shows": a DESC view (purchases, by date) previews its
 * newest row, so `max`; an ASC view (vendors, by name) previews its
 * alphabetically first, so `min`. `direction` then orders those keys. This is
 * why a descending vendor sort reverses by each product's first vendor rather
 * than ranking by its last — deliberate, and now derived rather than restated.
 *
 * `rootIdRef` is the enclosing query's id reference, hand-qualified by the
 * caller (`"product"."id"` under the relational query builder). `renderJoins`
 * emits `sql.raw` exclusively, so the whole clause survives both
 * `buildSelection`'s prefix stripping and the RQB's alias rewriting.
 */
export const relatedSortExpression = (
  relationKey: RelatedViewKey,
  rootIdRef: string,
): SQL => {
  const view = sqlRelatedView(relationKey);
  const aggregate = view.sortDirection === "DESC" ? "max" : "min";
  return sql`(SELECT ${sql.raw(aggregate)}(${sql.raw(view.sort)})
    FROM ${sql.raw(`"${view.sourceTable}"`)} s
    ${compiledRelatedJoins(relationKey)}
    WHERE s."id" = ${sql.raw(rootIdRef)} AND s."deletedAt" IS NULL
      ${viewWhere(view)})`;
};

export async function loadRelatedOptions(
  db: Database,
  input: RelatedOptionsInput,
): Promise<RelatedOptionsOutput> {
  const view = sqlRelatedView(input.relationKey);
  const search = input.search?.trim();
  const query = sql`
    SELECT
      t."shortcode" AS "id",
      ${sql.raw(view.label)}::text AS "label",
      count(DISTINCT s."id")::int AS "count"
    FROM ${sql.raw(`"${view.sourceTable}"`)} s
    ${compiledRelatedJoins(input.relationKey)}
    WHERE s."deletedAt" IS NULL
      ${viewWhere(view)}
      ${search ? sql`AND ${sql.raw(view.label)} ILIKE ${`%${search}%`}` : sql``}
    GROUP BY t."shortcode", ${sql.raw(view.label)}
    ORDER BY "label", "id"
    LIMIT ${input.limit}
  `;
  const result = await getDb(db).execute(query);
  const rows = optionRowSchema.array().parse(result.rows);
  return rows.map((row) => ({
    entity: view.targetEntity,
    id: row.id,
    label: row.label,
    count: Number(row.count),
  }));
}

type SummaryDefinition = {
  targetEntity: "product" | "project" | "vendor";
  targetJoin: string;
  /** Null targets are meaningful only for incomplete purchase/project provenance. */
  targetPresence: "required" | "optional";
  imageTarget: "product" | "project" | "vendor" | null;
};

const SUMMARY_DEFINITIONS = {
  "vendor.products": {
    targetEntity: "product",
    targetJoin: `JOIN "Product" t ON t."id" = se."productId" AND t."deletedAt" IS NULL`,
    targetPresence: "required",
    imageTarget: "product",
  },
  "vendor.projects": {
    targetEntity: "project",
    targetJoin: `LEFT JOIN "Project" t ON t."id" = se."projectId" AND t."deletedAt" IS NULL`,
    targetPresence: "optional",
    imageTarget: "project",
  },
  "purchase.projects": {
    targetEntity: "project",
    targetJoin: `LEFT JOIN "Project" t ON t."id" = se."projectId" AND t."deletedAt" IS NULL`,
    targetPresence: "optional",
    imageTarget: "project",
  },
  "project.vendors": {
    targetEntity: "vendor",
    targetJoin: `LEFT JOIN "Vendor" t ON t."id" = se."vendorId" AND t."deletedAt" IS NULL`,
    targetPresence: "optional",
    imageTarget: "vendor",
  },
  "project.purchasedProducts": {
    targetEntity: "product",
    targetJoin: `JOIN "Product" t ON t."id" = se."productId" AND t."deletedAt" IS NULL`,
    targetPresence: "required",
    imageTarget: "product",
  },
  "product.vendors": {
    targetEntity: "vendor",
    targetJoin: `LEFT JOIN "Vendor" t ON t."id" = se."vendorId" AND t."deletedAt" IS NULL`,
    targetPresence: "optional",
    imageTarget: "vendor",
  },
} satisfies Record<RelatedSummaryRelationKey, SummaryDefinition>;

/**
 * Expense-backed relationship rollups. The scope is deliberately expressed per
 * supported relation rather than trying to compile arbitrary graph paths into
 * SQL: these tables have money and liveness semantics that a generic join
 * builder cannot safely infer.
 */
export async function loadRelatedSummary(
  db: Database,
  input: RelatedSummaryInput,
): Promise<RelatedSummaryOutput> {
  const definition = SUMMARY_DEFINITIONS[input.relationKey];
  const scope = (() => {
    if (input.relationKey.startsWith("vendor.")) {
      if (input.relationKey === "vendor.projects") {
        return sql`scoped_expenses AS (
          SELECT e."id" AS "expenseId",
            (allocation."attributedCents"::bigint / 100.0) AS "cost",
            CASE WHEN allocation.basis = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
            allocation.incomplete AS "allocationIncomplete",
            e."productQuantity", e."future", e."date" AS "expenseDate",
            e."purchaseId", allocation."projectId", e."productId",
            p."date" AS "purchaseDate", p."vendorId"
          FROM "Vendor" s
          JOIN "Purchase" p ON p."vendorId" = s."id" AND p."deletedAt" IS NULL
          JOIN "Expense" e ON e."purchaseId" = p."id" AND e."deletedAt" IS NULL
          JOIN (${expenseProjectAllocationSql()}) allocation
            ON allocation."expenseId" = e."id"
          WHERE s."shortcode" = ${input.sourceId} AND s."deletedAt" IS NULL
        )`;
      }
      return sql`scoped_expenses AS (
        SELECT e."id" AS "expenseId", e."cost",
          CASE WHEN e."lineKind" = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
          false AS "allocationIncomplete", e."productQuantity", e."future",
          e."date" AS "expenseDate", e."purchaseId", e."projectId", e."productId",
          p."date" AS "purchaseDate", p."vendorId"
        FROM "Vendor" s
        JOIN "Purchase" p ON p."vendorId" = s."id" AND p."deletedAt" IS NULL
        JOIN "Expense" e ON e."purchaseId" = p."id" AND e."deletedAt" IS NULL
        WHERE s."shortcode" = ${input.sourceId} AND s."deletedAt" IS NULL
      )`;
    }
    if (input.relationKey.startsWith("purchase.")) {
      if (input.relationKey === "purchase.projects") {
        return sql`scoped_expenses AS (
          SELECT e."id" AS "expenseId",
            (allocation."attributedCents"::bigint / 100.0) AS "cost",
            CASE WHEN allocation.basis = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
            allocation.incomplete AS "allocationIncomplete",
            e."productQuantity", e."future", e."date" AS "expenseDate",
            e."purchaseId", allocation."projectId", e."productId",
            p."date" AS "purchaseDate", p."vendorId"
          FROM "Purchase" p
          JOIN "Expense" e ON e."purchaseId" = p."id" AND e."deletedAt" IS NULL
          JOIN (${expenseProjectAllocationSql()}) allocation
            ON allocation."expenseId" = e."id"
          WHERE p."shortcode" = ${input.sourceId} AND p."deletedAt" IS NULL
        )`;
      }
      return sql`scoped_expenses AS (
        SELECT e."id" AS "expenseId", e."cost",
          CASE WHEN e."lineKind" = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
          false AS "allocationIncomplete", e."productQuantity", e."future",
          e."date" AS "expenseDate", e."purchaseId", e."projectId", e."productId",
          p."date" AS "purchaseDate", p."vendorId"
        FROM "Purchase" p
        JOIN "Expense" e ON e."purchaseId" = p."id" AND e."deletedAt" IS NULL
        WHERE p."shortcode" = ${input.sourceId} AND p."deletedAt" IS NULL
      )`;
    }
    if (input.relationKey.startsWith("product.")) {
      return sql`scoped_expenses AS (
        SELECT e."id" AS "expenseId", e."cost",
          CASE WHEN e."lineKind" = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
          false AS "allocationIncomplete", e."productQuantity", e."future",
          e."date" AS "expenseDate", e."purchaseId", e."projectId", e."productId",
          p."date" AS "purchaseDate", p."vendorId"
        FROM "Product" s
        JOIN "Expense" e ON e."productId" = s."id" AND e."deletedAt" IS NULL
        LEFT JOIN "Purchase" p ON p."id" = e."purchaseId" AND p."deletedAt" IS NULL
        WHERE s."shortcode" = ${input.sourceId} AND s."deletedAt" IS NULL
          AND (e."purchaseId" IS NULL OR p."id" IS NOT NULL)
      )`;
    }
    if (input.includeSubProjects) {
      return sql`project_scope AS (
        SELECT "id" FROM "Project"
        WHERE "shortcode" = ${input.sourceId} AND "deletedAt" IS NULL
        UNION ALL
        SELECT child."id" FROM "Project" child
        JOIN project_scope parent ON child."parentProjectId" = parent."id"
        WHERE child."deletedAt" IS NULL
      ), scoped_expenses AS (
        SELECT e."id" AS "expenseId",
          (allocation."attributedCents"::bigint / 100.0) AS "cost",
          CASE WHEN allocation.basis = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
          allocation.incomplete AS "allocationIncomplete",
          e."productQuantity", e."future",
          e."date" AS "expenseDate", e."purchaseId", allocation."projectId", e."productId",
          p."date" AS "purchaseDate", p."vendorId"
        FROM project_scope scope
        JOIN (${expenseProjectAllocationSql()}) allocation
          ON allocation."projectId" = scope."id"
        JOIN "Expense" e ON e."id" = allocation."expenseId" AND e."deletedAt" IS NULL
        LEFT JOIN "Purchase" p ON p."id" = e."purchaseId" AND p."deletedAt" IS NULL
        WHERE e."purchaseId" IS NULL OR p."id" IS NOT NULL
      )`;
    }
    return sql`scoped_expenses AS (
      SELECT e."id" AS "expenseId",
        (allocation."attributedCents"::bigint / 100.0) AS "cost",
        CASE WHEN allocation.basis = 'principal' THEN 'item' ELSE 'shared' END AS "costComponent",
        allocation.incomplete AS "allocationIncomplete",
        e."productQuantity", e."future",
        e."date" AS "expenseDate", e."purchaseId", allocation."projectId", e."productId",
        p."date" AS "purchaseDate", p."vendorId"
      FROM "Project" s
      JOIN (${expenseProjectAllocationSql()}) allocation
        ON allocation."projectId" = s."id"
      JOIN "Expense" e ON e."id" = allocation."expenseId" AND e."deletedAt" IS NULL
      LEFT JOIN "Purchase" p ON p."id" = e."purchaseId" AND p."deletedAt" IS NULL
      WHERE s."shortcode" = ${input.sourceId} AND s."deletedAt" IS NULL
        AND (e."purchaseId" IS NULL OR p."id" IS NOT NULL)
    )`;
  })();
  const imageJoin = definition.imageTarget
    ? definition.imageTarget === "vendor"
      ? `LEFT JOIN LATERAL (
        SELECT i."id", i."key", i."filename", i."contentType"
        FROM "Image" i
        WHERE i."id" = t."logoImageId"
          AND i."deletedAt" IS NULL
          AND i."contentType" <> 'application/pdf'
          AND (i."renderStatus" IS NULL OR i."renderStatus" <> 'failed')
          AND (i."storageStatus" IS NULL OR i."storageStatus" NOT IN ('missing', 'metadata_mismatch'))
        LIMIT 1
      ) img ON TRUE`
      : `LEFT JOIN LATERAL (
        SELECT i."id", i."key", i."filename", i."contentType"
        FROM "${definition.imageTarget === "product" ? "ProductImage" : "ProjectImage"}" ti
        JOIN "Image" i ON i."id" = ti."imageId" AND i."deletedAt" IS NULL
        WHERE ti."${definition.imageTarget}Id" = t."id"
          AND ti."deletedAt" IS NULL
          AND i."contentType" <> 'application/pdf'
          AND (i."renderStatus" IS NULL OR i."renderStatus" <> 'failed')
          AND (i."storageStatus" IS NULL OR i."storageStatus" NOT IN ('missing', 'metadata_mismatch'))
        ORDER BY ti."sortOrder", ti."createdAt", ti."id"
        LIMIT 1
      ) img ON TRUE`
    : "";
  const targetValid =
    definition.targetPresence === "required"
      ? sql`true`
      : definition.targetEntity === "project"
        ? sql`(se."projectId" IS NULL OR t."id" IS NOT NULL)`
        : sql`(se."purchaseId" IS NULL OR t."id" IS NOT NULL)`;
  const search = input.search?.trim();
  const sort = input.sort ?? {
    field: "latestActivity" as const,
    direction: "desc" as const,
  };
  const sortColumn = {
    target: `COALESCE("targetLabel", '')`,
    latestActivity: `"latestActivity"`,
    netSpend: `"netSpend"`,
    purchaseCount: `"purchaseCount"`,
    expenseCount: `"expenseCount"`,
    knownAcquiredUnits: `"knownAcquiredUnits"`,
  }[sort.field];
  const imageColumns = definition.imageTarget
    ? sql`img."id"::text AS "imageId", img."key" AS "imageKey", img."filename" AS "imageFilename", img."contentType" AS "imageContentType"`
    : sql`NULL::text AS "imageId", NULL::text AS "imageKey", NULL::text AS "imageFilename", NULL::text AS "imageContentType"`;
  const query = sql`
    WITH RECURSIVE ${scope}, targeted AS (
      SELECT se.*, t."shortcode" AS "targetId", t."name" AS "targetLabel", ${imageColumns}
      FROM scoped_expenses se
      ${sql.raw(definition.targetJoin)}
      ${sql.raw(imageJoin)}
      WHERE ${targetValid}
        ${search ? sql`AND t."name" ILIKE ${`%${search}%`}` : sql``}
    ), grouped AS (
      SELECT
        "targetId", "targetLabel", "imageId", "imageKey", "imageFilename", "imageContentType",
        count(DISTINCT "expenseId")::int AS "expenseCount",
        count(DISTINCT "purchaseId")::int AS "purchaseCount",
        count(DISTINCT "expenseId") FILTER (WHERE "cost" IS NULL)::int AS "unpricedExpenseCount",
        COALESCE(sum("cost") FILTER (WHERE "costComponent" = 'item'), 0)::float8 AS "itemSpend",
        COALESCE(sum("cost") FILTER (WHERE "costComponent" = 'shared'), 0)::float8 AS "sharedChargeSpend",
        COALESCE(sum("cost"), 0)::float8 AS "netSpend",
        COALESCE(bool_or("allocationIncomplete"), false) AS "incomplete",
        max(COALESCE("purchaseDate", "expenseDate"))::text AS "latestActivity",
        COALESCE(sum("productQuantity") FILTER (WHERE "cost" > 0 AND NOT "future" AND "productQuantity" IS NOT NULL), 0)::double precision AS "knownAcquiredUnits",
        count(DISTINCT "expenseId") FILTER (WHERE "cost" > 0 AND NOT "future" AND "productQuantity" IS NULL)::int AS "unknownAcquisitionQuantityCount"
      FROM targeted
      GROUP BY "targetId", "targetLabel", "imageId", "imageKey", "imageFilename", "imageContentType"
    ), totals AS (
      SELECT
        count(DISTINCT "expenseId")::int AS "totalExpenseCount",
        count(DISTINCT "purchaseId")::int AS "totalPurchaseCount",
        count(DISTINCT "expenseId") FILTER (WHERE "cost" IS NULL)::int AS "totalUnpricedExpenseCount",
        COALESCE(sum("cost") FILTER (WHERE "costComponent" = 'item'), 0)::float8 AS "totalItemSpend",
        COALESCE(sum("cost") FILTER (WHERE "costComponent" = 'shared'), 0)::float8 AS "totalSharedChargeSpend",
        COALESCE(sum("cost"), 0)::float8 AS "totalNetSpend",
        COALESCE(bool_or("allocationIncomplete"), false) AS "totalIncomplete",
        COALESCE(sum("productQuantity") FILTER (WHERE "cost" > 0 AND NOT "future" AND "productQuantity" IS NOT NULL), 0)::double precision AS "totalKnownAcquiredUnits",
        count(DISTINCT "expenseId") FILTER (WHERE "cost" > 0 AND NOT "future" AND "productQuantity" IS NULL)::int AS "totalUnknownAcquisitionQuantityCount"
      FROM targeted
    ), paged AS (
      SELECT grouped.*, true AS "isPageRow"
      FROM grouped
      ORDER BY ${sql.raw(sortColumn)} ${sql.raw(sort.direction.toUpperCase())} NULLS LAST, "targetLabel", "targetId"
      LIMIT ${input.limit} OFFSET ${input.offset}
    )
    SELECT paged.*, totals.*, (SELECT count(*)::int FROM grouped) AS "count"
    FROM totals LEFT JOIN paged ON TRUE
  `;
  const result = await getDb(db).execute(query);
  const rows = summaryRowSchema.array().parse(result.rows);
  const first = rows[0];
  const zeroTotals = {
    expenseCount: 0,
    purchaseCount: 0,
    unpricedExpenseCount: 0,
    itemSpend: 0,
    sharedChargeSpend: 0,
    netSpend: 0,
    incomplete: false,
    knownAcquiredUnits: 0,
    unknownAcquisitionQuantityCount: 0,
  };
  const totals = first
    ? {
        expenseCount: Number(first.totalExpenseCount),
        purchaseCount: Number(first.totalPurchaseCount),
        unpricedExpenseCount: Number(first.totalUnpricedExpenseCount),
        itemSpend: Number(first.totalItemSpend),
        sharedChargeSpend: Number(first.totalSharedChargeSpend),
        netSpend: Number(first.totalNetSpend),
        incomplete: first.totalIncomplete ?? false,
        knownAcquiredUnits: Number(first.totalKnownAcquiredUnits),
        unknownAcquisitionQuantityCount: Number(
          first.totalUnknownAcquisitionQuantityCount,
        ),
      }
    : zeroTotals;
  const count = first ? Number(first.count) : 0;
  const pageRows = rows.filter((row) => row.isPageRow);
  return {
    data: pageRows.map((row) => ({
      target:
        row.targetId && row.targetLabel
          ? {
              entity: definition.targetEntity,
              id: row.targetId,
              label: row.targetLabel,
              image:
                row.imageId &&
                row.imageKey &&
                row.imageFilename &&
                row.imageContentType
                  ? {
                      id: row.imageId,
                      url: getR2PublicUrl(row.imageKey),
                      filename: row.imageFilename,
                      contentType: row.imageContentType,
                    }
                  : null,
            }
          : null,
      expenseCount: Number(row.expenseCount),
      purchaseCount: Number(row.purchaseCount),
      unpricedExpenseCount: Number(row.unpricedExpenseCount),
      itemSpend: Number(row.itemSpend),
      sharedChargeSpend: Number(row.sharedChargeSpend),
      netSpend: Number(row.netSpend),
      incomplete: row.incomplete ?? false,
      latestActivity: row.latestActivity,
      knownAcquiredUnits: Number(row.knownAcquiredUnits),
      unknownAcquisitionQuantityCount: Number(
        row.unknownAcquisitionQuantityCount,
      ),
    })),
    count,
    totals,
    nextOffset:
      input.offset + pageRows.length < count
        ? input.offset + pageRows.length
        : null,
  };
}

/**
 * Server-side predicates for the structured relation trio on an entity list.
 * Repositories append these to their normal where-clause conditions, keeping
 * pagination/counts honest while sharing the exact same curated joins as the
 * preview endpoint.
 */
export function relatedWhereConditions<TFilters extends object>(
  source: Entity,
  filters: TFilters,
  sourceId: SQLWrapper,
): SQL[] {
  const filterValues = new Map(Object.entries(filters));
  return relatedViewRegistry
    .filter((view) => view.source === source)
    .flatMap((definition) => {
      const view = sqlRelatedView(definition.key);
      const prefix = relatedFilterPrefix(definition);
      const rawIds = filterValues.get(`${prefix}Id`);
      const parsedIds = relatedIdsFilterSchema.safeParse(rawIds);
      const ids = parsedIds.success
        ? Array.isArray(parsedIds.data)
          ? parsedIds.data
          : [parsedIds.data]
        : undefined;
      const presence = filterValues.get(`${prefix}PresenceFilter`);
      const rawSearch = filterValues.get(`${prefix}Search`);
      const parsedSearch = relatedSearchFilterSchema.safeParse(rawSearch);
      const search = parsedSearch.success ? parsedSearch.data : undefined;
      if (!ids && presence !== "has" && presence !== "none" && !search) {
        return [];
      }
      const exists = (extra?: SQL) => sql`EXISTS (
        SELECT 1
        FROM ${sql.raw(`"${view.sourceTable}"`)} s
        ${compiledRelatedJoins(definition.key)}
        WHERE s."id" = ${sourceId}
          AND s."deletedAt" IS NULL
          ${viewWhere(view)}
          ${extra ? sql`AND ${extra}` : sql``}
      )`;
      // Compare against the CANONICAL code. Shortcodes are accepted in any
      // casing and with legacy prefixes (`parseShortcode` uppercases and
      // remaps), but the stored column only ever holds the canonical form — so
      // a raw `IN (...)` silently misses `?parentTaskId=tsk-abcd`. A code that
      // doesn't parse at all is kept as-is: it matches nothing, which is the
      // right answer for an unresolvable filter and keeps this predicate's
      // failure direction safe (it ANDs, so it can never widen the query).
      const canonicalIds = ids?.map(
        (id) => parseShortcode(id)?.shortcode ?? id,
      );
      const exact = canonicalIds
        ? canonicalIds.length === 0
          ? sql`false`
          : exists(
              sql`t."shortcode" IN (${sql.join(
                canonicalIds.map((id) => sql`${id}`),
                sql`, `,
              )})`,
            )
        : undefined;
      const presencePredicate =
        presence === "has"
          ? exists()
          : presence === "none"
            ? sql`NOT ${exists()}`
            : undefined;
      const identity =
        exact && presencePredicate
          ? or(exact, presencePredicate)
          : (exact ?? presencePredicate);
      const name = search
        ? exists(sql`${sql.raw(view.label)} ILIKE ${`%${search}%`}`)
        : undefined;
      const condition = and(identity, name);
      return condition ? [condition] : [];
    });
}
