/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: ffb9adde29cbadf9617ce35f36aea850)
interface __BaseEnv_CloudflareBindings {
  USDA_BUNDLES: R2Bucket;
  DB: D1Database;
  API_BASE_URL: string;
  SENTRY_ENVIRONMENT: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "API_BASE_URL" | "SENTRY_ENVIRONMENT">
    > {}
}
