/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: e935974a6a6a17b6743172bc170fdc9e)
interface __BaseEnv_CloudflareBindings {
	AI: Ai;
	CUBBY_PURCHASE_SERVICE: Service /* entrypoint PurchaseImportService from cubby */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
