/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: a04dcef4219b42f20b82d00618895ac5)
interface __BaseEnv_CloudflareBindings {
	AI: Ai;
	SENTRY_ENVIRONMENT: string;
	PURCHASE_IMPORT_RUN: DurableObjectNamespace<import("./src/index").PurchaseImportRunAgent>;
	CUBBY_PURCHASE_SERVICE: Service /* entrypoint PurchaseImportService from cubby */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PurchaseImportRunAgent";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SENTRY_ENVIRONMENT">> {}
}
