/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: ddb3d4e8e33d5f006520d4d2a1c232d3)
interface __BaseEnv_CloudflareBindings {
	AI: Ai;
	SENTRY_ENVIRONMENT: string;
	SENTRY_TRACES_SAMPLE_RATE: string;
	CUBBY_PURCHASE_SERVICE: Service /* entrypoint PurchaseImportService from cubby */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SENTRY_ENVIRONMENT" | "SENTRY_TRACES_SAMPLE_RATE">> {}
}
