[package]
name = "recipebridge"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.9"
# https://doc.rust-lang.org/cargo/reference/config.html
# override: 
# [patch."https://github.com/nickysemenza/ingredient-parser"]
# recipe-scraper = { path = "dev/ingredient-parser/recipe-scraper" }
# ingredient = { path = "dev/ingredient-parser/ingredient-parser" }
ingredient = { git = "https://github.com/nickysemenza/ingredient-parser", branch = "main" }
recipe-scraper = { git = "https://github.com/nickysemenza/ingredient-parser", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
# https://docs.rs/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }
wasm-tracing = "1.0.0"
console_error_panic_hook = "0.1.7"
wee_alloc = { version = "0.4.5", optional = true }

[features]
default = ["wee_alloc"]
