import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { availableParallelism } from "node:os";
import { dirname, join, resolve } from "node:path";
import type { EntityArtifacts } from "./entities/declarations.ts";

/**
 * The ownership header every `//`-commented artifact starts with (`.ts` and
 * `.swift`). YAML carries `yamlGeneratedHeader`; JSON carries nothing and is
 * compared byte for byte.
 */
export const generatedHeader =
  "// Generated by `pnpm generate` — do not edit.\n\n";
export const yamlGeneratedHeader =
  "# Generated by `pnpm generate` — do not edit.\n";
export const markdownGeneratedHeader =
  "<!-- Generated by `pnpm generate` — do not edit. -->\n\n";

export const compactLiteral = <T>(value: T) =>
  JSON.stringify(value).replaceAll(
    /"([A-Za-z_$][\w$]*)":/g,
    (_, key: string) => `${key}:`,
  );

/**
 * `.ts` / `.tsx` artifacts are formatted with oxfmt and sealed with a hash
 * line, so `--check` compares hashes instead of re-formatting. `.json`,
 * `.yaml` and `.swift` are written as rendered and compared raw: oxfmt does
 * not format them (the OpenAPI document is on its ignore list) and a hash
 * line has no home in JSON.
 */
const isSealed = (relativePath: string) => /\.tsx?$/.test(relativePath);

// The workspace's oxfmt binary, run in parallel: each `pnpm exec oxfmt`
// spawn cost ~1.9s against ~0.5s direct, and a serial pass over ~58 sealed
// artifacts made `pnpm generate` (and the post-merge regeneration) slow.
const formatSource = (root: string, artifact: EntityArtifacts) =>
  new Promise<string>((resolvePromise, reject) => {
    const child = execFile(
      join(root, "node_modules/.bin/oxfmt"),
      ["--stdin-filepath", artifact.relativePath],
      { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
      (error, stdout) => (error ? reject(error) : resolvePromise(stdout)),
    );
    child.stdin?.end(artifact.source);
  });

const ARTIFACT_HASH_PATTERN =
  /^\/\/ Artifact hashes: source=([a-f0-9]+) content=([a-f0-9]+)\n/m;
const artifactHash = (source: string) =>
  createHash("sha256").update(source).digest("hex").slice(0, 16);

const sealArtifact = async (
  root: string,
  artifact: EntityArtifacts,
): Promise<EntityArtifacts> => {
  if (!isSealed(artifact.relativePath)) return artifact;
  if (!artifact.source.startsWith(generatedHeader))
    throw new Error(
      `${artifact.relativePath} does not start with the generated header.`,
    );
  const formatted = await formatSource(root, artifact);
  const hashLine = `// Artifact hashes: source=${artifactHash(artifact.source)} content=${artifactHash(formatted)}\n`;
  return {
    ...artifact,
    source: formatted.replace(generatedHeader, generatedHeader + hashLine),
  };
};

/** Seals every artifact, formatting at most one oxfmt process per core. */
export const sealArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
): Promise<EntityArtifacts[]> => {
  const sealed = [...artifacts];
  let next = 0;
  const worker = async () => {
    for (let index = next++; index < sealed.length; index = next++) {
      // SAFETY: the loop condition bounds index to sealed's length.
      sealed[index] = await sealArtifact(
        root,
        sealed[index] as EntityArtifacts,
      );
    }
  };
  const workers = Math.min(availableParallelism(), sealed.length);
  await Promise.all(Array.from({ length: workers }, worker));
  return sealed;
};

// The generator ownership header's first line, shared by every `//`-commented
// artifact. Matching on this instead of a hand-maintained filename allowlist
// means a retired artifact name is still caught as extraneous: the stale file
// on disk keeps carrying the header until something deletes it.
// SAFETY: generatedHeader is a non-empty literal defined above, so splitting
// on "\n" always yields at least one element.
const generatedHeaderMarker = generatedHeader.split("\n")[0] as string;

const carriesGeneratedHeader = async (absolutePath: string) => {
  try {
    const content = await readFile(absolutePath, "utf8");
    return (
      content.startsWith(generatedHeaderMarker) ||
      content.startsWith(yamlGeneratedHeader) ||
      content.startsWith(markdownGeneratedHeader)
    );
  } catch {
    // Unreadable (permissions, binary, race with a concurrent delete) is
    // never one of ours to flag.
    return false;
  }
};

/**
 * Files carrying the generated header in an artifact directory that no
 * artifact claims. Run once over the union of every stage's artifacts: the
 * stages share output directories, so a per-stage scan would flag the other
 * stages' files.
 */
export const findExtraArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  const expected = new Set(artifacts.map(({ relativePath }) => relativePath));
  const directories = new Set(
    artifacts.map(({ relativePath }) => dirname(relativePath)),
  );
  const extras: string[] = [];
  for (const directory of directories) {
    const absoluteDirectory = resolve(root, directory);
    try {
      const entries = await readdir(absoluteDirectory, { withFileTypes: true });
      for (const entry of entries) {
        const relativePath = `${directory}/${entry.name}`;
        if (
          entry.isFile() &&
          !expected.has(relativePath) &&
          (await carriesGeneratedHeader(resolve(root, relativePath)))
        ) {
          extras.push(relativePath);
        }
      }
    } catch (error) {
      if (
        !(error instanceof Error) ||
        !("code" in error) ||
        error.code !== "ENOENT"
      ) {
        throw error;
      }
    }
  }
  return extras.sort();
};

/**
 * `stale:` / `missing:` problems for unsealed (as-rendered) artifacts. A
 * sealed `.ts` file is current when its recorded source hash matches the
 * render and its content hash matches the file, which catches a hand edit
 * without re-running oxfmt; everything else must match byte for byte.
 */
export const checkArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  const problems: string[] = [];
  for (const artifact of artifacts) {
    try {
      const current = await readFile(
        resolve(root, artifact.relativePath),
        "utf8",
      );
      let stale = current !== artifact.source;
      if (isSealed(artifact.relativePath)) {
        const hashes = current.match(ARTIFACT_HASH_PATTERN);
        const content = current.replace(ARTIFACT_HASH_PATTERN, "");
        stale =
          hashes?.[1] !== artifactHash(artifact.source) ||
          hashes?.[2] !== artifactHash(content);
      }
      if (stale) problems.push(`stale: ${artifact.relativePath}`);
    } catch (error) {
      if (
        error instanceof Error &&
        "code" in error &&
        error.code === "ENOENT"
      ) {
        problems.push(`missing: ${artifact.relativePath}`);
        continue;
      }
      throw error;
    }
  }
  return problems;
};

export const writeArtifacts = async (
  root: string,
  artifacts: readonly EntityArtifacts[],
) => {
  for (const artifact of artifacts) {
    const artifactPath = resolve(root, artifact.relativePath);
    await mkdir(dirname(artifactPath), { recursive: true });
    await writeFile(artifactPath, artifact.source);
  }
};
