//! Parsing + formatting exports: ingredient lines, rich instruction text,
//! scraped recipes, and freeform yields.
//!
//! The `W*` types here are a deliberate boundary layer, not duplication of the
//! upstream `ingredient` types. Each one declares the **stable TS wire contract**
//! — decoupled from the upstream type's internal representation (e.g. `Measure`'s
//! private `Unit`/`Rational64` fields, which `Tsify` can't see through because it
//! infers `.d.ts` from Rust field *types*, not `serialize_with` output) — and its
//! `From<upstream>` impl is a **compile-time drift tripwire**. The mirror enums
//! (`WIngredientUsage`, `WConfidence`, `WField`) are generated by [`mirror_enum!`],
//! which keeps the `From` match exhaustive so an upstream variant addition fails
//! to compile until mirrored.

use ingredient::{
    Confidence, Decomposition, Field, ParseNotes, decompose as decompose_str,
    from_str as parse_ingredient_str,
    ingredient::Ingredient,
    rich_text::{Chunk, RichParser},
    usage::IngredientUsage,
};
use recipe_scraper::{RecipeSection, RecipeYield, ScrapedRecipe};
use serde::{Deserialize, Serialize};
use tsify_next::Tsify;
use wasm_bindgen::prelude::*;

use ingredient::unit::Measure;

use crate::WAmount;

mirror_enum! {
    /// The role an ingredient line plays in a recipe (mirrors `IngredientUsage`).
    #[tsify(into_wasm_abi)]
    #[serde(rename_all = "snake_case")]
    pub enum WIngredientUsage <= IngredientUsage {
        Normal,
        FryingMedium,
        PanGrease,
        Seasoning,
        Dredging,
        Garnish,
        Marinade,
    }
}

mirror_enum! {
    /// How confident the parser is in a result (mirrors `Confidence`).
    #[tsify(into_wasm_abi)]
    #[serde(rename_all = "lowercase")]
    pub enum WConfidence <= Confidence {
        High,
        Medium,
        Low,
    }
}

/// Non-failing metadata about *how* a line parsed (mirrors `ParseNotes`):
/// parse fidelity, not costability. "a pinch of salt" is a clean parse whose
/// uncostable quantity a consumer derives from the unit, not from here. Review
/// surfaces key off the discrete `fell_back` / `unparsed_digit` booleans rather
/// than a `confidence` threshold. Booleans are always emitted (no skip) so the
/// TS shape is a definite `{ confidence, fell_back, unparsed_digit }`.
#[derive(Tsify, Serialize, Deserialize, Clone, Copy, PartialEq, Eq, Debug)]
#[tsify(into_wasm_abi)]
pub struct WParseNotes {
    /// Convenience rollup of the booleans below.
    pub confidence: WConfidence,
    /// The parse fell back to a name-only ingredient (no recognizer/core parse).
    pub fell_back: bool,
    /// A digit was present but produced no amount — a likely missed quantity.
    pub unparsed_digit: bool,
}

impl From<ParseNotes> for WParseNotes {
    fn from(n: ParseNotes) -> Self {
        Self {
            confidence: n.confidence.into(),
            fell_back: n.fell_back,
            unparsed_digit: n.unparsed_digit,
        }
    }
}

/// A parsed ingredient (mirrors `Ingredient`).
#[derive(Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi)]
pub struct WIngredient {
    pub name: String,
    pub amounts: Vec<WAmount>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub modifier: Option<String>,
    /// Whether the line is optional (e.g. wrapped in parentheses). Omitted when
    /// false, so the TS shape is `optional?: boolean`.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub optional: bool,
    /// The role the line declares ("oil, for frying" → `frying_medium`).
    pub usage: WIngredientUsage,
    /// Non-failing metadata about how this line parsed (confidence + flags).
    pub parse_notes: WParseNotes,
}

impl From<Ingredient> for WIngredient {
    fn from(i: Ingredient) -> Self {
        Self {
            name: i.name,
            amounts: i.amounts.iter().map(WAmount::from).collect(),
            modifier: i.modifier,
            optional: i.optional,
            usage: i.usage.into(),
            parse_notes: i.parse_notes.into(),
        }
    }
}

/// Structured yield, e.g. `{ value: 12, unit: "pancakes" }`.
#[derive(Tsify, Serialize, Deserialize)]
pub struct WRecipeYield {
    pub value: f64,
    pub unit: String,
}

impl From<RecipeYield> for WRecipeYield {
    fn from(y: RecipeYield) -> Self {
        Self {
            value: y.value,
            unit: y.unit,
        }
    }
}

/// Result of parsing a freeform yield string into structured yield + servings.
#[derive(Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi)]
pub struct WYieldResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe_yield: Option<WRecipeYield>,
    /// Servings as integer (extracted from yield if unit is "serving(s)").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub servings: Option<u32>,
}

/// A recipe component with raw ingredient/instruction lines (mirrors `RecipeSection`).
#[derive(Tsify, Serialize, Deserialize)]
pub struct WRecipeSection {
    /// Component label (e.g., "For the sauce"); absent for the main/only section.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub ingredients: Vec<String>,
    pub instructions: Vec<String>,
}

impl From<RecipeSection> for WRecipeSection {
    fn from(s: RecipeSection) -> Self {
        Self {
            name: s.name,
            ingredients: s.ingredients,
            instructions: s.instructions,
        }
    }
}

/// A scraped recipe (the cubby-facing subset of `ScrapedRecipe`); the TS side
/// converts it to the shared `ImportRecipe` carrier.
#[derive(Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi)]
pub struct WScrapedRecipe {
    /// Recipe components; most recipes have a single unnamed section.
    pub sections: Vec<WRecipeSection>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Headnote / intro blurb (schema.org `description`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Parsed yield (e.g., `{ value: 12, unit: "pancakes" }`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe_yield: Option<WRecipeYield>,
    /// Servings as integer (extracted from yield if unit is "serving(s)").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub servings: Option<u32>,
}

impl From<ScrapedRecipe> for WScrapedRecipe {
    fn from(r: ScrapedRecipe) -> Self {
        Self {
            sections: r.sections.into_iter().map(WRecipeSection::from).collect(),
            name: Some(r.name),
            url: Some(r.url),
            image: r.image,
            description: r.description,
            recipe_yield: r.recipe_yield.map(WRecipeYield::from),
            servings: r.servings,
        }
    }
}

/// One span of measurement-aware instruction text (mirrors `Chunk`).
#[derive(Tsify, Serialize, Deserialize)]
#[serde(tag = "kind", content = "value")]
pub enum WRichItem {
    Text(String),
    Ing(String),
    Measure(Vec<WAmount>),
}

impl From<Chunk> for WRichItem {
    fn from(c: Chunk) -> Self {
        match c {
            Chunk::Text(t) => WRichItem::Text(t),
            Chunk::Ing(i) => WRichItem::Ing(i),
            Chunk::Measure(ms) => WRichItem::Measure(ms.iter().map(WAmount::from).collect()),
        }
    }
}

/// `WRichItem[]` (`transparent` → `type WRichItems = WRichItem[]`).
#[derive(Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi)]
#[serde(transparent)]
pub struct WRichItems(pub Vec<WRichItem>);

mirror_enum! {
    /// Which output field a decomposition segment became (mirrors `Field`).
    /// Renders as the TS string union `"amount" | "name" | "modifier"`, matching
    /// the keys of the `INGREDIENT_PART_COLOR` map on the TS side.
    #[serde(rename_all = "lowercase")]
    pub enum WField <= Field {
        Amount,
        Name,
        Modifier,
    }
}

/// One contiguous chunk of the decomposed line: either a labeled field span or
/// unlabeled gap text. The segments concatenate back to the whole source, so JS
/// renders them in order with no byte-offset math (the Rust spans are UTF-8 byte
/// ranges, which don't map to JS UTF-16 indices).
#[derive(Tsify, Serialize, Deserialize)]
pub struct WSegment {
    pub text: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field: Option<WField>,
}

/// How the grammar carved a line into fields (mirrors `Decomposition`), as an
/// ordered list of segments covering the whole source. `segments` carries no
/// labeled entries when a whole-line recognizer or the name-only fallback
/// produced the result (then it's a single unlabeled segment = the whole line).
#[derive(Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi)]
pub struct WDecomposition {
    pub source: String,
    pub segments: Vec<WSegment>,
}

impl From<Decomposition> for WDecomposition {
    fn from(d: Decomposition) -> Self {
        // Walk the sorted, non-overlapping spans, emitting any gap text before
        // each labeled span, then the span itself, then the trailing gap.
        //
        // Slice via `get` (not `[..]`): the spans are upstream byte ranges from a
        // parser pinned to an upstream commit. A range that's out of bounds,
        // overlapping (`start < prev_end`), or lands mid-UTF-8 would panic an
        // index — `get` yields `None` and we skip that gap instead of trapping.
        let mut segments = Vec::new();
        let mut prev_end = 0usize;
        for span in &d.spans {
            if span.range.start > prev_end {
                if let Some(gap) = d.source.get(prev_end..span.range.start) {
                    segments.push(WSegment {
                        text: gap.to_string(),
                        field: None,
                    });
                }
            }
            segments.push(WSegment {
                text: span.text.clone(),
                field: Some(span.field.into()),
            });
            prev_end = span.range.end;
        }
        if prev_end < d.source.len() {
            if let Some(tail) = d.source.get(prev_end..) {
                segments.push(WSegment {
                    text: tail.to_string(),
                    field: None,
                });
            }
        }
        WDecomposition {
            source: d.source,
            segments,
        }
    }
}

#[wasm_bindgen]
pub fn parse_ingredient(input: &str) -> WIngredient {
    parse_ingredient_str(input).into()
}

/// `WIngredient[]` (`transparent` → `type WParsedLines = WIngredient[]`).
#[derive(Tsify, Serialize, Deserialize)]
#[tsify(into_wasm_abi)]
#[serde(transparent)]
pub struct WParsedLines(pub Vec<WIngredient>);

/// Batch [`parse_ingredient`]: one boundary crossing for N lines (collapses the
/// TS per-line loops on paste/import/report surfaces). Output order matches
/// input; each element is exactly what `parse_ingredient` returns for that line.
#[wasm_bindgen]
pub fn parse_ingredient_lines(lines: Vec<String>) -> WParsedLines {
    WParsedLines(
        lines
            .iter()
            .map(|line| parse_ingredient_str(line).into())
            .collect(),
    )
}

/// Decompose a line into ordered `{text, field?}` segments showing how the
/// grammar carved it into amount / name / modifier spans. `source` is the
/// *normalized* line the spans index into, not the verbatim raw input.
#[wasm_bindgen]
pub fn decompose_ingredient(input: &str) -> WDecomposition {
    decompose_str(input).into()
}

#[wasm_bindgen]
pub fn format_amount(amount: WAmount) -> String {
    amount.to_measure().to_string()
}

/// Grams per ounce / ounces per pound — the same factors the parser normalizes
/// weights with, restated here because they are private upstream.
const GRAM_TO_OZ: f64 = 28.3495;
const OZ_TO_LB: f64 = 16.0;
const ML_TO_L: f64 = 1000.0;

/// Pick a shopping-friendly unit and value for a base-unit measure.
///
/// Returns `None` when the caller should just use the normal formatter.
fn shopper_unit(unit: &str, value: f64) -> Option<(&'static str, f64)> {
    match unit {
        // The availability engine reconciles weights in grams, so a shortfall
        // arrives as "1360 g" — true, and useless at a shelf. Ounces below a
        // pound, pounds above it.
        "g" => {
            if value >= GRAM_TO_OZ * OZ_TO_LB {
                Some(("lb", value / (GRAM_TO_OZ * OZ_TO_LB)))
            } else if value >= GRAM_TO_OZ {
                Some(("oz", value / GRAM_TO_OZ))
            } else {
                None
            }
        }
        // Volume already ladders tsp -> tbsp -> cup upstream; only the metric
        // base stays put, so this is just the litre step.
        "ml" => {
            if value >= ML_TO_L {
                Some(("l", value / ML_TO_L))
            } else {
                None
            }
        }
        _ => None,
    }
}

/// Format an amount the way it would be read off a shopping list rather than
/// out of the conversion graph.
///
/// `format_amount` renders the measure as stored, and `Measure::denormalize`
/// (which it does not call) ladders teaspoons and cents but deliberately leaves
/// `Gram` and `Milliliter` untouched. That is exactly the pair the shopping
/// list produces, which is why a flour shortfall prints as "1360 g" instead of
/// "3 lb".
///
/// Kept here rather than upstream in `ingredient` only to avoid a cross-repo
/// rev bump; the ladder is generic unit formatting with no cubby domain in it,
/// so it belongs in the parser crate eventually — same migration the TODO in
/// `reconcile.rs` describes.
#[wasm_bindgen]
pub fn format_amount_shopper(amount: WAmount) -> String {
    let denormalized = amount.to_measure().denormalize();
    let value = denormalized.value();

    // Nothing better to say — fall back to the normal rendering rather than
    // inventing a unit.
    let Some((target, scaled)) = shopper_unit(&denormalized.unit().to_str(), value) else {
        return denormalized.to_string();
    };

    match denormalized.upper_value() {
        // Both ends scale by the same factor so the range stays true. `value`
        // is non-zero here: every `shopper_unit` arm requires it to clear a
        // positive threshold first.
        Some(upper) => Measure::with_range(target, scaled, upper * (scaled / value)).to_string(),
        None => Measure::new(target, scaled).to_string(),
    }
}

/// Render a quantity float as an *editable* ASCII fraction for the recipe editor's
/// quantity cell: `0.333… → "1/3"`, `1.5 → "1 1/2"`, `34 → "34"`, decimal fallback for
/// non-fractions (`0.37 → "0.37"`). The inverse of `parse_quantity`.
///
/// Thin WASM shim over `ingredient::util::format_quantity_ascii` — the algorithm lives
/// upstream alongside the parser's glyph `format_quantity`, sharing the fraction logic
/// (see that fn for the denominator-cap + `1e-6` recheck details).
#[wasm_bindgen]
pub fn format_quantity(value: f64) -> String {
    ingredient::util::format_quantity_ascii(value)
}

/// Parse a quantity string (`"1/3"`, `"1 1/2"`, `"⅓"`, `"0.5"`, `"34"`) back to an
/// f64, reusing the ingredient parser's measurement grammar (mixed numbers, vulgar
/// fractions). The inverse of `format_quantity`. The editor's quantity cell holds
/// only a quantity — the unit is a separate field — so a faux `"<qty> x"` line backs
/// up the bare-measurement parse when the grammar wants a trailing token.
#[wasm_bindgen]
pub fn parse_quantity(input: &str) -> Result<f64, String> {
    // Trim once up front so both parse paths (bare-measurement and the faux-line
    // fallback) see the same normalized input.
    let trimmed = input.trim();
    let parser = ingredient::IngredientParser::new();
    if let Ok(measures) = parser.parse_amount(trimmed) {
        if let Some(m) = measures.first() {
            return Ok(m.value());
        }
    }
    parser
        .from_str(&format!("{trimmed} x"))
        .amounts
        .first()
        .map(|m| m.value())
        .ok_or_else(|| format!("could not parse quantity {input:?}"))
}

/// Parse an amount string (`"1 1/2 cups"`, `"2.5 lb"`, `"5 each"`, bare `"3"`) into a
/// structured `{ value, unit }` — the unit-KEEPING sibling of [`parse_quantity`], which
/// runs the same `parse_amount` grammar and then throws the unit away.
///
/// This is the only correct way to turn free-text amount input (a clipboard paste, a
/// typed cell) into a stored `Amount`. The grammar owns mixed numbers (`"1 1/2"` → 1.5),
/// vulgar fractions, ranges, and unit normalization — none of which a TS regex
/// reproduces: the hand-rolled `^(-?\d+(?:\.\d+)?)\s*(.*)$` it replaces read
/// `"1 1/2 cups"` as `1` of `"1/2 cups"`, a 33% understatement carrying a unit that can
/// never resolve in the unit graph, and then saved it.
///
/// Errors rather than guessing when the input carries no recognizable measurement, so
/// the caller rejects the paste instead of persisting garbage.
#[wasm_bindgen]
pub fn parse_amount(input: &str) -> Result<WAmount, String> {
    // Trim up front so the grammar sees the same normalized input `parse_quantity` does.
    let trimmed = input.trim();
    ingredient::IngredientParser::new()
        .parse_amount(trimmed)
        .ok()
        .and_then(|measures| measures.first().map(WAmount::from))
        .ok_or_else(|| format!("could not parse amount {input:?}"))
}

/// Singularize a unit for display labels ("churros" → "churro", "cups" → "cup").
/// Wraps the parser's `singular` so cubby and ingredient-parser agree on the rule,
/// including the `-es` guard ("glasses" → "glass", not "glasse"). It expects a
/// plural; an already-singular word is out of contract (e.g. "glass" → "glas").
/// See `singularize_unit_table` in the tests for the locked-in cases.
#[wasm_bindgen]
pub fn singularize_unit(unit: String) -> String {
    ingredient::unit::singular(&unit).to_string()
}

#[wasm_bindgen]
pub fn parse_scraped_recipe(body: &str, url: &str) -> Result<WScrapedRecipe, String> {
    recipe_scraper::scrape(body, url)
        .map_err(|e| format!("Failed to scrape: {e}"))
        .map(WScrapedRecipe::from)
}

/// Parse a freeform yield string ("Makes about 12 pancakes", "Serves 4") into a
/// structured `{ recipe_yield?, servings? }`, using the same parser the web
/// scraper uses for JSON-LD yields (so cookbook and web yields stay consistent).
#[wasm_bindgen]
pub fn parse_yield(input: &str) -> WYieldResult {
    let (recipe_yield, servings) = recipe_scraper::parse_yield_string(input);
    WYieldResult {
        recipe_yield: recipe_yield.map(WRecipeYield::from),
        servings,
    }
}

#[wasm_bindgen]
pub fn parse_rich_text(text: String, ingredient_names: Vec<String>) -> Result<WRichItems, String> {
    RichParser::new(ingredient_names)
        .parse(&text)
        .map_err(|e| e.to_string())
        .map(|chunks| WRichItems(chunks.into_iter().map(WRichItem::from).collect()))
}

// Golden tests — drift tripwires for the ingredient / recipe-scraper crates
// (pinned by exact git rev in Cargo.toml). The parse_* fns are plain Rust under
// the #[wasm_bindgen] attribute, so they run natively under `cargo test`. The
// asserts pin the W-bridge serde shapes the TS side reads; a parser rev bump
// that changes classification, the snake_case rename, yield/singularization, or
// the rich-text chunk contract fails here instead of three layers downstream.
#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    fn amount(unit: &str, value: f64) -> WAmount {
        WAmount {
            unit: unit.to_string(),
            value,
            upper_value: None,
        }
    }

    /// The shopping-list ladder. `format_amount` renders the base unit the
    /// availability engine reconciles in, which is why a flour shortfall used
    /// to read "1360 g" on a surface meant to be carried to a shop.
    #[rstest]
    #[case("g", 1360.0, "3 lb")]
    #[case("g", 500.0, "1.1 lb")]
    #[case("g", 100.0, "3.53 oz")]
    // Below an ounce there is no friendlier unit; grams are already the answer.
    #[case("g", 12.0, "12 g")]
    // Fractions render as glyphs — the parser's own quantity formatting.
    #[case("ml", 1500.0, "1\u{00bd} l")]
    #[case("ml", 250.0, "250 ml")]
    // Volume already ladders upstream via `denormalize`; this must not undo it.
    #[case("tsp", 48.0, "1 cup")]
    // Non-weight, non-volume units pass through untouched.
    #[case("whole", 3.0, "3")]
    fn shopper_amounts(#[case] unit: &str, #[case] value: f64, #[case] expected: &str) {
        assert_eq!(format_amount_shopper(amount(unit, value)), expected);
    }

    /// A range scales by one factor, so both ends stay in the same unit.
    #[test]
    fn shopper_amount_keeps_ranges_together() {
        let ranged = WAmount {
            unit: "g".to_string(),
            value: 1000.0,
            upper_value: Some(2000.0),
        };
        let formatted = format_amount_shopper(ranged);
        assert!(formatted.contains("lb"), "expected pounds, got {formatted}");
        assert!(
            !formatted.contains('g'),
            "range should not mix units: {formatted}"
        );
    }

    /// One line per `WIngredientUsage` variant: the `IngredientUsage` drift
    /// tripwire. A parser change that drops or reclassifies a role would silently
    /// mis-cost (e.g. "oil, for frying" billed as a full ingredient) — caught here.
    #[rstest]
    #[case("2 cups flour", WIngredientUsage::Normal)]
    #[case("oil, for frying", WIngredientUsage::FryingMedium)]
    #[case("butter, for the pan", WIngredientUsage::PanGrease)]
    #[case("salt, to taste", WIngredientUsage::Seasoning)]
    #[case("flour, for dredging", WIngredientUsage::Dredging)]
    #[case("parsley, for garnish", WIngredientUsage::Garnish)]
    #[case("soy sauce, for marinating", WIngredientUsage::Marinade)]
    fn usage_classification(#[case] line: &str, #[case] expected: WIngredientUsage) {
        assert_eq!(parse_ingredient(line).usage, expected);
    }

    /// The snake_case wire contract the TS side reads (`frying_medium`, not
    /// `FryingMedium`) — locks the serde rename against an accidental drop.
    #[test]
    fn usage_serde_is_snake_case() {
        assert_eq!(
            serde_json::to_value(WIngredientUsage::FryingMedium).unwrap(),
            serde_json::json!("frying_medium")
        );
        assert_eq!(
            serde_json::to_value(WIngredientUsage::Normal).unwrap(),
            serde_json::json!("normal")
        );
    }

    /// `parse_ingredient` golden over serde — confirms the full W-bridge shape
    /// (name, one `{value, unit}` amount, snake_case usage, modifier omitted when
    /// absent, definite `parse_notes`), mirroring
    /// `component_source_serde_matches_the_zod_contract`.
    #[test]
    fn parse_ingredient_golden_shape() {
        let parsed = parse_ingredient("2 1/2 cups flour");
        assert_eq!(parsed.name, "flour");
        assert_eq!(parsed.usage, WIngredientUsage::Normal);
        assert_eq!(
            serde_json::to_value(&parsed).unwrap(),
            serde_json::json!({
                "name": "flour",
                "amounts": [{ "unit": "cup", "value": 2.5 }],
                "usage": "normal",
                "parse_notes": {
                    "confidence": "high",
                    "fell_back": false,
                    "unparsed_digit": false,
                },
            })
        );
    }

    /// `optional` round-trips from upstream `Ingredient::optional` (regression:
    /// the field was previously dropped at the boundary, so a parenthesized
    /// "optional" line lost that signal on the way to TS). A parenthesized line
    /// emits `optional: true`; a normal line omits the key (skip_serializing_if).
    #[test]
    fn optional_ingredient_surfaces() {
        let opt = parse_ingredient("(½ cup chopped walnuts)");
        assert!(opt.optional, "parenthesized line should be optional");
        assert_eq!(
            serde_json::to_value(&opt).unwrap()["optional"],
            serde_json::json!(true)
        );

        let normal = parse_ingredient("2 cups flour");
        assert!(!normal.optional);
        assert_eq!(
            serde_json::to_value(&normal).unwrap().get("optional"),
            None,
            "a non-optional line omits the key"
        );
    }

    /// `parse_notes` drift tripwire: the confidence rollup + the discrete
    /// `unparsed_digit` review signal the TS side keys off. A structured parse is
    /// High; a clean name-only line is Medium; a digit that yields no amount is
    /// Low and flags `unparsed_digit` (the silent-dropped-quantity case).
    #[rstest]
    #[case("2 cups flour", WConfidence::High, false)]
    #[case("Chocolate Chip Cookies", WConfidence::Medium, false)]
    #[case("salt to taste", WConfidence::Medium, false)]
    #[case("1+1 multivitamins", WConfidence::Low, true)]
    fn parse_notes_drift(
        #[case] line: &str,
        #[case] confidence: WConfidence,
        #[case] unparsed_digit: bool,
    ) {
        let notes = parse_ingredient(line).parse_notes;
        assert_eq!(notes.confidence, confidence, "confidence for: {line}");
        assert_eq!(
            notes.unparsed_digit, unparsed_digit,
            "unparsed_digit for: {line}"
        );
    }

    /// `parse_ingredient_lines` ≡ N sequential `parse_ingredient` calls — the
    /// equivalence contract the TS loop-collapse relies on. Mixed batch: a
    /// structured line, an amount-less name, an empty string, an optional
    /// parenthesized line, and a usage-classified line. Compared over serde so
    /// the whole wire shape (amounts, flags, notes) is pinned, plus the
    /// `transparent` array serialization.
    #[test]
    fn parse_ingredient_lines_matches_sequential() {
        let lines = [
            "2 1/2 cups flour",
            "Chocolate Chip Cookies",
            "",
            "(½ cup chopped walnuts)",
            "oil, for frying",
        ];
        let batch = parse_ingredient_lines(lines.iter().map(|s| s.to_string()).collect());
        assert_eq!(
            batch.0.len(),
            lines.len(),
            "output order/length matches input"
        );
        let sequential: Vec<serde_json::Value> = lines
            .iter()
            .map(|l| serde_json::to_value(parse_ingredient(l)).expect("serializes"))
            .collect();
        assert_eq!(
            serde_json::to_value(&batch).expect("serializes"),
            serde_json::Value::Array(sequential),
            "batch is transparent array of per-line parse_ingredient results"
        );
    }

    /// `parse_scraped_recipe` drift tripwire: pins the `From<ScrapedRecipe>`
    /// reshaping the TS import relies on — `name`/`url` wrapped in `Some`, sections
    /// carried through, yield parsed. A scraper field rename would surface here
    /// rather than silently producing an empty import.
    #[test]
    fn parse_scraped_recipe_reshapes_jsonld() {
        let html = r#"<html><head><script type="application/ld+json">{"name":"Test Cake","recipeIngredient":["2 cups flour","1 cup sugar"],"recipeInstructions":"Mix. Bake.","recipeYield":"8 servings"}</script></head><body></body></html>"#;
        let r = parse_scraped_recipe(html, "https://example.com/cake").expect("scrapes");
        assert_eq!(r.name.as_deref(), Some("Test Cake"));
        assert_eq!(r.url.as_deref(), Some("https://example.com/cake"));
        assert!(
            r.sections
                .iter()
                .any(|s| s.ingredients.iter().any(|i| i.contains("flour"))),
            "ingredient lines carried through into sections"
        );
    }

    /// `parse_yield` pins the cookbook/web yield-consistency contract: a count
    /// yield carries the generic `whole` unit and no servings; a "Serves N" line
    /// populates `servings`. (Both surface the same parser the web scraper uses.)
    #[rstest]
    #[case("Makes about 12 pancakes", 12.0, None)]
    #[case("Serves 4", 4.0, Some(4))]
    fn parse_yield_table(#[case] input: &str, #[case] value: f64, #[case] servings: Option<u32>) {
        let result = parse_yield(input);
        let y = result.recipe_yield.expect("recipe_yield present");
        assert_eq!(y.value, value);
        // The parser emits a generic count unit ("whole") for bare counts; the
        // display layer relabels using the trailing noun.
        assert_eq!(y.unit, "whole");
        assert_eq!(result.servings, servings);
    }

    /// `singularize_unit` for display labels. The `-es` guard is the real lock:
    /// "glasses" → "glass" (not "glasse"). Note the singularizer's contract is
    /// plural → singular; an already-singular "glass" is out of scope and returns
    /// the naive strip "glas", so it isn't asserted here.
    #[rstest]
    #[case("cups", "cup")]
    #[case("churros", "churro")]
    #[case("glasses", "glass")]
    fn singularize_unit_table(#[case] plural: &str, #[case] expected: &str) {
        assert_eq!(singularize_unit(plural.to_string()), expected);
    }

    /// Shim sanity: `format_quantity` delegates to `ingredient::util::
    /// format_quantity_ascii` (exhaustive cases — negatives, denom cap, decimal
    /// fallback — live in that crate's `util` tests). Just confirms the WASM export
    /// is wired to the upstream formatter.
    #[rstest]
    #[case(1.0 / 3.0, "1/3")]
    #[case(1.0 / 16.0, "1/16")]
    #[case(34.0, "34")]
    fn format_quantity_delegates(#[case] value: f64, #[case] expected: &str) {
        assert_eq!(format_quantity(value), expected);
    }

    /// Unparseable input falls through the bare-measurement parse *and* the faux-line
    /// fallback to an `Err`, rather than panicking or returning a bogus number — the
    /// editor surfaces this as `aria-invalid` and retains the typed text.
    #[rstest]
    #[case("xyz")]
    #[case("")]
    fn parse_quantity_rejects_non_quantities(#[case] input: &str) {
        assert!(parse_quantity(input).is_err(), "expected Err for {input:?}");
    }

    /// `parse_quantity` reads the leading quantity (mixed numbers, vulgar glyphs,
    /// decimals) the way the editor's qty cell feeds it — no unit.
    #[rstest]
    #[case("1/3", 1.0 / 3.0)]
    #[case("1/2", 0.5)]
    #[case("1 1/2", 1.5)]
    #[case("⅓", 1.0 / 3.0)]
    #[case("0.5", 0.5)]
    #[case("34", 34.0)]
    fn parse_quantity_table(#[case] input: &str, #[case] expected: f64) {
        let v = parse_quantity(input).expect("parses");
        assert!(
            (v - expected).abs() < 1e-6,
            "{input} -> {v}, want {expected}"
        );
    }

    /// `parse_amount` over the exact clipboard-paste cases the data-table's amount
    /// cell feeds it. The first two rows are the regression: the TS regex this
    /// replaces (`^(-?\d+(?:\.\d+)?)\s*(.*)$`) read them as `1` of `"1/2 cups"` and
    /// `1` of `",5 kg"` — a wrong number plus a unit no unit-graph edge can reach —
    /// and then SAVED that. Bare counts canonicalize to the engine's `whole`
    /// (`Unit::Whole`, which `"each"` also parses to), so a unit-less paste yields a
    /// schema-valid unit rather than the old `""`.
    #[rstest]
    #[case("1 1/2 cups", 1.5, "cup")]
    #[case("1,5 kg", 1.0, "whole")]
    #[case("2.5 lb", 2.5, "lb")]
    #[case("5 each", 5.0, "whole")]
    #[case("3", 3.0, "whole")]
    #[case("  12 oz  ", 12.0, "oz")]
    #[case("⅓ cup", 1.0 / 3.0, "cup")]
    fn parse_amount_table(#[case] input: &str, #[case] value: f64, #[case] unit: &str) {
        let a = parse_amount(input).expect("parses");
        assert!(
            (a.value - value).abs() < 1e-9,
            "{input} -> {}, want {value}",
            a.value
        );
        assert_eq!(a.unit, unit, "unit for {input}");
    }

    /// A ranged paste keeps its upper bound, so `"2-3 cups"` round-trips into the
    /// persisted `Amount`'s `upperValue` instead of silently collapsing to its lower
    /// bound.
    #[test]
    fn parse_amount_carries_a_range() {
        let a = parse_amount("2-3 cups").expect("parses");
        assert_eq!((a.value, a.unit.as_str()), (2.0, "cup"));
        assert_eq!(a.upper_value, Some(3.0));
    }

    /// Text carrying no recognizable measurement is an `Err`, never a guess — the
    /// caller surfaces "not an amount" and leaves the cell alone. This is the whole
    /// point of routing paste through the grammar: the old regex had no failure mode
    /// short of a leading non-digit, so anything digit-initial was persisted.
    #[rstest]
    #[case("not an amount")]
    #[case("")]
    #[case("   ")]
    fn parse_amount_rejects_non_amounts(#[case] input: &str) {
        assert!(parse_amount(input).is_err(), "expected Err for {input:?}");
    }

    /// `parse_amount` and `parse_quantity` read the SAME grammar — the former keeps
    /// the unit, the latter drops it. Pinned so the two can't drift into disagreeing
    /// about a value (they share one `IngredientParser::parse_amount` call).
    #[rstest]
    #[case("1 1/2 cups")]
    #[case("2.5 lb")]
    #[case("3")]
    fn parse_amount_value_matches_parse_quantity(#[case] input: &str) {
        let a = parse_amount(input).expect("parses");
        let q = parse_quantity(input).expect("parses");
        assert!((a.value - q).abs() < 1e-9, "{input}: {} vs {q}", a.value);
    }

    /// `format(parse(x))` is stable for fraction strings — the editor can resync a
    /// blurred cell without drift.
    #[rstest]
    #[case("1/3")]
    #[case("1 1/2")]
    #[case("3/16")]
    #[case("1/16")]
    fn quantity_roundtrip(#[case] s: &str) {
        let v = parse_quantity(s).expect("parses");
        assert_eq!(format_quantity(v), s);
    }

    /// `WDecomposition::from` invariant: the segments always concatenate back to
    /// the whole `source` (no characters dropped or duplicated). This is the
    /// contract the TS renderer relies on to draw the carve with no offset math.
    /// Built directly from a `Decomposition` so the gap-walking is exercised
    /// without depending on a specific parser carving.
    #[test]
    fn decomposition_segments_cover_source() {
        use ingredient::FieldSpan;
        // "AA NN, MM" — a gap (space) before NN, the ", " gap before MM.
        let d = Decomposition {
            source: "AA NN, MM".to_string(),
            spans: vec![
                FieldSpan {
                    field: Field::Amount,
                    range: 0..2,
                    text: "AA".to_string(),
                },
                FieldSpan {
                    field: Field::Name,
                    range: 3..5,
                    text: "NN".to_string(),
                },
                FieldSpan {
                    field: Field::Modifier,
                    range: 7..9,
                    text: "MM".to_string(),
                },
            ],
        };
        let w = WDecomposition::from(d);
        // Segments concatenate back to the source verbatim.
        let joined: String = w.segments.iter().map(|s| s.text.as_str()).collect();
        assert_eq!(joined, "AA NN, MM");
        // Labeled fields appear in input order; gaps are unlabeled.
        let labeled: Vec<(&str, bool)> = w
            .segments
            .iter()
            .map(|s| (s.text.as_str(), s.field.is_some()))
            .collect();
        assert_eq!(
            labeled,
            [
                ("AA", true),
                (" ", false),
                ("NN", true),
                (", ", false),
                ("MM", true),
            ]
        );
    }

    /// Defensive: the spans are upstream byte ranges from a parser pinned to an
    /// moving `branch = main`. A range landing mid-UTF-8 (here byte 1 of the
    /// 2-byte 'é') must not panic the gap slice — pre-fix `source[0..1]` did.
    #[test]
    fn decomposition_tolerates_non_char_boundary_span() {
        use ingredient::FieldSpan;
        let w = WDecomposition::from(Decomposition {
            source: "é".to_string(), // bytes [0xC3, 0xA9]
            spans: vec![FieldSpan {
                field: Field::Name,
                range: 1..2, // starts mid-codepoint
                text: "x".to_string(),
            }],
        });
        // No panic; the mid-char gap is skipped, the span text still emitted.
        assert!(w.segments.iter().any(|s| s.text == "x"));
    }

    /// Empty-spans case (whole-line recognizer / name-only fallback): a single
    /// unlabeled segment equal to the whole source, so the TS side renders plain
    /// text with no special-casing.
    #[test]
    fn decomposition_empty_spans_is_one_plain_segment() {
        let w = WDecomposition::from(Decomposition {
            source: "whole line".to_string(),
            spans: vec![],
        });
        assert_eq!(w.segments.len(), 1);
        assert_eq!(w.segments[0].text, "whole line");
        assert!(w.segments[0].field.is_none());
    }

    /// `decompose_ingredient` over a real parse: the carve of a standard line
    /// covers the source and labels amount/name spans. The `"lowercase"` serde
    /// rename (the TS string union) is pinned alongside.
    #[test]
    fn decompose_ingredient_real_parse() {
        let w = decompose_ingredient("2 cups flour");
        let joined: String = w.segments.iter().map(|s| s.text.as_str()).collect();
        assert_eq!(joined, w.source);
        let fields: Vec<serde_json::Value> = w
            .segments
            .iter()
            .filter_map(|s| s.field.as_ref())
            .map(|f| serde_json::to_value(f).unwrap())
            .collect();
        assert_eq!(
            fields,
            [serde_json::json!("amount"), serde_json::json!("name")]
        );
    }

    /// `parse_rich_text` chunk sequence + the `{kind, value}` serde tag shape the
    /// richtext UI consumes: known ingredient names → `Ing`, an inline measure →
    /// `Measure`, the rest → `Text`.
    #[test]
    fn parse_rich_text_chunks_and_tag_shape() {
        let items = parse_rich_text(
            "heat the oil and add 2 cups water".to_string(),
            vec!["oil".to_string(), "water".to_string()],
        )
        .expect("rich text parses");

        let kinds: Vec<&str> = items
            .0
            .iter()
            .map(|c| match c {
                WRichItem::Text(_) => "Text",
                WRichItem::Ing(_) => "Ing",
                WRichItem::Measure(_) => "Measure",
            })
            .collect();
        assert_eq!(kinds, ["Text", "Ing", "Text", "Measure", "Text", "Ing"]);

        assert_eq!(
            serde_json::to_value(&items).unwrap(),
            serde_json::json!([
                { "kind": "Text", "value": "heat the " },
                { "kind": "Ing", "value": "oil" },
                { "kind": "Text", "value": " and add " },
                { "kind": "Measure", "value": [{ "unit": "cup", "value": 2.0 }] },
                { "kind": "Text", "value": " " },
                { "kind": "Ing", "value": "water" },
            ])
        );
    }
}
