import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./usda"; // generated by openapi-typescript
import { type Span, trace } from "@opentelemetry/api";

// npx openapi-typescript http://localhost:8080/doc -o src/usda-api-client/usda.d.ts

// Extend Request type to include tracing properties
interface TracedRequest extends Request {
  __span?: Span;
  __startTime?: number;
}

export class UsdaApiClient {
  private client: ReturnType<typeof createClient<paths>>;

  constructor(baseUrl: string) {
    this.client = createClient<paths>({ baseUrl });

    // Get tracer instance
    const tracer = trace.getTracer("usda-api");

    // Add tracing middleware
    const tracingMiddleware: Middleware = {
      async onRequest({ request, schemaPath }) {
        const span = tracer.startSpan(
          `USDA API: ${request.method} ${schemaPath}`,
        );

        // Store span in request context for access in response/error handlers
        const tracedRequest = request as TracedRequest;
        tracedRequest.__span = span;

        span.setAttributes({
          "http.method": request.method,
          "http.url": request.url,
          "api.schema_path": schemaPath || "unknown",
          "api.client": "usda-api",
        });

        const startTime = Date.now();
        tracedRequest.__startTime = startTime;

        return request;
      },

      async onResponse({ request, response }) {
        const tracedRequest = request as TracedRequest;
        const span = tracedRequest.__span;
        const startTime = tracedRequest.__startTime;

        if (span && startTime) {
          const duration = Date.now() - startTime;

          span.setAttributes({
            "http.status_code": response.status,
            "http.response.duration_ms": duration,
          });

          if (response.ok) {
            span.setStatus({ code: 1 }); // OK
          } else {
            span.setStatus({
              code: 2, // ERROR
              message: `HTTP ${response.status}: ${response.statusText}`,
            });
          }

          span.end();
        }

        return response;
      },

      async onError({ request, error }) {
        const tracedRequest = request as TracedRequest;
        const span = tracedRequest.__span;

        if (span) {
          const errorObj =
            error instanceof Error ? error : new Error(String(error));

          span.setAttributes({
            error: true,
            "error.message": errorObj.message,
            "error.name": errorObj.name,
          });

          span.setStatus({
            code: 2, // ERROR
            message: errorObj.message,
          });

          span.end();
        }

        // Re-throw the error to preserve original behavior
        throw error;
      },
    };

    this.client.use(tracingMiddleware);
  }

  async getFood(fdcId: string) {
    return await this.client.GET("/api/foods/{fdc_id}", {
      params: {
        path: { fdc_id: fdcId },
      },
    });
  }

  async findFoodByUPC(gtinUpc: string) {
    return await this.client.GET("/api/foods/search/upc/{gtin_upc}", {
      params: {
        path: { gtin_upc: gtinUpc },
      },
    });
  }

  async findFoodByNDB(ndbNumber: string) {
    return await this.client.GET("/api/foods/search/ndb/{ndb_number}", {
      params: {
        path: { ndb_number: ndbNumber },
      },
    });
  }

  async listFoods(params?: {
    nameFilter?: string;
    dataTypeFilter?: string;
    orderBy?: "description" | "data_type" | "fdc_id";
    direction?: "asc" | "desc";
    pageIndex?: number | null;
    pageSize?: number | null;
  }) {
    return await this.client.GET("/api/foods", {
      params: {
        query: params,
      },
    });
  }
}
