export type HoverPreviewEntity =
  | "recipe"
  | "ingredient"
  | "product"
  | "usda-food"
  | "cookbook"
  | "location"
  | "inventory"
  | "meal"
  | "project"
  | "task"
  | "expense"
  | "purchase"
  | "vendor"
  | "financialAccount"
  | "financialTransaction"
  | "wish"
  | "image";
