// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=191220eba4c863da content=47dd8280db14adb4
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { cookbookDetailQuery } from "~/entities/cookbook.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const CookbooksDetailPage = detailPage({
  entity: "cookbook",
  query: (shortcode) => cookbookDetailQuery(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="cookbook" record={record} />
  ),
  title: (record) => record.book,
});

const CookbooksNotFound = notFoundPage("cookbook");

export const Route = createFileRoute("/_authenticated/cookbooks/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      cookbookDetailQuery(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: CookbooksNotFound,
  head: shortcodeHead,
  component: CookbooksDetailPage,
});
