// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=d3a0ca5226a6ea12 content=d3a0ca5226a6ea12
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const DevicesPage = listPage({
  entity: "device",
});

export const Route = createFileRoute("/_authenticated/devices/")({
  validateSearch: entitySearch.device.schema,
  search: { middlewares: [stripSearchParams(entitySearch.device.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("device"),
  head: () => ({ meta: [{ title: pageTitle("Devices") }] }),
  component: DevicesPage,
});
