// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=bab61514ac35692e content=bab61514ac35692e
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ExpensesPage = listPage({
  entity: "expense",
  actions: () => <CreateDialogAction request={captureRequest("expense")} />,
});

export const Route = createFileRoute("/_authenticated/expenses/")({
  validateSearch: entitySearch.expense.schema,
  search: { middlewares: [stripSearchParams(entitySearch.expense.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("expense"),
  head: () => ({ meta: [{ title: pageTitle("Expenses") }] }),
  component: ExpensesPage,
});
