// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=e440dbe5a9cec090 content=d47b198aabb3526d
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ExpensesDetailPage = detailPage({
  entity: "expense",
  query: (shortcode) => entityDetailFor("expense").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="expense" record={record} />
  ),
  title: (record) => record.name,
});

const ExpensesNotFound = notFoundPage("expense");

export const Route = createFileRoute("/_authenticated/expenses/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("expense").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ExpensesNotFound,
  head: shortcodeHead,
  component: ExpensesDetailPage,
});
