// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=488807045cdb484f content=7697994ab509a839
import { createFileRoute } from "@tanstack/react-router";

import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { ExpenseDetail } from "~/app/expenses/expense-detail";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ExpensesDetailPage = detailPage({
  query: (shortcode) => entityDetailFor("expense").queryOptions(shortcode),
  render: (record, shortcode) => (
    <ExpenseDetail key={shortcode} record={record} />
  ),
  title: (record) => record.name,
});

const ExpensesNotFound = notFoundPage("expense");

export const Route = createFileRoute("/_authenticated/expenses/$shortcode")({
  loader: ({ params, context }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("expense").queryOptions(params.shortcode),
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ExpensesNotFound,
  head: shortcodeHead,
  component: ExpensesDetailPage,
});
