// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=f68daf1c6893481e content=d229ef108b2e1582
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { FinancialTransactionList } from "~/app/finance/financial-transaction-list";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const FinancialTransactionsPage = listPage({
  title: "Transactions",
  entity: "financialTransaction",
  list: FinancialTransactionList,
  actions: () => (
    <CreateDialogAction request={captureRequest("financialTransaction")}>
      New Financial Transaction
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/financial-transactions/")(
  {
    validateSearch: entitySearch.financialTransaction.schema,
    search: {
      middlewares: [
        stripSearchParams(entitySearch.financialTransaction.defaults),
      ],
    },
    loaderDeps: ({ search }) => search,
    loader: entityListLoader("financialTransaction"),
    head: () => ({ meta: [{ title: pageTitle("Transactions") }] }),
    component: FinancialTransactionsPage,
  },
);
