// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=819d25d341f41e14 content=0b36c428373b79a2
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const FinancialAccountsDetailPage = detailPage({
  entity: "financialAccount",
  query: (shortcode) =>
    entityDetailFor("financialAccount").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail
      key={shortcode}
      entity="financialAccount"
      record={record}
    />
  ),
  title: (record) => record.name,
});

const FinancialAccountsNotFound = notFoundPage("financialAccount");

export const Route = createFileRoute(
  "/_authenticated/financial-accounts/$shortcode",
)({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("financialAccount").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: FinancialAccountsNotFound,
  head: shortcodeHead,
  component: FinancialAccountsDetailPage,
});
