// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=f79cd29a018c116d content=7c57fd720d4dbf1b
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const GardenEntriesPage = listPage({
  entity: "gardenEntry",
  actions: () => <CreateDialogAction request={captureRequest("gardenEntry")} />,
});

export const Route = createFileRoute("/_authenticated/garden-entries/")({
  validateSearch: entitySearch.gardenEntry.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.gardenEntry.defaults)],
  },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("gardenEntry"),
  head: () => ({ meta: [{ title: pageTitle("Garden Entries") }] }),
  component: GardenEntriesPage,
});
