// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=046202bf1838822d content=51820280a74222f2
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { imageDetailQuery } from "~/entities/image.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ImagesDetailPage = detailPage({
  entity: "image",
  query: (shortcode) => imageDetailQuery(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="image" record={record} />
  ),
  title: (record) => record.filename,
});

const ImagesNotFound = notFoundPage("image");

export const Route = createFileRoute("/_authenticated/images/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      imageDetailQuery(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ImagesNotFound,
  head: shortcodeHead,
  component: ImagesDetailPage,
});
