// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=b6fea5fe271eb167 content=a4cd33364d159c6e
import { createFileRoute } from "@tanstack/react-router";

import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { ImageDetailPage } from "~/app/images/image-detail-page";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { imageDetailQuery } from "~/entities/image.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ImagesDetailPage = detailPage({
  query: (shortcode) => imageDetailQuery(shortcode),
  render: (record, shortcode) => (
    <ImageDetailPage key={shortcode} record={record} />
  ),
  title: (record) => record.filename,
});

const ImagesNotFound = notFoundPage("image");

export const Route = createFileRoute("/_authenticated/images/$shortcode")({
  loader: ({ params, context }) =>
    ensureDetailRecord(context.queryClient, imageDetailQuery(params.shortcode)),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ImagesNotFound,
  head: shortcodeHead,
  component: ImagesDetailPage,
});
