// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=1947ff9ae586d381 content=30182b44423c4f9e
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ImageSightingsDetailPage = detailPage({
  entity: "imageSighting",
  query: (shortcode) =>
    entityDetailFor("imageSighting").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail
      key={shortcode}
      entity="imageSighting"
      record={record}
    />
  ),
  title: (record) => record.displayName,
});

const ImageSightingsNotFound = notFoundPage("imageSighting");

export const Route = createFileRoute(
  "/_authenticated/image-sightings/$shortcode",
)({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("imageSighting").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ImageSightingsNotFound,
  head: shortcodeHead,
  component: ImageSightingsDetailPage,
});
