// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=10b2648cd59963d2 content=9a24c3a975bebe86
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { IngredientList } from "~/app/ingredients/ingredientlist";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const IngredientsPage = listPage({
  title: "Ingredients",
  entity: "ingredient",
  list: IngredientList,
  actions: () => (
    <CreateDialogAction request={captureRequest("ingredient")}>
      New Ingredient
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/ingredients/")({
  validateSearch: entitySearch.ingredient.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.ingredient.defaults)],
  },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("ingredient"),
  head: () => ({ meta: [{ title: pageTitle("Ingredients") }] }),
  component: IngredientsPage,
});
