// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=f94881421d9a2d31 content=97ea14eb828df413
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { IngredientList } from "~/app/ingredients/ingredientlist";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const IngredientsPage = listPage({
  title: "Ingredients",
  entity: "ingredient",
  list: IngredientList,
});

export const Route = createFileRoute("/_authenticated/ingredients/")({
  validateSearch: entitySearch.ingredient.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.ingredient.defaults)],
  },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("ingredient"),
  head: () => ({ meta: [{ title: pageTitle("Ingredients") }] }),
  component: IngredientsPage,
});
