// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=6bd8c2e2230eb6ac content=36456e4e9b129b76
import { createFileRoute } from "@tanstack/react-router";

import { IngredientDetail } from "~/app/_components/ingredients/ingredient-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const IngredientsDetailPage = detailPage({
  query: (shortcode) => entityDetailFor("ingredient").queryOptions(shortcode),
  render: (record, shortcode) => (
    <IngredientDetail key={shortcode} record={record} />
  ),
  title: (record) => record.name,
});

const IngredientsNotFound = notFoundPage("ingredient");

export const Route = createFileRoute("/_authenticated/ingredients/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("ingredient").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: IngredientsNotFound,
  head: shortcodeHead,
  component: IngredientsDetailPage,
});
