// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=c5b1b7d0f9e36bfd content=1b4c68172dae0c58
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { GenericEntityList } from "~/app/_components/entity-list/generic-entity-list";
import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { entityListPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const InventoryPage = entityListPage({
  entity: "inventory",
  list: () => <GenericEntityList entity="inventory" />,
  actions: () => (
    <CreateDialogAction request={captureRequest("inventory")}>
      New Inventory Item
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/inventory/")({
  validateSearch: entitySearch.inventory.schema,
  search: { middlewares: [stripSearchParams(entitySearch.inventory.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("inventory"),
  head: () => ({ meta: [{ title: pageTitle("Inventory") }] }),
  component: InventoryPage,
});
