// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=8e9a0ebe4ed510db content=406c4ca798a68991
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { InventoryActions } from "~/app/inventory/inventory-actions";
import { InventoryItemList } from "~/app/inventory/inventoryitemlist";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const InventoryPage = listPage({
  title: "Inventory",
  entity: "inventory",
  list: InventoryItemList,
  actions: () => <InventoryActions />,
});

export const Route = createFileRoute("/_authenticated/inventory/")({
  validateSearch: entitySearch.inventory.schema,
  search: { middlewares: [stripSearchParams(entitySearch.inventory.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("inventory"),
  head: () => ({ meta: [{ title: pageTitle("Inventory") }] }),
  component: InventoryPage,
});
