// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=ae94b1959fbbc0df content=20ea491eaa942e68
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const LedgerPartiesDetailPage = detailPage({
  entity: "ledgerParty",
  query: (shortcode) => entityDetailFor("ledgerParty").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="ledgerParty" record={record} />
  ),
  title: (record) => record.name,
});

const LedgerPartiesNotFound = notFoundPage("ledgerParty");

export const Route = createFileRoute(
  "/_authenticated/ledger-parties/$shortcode",
)({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("ledgerParty").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: LedgerPartiesNotFound,
  head: shortcodeHead,
  component: LedgerPartiesDetailPage,
});
