// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=fa51268267105fc2 content=a11e5aab4fdcfe9d
import { createFileRoute } from "@tanstack/react-router";

import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { LedgerTransferDetail } from "~/app/finance/ledger-transfer-detail";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const LedgerTransfersDetailPage = detailPage({
  query: (shortcode) =>
    entityDetailFor("ledgerTransfer").queryOptions(shortcode),
  render: (record, shortcode) => (
    <LedgerTransferDetail key={shortcode} record={record} />
  ),
  title: (record) => record.fromPartyName,
});

const LedgerTransfersNotFound = notFoundPage("ledgerTransfer");

export const Route = createFileRoute(
  "/_authenticated/ledger-transfers/$shortcode",
)({
  loader: ({ params, context }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("ledgerTransfer").queryOptions(params.shortcode),
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: LedgerTransfersNotFound,
  head: shortcodeHead,
  component: LedgerTransfersDetailPage,
});
