// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=af2917991b514273 content=0d85bf9d40779b12
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { GenericEntityList } from "~/app/_components/entity-list/generic-entity-list";
import { entityListPage } from "~/app/_components/routing/entity-routes";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const LedgerTransfersPage = entityListPage({
  entity: "ledgerTransfer",
  list: () => <GenericEntityList entity="ledgerTransfer" />,
});

export const Route = createFileRoute("/_authenticated/ledger-transfers/")({
  validateSearch: entitySearch.ledgerTransfer.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.ledgerTransfer.defaults)],
  },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("ledgerTransfer"),
  head: () => ({ meta: [{ title: pageTitle("Transfers") }] }),
  component: LedgerTransfersPage,
});
