// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=73ae54cfa6051c8d content=623cd64ff43b752a
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { GenericEntityList } from "~/app/_components/entity-list/generic-entity-list";
import { entityListPage } from "~/app/_components/routing/entity-routes";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const LedgerPartiesPage = entityListPage({
  entity: "ledgerParty",
  list: () => <GenericEntityList entity="ledgerParty" />,
});

export const Route = createFileRoute("/_authenticated/ledger-parties/")({
  validateSearch: entitySearch.ledgerParty.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.ledgerParty.defaults)],
  },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("ledgerParty"),
  head: () => ({ meta: [{ title: pageTitle("Ledger Parties") }] }),
  component: LedgerPartiesPage,
});
