// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=6389ac832a5715d6 content=b7161f51bc02b62d
import { createFileRoute } from "@tanstack/react-router";

import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { MealDetailPage } from "~/app/meals/meal-detail-page";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const MealsDetailPage = detailPage({
  query: (shortcode) => entityDetailFor("meal").queryOptions(shortcode),
  render: (record, shortcode) => (
    <MealDetailPage key={shortcode} record={record} />
  ),
  title: (record) => record.displayName,
});

const MealsNotFound = notFoundPage("meal");

export const Route = createFileRoute("/_authenticated/meals/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("meal").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: MealsNotFound,
  head: shortcodeHead,
  component: MealsDetailPage,
});
