// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=4214ee0360626af5 content=9f557aeea0ba3322
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const PlantingsDetailPage = detailPage({
  entity: "planting",
  query: (shortcode) => entityDetailFor("planting").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="planting" record={record} />
  ),
  title: (record) => record.displayName,
});

const PlantingsNotFound = notFoundPage("planting");

export const Route = createFileRoute("/_authenticated/plantings/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("planting").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: PlantingsNotFound,
  head: shortcodeHead,
  component: PlantingsDetailPage,
});
