// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=33276ada62809cff content=33276ada62809cff
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const PlantingsPage = listPage({
  entity: "planting",
});

export const Route = createFileRoute("/_authenticated/plantings/")({
  validateSearch: entitySearch.planting.schema,
  search: { middlewares: [stripSearchParams(entitySearch.planting.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("planting"),
  head: () => ({ meta: [{ title: pageTitle("Plantings") }] }),
  component: PlantingsPage,
});
