// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=1a35699a3c94c095 content=c9f0869d9eb36de3
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const PlantsDetailPage = detailPage({
  entity: "plant",
  query: (shortcode) => entityDetailFor("plant").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="plant" record={record} />
  ),
  title: (record) => record.displayName,
});

const PlantsNotFound = notFoundPage("plant");

export const Route = createFileRoute("/_authenticated/plants/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("plant").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: PlantsNotFound,
  head: shortcodeHead,
  component: PlantsDetailPage,
});
