// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=ec53ae7f90d4a34f content=7dcacb419fc37eb4
import { createFileRoute } from "@tanstack/react-router";

import { ProductDetail } from "~/app/_components/products/product-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ProductsDetailPage = detailPage({
  query: (shortcode) => entityDetailFor("product").queryOptions(shortcode),
  render: (record, shortcode) => (
    <ProductDetail key={shortcode} record={record} />
  ),
  title: (record) => record.name,
});

const ProductsNotFound = notFoundPage("product");

export const Route = createFileRoute("/_authenticated/products/$shortcode")({
  loader: ({ params, context }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("product").queryOptions(params.shortcode),
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ProductsNotFound,
  head: shortcodeHead,
  component: ProductsDetailPage,
});
