// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=cd939f8eeb4a4d9e content=85beba0f09720703
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const ProjectsDetailPage = detailPage({
  entity: "project",
  query: (shortcode) => entityDetailFor("project").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="project" record={record} />
  ),
  title: (record) => record.name,
});

const ProjectsNotFound = notFoundPage("project");

export const Route = createFileRoute("/_authenticated/projects/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("project").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: ProjectsNotFound,
  head: shortcodeHead,
  component: ProjectsDetailPage,
});
