// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=95074a336783c93a content=edb0131abdddc4af
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { GenericEntityList } from "~/app/_components/entity-list/generic-entity-list";
import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { entityListPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const PurchasesPage = entityListPage({
  entity: "purchase",
  list: () => <GenericEntityList entity="purchase" />,
  actions: () => (
    <CreateDialogAction request={captureRequest("purchase")}>
      New Purchase
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/purchases/")({
  validateSearch: entitySearch.purchase.schema,
  search: { middlewares: [stripSearchParams(entitySearch.purchase.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("purchase"),
  head: () => ({ meta: [{ title: pageTitle("Purchases") }] }),
  component: PurchasesPage,
});
