// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=89f563c44538ffb3 content=9a1bfd313e869355
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const PurchaseImportsPage = listPage({
  entity: "purchaseImportRun",
});

export const Route = createFileRoute("/_authenticated/purchase-imports/")({
  validateSearch: entitySearch.purchaseImportRun.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.purchaseImportRun.defaults)],
  },
  head: () => ({ meta: [{ title: pageTitle("Import Runs") }] }),
  component: PurchaseImportsPage,
});
