// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=a7f29e959c89f0f2 content=928edf37ad665b2b
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { PurchaseList } from "~/app/purchases/purchaselist";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const PurchasesPage = listPage({
  title: "Purchases",
  entity: "purchase",
  list: PurchaseList,
  actions: () => (
    <CreateDialogAction request={captureRequest("purchase")}>
      New Purchase
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/purchases/")({
  validateSearch: entitySearch.purchase.schema,
  search: { middlewares: [stripSearchParams(entitySearch.purchase.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("purchase"),
  head: () => ({ meta: [{ title: pageTitle("Purchases") }] }),
  component: PurchasesPage,
});
