// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=0d61a1fa0c86bb1a content=1a591be6fccf9993
import { PlusIcon as Plus } from "@phosphor-icons/react/dist/csr/Plus";
import {
  createFileRoute,
  Link,
  stripSearchParams,
} from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { Button } from "~/components/ui/button";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const RecipesPage = listPage({
  entity: "recipe",
  actions: () => (
    <Button render={<Link to="/recipes/new" />} nativeButton={false}>
      <Plus />
      New
    </Button>
  ),
});

export const Route = createFileRoute("/_authenticated/recipes/")({
  validateSearch: entitySearch.recipe.schema,
  search: { middlewares: [stripSearchParams(entitySearch.recipe.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("recipe"),
  head: () => ({ meta: [{ title: pageTitle("Recipes") }] }),
  component: RecipesPage,
});
