// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=9e338c6355d6664e content=9e338c6355d6664e
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { listPage } from "~/app/_components/routing/entity-routes";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const RunsPage = listPage({
  entity: "importRun",
});

export const Route = createFileRoute("/_authenticated/runs/")({
  validateSearch: entitySearch.importRun.schema,
  search: { middlewares: [stripSearchParams(entitySearch.importRun.defaults)] },
  head: () => ({ meta: [{ title: pageTitle("Runs") }] }),
  component: RunsPage,
});
