// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=4386c3d19bd87631 content=df9674a1020a0813
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { runDetailQuery } from "~/entities/run.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const RunsDetailPage = detailPage({
  entity: "importRun",
  query: (shortcode) => runDetailQuery(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail key={shortcode} entity="importRun" record={record} />
  ),
  title: (record) => record.displayName,
});

const RunsNotFound = notFoundPage("importRun");

export const Route = createFileRoute("/_authenticated/runs/$shortcode")({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(context.queryClient, runDetailQuery(params.shortcode), {
      shortcode: params.shortcode,
      href: location.href,
    }),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: RunsNotFound,
  head: shortcodeHead,
  component: RunsDetailPage,
});
