// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=d43c18a95347f774 content=d43c18a95347f774
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const TasksPage = listPage({
  entity: "task",
  actions: () => <CreateDialogAction request={captureRequest("task")} />,
});

export const Route = createFileRoute("/_authenticated/tasks/")({
  validateSearch: entitySearch.task.schema,
  search: { middlewares: [stripSearchParams(entitySearch.task.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("task"),
  head: () => ({ meta: [{ title: pageTitle("Tasks") }] }),
  component: TasksPage,
});
