// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=2440f4896f0eeaed content=fc281755dbd4ad7b
import { createFileRoute } from "@tanstack/react-router";

import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { TaskDetail } from "~/app/tasks/task-detail";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const TasksDetailPage = detailPage({
  query: (shortcode) => entityDetailFor("task").queryOptions(shortcode),
  render: (record, shortcode) => <TaskDetail key={shortcode} record={record} />,
  title: (record) => record.name,
});

const TasksNotFound = notFoundPage("task");

export const Route = createFileRoute("/_authenticated/tasks/$shortcode")({
  loader: ({ params, context }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("task").queryOptions(params.shortcode),
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: TasksNotFound,
  head: shortcodeHead,
  component: TasksDetailPage,
});
