// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=4d6a5f34cf56e807 content=0f3cbfea6e861cff
import { createFileRoute } from "@tanstack/react-router";

import { GenericEntityDetail } from "~/app/_components/entity-detail/generic-entity-detail";
import { ensureDetailRecord } from "~/app/_components/routing/detail-loader";
import {
  detailPage,
  notFoundPage,
} from "~/app/_components/routing/entity-routes";
import { RouteErrorComponent } from "~/components/lazy-route-error";
import { DetailPagePending } from "~/components/route-pending";
import { entityDetailFor } from "~/entities/entity-detail.functions";
import { shortcodeHead } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const VendorAccountsDetailPage = detailPage({
  entity: "vendorAccount",
  query: (shortcode) =>
    entityDetailFor("vendorAccount").queryOptions(shortcode),
  render: (record, shortcode) => (
    <GenericEntityDetail
      key={shortcode}
      entity="vendorAccount"
      record={record}
    />
  ),
  title: (record) => record.label,
});

const VendorAccountsNotFound = notFoundPage("vendorAccount");

export const Route = createFileRoute(
  "/_authenticated/vendor-accounts/$shortcode",
)({
  loader: ({ params, context, location }) =>
    ensureDetailRecord(
      context.queryClient,
      entityDetailFor("vendorAccount").queryOptions(params.shortcode),
      {
        shortcode: params.shortcode,
        href: location.href,
      },
    ),
  pendingComponent: DetailPagePending,
  errorComponent: RouteErrorComponent,
  notFoundComponent: VendorAccountsNotFound,
  head: shortcodeHead,
  component: VendorAccountsDetailPage,
});
