// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=b497b29fdac3cdfc content=55ab25c25f96b20a
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { listPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const VendorAccountsPage = listPage({
  entity: "vendorAccount",
  actions: () => (
    <CreateDialogAction request={captureRequest("vendorAccount")} />
  ),
});

export const Route = createFileRoute("/_authenticated/vendor-accounts/")({
  validateSearch: entitySearch.vendorAccount.schema,
  search: {
    middlewares: [stripSearchParams(entitySearch.vendorAccount.defaults)],
  },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("vendorAccount"),
  head: () => ({ meta: [{ title: pageTitle("Vendor Accounts") }] }),
  component: VendorAccountsPage,
});
