// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=c866b292257d6edc content=d6394cf2f0001f1a
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { GenericEntityList } from "~/app/_components/entity-list/generic-entity-list";
import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { entityListPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const VendorsPage = entityListPage({
  entity: "vendor",
  list: () => <GenericEntityList entity="vendor" />,
  actions: () => (
    <CreateDialogAction request={captureRequest("vendor")}>
      New Vendor
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/vendors/")({
  validateSearch: entitySearch.vendor.schema,
  search: { middlewares: [stripSearchParams(entitySearch.vendor.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("vendor"),
  head: () => ({ meta: [{ title: pageTitle("Vendors") }] }),
  component: VendorsPage,
});
