// Generated by `pnpm generate` — do not edit.

// Artifact hashes: source=20851df078c46ebf content=509f762ede3ad45b
import { createFileRoute, stripSearchParams } from "@tanstack/react-router";

import { GenericEntityList } from "~/app/_components/entity-list/generic-entity-list";
import { CreateDialogAction } from "~/app/_components/forms/create-dialog-action";
import { entityListPage } from "~/app/_components/routing/entity-routes";
import { captureRequest } from "~/entities/editing/editor-requests";
import { entityListLoader } from "~/entities/entity-list-ssr";
import { entitySearch } from "~/entities/generated/entity-search.gen";
import { pageTitle } from "~/lib/page-title";

// Bound to a const, not inlined into the options object: the router plugin's
// splitter re-parses an inlined call expression with a JSX-less babel config,
// so only the identifier path survives a page body that renders JSX.
const WishesPage = entityListPage({
  entity: "wish",
  list: () => <GenericEntityList entity="wish" />,
  actions: () => (
    <CreateDialogAction request={captureRequest("wish")}>
      New Wish
    </CreateDialogAction>
  ),
});

export const Route = createFileRoute("/_authenticated/wishes/")({
  validateSearch: entitySearch.wish.schema,
  search: { middlewares: [stripSearchParams(entitySearch.wish.defaults)] },
  loaderDeps: ({ search }) => search,
  loader: entityListLoader("wish"),
  head: () => ({ meta: [{ title: pageTitle("Wishlist") }] }),
  component: WishesPage,
});
